-- ./excel/fight/fengyao.xlsx
return {

    [1011] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "30级封妖",
        friend = {},
        id = 1011,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10010, ["count"] = 1}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1012] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "40级封妖",
        friend = {},
        id = 1012,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10020, ["count"] = 1}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1013] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "50级封妖",
        friend = {},
        id = 1013,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10030, ["count"] = 1}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1014] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "60级封妖",
        friend = {},
        id = 1014,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10040, ["count"] = 1}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1015] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "70级封妖",
        friend = {},
        id = 1015,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10050, ["count"] = 1}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1016] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "80级封妖",
        friend = {},
        id = 1016,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10060, ["count"] = 1}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2001] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "30级妖王",
        friend = {},
        id = 2001,
        lineup = {1, 1},
        monster = {{["monsterid"] = 20010, ["count"] = 1}, {["monsterid"] = 20012, ["count"] = 1}, {["monsterid"] = 20013, ["count"] = 1}, {["monsterid"] = 20014, ["count"] = 1}, {["monsterid"] = 20015, ["count"] = 2}, {["monsterid"] = 20011, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2002] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "40级妖王",
        friend = {},
        id = 2002,
        lineup = {1, 1},
        monster = {{["monsterid"] = 20020, ["count"] = 1}, {["monsterid"] = 20022, ["count"] = 1}, {["monsterid"] = 20023, ["count"] = 1}, {["monsterid"] = 20024, ["count"] = 1}, {["monsterid"] = 20025, ["count"] = 2}, {["monsterid"] = 20021, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2003] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "50级妖王",
        friend = {},
        id = 2003,
        lineup = {1, 1},
        monster = {{["monsterid"] = 20030, ["count"] = 1}, {["monsterid"] = 20032, ["count"] = 1}, {["monsterid"] = 20033, ["count"] = 1}, {["monsterid"] = 20034, ["count"] = 1}, {["monsterid"] = 20035, ["count"] = 2}, {["monsterid"] = 20031, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2004] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "60级妖王",
        friend = {},
        id = 2004,
        lineup = {1, 1},
        monster = {{["monsterid"] = 20040, ["count"] = 1}, {["monsterid"] = 20042, ["count"] = 1}, {["monsterid"] = 20043, ["count"] = 1}, {["monsterid"] = 20044, ["count"] = 1}, {["monsterid"] = 20045, ["count"] = 2}, {["monsterid"] = 20041, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2005] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "70级妖王",
        friend = {},
        id = 2005,
        lineup = {1, 1},
        monster = {{["monsterid"] = 20050, ["count"] = 1}, {["monsterid"] = 20052, ["count"] = 1}, {["monsterid"] = 20053, ["count"] = 1}, {["monsterid"] = 20054, ["count"] = 1}, {["monsterid"] = 20055, ["count"] = 2}, {["monsterid"] = 20051, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2006] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "80级妖王",
        friend = {},
        id = 2006,
        lineup = {1, 1},
        monster = {{["monsterid"] = 20060, ["count"] = 1}, {["monsterid"] = 20062, ["count"] = 1}, {["monsterid"] = 20063, ["count"] = 1}, {["monsterid"] = 20064, ["count"] = 1}, {["monsterid"] = 20065, ["count"] = 2}, {["monsterid"] = 20061, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2011] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "30级妖王",
        friend = {},
        id = 2011,
        lineup = {2, 1},
        monster = {{["monsterid"] = 21010, ["count"] = 1}, {["monsterid"] = 21012, ["count"] = 1}, {["monsterid"] = 21013, ["count"] = 1}, {["monsterid"] = 21014, ["count"] = 1}, {["monsterid"] = 21015, ["count"] = 2}, {["monsterid"] = 21011, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2012] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "40级妖王",
        friend = {},
        id = 2012,
        lineup = {2, 1},
        monster = {{["monsterid"] = 21020, ["count"] = 1}, {["monsterid"] = 21022, ["count"] = 1}, {["monsterid"] = 21023, ["count"] = 1}, {["monsterid"] = 21024, ["count"] = 1}, {["monsterid"] = 21025, ["count"] = 2}, {["monsterid"] = 21021, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2013] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "50级妖王",
        friend = {},
        id = 2013,
        lineup = {2, 1},
        monster = {{["monsterid"] = 21030, ["count"] = 1}, {["monsterid"] = 21032, ["count"] = 1}, {["monsterid"] = 21033, ["count"] = 1}, {["monsterid"] = 21034, ["count"] = 1}, {["monsterid"] = 21035, ["count"] = 2}, {["monsterid"] = 21031, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2014] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "60级妖王",
        friend = {},
        id = 2014,
        lineup = {2, 1},
        monster = {{["monsterid"] = 21040, ["count"] = 1}, {["monsterid"] = 21042, ["count"] = 1}, {["monsterid"] = 21043, ["count"] = 1}, {["monsterid"] = 21044, ["count"] = 1}, {["monsterid"] = 21045, ["count"] = 2}, {["monsterid"] = 21041, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2015] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "70级妖王",
        friend = {},
        id = 2015,
        lineup = {2, 1},
        monster = {{["monsterid"] = 21050, ["count"] = 1}, {["monsterid"] = 21052, ["count"] = 1}, {["monsterid"] = 21053, ["count"] = 1}, {["monsterid"] = 21054, ["count"] = 1}, {["monsterid"] = 21055, ["count"] = 2}, {["monsterid"] = 21051, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2016] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "80级妖王",
        friend = {},
        id = 2016,
        lineup = {2, 1},
        monster = {{["monsterid"] = 21060, ["count"] = 1}, {["monsterid"] = 21062, ["count"] = 1}, {["monsterid"] = 21063, ["count"] = 1}, {["monsterid"] = 21064, ["count"] = 1}, {["monsterid"] = 21065, ["count"] = 2}, {["monsterid"] = 21061, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2021] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "30级妖王",
        friend = {},
        id = 2021,
        lineup = {3, 1},
        monster = {{["monsterid"] = 22010, ["count"] = 1}, {["monsterid"] = 22012, ["count"] = 1}, {["monsterid"] = 22013, ["count"] = 1}, {["monsterid"] = 22014, ["count"] = 1}, {["monsterid"] = 22015, ["count"] = 2}, {["monsterid"] = 22011, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2022] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "40级妖王",
        friend = {},
        id = 2022,
        lineup = {3, 1},
        monster = {{["monsterid"] = 22020, ["count"] = 1}, {["monsterid"] = 22022, ["count"] = 1}, {["monsterid"] = 22023, ["count"] = 1}, {["monsterid"] = 22024, ["count"] = 1}, {["monsterid"] = 22025, ["count"] = 2}, {["monsterid"] = 22021, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2023] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "50级妖王",
        friend = {},
        id = 2023,
        lineup = {3, 1},
        monster = {{["monsterid"] = 22030, ["count"] = 1}, {["monsterid"] = 22032, ["count"] = 1}, {["monsterid"] = 22033, ["count"] = 1}, {["monsterid"] = 22034, ["count"] = 1}, {["monsterid"] = 22035, ["count"] = 2}, {["monsterid"] = 22031, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2024] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "60级妖王",
        friend = {},
        id = 2024,
        lineup = {3, 1},
        monster = {{["monsterid"] = 22040, ["count"] = 1}, {["monsterid"] = 22042, ["count"] = 1}, {["monsterid"] = 22043, ["count"] = 1}, {["monsterid"] = 22044, ["count"] = 1}, {["monsterid"] = 22045, ["count"] = 2}, {["monsterid"] = 22041, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2025] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "70级妖王",
        friend = {},
        id = 2025,
        lineup = {3, 1},
        monster = {{["monsterid"] = 22050, ["count"] = 1}, {["monsterid"] = 22052, ["count"] = 1}, {["monsterid"] = 22053, ["count"] = 1}, {["monsterid"] = 22054, ["count"] = 1}, {["monsterid"] = 22055, ["count"] = 2}, {["monsterid"] = 22051, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2026] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "80级妖王",
        friend = {},
        id = 2026,
        lineup = {3, 1},
        monster = {{["monsterid"] = 22060, ["count"] = 1}, {["monsterid"] = 22062, ["count"] = 1}, {["monsterid"] = 22063, ["count"] = 1}, {["monsterid"] = 22064, ["count"] = 1}, {["monsterid"] = 22065, ["count"] = 2}, {["monsterid"] = 22061, ["count"] = 2}},
        sky_war = 0,
        war_confirm = 0,
        weather = 0,
    },

}
