-- ./excel/fight/fuben.xlsx
return {

    [1001] = {
        action_id = {1003},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败妖鬼",
        friend = {},
        id = 1001,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10001, ["count"] = 1}, {["monsterid"] = 10002, ["count"] = 1}, {["monsterid"] = 10003, ["count"] = 2}, {["monsterid"] = 10004, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1002] = {
        action_id = {1003},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败李广",
        friend = {},
        id = 1002,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10005, ["count"] = 1}, {["monsterid"] = 10006, ["count"] = 3}, {["monsterid"] = 10007, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1003] = {
        action_id = {1003},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败情殇",
        friend = {{["monsterid"] = 10008, ["count"] = 1}},
        id = 1003,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10009, ["count"] = 1}, {["monsterid"] = 10010, ["count"] = 2}, {["monsterid"] = 10012, ["count"] = 2}, {["monsterid"] = 10011, ["count"] = 3}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1004] = {
        action_id = {1003},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败霍去病",
        friend = {{["monsterid"] = 10008, ["count"] = 1}},
        id = 1004,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10013, ["count"] = 1}, {["monsterid"] = 10014, ["count"] = 1}, {["monsterid"] = 10015, ["count"] = 1}, {["monsterid"] = 10016, ["count"] = 2}, {["monsterid"] = 10017, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1005] = {
        action_id = {1003},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 1,
        desc = "打败南方鬼帝",
        friend = {{["monsterid"] = 10008, ["count"] = 1}},
        id = 1005,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10018, ["count"] = 1}, {["monsterid"] = 10019, ["count"] = 1}, {["monsterid"] = 10020, ["count"] = 1}, {["monsterid"] = 10021, ["count"] = 1}, {["monsterid"] = 10022, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 2,
    },

    [2001] = {
        action_id = {1005},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败拦路的小妖",
        friend = {},
        id = 2001,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20001, ["count"] = 1}, {["monsterid"] = 20002, ["count"] = 2}, {["monsterid"] = 20004, ["count"] = 2}},
        sky_war = 0,
        speek_id = 1001,
        weather = 0,
    },

    [2002] = {
        action_id = {1005},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "向白素贞解释自己的来历",
        friend = {},
        id = 2002,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20008, ["count"] = 1}, {["monsterid"] = 20009, ["count"] = 1}, {["monsterid"] = 20010, ["count"] = 3}},
        sky_war = 0,
        speek_id = 1002,
        weather = 0,
    },

    [2003] = {
        action_id = {1005},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "让许仙恢复清明",
        friend = {{["monsterid"] = 20018, ["count"] = 1}, {["monsterid"] = 20019, ["count"] = 1}},
        id = 2003,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20020, ["count"] = 1}, {["monsterid"] = 20021, ["count"] = 1}, {["monsterid"] = 20022, ["count"] = 1}, {["monsterid"] = 20023, ["count"] = 1}, {["monsterid"] = 20024, ["count"] = 1}, {["monsterid"] = 20025, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [2004] = {
        action_id = {1005},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "阻止法海击杀白素贞",
        friend = {},
        id = 2004,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20026, ["count"] = 1}, {["monsterid"] = 20030, ["count"] = 1}, {["monsterid"] = 20031, ["count"] = 1}, {["monsterid"] = 20029, ["count"] = 1}, {["monsterid"] = 20032, ["count"] = 1}, {["monsterid"] = 20028, ["count"] = 1}, {["monsterid"] = 20027, ["count"] = 1}},
        sky_war = 0,
        speek_id = 1003,
        weather = 0,
    },

    [2005] = {
        action_id = {1005},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "击败黑化的法海",
        friend = {},
        id = 2005,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20033, ["count"] = 1}, {["monsterid"] = 20034, ["count"] = 1}, {["monsterid"] = 20035, ["count"] = 1}, {["monsterid"] = 20036, ["count"] = 1}, {["monsterid"] = 20037, ["count"] = 1}, {["monsterid"] = 20038, ["count"] = 1}, {["monsterid"] = 20039, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 1,
    },

    [1101] = {
        action_id = {1003},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败妖鬼",
        friend = {},
        id = 1101,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 11001, ["count"] = 1}, {["monsterid"] = 11002, ["count"] = 1}, {["monsterid"] = 11003, ["count"] = 2}, {["monsterid"] = 11004, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1102] = {
        action_id = {1003},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败李广",
        friend = {},
        id = 1102,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 11005, ["count"] = 1}, {["monsterid"] = 11006, ["count"] = 3}, {["monsterid"] = 11007, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1103] = {
        action_id = {1003},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败情殇",
        friend = {{["monsterid"] = 11008, ["count"] = 1}},
        id = 1103,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 11009, ["count"] = 1}, {["monsterid"] = 11010, ["count"] = 2}, {["monsterid"] = 11012, ["count"] = 2}, {["monsterid"] = 11011, ["count"] = 3}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1104] = {
        action_id = {1003},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败霍去病",
        friend = {{["monsterid"] = 11008, ["count"] = 1}},
        id = 1104,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 11013, ["count"] = 1}, {["monsterid"] = 11014, ["count"] = 1}, {["monsterid"] = 11015, ["count"] = 1}, {["monsterid"] = 11016, ["count"] = 2}, {["monsterid"] = 11017, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1105] = {
        action_id = {1003},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 1,
        desc = "打败南方鬼帝",
        friend = {{["monsterid"] = 11008, ["count"] = 1}},
        id = 1105,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 11018, ["count"] = 1}, {["monsterid"] = 11019, ["count"] = 1}, {["monsterid"] = 11020, ["count"] = 1}, {["monsterid"] = 11021, ["count"] = 1}, {["monsterid"] = 11023, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [2101] = {
        action_id = {1005},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "打败拦路的小妖",
        friend = {},
        id = 2101,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 21001, ["count"] = 1}, {["monsterid"] = 21002, ["count"] = 2}, {["monsterid"] = 21004, ["count"] = 2}},
        sky_war = 0,
        speek_id = 1001,
        weather = 0,
    },

    [2102] = {
        action_id = {1005},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "向白素贞解释自己的来历",
        friend = {},
        id = 2102,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 21008, ["count"] = 1}, {["monsterid"] = 21009, ["count"] = 1}, {["monsterid"] = 21010, ["count"] = 1}, {["monsterid"] = 21011, ["count"] = 1}, {["monsterid"] = 21012, ["count"] = 1}},
        sky_war = 0,
        speek_id = 1002,
        weather = 0,
    },

    [2103] = {
        action_id = {1005},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "让许仙恢复清明",
        friend = {{["monsterid"] = 21018, ["count"] = 1}, {["monsterid"] = 21019, ["count"] = 1}},
        id = 2103,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 21020, ["count"] = 1}, {["monsterid"] = 21021, ["count"] = 1}, {["monsterid"] = 21022, ["count"] = 1}, {["monsterid"] = 21023, ["count"] = 1}, {["monsterid"] = 21024, ["count"] = 1}, {["monsterid"] = 21025, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [2104] = {
        action_id = {1005},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "阻止法海击杀白素贞",
        friend = {},
        id = 2104,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 21026, ["count"] = 1}, {["monsterid"] = 21030, ["count"] = 1}, {["monsterid"] = 21031, ["count"] = 1}, {["monsterid"] = 21029, ["count"] = 1}, {["monsterid"] = 21032, ["count"] = 1}, {["monsterid"] = 21028, ["count"] = 1}, {["monsterid"] = 21027, ["count"] = 1}},
        sky_war = 0,
        speek_id = 1003,
        weather = 0,
    },

    [2105] = {
        action_id = {1005},
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "击败黑化的法海",
        friend = {},
        id = 2105,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 21033, ["count"] = 1}, {["monsterid"] = 21034, ["count"] = 1}, {["monsterid"] = 21035, ["count"] = 1}, {["monsterid"] = 21036, ["count"] = 1}, {["monsterid"] = 21037, ["count"] = 1}, {["monsterid"] = 21038, ["count"] = 1}, {["monsterid"] = 21039, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

}
