-- ./excel/fight/ghost.xlsx
return {

    [1001] = {
        action_id = {1001},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "伏魔——战斗",
        friend = {},
        id = 1001,
        lineup = {1, 1},
        monster = {{["monsterid"] = 1001, ["count"] = 1}},
        sky_war = 0,
        weather = 0,
    },

    [1002] = {
        action_id = {1001},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "伏魔——战斗",
        friend = {},
        id = 1002,
        lineup = {1, 1},
        monster = {{["monsterid"] = 1002, ["count"] = 1}},
        sky_war = 0,
        weather = 0,
    },

    [1003] = {
        action_id = {1001},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "伏魔——战斗",
        friend = {},
        id = 1003,
        lineup = {1, 1},
        monster = {{["monsterid"] = 1003, ["count"] = 1}},
        sky_war = 0,
        weather = 0,
    },

    [1004] = {
        action_id = {1001},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "伏魔——战斗",
        friend = {},
        id = 1004,
        lineup = {1, 1},
        monster = {{["monsterid"] = 1004, ["count"] = 1}},
        sky_war = 0,
        weather = 0,
    },

    [1005] = {
        action_id = {1001},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "伏魔——战斗",
        friend = {},
        id = 1005,
        lineup = {1, 1},
        monster = {{["monsterid"] = 1005, ["count"] = 1}},
        sky_war = 0,
        weather = 0,
    },

}
