-- ./excel/fight/ghost.xlsx
return {

    [1001] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 5205, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 401,
        critRate = "0",
        desc = "双抗（飞羽）",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5113,
        hp = "100+level*40+(level-20)*level",
        id = 1001,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*12+10",
        magDefense = "level*5+(level-25)*6+10",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4250}},
        phyAttack = "level*15+20",
        phyDefense = "level*10+(level-25)*6+10",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*7",
    },

    [1002] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 5211, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 401,
        critRate = "0",
        desc = "物抗（如意）",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5116,
        hp = "100+level*80+(level-20)*level*2",
        id = 1002,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*12+10",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4250}},
        phyAttack = "level*15+20",
        phyDefense = "level*8+(level-25)*6+10",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*7",
    },

    [1003] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 5206, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 401,
        critRate = "0",
        desc = "法抗（兔精）",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5104,
        hp = "100+level*110+(level-20)*level*2",
        id = 1003,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*12+10",
        magDefense = "level*7+(level-25)*6+10",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4250}},
        phyAttack = "level*15+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*7",
    },

    [1004] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 5207, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 401,
        critRate = "0",
        desc = "血鬼（熊猫）",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5106,
        hp = "100+level*200+(level-20)*level*2",
        id = 1004,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*12+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4250}},
        phyAttack = "level*15+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*7",
    },

    [1005] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 5212, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 401,
        critRate = "0",
        desc = "鬼王",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5128,
        hp = "100+level*150+(level-20)*level*2",
        id = 1005,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*12+10",
        magDefense = "level*6+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4250}},
        phyAttack = "level*15+20",
        phyDefense = "level*6+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*7",
    },

    [2001] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "抓鬼",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5101,
        hp = "100+level*35+(level-25)*level/2",
        id = 2001,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "蠢萌的喽啰",
        passiveSkills = {},
        phyAttack = "level*12+10",
        phyDefense = "level*1+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*3",
    },

    [2002] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "抓鬼",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5102,
        hp = "100+level*35+(level-25)*level/2",
        id = 2002,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "萌萌的喽啰",
        passiveSkills = {},
        phyAttack = "level*12+10",
        phyDefense = "level*1+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*4",
    },

    [2003] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "抓鬼",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5103,
        hp = "100+level*35+(level-25)*level/2",
        id = 2003,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "腹白的喽啰",
        passiveSkills = {},
        phyAttack = "level*12+10",
        phyDefense = "level*1+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*4",
    },

    [2004] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "抓鬼",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5105,
        hp = "100+level*35+(level-25)*level/2",
        id = 2004,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天然呆的喽啰",
        passiveSkills = {},
        phyAttack = "level*12+10",
        phyDefense = "level*1+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*4",
    },

    [2005] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "抓鬼",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5101,
        hp = "100+level*35+(level-25)*level/2",
        id = 2005,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "腹黑的喽啰",
        passiveSkills = {},
        phyAttack = "level*12+10",
        phyDefense = "level*1+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*4",
    },

    [2006] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "抓鬼",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5116,
        hp = "100+level*35+(level-25)*level/2",
        id = 2006,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "低调的喽啰",
        passiveSkills = {},
        phyAttack = "level*12+10",
        phyDefense = "level*1+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*4",
    },

    [2007] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "抓鬼",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5114,
        hp = "100+level*35+(level-25)*level/2",
        id = 2007,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "傲娇的喽啰",
        passiveSkills = {},
        phyAttack = "level*12+10",
        phyDefense = "level*1+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*4",
    },

    [3001] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 3011, ["ai_target"] = 2, ["ratio"] = 100}},
        aitype = 101,
        critRate = "0",
        desc = "抓鬼",
        dodgeRate = "0",
        expertskill = {"0", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5102,
        hp = "100+level*250+(level-25)*level/2",
        id = 3001,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10+10",
        magDefense = "level*10+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "魅",
        passiveSkills = {},
        phyAttack = "level*12+10",
        phyDefense = "level*10+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*20",
    },

}
