-- ./excel/fight/guessgame.xlsx
return {

    [10011] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1606, ["ai_target"] = 2, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1605, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 101,
        critRate = "0",
        desc = "假·守阵之灵",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5131,
        hp = "level*70-120+(level-35)*level/2",
        id = 10011,
        is_boss = 1,
        level = "ALV",
        magAttack = "level*10-35",
        magDefense = "level*7-35",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "假·守阵之灵",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 5108}},
        phyAttack = "level*15-35",
        phyDefense = "level*7-35",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
    },

    [10012] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1103, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "真·守阵之灵",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 51313,
        hp = "level*75-120+(level-35)*level/2",
        id = 10012,
        is_boss = 1,
        level = "ALV",
        magAttack = "level*10-35",
        magDefense = "level*7-35",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "真·守阵之灵",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 5108}},
        phyAttack = "level*15-35",
        phyDefense = "level*7-35",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
    },

    [10013] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1103, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "飞羽将军",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5103,
        hp = "level*50-120+(level-35)*level/2",
        id = 10013,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*8-35",
        magDefense = "level*6-35",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "青蛙守卫",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 5108}},
        phyAttack = "level*12-35",
        phyDefense = "level*6-35",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+1",
    },

    [10014] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "插翅虎",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5121,
        hp = "level*50-120+(level-35)*level/2",
        id = 10014,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*8-35",
        magDefense = "level*6-35",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "插翅虎守卫",
        passiveSkills = {},
        phyAttack = "level*12-35",
        phyDefense = "level*4-35",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+1",
    },

    [10015] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 100}},
        aitype = 401,
        critRate = "0",
        desc = "泥石人",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5120,
        hp = "level*50-120+(level-35)*level/2",
        id = 10015,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*8-35",
        magDefense = "level*4-35",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "泥石人守卫",
        passiveSkills = {},
        phyAttack = "level*12-35",
        phyDefense = "level*6-35",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+1",
    },

    [10016] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 100}},
        aitype = 401,
        critRate = "0",
        desc = "天师道人",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5108,
        hp = "level*50-120+(level-35)*level/2",
        id = 10016,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*8-35",
        magDefense = "level*6-35",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天师守卫",
        passiveSkills = {},
        phyAttack = "level*12-35",
        phyDefense = "level*4-35",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+1",
    },

}
