-- ./excel/fight/moneytree.xlsx
return {

    [10010] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 4221}},
        aitype = 101,
        critRate = "0",
        desc = "如意仙女",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5116,
        hp = "level*90-120+(level-30)*level/2",
        id = 10010,
        is_boss = 1,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*7-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "如意仙女",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 6, ["pfid"] = 4283}},
        phyAttack = "level*15-30",
        phyDefense = "level*7-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "",
    },

    [10020] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 4221}},
        aitype = 101,
        critRate = "0",
        desc = "吉祥仙女",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5127,
        hp = "level*100-120+(level-30)*level/2",
        id = 10020,
        is_boss = 1,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*7-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "吉祥仙女",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 7, ["pfid"] = 4283}},
        phyAttack = "level*15-30",
        phyDefense = "level*7-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "",
    },

    [10011] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "守卫",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5132,
        hp = "level*60-120+(level-30)*level/2",
        id = 10011,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*6-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "守卫",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 5, ["pfid"] = 4250}},
        phyAttack = "level*15-30",
        phyDefense = "level*6-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "",
    },

    [10012] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "炸弹人",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5122,
        hp = "level*15-120+(level-30)*level/2",
        id = 10012,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*2-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "炸弹人",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4219}, {["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 6, ["pfid"] = 4283}},
        phyAttack = "level*15-30",
        phyDefense = "level*2-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "自爆",
    },

    [10013] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "治疗",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5128,
        hp = "level*15-120+(level-30)*level/2",
        id = 10013,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*4-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "止血妖",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 6, ["pfid"] = 4283}},
        phyAttack = "level*15-30",
        phyDefense = "level*4-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "加血",
    },

    [10014] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "经验狗",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5101,
        hp = "level*15-120+(level-30)*level/2",
        id = 10014,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*4-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "经验狗",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 6, ["pfid"] = 4283}},
        phyAttack = "level*15-30",
        phyDefense = "level*4-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "经验",
    },

    [10015] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "银币虎",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5121,
        hp = "level*15-120+(level-30)*level/2",
        id = 10015,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*4-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "银币虎",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 6, ["pfid"] = 4283}},
        phyAttack = "level*15-30",
        phyDefense = "level*4-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "银币",
    },

    [10016] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "金币怪",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 51054,
        hp = "level*15-120+(level-30)*level/2",
        id = 10016,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*4-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "金币牛",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 6, ["pfid"] = 4283}},
        phyAttack = "level*15-30",
        phyDefense = "level*4-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "金币",
    },

    [10017] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "水晶兽",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5107,
        hp = "level*15-120+(level-30)*level/2",
        id = 10017,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*4-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "水晶兽",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 6, ["pfid"] = 4283}},
        phyAttack = "level*15-30",
        phyDefense = "level*4-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "强化水晶",
    },

    [10018] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "宝箱怪",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5112,
        hp = "level*15-120+(level-30)*level/2",
        id = 10018,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10-30",
        magDefense = "level*4-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "宝箱守护者",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 6, ["pfid"] = 4283}},
        phyAttack = "level*15-30",
        phyDefense = "level*4-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "道具",
    },

    [20011] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "守卫",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5132,
        hp = "level*65-120+(level-30)*level/2",
        id = 20011,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*10+20",
        magDefense = "level*8-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "守卫",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 5, ["pfid"] = 4250}},
        phyAttack = "level*2+20",
        phyDefense = "level*8-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "",
    },

    [20012] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "炸弹人",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5122,
        hp = "level*20-120+(level-30)*level/2",
        id = 20012,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*7+20",
        magDefense = "level*3-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "炸弹人",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4219}, {["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 7, ["pfid"] = 4283}},
        phyAttack = "level*10+20",
        phyDefense = "level*3-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "自爆",
    },

    [20013] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "治疗",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5128,
        hp = "level*20-120+(level-30)*level/2",
        id = 20013,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*3+20",
        magDefense = "level*6-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "止血妖",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 7, ["pfid"] = 4283}},
        phyAttack = "level*3+20",
        phyDefense = "level*6-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "加血",
    },

    [20014] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "经验狗",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5101,
        hp = "level*20-120+(level-30)*level/2",
        id = 20014,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*3+20",
        magDefense = "level*6-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "经验狗",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 7, ["pfid"] = 4283}},
        phyAttack = "level*3+20",
        phyDefense = "level*6-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "经验",
    },

    [20015] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "银币虎",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5121,
        hp = "level*20-120+(level-30)*level/2",
        id = 20015,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*3+20",
        magDefense = "level*6-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "银币虎",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 7, ["pfid"] = 4283}},
        phyAttack = "level*3+20",
        phyDefense = "level*6-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "银币",
    },

    [20016] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "金币怪",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 51054,
        hp = "level*20-120+(level-30)*level/2",
        id = 20016,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*3+20",
        magDefense = "level*6-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "金币牛",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 7, ["pfid"] = 4283}},
        phyAttack = "level*3+20",
        phyDefense = "level*6-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "金币",
    },

    [20017] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "水晶兽",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5107,
        hp = "level*20-120+(level-30)*level/2",
        id = 20017,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*3+20",
        magDefense = "level*6-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "水晶兽",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 7, ["pfid"] = 4283}},
        phyAttack = "level*3+20",
        phyDefense = "level*6-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "强化水晶",
    },

    [20018] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "宝箱怪",
        dodgeRate = "0",
        expertskill = {"level/10", "level/10", "level/10", "level/10"},
        figureid = 5112,
        hp = "level*20-120+(level-30)*level/2",
        id = 20018,
        is_boss = 0,
        level = "ALV",
        magAttack = "level*3+20",
        magDefense = "level*6-30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "宝箱守护者",
        passiveSkills = {{["lv"] = 10, ["pfid"] = 4250}, {["lv"] = 5, ["pfid"] = 4222}, {["lv"] = 7, ["pfid"] = 4283}},
        phyAttack = "level*3+20",
        phyDefense = "level*6-30",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "0",
        speed = "level*5+10",
        title = "道具",
    },

}
