-- ./excel/fight/runring.xlsx
return {

    [1001] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1001,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5253, ["count"] = 1}, {["monsterid"] = 5256, ["count"] = 1}, {["monsterid"] = 5286, ["count"] = 1}, {["monsterid"] = 5280, ["count"] = 1}, {["monsterid"] = 5212, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1002] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1002,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5256, ["count"] = 1}, {["monsterid"] = 5235, ["count"] = 1}, {["monsterid"] = 5227, ["count"] = 1}, {["monsterid"] = 5225, ["count"] = 1}, {["monsterid"] = 5230, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1003] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1003,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5286, ["count"] = 1}, {["monsterid"] = 5256, ["count"] = 1}, {["monsterid"] = 5253, ["count"] = 1}, {["monsterid"] = 5280, ["count"] = 1}, {["monsterid"] = 5212, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1004] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1004,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5280, ["count"] = 1}, {["monsterid"] = 5286, ["count"] = 1}, {["monsterid"] = 5256, ["count"] = 1}, {["monsterid"] = 5253, ["count"] = 1}, {["monsterid"] = 5212, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1005] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1005,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5232, ["count"] = 1}, {["monsterid"] = 5230, ["count"] = 1}, {["monsterid"] = 5212, ["count"] = 1}, {["monsterid"] = 5225, ["count"] = 1}, {["monsterid"] = 5253, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1006] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1006,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5230, ["count"] = 1}, {["monsterid"] = 5232, ["count"] = 1}, {["monsterid"] = 5225, ["count"] = 1}, {["monsterid"] = 5227, ["count"] = 1}, {["monsterid"] = 5253, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1007] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1007,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5212, ["count"] = 1}, {["monsterid"] = 5256, ["count"] = 1}, {["monsterid"] = 5230, ["count"] = 1}, {["monsterid"] = 5225, ["count"] = 1}, {["monsterid"] = 5286, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1008] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1008,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5225, ["count"] = 1}, {["monsterid"] = 5286, ["count"] = 1}, {["monsterid"] = 5286, ["count"] = 1}, {["monsterid"] = 5286, ["count"] = 1}, {["monsterid"] = 5286, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1009] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1009,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5227, ["count"] = 1}, {["monsterid"] = 5286, ["count"] = 1}, {["monsterid"] = 5256, ["count"] = 1}, {["monsterid"] = 5232, ["count"] = 1}, {["monsterid"] = 5230, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1010] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环战斗",
        difficulty = {},
        friend = {},
        id = 1010,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5235, ["count"] = 1}, {["monsterid"] = 5256, ["count"] = 1}, {["monsterid"] = 5253, ["count"] = 1}, {["monsterid"] = 5286, ["count"] = 1}, {["monsterid"] = 5280, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2001] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2001,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5131, ["count"] = 1}, {["monsterid"] = 5105, ["count"] = 1}, {["monsterid"] = 5122, ["count"] = 1}, {["monsterid"] = 5112, ["count"] = 1}, {["monsterid"] = 5121, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2002] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2002,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5107, ["count"] = 1}, {["monsterid"] = 5116, ["count"] = 1}, {["monsterid"] = 5106, ["count"] = 1}, {["monsterid"] = 5127, ["count"] = 1}, {["monsterid"] = 5123, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2003] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2003,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5128, ["count"] = 1}, {["monsterid"] = 5108, ["count"] = 1}, {["monsterid"] = 5122, ["count"] = 1}, {["monsterid"] = 5107, ["count"] = 1}, {["monsterid"] = 5106, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2004] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2004,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5105, ["count"] = 1}, {["monsterid"] = 5121, ["count"] = 1}, {["monsterid"] = 5127, ["count"] = 1}, {["monsterid"] = 5121, ["count"] = 1}, {["monsterid"] = 5108, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2005] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2005,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5122, ["count"] = 1}, {["monsterid"] = 5107, ["count"] = 1}, {["monsterid"] = 5131, ["count"] = 1}, {["monsterid"] = 5112, ["count"] = 1}, {["monsterid"] = 5105, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2006] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2006,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5128, ["count"] = 1}, {["monsterid"] = 5108, ["count"] = 1}, {["monsterid"] = 5112, ["count"] = 1}, {["monsterid"] = 5116, ["count"] = 1}, {["monsterid"] = 5107, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2007] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2007,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5112, ["count"] = 1}, {["monsterid"] = 5121, ["count"] = 1}, {["monsterid"] = 5105, ["count"] = 1}, {["monsterid"] = 5107, ["count"] = 1}, {["monsterid"] = 5116, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2008] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2008,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5127, ["count"] = 1}, {["monsterid"] = 5116, ["count"] = 1}, {["monsterid"] = 5112, ["count"] = 1}, {["monsterid"] = 5131, ["count"] = 1}, {["monsterid"] = 5105, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2009] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2009,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5121, ["count"] = 1}, {["monsterid"] = 5107, ["count"] = 1}, {["monsterid"] = 5127, ["count"] = 1}, {["monsterid"] = 5106, ["count"] = 1}, {["monsterid"] = 5105, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [2010] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "跑环传说",
        difficulty = {},
        friend = {},
        id = 2010,
        lineup = {1, 1},
        monster = {{["monsterid"] = 5128, ["count"] = 1}, {["monsterid"] = 5108, ["count"] = 1}, {["monsterid"] = 5123, ["count"] = 1}, {["monsterid"] = 5106, ["count"] = 1}, {["monsterid"] = 5127, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

}
