-- ./excel/fight/schoolpass.xlsx
return {

    [5258] = {
        action_id = {1004},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 1001,
        desc = "青城山",
        friend = {},
        id = 5258,
        lineup = {1, 1},
        mirror_school = 5,
        monster = {{["monsterid"] = 11001, ["count"] = 1}, {["monsterid"] = 11002, ["count"] = 2}, {["monsterid"] = 11003, ["count"] = 2}, {["monsterid"] = 13001, ["count"] = 1}, {["monsterid"] = 11004, ["count"] = 2}, {["monsterid"] = 11005, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5259] = {
        action_id = {1004},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 1002,
        desc = "蜀山",
        friend = {},
        id = 5259,
        lineup = {1, 1},
        mirror_school = 1,
        monster = {{["monsterid"] = 11011, ["count"] = 1}, {["monsterid"] = 11012, ["count"] = 2}, {["monsterid"] = 11013, ["count"] = 2}, {["monsterid"] = 13002, ["count"] = 1}, {["monsterid"] = 11014, ["count"] = 2}, {["monsterid"] = 11015, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5260] = {
        action_id = {1004},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 1003,
        desc = "太初",
        friend = {},
        id = 5260,
        lineup = {1, 1},
        mirror_school = 3,
        monster = {{["monsterid"] = 11021, ["count"] = 1}, {["monsterid"] = 11022, ["count"] = 2}, {["monsterid"] = 11023, ["count"] = 2}, {["monsterid"] = 13003, ["count"] = 1}, {["monsterid"] = 11024, ["count"] = 2}, {["monsterid"] = 11025, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5261] = {
        action_id = {1004},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 1004,
        desc = "妖神宫",
        friend = {},
        id = 5261,
        lineup = {1, 1},
        mirror_school = 6,
        monster = {{["monsterid"] = 11031, ["count"] = 1}, {["monsterid"] = 11032, ["count"] = 2}, {["monsterid"] = 11033, ["count"] = 2}, {["monsterid"] = 13004, ["count"] = 1}, {["monsterid"] = 11034, ["count"] = 2}, {["monsterid"] = 11035, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5262] = {
        action_id = {1004},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 1005,
        desc = "瑶池",
        friend = {},
        id = 5262,
        lineup = {1, 1},
        mirror_school = 4,
        monster = {{["monsterid"] = 11041, ["count"] = 1}, {["monsterid"] = 11042, ["count"] = 2}, {["monsterid"] = 11043, ["count"] = 2}, {["monsterid"] = 13005, ["count"] = 1}, {["monsterid"] = 11044, ["count"] = 2}, {["monsterid"] = 11045, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5263] = {
        action_id = {1004},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 1006,
        desc = "金山寺",
        friend = {},
        id = 5263,
        lineup = {1, 1},
        mirror_school = 2,
        monster = {{["monsterid"] = 11051, ["count"] = 1}, {["monsterid"] = 11052, ["count"] = 2}, {["monsterid"] = 11053, ["count"] = 2}, {["monsterid"] = 11054, ["count"] = 2}, {["monsterid"] = 11055, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5236] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 0,
        desc = "青城山",
        friend = {},
        id = 5236,
        lineup = {1, 1},
        mirror_school = 0,
        monster = {{["monsterid"] = 14001, ["count"] = 1}, {["monsterid"] = 14002, ["count"] = 2}, {["monsterid"] = 14003, ["count"] = 2}, {["monsterid"] = 14004, ["count"] = 2}, {["monsterid"] = 14005, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5237] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 0,
        desc = "蜀山",
        friend = {},
        id = 5237,
        lineup = {1, 1},
        mirror_school = 0,
        monster = {{["monsterid"] = 14011, ["count"] = 1}, {["monsterid"] = 14012, ["count"] = 2}, {["monsterid"] = 14013, ["count"] = 2}, {["monsterid"] = 14014, ["count"] = 2}, {["monsterid"] = 14015, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5238] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 0,
        desc = "太初",
        friend = {},
        id = 5238,
        lineup = {1, 1},
        mirror_school = 0,
        monster = {{["monsterid"] = 14021, ["count"] = 1}, {["monsterid"] = 14022, ["count"] = 2}, {["monsterid"] = 14023, ["count"] = 2}, {["monsterid"] = 14024, ["count"] = 2}, {["monsterid"] = 14025, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5239] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 0,
        desc = "妖神宫",
        friend = {},
        id = 5239,
        lineup = {1, 1},
        mirror_school = 0,
        monster = {{["monsterid"] = 14031, ["count"] = 1}, {["monsterid"] = 14032, ["count"] = 2}, {["monsterid"] = 14033, ["count"] = 2}, {["monsterid"] = 14034, ["count"] = 2}, {["monsterid"] = 14035, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5240] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 0,
        desc = "瑶池",
        friend = {},
        id = 5240,
        lineup = {1, 1},
        mirror_school = 0,
        monster = {{["monsterid"] = 14041, ["count"] = 1}, {["monsterid"] = 14042, ["count"] = 2}, {["monsterid"] = 14043, ["count"] = 2}, {["monsterid"] = 14044, ["count"] = 2}, {["monsterid"] = 14045, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

    [5241] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        custom_speek_id = 0,
        desc = "金山寺",
        friend = {},
        id = 5241,
        lineup = {1, 1},
        mirror_school = 0,
        monster = {{["monsterid"] = 14051, ["count"] = 1}, {["monsterid"] = 14052, ["count"] = 2}, {["monsterid"] = 14053, ["count"] = 2}, {["monsterid"] = 14054, ["count"] = 2}, {["monsterid"] = 14055, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        weather = 0,
    },

}
