-- ./excel/fight/shimen.xlsx
return {

    [61003] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61003,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11001, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61012] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61012,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11002, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61013] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61013,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11003, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61014] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61014,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11004, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61015] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61015,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11005, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61016] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61016,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11001, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61017] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61017,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11002, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61018] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61018,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11003, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61019] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61019,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11004, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61020] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门——战斗",
        friend = {},
        id = 61020,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11005, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 3}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61998] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门-收伏",
        friend = {},
        id = 61998,
        lineup = {1, 1},
        monster = {{["monsterid"] = 12002, ["count"] = 1}, {["monsterid"] = 11020, ["count"] = 2}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 61998,
        weather = 0,
    },

    [61999] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "师门-镜像战斗",
        friend = {},
        id = 61999,
        lineup = {1, 1},
        monster = {{["monsterid"] = 12001, ["count"] = 1}, {["monsterid"] = 12003, ["count"] = 1}, {["monsterid"] = 11011, ["count"] = 2}},
        monster_pos = {1, 6},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61103] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "蜀山——战斗",
        friend = {},
        id = 61103,
        lineup = {2, 1},
        monster = {{["monsterid"] = 11001, ["count"] = 1}, {["monsterid"] = 11020, ["count"] = 1}, {["monsterid"] = 11022, ["count"] = 1}, {["monsterid"] = 11024, ["count"] = 1}, {["monsterid"] = 11028, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61104] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "蜀山——战斗",
        friend = {},
        id = 61104,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11002, ["count"] = 1}, {["monsterid"] = 11021, ["count"] = 1}, {["monsterid"] = 11023, ["count"] = 1}, {["monsterid"] = 11026, ["count"] = 1}, {["monsterid"] = 11030, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61106] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "蜀山-镜像战斗",
        friend = {},
        id = 61106,
        lineup = {1, 1},
        monster = {{["monsterid"] = 12006, ["count"] = 1}, {["monsterid"] = 12003, ["count"] = 1}, {["monsterid"] = 12009, ["count"] = 1}, {["monsterid"] = 12010, ["count"] = 1}, {["monsterid"] = 12015, ["count"] = 1}, {["monsterid"] = 12014, ["count"] = 1}},
        monster_pos = {1, 6},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61107] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "蜀山-巡逻",
        friend = {},
        id = 61107,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11042, ["count"] = 1}, {["monsterid"] = 11043, ["count"] = 4}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61203] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "金山——战斗",
        friend = {},
        id = 61203,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11003, ["count"] = 1}, {["monsterid"] = 11021, ["count"] = 1}, {["monsterid"] = 11022, ["count"] = 1}, {["monsterid"] = 11024, ["count"] = 1}, {["monsterid"] = 11028, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61204] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "金山——战斗",
        friend = {},
        id = 61204,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11004, ["count"] = 1}, {["monsterid"] = 11021, ["count"] = 1}, {["monsterid"] = 11023, ["count"] = 1}, {["monsterid"] = 11026, ["count"] = 1}, {["monsterid"] = 11030, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61206] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "金山-镜像战斗",
        friend = {},
        id = 61206,
        lineup = {1, 1},
        monster = {{["monsterid"] = 12006, ["count"] = 1}, {["monsterid"] = 12003, ["count"] = 1}, {["monsterid"] = 12009, ["count"] = 1}, {["monsterid"] = 12012, ["count"] = 1}, {["monsterid"] = 12013, ["count"] = 1}, {["monsterid"] = 12020, ["count"] = 1}},
        monster_pos = {1, 6},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61207] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "金山-巡逻",
        friend = {},
        id = 61207,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11042, ["count"] = 1}, {["monsterid"] = 11043, ["count"] = 4}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61303] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "太初——战斗",
        friend = {},
        id = 61303,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11007, ["count"] = 1}, {["monsterid"] = 11021, ["count"] = 1}, {["monsterid"] = 11022, ["count"] = 1}, {["monsterid"] = 11029, ["count"] = 1}, {["monsterid"] = 11030, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61304] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "太初——战斗",
        friend = {},
        id = 61304,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11008, ["count"] = 1}, {["monsterid"] = 11023, ["count"] = 1}, {["monsterid"] = 11027, ["count"] = 1}, {["monsterid"] = 11030, ["count"] = 1}, {["monsterid"] = 11031, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61306] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "太初-镜像战斗",
        friend = {},
        id = 61306,
        lineup = {1, 1},
        monster = {{["monsterid"] = 12007, ["count"] = 1}, {["monsterid"] = 12003, ["count"] = 1}, {["monsterid"] = 12011, ["count"] = 1}, {["monsterid"] = 12016, ["count"] = 1}, {["monsterid"] = 12014, ["count"] = 1}, {["monsterid"] = 12019, ["count"] = 1}},
        monster_pos = {1, 6},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61307] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "太初-巡逻",
        friend = {},
        id = 61307,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11042, ["count"] = 1}, {["monsterid"] = 11043, ["count"] = 4}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61403] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "瑶池——战斗",
        friend = {},
        id = 61403,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11005, ["count"] = 1}, {["monsterid"] = 11020, ["count"] = 1}, {["monsterid"] = 11023, ["count"] = 1}, {["monsterid"] = 11030, ["count"] = 1}, {["monsterid"] = 11031, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61404] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "瑶池——战斗",
        friend = {},
        id = 61404,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11006, ["count"] = 1}, {["monsterid"] = 11020, ["count"] = 1}, {["monsterid"] = 11021, ["count"] = 1}, {["monsterid"] = 11024, ["count"] = 1}, {["monsterid"] = 11026, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61406] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "瑶池-镜像战斗",
        friend = {},
        id = 61406,
        lineup = {1, 1},
        monster = {{["monsterid"] = 12007, ["count"] = 1}, {["monsterid"] = 12003, ["count"] = 1}, {["monsterid"] = 12018, ["count"] = 1}, {["monsterid"] = 12012, ["count"] = 1}, {["monsterid"] = 12010, ["count"] = 1}, {["monsterid"] = 12014, ["count"] = 1}},
        monster_pos = {1, 6},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61407] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "瑶池-巡逻",
        friend = {},
        id = 61407,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11042, ["count"] = 1}, {["monsterid"] = 11043, ["count"] = 4}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61503] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "青城——战斗",
        friend = {},
        id = 61503,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11009, ["count"] = 1}, {["monsterid"] = 11020, ["count"] = 1}, {["monsterid"] = 11023, ["count"] = 1}, {["monsterid"] = 11029, ["count"] = 1}, {["monsterid"] = 11030, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61504] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "青城——战斗",
        friend = {},
        id = 61504,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11010, ["count"] = 1}, {["monsterid"] = 11021, ["count"] = 1}, {["monsterid"] = 11024, ["count"] = 1}, {["monsterid"] = 11028, ["count"] = 1}, {["monsterid"] = 11031, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61506] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "青城-镜像战斗",
        friend = {},
        id = 61506,
        lineup = {1, 1},
        monster = {{["monsterid"] = 12008, ["count"] = 1}, {["monsterid"] = 12003, ["count"] = 1}, {["monsterid"] = 12009, ["count"] = 1}, {["monsterid"] = 12010, ["count"] = 1}, {["monsterid"] = 12012, ["count"] = 1}, {["monsterid"] = 12014, ["count"] = 1}},
        monster_pos = {1, 6},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61507] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "青城-巡逻",
        friend = {},
        id = 61507,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11042, ["count"] = 1}, {["monsterid"] = 11043, ["count"] = 4}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61603] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "妖神——战斗",
        friend = {},
        id = 61603,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11011, ["count"] = 1}, {["monsterid"] = 11022, ["count"] = 1}, {["monsterid"] = 11028, ["count"] = 1}, {["monsterid"] = 11029, ["count"] = 1}, {["monsterid"] = 11030, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61604] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "妖神——战斗",
        friend = {},
        id = 61604,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11012, ["count"] = 1}, {["monsterid"] = 11023, ["count"] = 1}, {["monsterid"] = 11024, ["count"] = 1}, {["monsterid"] = 11028, ["count"] = 1}, {["monsterid"] = 11031, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61606] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "妖神-镜像战斗",
        friend = {},
        id = 61606,
        lineup = {1, 1},
        monster = {{["monsterid"] = 12008, ["count"] = 1}, {["monsterid"] = 12003, ["count"] = 1}, {["monsterid"] = 12020, ["count"] = 1}, {["monsterid"] = 12010, ["count"] = 1}, {["monsterid"] = 12013, ["count"] = 1}, {["monsterid"] = 12016, ["count"] = 1}},
        monster_pos = {1, 6},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [61607] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "妖神-巡逻",
        friend = {},
        id = 61607,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11042, ["count"] = 1}, {["monsterid"] = 11043, ["count"] = 4}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

}
