-- ./excel/fight/shimen.xlsx
return {

    [11001] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "师门蜀山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 12101,
        hp = "100+level*100+(level-20)*level",
        id = 11001,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11002] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1401, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1403, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "师门蜀山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 12201,
        hp = "100+level*100+(level-20)*level",
        id = 11002,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11003] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1401, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1403, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "师门金山寺",
        dodgeRate = "0",
        expertskill = {},
        figureid = 12101,
        hp = "100+level*50+(level-20)*level",
        id = 11003,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11004] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "师门金山寺",
        dodgeRate = "0",
        expertskill = {},
        figureid = 12201,
        hp = "100+level*50+(level-20)*level",
        id = 11004,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11005] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1501, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1503, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "师门瑶池",
        dodgeRate = "0",
        expertskill = {},
        figureid = 13101,
        hp = "100+level*50+(level-20)*level",
        id = 11005,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11006] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1601, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "师门瑶池",
        dodgeRate = "0",
        expertskill = {},
        figureid = 13201,
        hp = "100+level*50+(level-20)*level",
        id = 11006,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11007] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1601, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "师门太初",
        dodgeRate = "0",
        expertskill = {},
        figureid = 13101,
        hp = "100+level*80+(level-20)*level",
        id = 11007,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11008] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1501, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1503, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "师门太初",
        dodgeRate = "0",
        expertskill = {},
        figureid = 13201,
        hp = "100+level*80+(level-20)*level",
        id = 11008,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11009] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1201, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1202, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "师门青城山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 11101,
        hp = "100+level*50+(level-20)*level",
        id = 11009,
        is_boss = 1,
        level = "LV",
        magAttack = "level*7+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11010] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1104, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "师门青城山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 11201,
        hp = "100+level*50+(level-20)*level",
        id = 11010,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11011] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1201, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1202, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "师门妖神宫",
        dodgeRate = "0",
        expertskill = {},
        figureid = 11201,
        hp = "100+level*100+(level-20)*level",
        id = 11011,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11012] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1104, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "师门妖神宫",
        dodgeRate = "0",
        expertskill = {},
        figureid = 11101,
        hp = "100+level*100+(level-20)*level",
        id = 11012,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11020] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "许仙太初",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2101,
        hp = "100+level*30+(level-20)*level",
        id = 11020,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "许仙",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11021] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "璃镜太初",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2102,
        hp = "100+level*30+(level-20)*level",
        id = 11021,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "璃镜",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11022] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1104, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "洛凝霜蜀山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2201,
        hp = "100+level*30+(level-20)*level",
        id = 11022,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "洛凝霜",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11023] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1104, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "渊记蜀山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2202,
        hp = "100+level*30+(level-20)*level",
        id = 11023,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "渊记",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11024] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1501, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1503, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "白素贞青城",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2301,
        hp = "100+level*30+(level-20)*level",
        id = 11024,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "白素贞",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11025] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1501, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1503, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "小青青城",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2302,
        hp = "100+level*30+(level-20)*level",
        id = 11025,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "小青",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11026] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1201, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1202, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "法海金山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2401,
        hp = "100+level*30+(level-20)*level",
        id = 11026,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "法海",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11027] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1201, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1202, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "道济金山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2402,
        hp = "100+level*30+(level-20)*level",
        id = 11027,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "道济",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11028] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1401, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1403, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "龙吉公主瑶池",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2501,
        hp = "100+level*30+(level-20)*level",
        id = 11028,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "龙吉公主",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11029] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1401, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1403, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "九天玄女瑶池",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2502,
        hp = "100+level*30+(level-20)*level",
        id = 11029,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "九天玄女",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11030] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1601, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1602, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "时未寒妖神",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2601,
        hp = "100+level*30+(level-20)*level",
        id = 11030,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "时未寒",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11031] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1601, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1602, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "昊离归妖神",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2602,
        hp = "100+level*30+(level-20)*level",
        id = 11031,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "昊离归",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11040] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "巡逻",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5103,
        hp = "100+level*30+(level-20)*level",
        id = 11040,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "鬼祟的蛤蟆精",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11041] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "巡逻",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5101,
        hp = "100+level*30+(level-20)*level",
        id = 11041,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "哈士奇喽啰",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11042] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "巡逻",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5102,
        hp = "100+level*60+(level-20)*level",
        id = 11042,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "迷路的笋精",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11043] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "巡逻",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5105,
        hp = "100+level*30+(level-20)*level",
        id = 11043,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "笋精的玩具",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [11044] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "巡逻",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5106,
        hp = "100+level*60+(level-20)*level",
        id = 11044,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "鬼祟的熊猫",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12001] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "师门",
        dodgeRate = "0",
        expertskill = {},
        figureid = 1110,
        hp = "(100+level*10+(level-20)*(level-20)/10)*2",
        id = 12001,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$mirror",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12002] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "师门",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5113,
        hp = "(100+level*10+(level-20)*(level-20)/10)*2",
        id = 12002,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12003] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "师门宠物",
        dodgeRate = "0",
        expertskill = {},
        figureid = 1110,
        hp = "(100+level*10+(level-20)*(level-20)/10)*2",
        id = 12003,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$mirror_summ",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12004] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "师门",
        dodgeRate = "0",
        expertskill = {},
        figureid = 1110,
        hp = "(100+level*10+(level-20)*(level-20)/10)*2",
        id = 12004,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$mirror",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12006] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "师门蜀山、金山寺",
        dodgeRate = "0",
        expertskill = {},
        figureid = 12101,
        hp = "100+level*100+(level-20)*level",
        id = 12006,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$mirror",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12007] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "师门瑶池、太初",
        dodgeRate = "0",
        expertskill = {},
        figureid = 13101,
        hp = "100+level*100+(level-20)*level",
        id = 12007,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$mirror",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12008] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "师门青城山、妖神宫",
        dodgeRate = "0",
        expertskill = {},
        figureid = 11101,
        hp = "100+level*100+(level-20)*level",
        id = 12008,
        is_boss = 1,
        level = "LV",
        magAttack = "level*8+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$mirror",
        passiveSkills = {},
        phyAttack = "level*11+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12009] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "许仙太初",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2101,
        hp = "100+level*30+(level-20)*level",
        id = 12009,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "许仙",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12010] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "璃镜太初",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2102,
        hp = "100+level*30+(level-20)*level",
        id = 12010,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "璃镜",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12011] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1104, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "洛凝霜蜀山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2201,
        hp = "100+level*30+(level-20)*level",
        id = 12011,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "洛凝霜",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12012] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1104, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "渊记蜀山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2202,
        hp = "100+level*30+(level-20)*level",
        id = 12012,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "渊记",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12013] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1501, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1503, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "白素贞青城",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2301,
        hp = "100+level*30+(level-20)*level",
        id = 12013,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "白素贞",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12014] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1501, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1503, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "小青青城",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2302,
        hp = "100+level*30+(level-20)*level",
        id = 12014,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "小青",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12015] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1201, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1202, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "法海金山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2401,
        hp = "100+level*30+(level-20)*level",
        id = 12015,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "法海",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12016] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1201, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1202, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "道济金山",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2402,
        hp = "100+level*30+(level-20)*level",
        id = 12016,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "道济",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12017] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1401, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1403, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "龙吉公主瑶池",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2501,
        hp = "100+level*30+(level-20)*level",
        id = 12017,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "龙吉公主",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12018] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1401, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 3, ["pfid"] = 1403, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "九天玄女瑶池",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2502,
        hp = "100+level*30+(level-20)*level",
        id = 12018,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "九天玄女",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12019] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1601, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1602, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "时未寒妖神",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2601,
        hp = "100+level*30+(level-20)*level",
        id = 12019,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "时未寒",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

    [12020] = {
        activeSkills = {{["lv"] = 3, ["pfid"] = 1601, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 3, ["pfid"] = 1602, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 401,
        critRate = "0",
        desc = "昊离归妖神",
        dodgeRate = "0",
        expertskill = {},
        figureid = 2602,
        hp = "100+level*30+(level-20)*level",
        id = 12020,
        is_boss = 0,
        level = "LV",
        magAttack = "level*6.5+(level-30)*7+100",
        magDefense = "level*2+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "昊离归",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+100",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*3",
    },

}
