-- ./excel/fight/side.xlsx
return {

    [1001] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "30级",
        difficulty = {},
        friend = {},
        id = 1001,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10011, ["count"] = 1}, {["monsterid"] = 10012, ["count"] = 4}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1002] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "30级",
        difficulty = {},
        friend = {},
        id = 1002,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10021, ["count"] = 1}, {["monsterid"] = 10022, ["count"] = 5}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1003] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "30级",
        difficulty = {},
        friend = {},
        id = 1003,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10031, ["count"] = 1}, {["monsterid"] = 10032, ["count"] = 4}},
        sky_war = 0,
        speek_id = 1003,
        war_confirm = 0,
        weather = 0,
    },

    [1004] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "35级",
        difficulty = {},
        friend = {},
        id = 1004,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10041, ["count"] = 3}, {["monsterid"] = 10042, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1005] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "35级",
        difficulty = {},
        friend = {},
        id = 1005,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10051, ["count"] = 3}, {["monsterid"] = 10052, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1006] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "35级",
        difficulty = {},
        friend = {},
        id = 1006,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10061, ["count"] = 1}, {["monsterid"] = 10062, ["count"] = 1}, {["monsterid"] = 10063, ["count"] = 5}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1007] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "35级",
        difficulty = {},
        friend = {},
        id = 1007,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10071, ["count"] = 1}, {["monsterid"] = 10072, ["count"] = 4}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1008] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "40级",
        difficulty = {},
        friend = {{["monsterid"] = 10083, ["count"] = 1}},
        id = 1008,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10081, ["count"] = 1}, {["monsterid"] = 10082, ["count"] = 4}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1009] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "40级",
        difficulty = {},
        friend = {{["monsterid"] = 10093, ["count"] = 1}},
        id = 1009,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10091, ["count"] = 1}, {["monsterid"] = 10092, ["count"] = 4}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1010] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "53级",
        difficulty = {50},
        friend = {},
        id = 1010,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10101, ["count"] = 1}, {["monsterid"] = 10102, ["count"] = 2}, {["monsterid"] = 10103, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1011] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "53级",
        difficulty = {50},
        friend = {},
        id = 1011,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10111, ["count"] = 3}, {["monsterid"] = 10112, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1012] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 1,
        desc = "53级",
        difficulty = {50},
        friend = {},
        id = 1012,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10121, ["count"] = 1}, {["monsterid"] = 10122, ["count"] = 4}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1013] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "55级",
        difficulty = {50},
        friend = {},
        id = 1013,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10131, ["count"] = 1}, {["monsterid"] = 10132, ["count"] = 4}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1014] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "55级",
        difficulty = {50},
        friend = {{["monsterid"] = 10143, ["count"] = 1}},
        id = 1014,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10141, ["count"] = 1}, {["monsterid"] = 10142, ["count"] = 4}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1015] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "55级",
        difficulty = {50},
        friend = {{["monsterid"] = 10153, ["count"] = 1}},
        id = 1015,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10151, ["count"] = 1}, {["monsterid"] = 10152, ["count"] = 4}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1016] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "60级",
        difficulty = {60},
        friend = {},
        id = 1016,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10161, ["count"] = 1}, {["monsterid"] = 10162, ["count"] = 3}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1017] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "60级",
        difficulty = {60},
        friend = {},
        id = 1017,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10171, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1018] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "60级",
        difficulty = {60},
        friend = {},
        id = 1018,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10181, ["count"] = 1}, {["monsterid"] = 10182, ["count"] = 3}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1019] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "60级",
        difficulty = {60},
        friend = {},
        id = 1019,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10191, ["count"] = 1}, {["monsterid"] = 10192, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

}
