-- ./excel/fight/test.xlsx
return {

    [10001] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "测试NPC",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5103,
        hp = "500",
        id = 10001,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "豆豆",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.4",
        speed = "level*1+5",
    },

    [10002] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "测试NPC",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5103,
        hp = "50000",
        id = 10002,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "大豆",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.6",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*1+5",
    },

    [10003] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "友军",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5103,
        hp = "500",
        id = 10003,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "豆豆",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.7",
        phy_hit_res_ratio = "5+level*0.6",
        speed = "level*1+5",
    },

    [11001] = {
        activeSkills = {{["lv"] = 2, ["pfid"] = 1607, ["ratio"] = 0}},
        aitype = 10001,
        critRate = "0",
        desc = "许仙",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2101,
        hp = "5000",
        id = 11001,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "许仙",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.8",
        phy_hit_res_ratio = "5+level*0.7",
        speed = "level*1+5",
    },

    [11002] = {
        activeSkills = {{["lv"] = 1, ["pfid"] = 1307, ["ratio"] = 0}},
        aitype = 10002,
        critRate = "0",
        desc = "李玉致",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2102,
        hp = "50000",
        id = 11002,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "李玉致",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.9",
        phy_hit_res_ratio = "5+level*0.8",
        speed = "level*1+5",
    },

    [11003] = {
        activeSkills = {{["lv"] = 1, ["pfid"] = 1107, ["ratio"] = 0}},
        aitype = 10003,
        critRate = "0",
        desc = "林嘉",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2201,
        hp = "500",
        id = 11003,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "林嘉",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.10",
        phy_hit_res_ratio = "5+level*0.9",
        speed = "level*1+5",
    },

    [11004] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "秦剑",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2202,
        hp = "500",
        id = 11004,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "秦剑",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.11",
        phy_hit_res_ratio = "5+level*0.10",
        speed = "level*1+5",
    },

    [11005] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "白素贞",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2301,
        hp = "500",
        id = 11005,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "白素贞",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.12",
        phy_hit_res_ratio = "5+level*0.11",
        speed = "level*1+5",
    },

    [11006] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "小青",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2302,
        hp = "500",
        id = 11006,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "小青",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.13",
        phy_hit_res_ratio = "5+level*0.12",
        speed = "level*1+5",
    },

    [11007] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "法海",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2401,
        hp = "500",
        id = 11007,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "法海",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.14",
        phy_hit_res_ratio = "5+level*0.13",
        speed = "level*1+5",
    },

    [11008] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "道济",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2402,
        hp = "500",
        id = 11008,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "道济",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.15",
        phy_hit_res_ratio = "5+level*0.14",
        speed = "level*1+5",
    },

    [11009] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "龙吉公主",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2501,
        hp = "500",
        id = 11009,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "龙吉公主",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.16",
        phy_hit_res_ratio = "5+level*0.15",
        speed = "level*1+5",
    },

    [11010] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "九天玄女",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2502,
        hp = "50000",
        id = 11010,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "九天玄女",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.17",
        phy_hit_res_ratio = "5+level*0.16",
        speed = "level*1+5",
    },

    [11011] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "后羿",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2601,
        hp = "500",
        id = 11011,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "后羿",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.18",
        phy_hit_res_ratio = "5+level*0.17",
        speed = "level*1+5",
    },

    [11012] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "东皇太一",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2602,
        hp = "500",
        id = 11012,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "东皇太一",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.19",
        phy_hit_res_ratio = "5+level*0.18",
        speed = "level*1+5",
    },

    [11013] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "哈士奇",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5101,
        hp = "500",
        id = 11013,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "哈士奇",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.20",
        phy_hit_res_ratio = "5+level*0.19",
        speed = "level*1+5",
    },

    [11014] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "笋儿",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5102,
        hp = "500",
        id = 11014,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "笋儿",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.21",
        phy_hit_res_ratio = "5+level*0.20",
        speed = "level*1+5",
    },

    [11015] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "蛤蟆精",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5103,
        hp = "500",
        id = 11015,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "蛤蟆精",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.22",
        phy_hit_res_ratio = "5+level*0.21",
        speed = "level*1+5",
    },

    [11016] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "兔精",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5104,
        hp = "500",
        id = 11016,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "兔精",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.23",
        phy_hit_res_ratio = "5+level*0.22",
        speed = "level*1+5",
    },

    [11017] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "机关兽",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5105,
        hp = "500",
        id = 11017,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "机关兽",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.24",
        phy_hit_res_ratio = "5+level*0.23",
        speed = "level*1+5",
    },

    [11018] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "熊猫武师",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5106,
        hp = "50000",
        id = 11018,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "熊猫武师",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.25",
        phy_hit_res_ratio = "5+level*0.24",
        speed = "level*1+5",
    },

    [11019] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "剑灵",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5107,
        hp = "500",
        id = 11019,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "剑灵",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.26",
        phy_hit_res_ratio = "5+level*0.25",
        speed = "level*1+5",
    },

    [11020] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "天师道人",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5108,
        hp = "500",
        id = 11020,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天师道人",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.27",
        phy_hit_res_ratio = "5+level*0.26",
        speed = "level*1+5",
    },

    [11021] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "龙人",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5109,
        hp = "500",
        id = 11021,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "龙人",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.28",
        phy_hit_res_ratio = "5+level*0.27",
        speed = "level*1+5",
    },

    [11022] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "天狗",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5110,
        hp = "500",
        id = 11022,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天狗",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.29",
        phy_hit_res_ratio = "5+level*0.28",
        speed = "level*1+5",
    },

    [11023] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "秋田犬",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5111,
        hp = "500",
        id = 11023,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "秋田犬",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.30",
        phy_hit_res_ratio = "5+level*0.29",
        speed = "level*1+5",
    },

    [11024] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "仙鹤童子",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5112,
        hp = "500",
        id = 11024,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "仙鹤童子",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.31",
        phy_hit_res_ratio = "5+level*0.30",
        speed = "level*1+5",
    },

    [11025] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "飞羽将军",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5113,
        hp = "500",
        id = 11025,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "飞羽将军",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.32",
        phy_hit_res_ratio = "5+level*0.31",
        speed = "level*1+5",
    },

    [11026] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "织梦花妖",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5114,
        hp = "50000",
        id = 11026,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "织梦花妖",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.33",
        phy_hit_res_ratio = "5+level*0.32",
        speed = "level*1+5",
    },

    [11027] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "浪人",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5115,
        hp = "500",
        id = 11027,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "浪人",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.34",
        phy_hit_res_ratio = "5+level*0.33",
        speed = "level*1+5",
    },

    [11028] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "如意仙",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5116,
        hp = "500",
        id = 11028,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "如意仙",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.35",
        phy_hit_res_ratio = "5+level*0.34",
        speed = "level*1+5",
    },

    [11029] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "阴阳师",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5117,
        hp = "500",
        id = 11029,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "阴阳师",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.36",
        phy_hit_res_ratio = "5+level*0.35",
        speed = "level*1+5",
    },

    [11030] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "女魃",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5118,
        hp = "500",
        id = 11030,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "女魃",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.37",
        phy_hit_res_ratio = "5+level*0.36",
        speed = "level*1+5",
    },

    [11031] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "罗刹女",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5119,
        hp = "500",
        id = 11031,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "罗刹女",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.38",
        phy_hit_res_ratio = "5+level*0.37",
        speed = "level*1+5",
    },

    [11032] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "泥石人",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5120,
        hp = "500",
        id = 11032,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "泥石人",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.39",
        phy_hit_res_ratio = "5+level*0.38",
        speed = "level*1+5",
    },

    [11033] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "插翅虎",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5121,
        hp = "500",
        id = 11033,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "插翅虎",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.40",
        phy_hit_res_ratio = "5+level*0.39",
        speed = "level*1+5",
    },

    [11034] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "剑侠",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5122,
        hp = "50000",
        id = 11034,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "剑侠",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.41",
        phy_hit_res_ratio = "5+level*0.40",
        speed = "level*1+5",
    },

    [11035] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "大鹏鸟",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5123,
        hp = "500",
        id = 11035,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "大鹏鸟",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.42",
        phy_hit_res_ratio = "5+level*0.41",
        speed = "level*1+5",
    },

    [11036] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "水君",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5124,
        hp = "500",
        id = 11036,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "水君",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.43",
        phy_hit_res_ratio = "5+level*0.42",
        speed = "level*1+5",
    },

    [11037] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "枪天将",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5125,
        hp = "500",
        id = 11037,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "枪天将",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.44",
        phy_hit_res_ratio = "5+level*0.43",
        speed = "level*1+5",
    },

    [11038] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "鬼帝",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5126,
        hp = "500",
        id = 11038,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "鬼帝",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.45",
        phy_hit_res_ratio = "5+level*0.44",
        speed = "level*1+5",
    },

    [11039] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "天璇仙子",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5127,
        hp = "500",
        id = 11039,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天璇仙子",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.46",
        phy_hit_res_ratio = "5+level*0.45",
        speed = "level*1+5",
    },

    [11040] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "桃花妖",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5128,
        hp = "500",
        id = 11040,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "桃花妖",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.47",
        phy_hit_res_ratio = "5+level*0.46",
        speed = "level*1+5",
    },

    [11041] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "雪女",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5129,
        hp = "500",
        id = 11041,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "雪女",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.48",
        phy_hit_res_ratio = "5+level*0.47",
        speed = "level*1+5",
    },

    [11042] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "媚魔",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5130,
        hp = "50000",
        id = 11042,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "媚魔",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.49",
        phy_hit_res_ratio = "5+level*0.48",
        speed = "level*1+5",
    },

    [11043] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "神犬骑兵",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5131,
        hp = "500",
        id = 11043,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "神犬骑兵",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.50",
        phy_hit_res_ratio = "5+level*0.49",
        speed = "level*1+5",
    },

    [11044] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "虎傀儡",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5132,
        hp = "500",
        id = 11044,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "虎傀儡",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.51",
        phy_hit_res_ratio = "5+level*0.50",
        speed = "level*1+5",
    },

    [11045] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "熊猫剑侠",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5133,
        hp = "500",
        id = 11045,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "熊猫剑侠",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.52",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11046] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "迦楼罗",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5134,
        hp = "500",
        id = 11046,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "迦楼罗",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.53",
        phy_hit_res_ratio = "5+level*0.52",
        speed = "level*1+5",
    },

    [11047] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "龙女",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5135,
        hp = "500",
        id = 11047,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "龙女",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.54",
        phy_hit_res_ratio = "5+level*0.53",
        speed = "level*1+5",
    },

    [11048] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "真君",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5136,
        hp = "500",
        id = 11048,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "真君",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.55",
        phy_hit_res_ratio = "5+level*0.54",
        speed = "level*1+5",
    },

    [11049] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "瑶光圣女",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5137,
        hp = "500",
        id = 11049,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "瑶光圣女",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.56",
        phy_hit_res_ratio = "5+level*0.55",
        speed = "level*1+5",
    },

    [11050] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "花神君",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5138,
        hp = "50000",
        id = 11050,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "花神君",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.57",
        phy_hit_res_ratio = "5+level*0.56",
        speed = "level*1+5",
    },

    [11051] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "万年冰魇",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5139,
        hp = "500",
        id = 11051,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "万年冰魇",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.58",
        phy_hit_res_ratio = "5+level*0.57",
        speed = "level*1+5",
    },

    [11088] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 3000, ["ai_target"] = 2, ["ratio"] = 40}},
        aitype = 401,
        critRate = "0",
        desc = "test主线战斗",
        dodgeRate = "0",
        expertskill = {},
        figureid = 3116,
        hp = "400",
        id = 11088,
        is_boss = 0,
        level = "LV",
        magAttack = "60",
        magDefense = "10",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "静荷",
        passiveSkills = {},
        phyAttack = "60",
        phyDefense = "10",
        phy_hit_ratio = "LV",
        phy_hit_res_ratio = "5139",
        speed = "50",
    },

    [11089] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 3000, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 3008, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 1107, ["ai_target"] = 2, ["ratio"] = 0}},
        aitype = 401,
        critRate = "0",
        desc = "test主线战斗",
        dodgeRate = "0",
        expertskill = {},
        figureid = 1110,
        hp = "200",
        id = 11089,
        is_boss = 0,
        level = "LV",
        magAttack = "80",
        magDefense = "10",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "剑侍",
        passiveSkills = {},
        phyAttack = "80",
        phyDefense = "10",
        phy_hit_ratio = "LV",
        phy_hit_res_ratio = "5139",
        speed = "30",
    },

    [11090] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "test主线战斗",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5114,
        hp = "100",
        id = 11090,
        is_boss = 0,
        level = "LV",
        magAttack = "50",
        magDefense = "10",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "小妖",
        passiveSkills = {},
        phyAttack = "50",
        phyDefense = "10",
        phy_hit_ratio = "LV",
        phy_hit_res_ratio = "5139",
        speed = "30",
    },

    [11091] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "鬼魂宠",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5111,
        hp = "50000",
        id = 11091,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "鬼魂宠",
        passiveSkills = {{["lv"] = 1, ["pfid"] = 5116}},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.30",
        phy_hit_res_ratio = "5+level*0.29",
        speed = "level*1+5",
    },

    [11092] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1502}},
        aitype = 101,
        critRate = "0",
        desc = "封印宠",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5112,
        hp = "50000",
        id = 11092,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "封印宠",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.31",
        phy_hit_res_ratio = "5+level*0.30",
        speed = "level*1+5",
    },

    [11093] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "飞羽将军",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5113,
        hp = "50000",
        id = 11093,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "飞羽将军",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.32",
        phy_hit_res_ratio = "5+level*0.31",
        speed = "level*1+5",
    },

    [11094] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 4254}},
        aitype = 101,
        critRate = "0",
        desc = "嘲讽",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2401,
        hp = "5000",
        id = 11094,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "嘲讽",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.55",
        phy_hit_res_ratio = "5+level*0.54",
        speed = "level*1+5",
    },

    [11095] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 5101}},
        aitype = 401,
        critRate = "0",
        desc = "反击",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5134,
        hp = "3000",
        id = 11095,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "反击",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.53",
        phy_hit_res_ratio = "5+level*0.52",
        speed = "level*1+5",
    },

    [11096] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "熊猫剑侠",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5133,
        hp = "2500",
        id = 11096,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "熊猫剑侠",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.52",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11097] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1606, ["ai_target"] = 1, ["ratio"] = 40}},
        aitype = 101,
        critRate = "0",
        desc = "剑道巅峰小怪",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1120,
        hp = "10000",
        id = 11097,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "同门师弟",
        passiveSkills = {},
        phyAttack = "level*5+30",
        phyDefense = "level*2-15",
        phy_hit_ratio = "100+level*0.52",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11098] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1203, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 101,
        critRate = "0",
        desc = "剑道巅峰小怪",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "10000",
        id = 11098,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "同门师妹",
        passiveSkills = {},
        phyAttack = "50000",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11099] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1104, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 101,
        critRate = "0",
        desc = "剑道巅峰小怪",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "50000",
        id = 11099,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "豆豆1",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11100] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1303, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 101,
        critRate = "0",
        desc = "剑道巅峰小怪",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "50000",
        id = 11100,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "豆豆2",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11101] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1507, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 101,
        critRate = "0",
        desc = "剑道巅峰小怪",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "50000",
        id = 11101,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "豆豆3",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11102] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 9024, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 101,
        critRate = "0",
        desc = "剑道巅峰小怪",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "50000",
        id = 11102,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "豆豆4",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11103] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1602, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 101,
        critRate = "0",
        desc = "剑道巅峰小怪",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "50000",
        id = 11103,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "豆豆5",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11104] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "天兵1",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "500000",
        id = 11104,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵1",
        passiveSkills = {{["lv"] = 3, ["pfid"] = 5137}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "550",
    },

    [11105] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1306, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 101,
        critRate = "0",
        desc = "天兵2",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "500001",
        id = 11105,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵2",
        passiveSkills = {{["lv"] = 3, ["pfid"] = 5137}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "550",
    },

    [11106] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1203, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 101,
        critRate = "0",
        desc = "天兵2",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5113,
        hp = "500002",
        id = 11106,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵2",
        passiveSkills = {{["lv"] = 3, ["pfid"] = 5137}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "550",
    },

    [11107] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 5212, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 401,
        critRate = "0",
        desc = "鬼王",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5128,
        hp = "500003",
        id = 11107,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "鬼王",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 5101}, {["lv"] = 5, ["pfid"] = 5115}, {["lv"] = 1, ["pfid"] = 5531}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "550",
    },

    [11108] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 401,
        critRate = "0",
        desc = "鬼帝",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5128,
        hp = "500004",
        id = 11108,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "鬼帝",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 5101}, {["lv"] = 5, ["pfid"] = 5115}, {["lv"] = 1, ["pfid"] = 5531}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "550",
    },

    [11109] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1102, ["ai_target"] = 1, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 1, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 1201, ["ai_target"] = 1, ["ratio"] = 0}},
        aitype = 302,
        critRate = "0",
        desc = "鬼皇",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5128,
        hp = "500005",
        id = 11109,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "鬼皇",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11110] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛1",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11110,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛1",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11111] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛2",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11111,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛2",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11112] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛3",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11112,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛3",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11113] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛4",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11113,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛4",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11114] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛5",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11114,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛5",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11115] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛6",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11115,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛6",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11116] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛7",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11116,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛7",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11117] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛8",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11117,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛8",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11118] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛9",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11118,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛9",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11119] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "毛毛10",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11119,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛10",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11120] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 1, ["ratio"] = 80}},
        aitype = 101,
        critRate = "0",
        desc = "毛毛10",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11120,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛10",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11121] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1202, ["ai_target"] = 29, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "毛毛5",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11121,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛5",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11122] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1502, ["ai_target"] = 30, ["ratio"] = 100}},
        aitype = 401,
        critRate = "0",
        desc = "毛毛6",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11122,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛6",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11123] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1505, ["ai_target"] = 31, ["ratio"] = 100}},
        aitype = 401,
        critRate = "0",
        desc = "毛毛7",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11123,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛7",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11124] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1507, ["ai_target"] = 32, ["ratio"] = 100}},
        aitype = 401,
        critRate = "0",
        desc = "毛毛8",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11124,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛8",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11125] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1205, ["ai_target"] = 1, ["ratio"] = 90}, {["lv"] = 5, ["pfid"] = 1202, ["ai_target"] = 29, ["ratio"] = 10}},
        aitype = 401,
        critRate = "0",
        desc = "毛毛9",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11125,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "毛毛9",
        passiveSkills = {{["lv"] = 3, ["pfid"] = 3014}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11126] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 3021, ["ai_target"] = 2, ["ratio"] = 60}, {["lv"] = 5, ["pfid"] = 3006, ["ai_target"] = 2, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 3032, ["ai_target"] = 2, ["ratio"] = 0}},
        aitype = 302,
        critRate = "0",
        desc = "魔帝幻象",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 6101,
        hp = "500005",
        id = 11126,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "魔帝幻象",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4200}, {["lv"] = 5, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 4255}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11127] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 3017, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 3028, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 302,
        critRate = "0",
        desc = "南方鬼帝",
        dodgeRate = "0",
        expertskill = {"5", "5", "5", "5"},
        figureid = 6104,
        hp = "(level*250+(level-20)*level+100)*2.25",
        id = 11127,
        is_boss = 0,
        level = "LV",
        magAttack = "(level*20+50)*1.15",
        magDefense = "level*6+50+30",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "南方鬼帝",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4200}, {["lv"] = 5, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 4255}, {["lv"] = 5, ["pfid"] = 5108}, {["lv"] = 1, ["pfid"] = 4211}},
        phyAttack = "(level*25+50)*1.15",
        phyDefense = "level*8+50+30",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*10",
    },

    [11128] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 1306, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 302,
        critRate = "0",
        desc = "法海魔相",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 6105,
        hp = "500005",
        id = 11128,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "法海魔相",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4200}, {["lv"] = 5, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 4255}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11129] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 3020, ["ai_target"] = 4, ["ratio"] = 60}, {["lv"] = 5, ["pfid"] = 5210, ["ai_target"] = 4, ["ratio"] = 40}},
        aitype = 303,
        critRate = "0",
        desc = "金钹法王",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 6102,
        hp = "500005",
        id = 11129,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "金钹法王",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4200}, {["lv"] = 5, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 4255}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11130] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1401, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 3011, ["ai_target"] = 2, ["ratio"] = 50}},
        aitype = 302,
        critRate = "0",
        desc = "特殊怪",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 1110,
        hp = "500005",
        id = 11130,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$player",
        passiveSkills = {{["lv"] = 1, ["pfid"] = 5118}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11131] = {
        activeSkills = {},
        aitype = 101,
        critRate = "0",
        desc = "特殊怪",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5103,
        hp = "500005",
        id = 11131,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "剧毒蛤蟆",
        passiveSkills = {{["lv"] = 2, ["pfid"] = 4251}, {["lv"] = 5, ["pfid"] = 4253}, {["lv"] = 5, ["pfid"] = 4252}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11132] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1502, ["ai_target"] = 28, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1505, ["ai_target"] = 28, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1507, ["ai_target"] = 30, ["ratio"] = 20}},
        aitype = 302,
        critRate = "0",
        desc = "青城（通用）",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5112,
        hp = "500005",
        id = 11132,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "御风",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11133] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1202, ["ai_target"] = 29, ["ratio"] = 35}, {["lv"] = 5, ["pfid"] = 1203, ["ai_target"] = 3, ["ratio"] = 35}, {["lv"] = 5, ["pfid"] = 1201, ["ai_target"] = 2, ["ratio"] = 15}, {["lv"] = 5, ["pfid"] = 4290, ["ai_target"] = 2, ["ratio"] = 15}, {["lv"] = 5, ["pfid"] = 1205, ["ai_target"] = 2, ["ratio"] = 0}, {["lv"] = 5, ["pfid"] = 9026, ["ai_target"] = 2, ["ratio"] = 0}, {["lv"] = 5, ["pfid"] = 9024, ["ai_target"] = 2, ["ratio"] = 0}, {["lv"] = 5, ["pfid"] = 9018, ["ai_target"] = 2, ["ratio"] = 0}},
        aitype = 713,
        critRate = "0",
        desc = "金山（通用）",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3113,
        hp = "500005",
        id = 11133,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "魔僧",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11134] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 3, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 1104, ["ai_target"] = 4, ["ratio"] = 50}},
        aitype = 303,
        critRate = "0",
        desc = "蜀山（通用）",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5107,
        hp = "500005",
        id = 11134,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "剑魂",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 5107}, {["lv"] = 5, ["pfid"] = 5108}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11135] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1401, ["ai_target"] = 5, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 1403, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 1404, ["ai_target"] = 2, ["ratio"] = 20}},
        aitype = 302,
        critRate = "0",
        desc = "瑶池（通用）",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5127,
        hp = "500005",
        id = 11135,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "尘仙",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 5107}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11136] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 33, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1303, ["ai_target"] = 33, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1306, ["ai_target"] = 33, ["ratio"] = 40}},
        aitype = 302,
        critRate = "0",
        desc = "太初（通用）",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5116,
        hp = "500005",
        id = 11136,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "焚炎",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 5107}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11137] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1606, ["ai_target"] = 2, ["ratio"] = 80}},
        aitype = 303,
        critRate = "0",
        desc = "妖神宫（通用）",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5123,
        hp = "500005",
        id = 11137,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天鹏",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 5107}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11138] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 4271, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 9030, ["ai_target"] = 3, ["ratio"] = 40}},
        aitype = 302,
        critRate = "0",
        desc = "精英怪1物法",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5132,
        hp = "500005",
        id = 11138,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "无相天魔",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 5107}, {["lv"] = 5, ["pfid"] = 3027}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11139] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1105, ["ai_target"] = 2, ["ratio"] = 60}, {["lv"] = 5, ["pfid"] = 1107, ["ai_target"] = 4, ["ratio"] = 40}},
        aitype = 303,
        critRate = "0",
        desc = "精英怪1蜀山",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5122,
        hp = "500005",
        id = 11139,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "阿修罗",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 5107}, {["lv"] = 5, ["pfid"] = 3027}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11140] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1103, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 1104, ["ai_target"] = 4, ["ratio"] = 50}},
        aitype = 303,
        critRate = "0",
        desc = "精英怪2蜀山",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5133,
        hp = "500005",
        id = 11140,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "断魂",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 5107}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11141] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 3030, ["ai_target"] = 2, ["ratio"] = 20}},
        aitype = 303,
        critRate = "0",
        desc = "精英怪2",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5121,
        hp = "500005",
        id = 11141,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "噬天虎",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 5107}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11142] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 1306, ["ai_target"] = 5, ["ratio"] = 35}},
        aitype = 303,
        critRate = "0",
        desc = "精英怪2太初",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5118,
        hp = "500005",
        id = 11142,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "旱魁",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 4255}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11143] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1303, ["ai_target"] = 5, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1306, ["ai_target"] = 5, ["ratio"] = 40}},
        aitype = 302,
        critRate = "0",
        desc = "精英怪3金山",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2402,
        hp = "500005",
        id = 11143,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "降龙罗汉",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11144] = {
        activeSkills = {{["lv"] = 10, ["pfid"] = 1201, ["ai_target"] = 2, ["ratio"] = 60}},
        aitype = 302,
        critRate = "0",
        desc = "精英怪3",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 2401,
        hp = "500005",
        id = 11144,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "迷失的本我",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 5, ["pfid"] = 4257}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11145] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1303, ["ai_target"] = 5, ["ratio"] = 65}},
        aitype = 302,
        critRate = "0",
        desc = "精英怪3",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3113,
        hp = "500005",
        id = 11145,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "魔化沙弥",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 5108}, {["lv"] = 5, ["pfid"] = 3033}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11146] = {
        activeSkills = {{["lv"] = 20, ["pfid"] = 1403, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 303,
        critRate = "0",
        desc = "精英怪4瑶池",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3124,
        hp = "500005",
        id = 11146,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "蜈蚣精王道灵",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11147] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1102, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 302,
        critRate = "0",
        desc = "喽啰",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 5114,
        hp = "500005",
        id = 11147,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "山精",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3014}, {["lv"] = 3, ["pfid"] = 5137}, {["lv"] = 5, ["pfid"] = 3031}},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11148] = {
        activeSkills = {{["lv"] = 4, ["pfid"] = 1104, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 4, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 4, ["pfid"] = 1102, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 302,
        critRate = "0",
        desc = "天兵(蜀山)",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "2000",
        id = 11148,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵(蜀山)",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11149] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1204, ["ai_target"] = 7, ["ratio"] = 50}, {["lv"] = 4, ["pfid"] = 1202, ["ai_target"] = 3, ["ratio"] = 50}, {["lv"] = 4, ["pfid"] = 1203, ["ai_target"] = 3, ["ratio"] = 50}, {["lv"] = 4, ["pfid"] = 1205, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 4, ["pfid"] = 1201, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 302,
        critRate = "0",
        desc = "天兵(金山)",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "2000",
        id = 11149,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵(金山)",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11150] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 3, ["ratio"] = 50}, {["lv"] = 4, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 4, ["pfid"] = 1302, ["ai_target"] = 2, ["ratio"] = 20}},
        aitype = 302,
        critRate = "0",
        desc = "天兵(太初)",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "2000",
        id = 11150,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵(太初)",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11151] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1402, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 1405, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 4, ["pfid"] = 1403, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 302,
        critRate = "0",
        desc = "天兵(瑶池)",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "2000",
        id = 11151,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵(瑶池)",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11152] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1502, ["ai_target"] = 28, ["ratio"] = 50}, {["lv"] = 5, ["pfid"] = 1505, ["ai_target"] = 28, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 1506, ["ai_target"] = 2, ["ratio"] = 5}},
        aitype = 302,
        critRate = "0",
        desc = "天兵(青城)",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "2000",
        id = 11152,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵(青城)",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11153] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1606, ["ai_target"] = 2, ["ratio"] = 50}, {["lv"] = 4, ["pfid"] = 1601, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 302,
        critRate = "0",
        desc = "天兵(妖神)",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "2000",
        id = 11153,
        is_boss = 0,
        level = "LV",
        magAttack = "level*5+30",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵(妖神)",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11154] = {
        activeSkills = {},
        aitype = 302,
        critRate = "0",
        desc = "上古箭神小怪",
        dodgeRate = "0",
        expertskill = {"level/5-3", "level/5-3", "level/5-3", "level/5-3"},
        figureid = 5101,
        hp = "1000",
        id = 11154,
        is_boss = 0,
        level = "ALV",
        magAttack = "500",
        magDefense = "100",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "看门狗",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 3025}, {["lv"] = 5, ["pfid"] = 4253}},
        phyAttack = "500",
        phyDefense = "100",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "100",
    },

    [11155] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 3023, ["ai_target"] = 1, ["ratio"] = 60}},
        aitype = 302,
        critRate = "0",
        desc = "上古箭神主怪",
        dodgeRate = "0",
        expertskill = {"level/5-3", "level/5-3", "level/5-3", "level/5-3"},
        figureid = 2602,
        hp = "1000",
        id = 11155,
        is_boss = 1,
        level = "ALV",
        magAttack = "500",
        magDefense = "100",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "十日金乌",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4200}, {["lv"] = 5, ["pfid"] = 3024}, {["lv"] = 5, ["pfid"] = 4255}, {["lv"] = 1, ["pfid"] = 5129}},
        phyAttack = "500",
        phyDefense = "100",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "100",
    },

    [11156] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1104, ["ai_target"] = 33, ["ratio"] = 80}},
        aitype = 302,
        critRate = "0",
        desc = "天兵(蜀山)",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "100000",
        id = 11156,
        is_boss = 0,
        level = "LV",
        magAttack = "1500",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵(蜀山)",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11157] = {
        activeSkills = {{["lv"] = 1, ["pfid"] = 1305, ["ai_target"] = 33, ["ratio"] = 80}},
        aitype = 302,
        critRate = "0",
        desc = "天兵(蜀山)",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "100000",
        id = 11157,
        is_boss = 0,
        level = "LV",
        magAttack = "1500",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵(蜀山)",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

    [11158] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "天兵(蜀山)",
        dodgeRate = "0",
        expertskill = {"1", "1", "1", "1"},
        figureid = 3119,
        hp = "100000",
        id = 11158,
        is_boss = 0,
        level = "LV",
        magAttack = "1500",
        magDefense = "level*2-15",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "天兵(蜀山)",
        passiveSkills = {},
        phyAttack = "100",
        phyDefense = "level*2-15",
        phy_hit_ratio = "200",
        phy_hit_res_ratio = "5+level*0.51",
        speed = "level*1+5",
    },

}
