-- ./excel/fight/trapmine.xlsx
return {

    [10001] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "暗雷测试",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5101,
        hp = "100+level*30+(level-20)*(level-20)/10",
        id = 10001,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+50+level*level/100",
        magDefense = "level*8+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100",
        name = "大耳兔",
        passiveSkills = {},
        phyAttack = "level*10+50+level*level/100",
        phyDefense = "level*10+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.4",
        speed = "level*7",
    },

    [10002] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "暗雷测试",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5113,
        hp = "100+level*30+(level-20)*(level-20)/10",
        id = 10002,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+50+level*level/100",
        magDefense = "level*8+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100",
        name = "长耳狐",
        passiveSkills = {},
        phyAttack = "level*10+50+level*level/100",
        phyDefense = "level*10+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.4",
        speed = "level*7",
    },

    [10003] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "暗雷测试",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5111,
        hp = "100+level*30+(level-20)*(level-20)/10",
        id = 10003,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+50+level*level/100",
        magDefense = "level*8+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100",
        name = "螃蟹",
        passiveSkills = {},
        phyAttack = "level*10+50+level*level/100",
        phyDefense = "level*10+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.4",
        speed = "level*7",
    },

    [10004] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "暗雷测试",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5114,
        hp = "100+level*30+(level-20)*(level-20)/10",
        id = 10004,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+50+level*level/100",
        magDefense = "level*8+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100",
        name = "野猪",
        passiveSkills = {},
        phyAttack = "level*10+50+level*level/100",
        phyDefense = "level*10+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.4",
        speed = "level*7",
    },

    [10005] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "暗雷测试",
        dodgeRate = "0",
        expertskill = {},
        figureid = 5122,
        hp = "100+level*30+(level-20)*(level-20)/10",
        id = 10005,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+50+level*level/100",
        magDefense = "level*8+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100",
        name = "凤凰",
        passiveSkills = {},
        phyAttack = "level*10+50+level*level/100",
        phyDefense = "level*10+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.4",
        speed = "level*7",
    },

}
