-- ./excel/fight/xuanshang.xlsx
return {

    [1001] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1001,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10011, ["count"] = 1}, {["monsterid"] = 10012, ["count"] = 1}, {["monsterid"] = 10013, ["count"] = 1}, {["monsterid"] = 10014, ["count"] = 1}, {["monsterid"] = 10015, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1002] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1002,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10021, ["count"] = 1}, {["monsterid"] = 10022, ["count"] = 1}, {["monsterid"] = 10023, ["count"] = 1}, {["monsterid"] = 10024, ["count"] = 1}, {["monsterid"] = 10025, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1003] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1003,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10031, ["count"] = 1}, {["monsterid"] = 10032, ["count"] = 1}, {["monsterid"] = 10033, ["count"] = 1}, {["monsterid"] = 10034, ["count"] = 1}, {["monsterid"] = 10035, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1004] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1004,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10041, ["count"] = 1}, {["monsterid"] = 10042, ["count"] = 1}, {["monsterid"] = 10043, ["count"] = 1}, {["monsterid"] = 10044, ["count"] = 1}, {["monsterid"] = 10045, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1005] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1005,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10051, ["count"] = 1}, {["monsterid"] = 10052, ["count"] = 1}, {["monsterid"] = 10053, ["count"] = 1}, {["monsterid"] = 10054, ["count"] = 1}, {["monsterid"] = 10055, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1006] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1006,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10061, ["count"] = 1}, {["monsterid"] = 10062, ["count"] = 1}, {["monsterid"] = 10063, ["count"] = 1}, {["monsterid"] = 10064, ["count"] = 1}, {["monsterid"] = 10065, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1007] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1007,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10071, ["count"] = 1}, {["monsterid"] = 10072, ["count"] = 1}, {["monsterid"] = 10073, ["count"] = 1}, {["monsterid"] = 10074, ["count"] = 1}, {["monsterid"] = 10075, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1008] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1008,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10081, ["count"] = 1}, {["monsterid"] = 10082, ["count"] = 1}, {["monsterid"] = 10083, ["count"] = 1}, {["monsterid"] = 10084, ["count"] = 1}, {["monsterid"] = 10085, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1009] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1009,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10091, ["count"] = 1}, {["monsterid"] = 10092, ["count"] = 1}, {["monsterid"] = 10093, ["count"] = 1}, {["monsterid"] = 10094, ["count"] = 1}, {["monsterid"] = 10095, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

    [1010] = {
        action_id = {},
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "悬赏",
        difficulty = {},
        friend = {},
        id = 1010,
        lineup = {1, 1},
        monster = {{["monsterid"] = 10101, ["count"] = 1}, {["monsterid"] = 10102, ["count"] = 1}, {["monsterid"] = 10103, ["count"] = 1}, {["monsterid"] = 10104, ["count"] = 1}, {["monsterid"] = 10105, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        war_confirm = 0,
        weather = 0,
    },

}
