-- ./excel/fight/yibao.xlsx
return {

    [11001] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1605, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 1601, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 401,
        critRate = "0",
        desc = "1星",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5102,
        hp = "100+level*50+(level-20)*level",
        id = 11001,
        is_boss = 1,
        level = "LV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*11+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*7",
    },

    [11002] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 5, ["pfid"] = 1104, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "2星",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5103,
        hp = "100+level*70+(level-20)*level",
        id = 11002,
        is_boss = 1,
        level = "LV",
        magAttack = "level*11+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*12+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*7",
    },

    [11003] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1306, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "3星",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5115,
        hp = "100+level*80+(level-20)*level",
        id = 11003,
        is_boss = 0,
        level = "LV",
        magAttack = "level*12+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {},
        phyAttack = "level*13+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*7",
    },

    [11004] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1605, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 1601, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 401,
        critRate = "0",
        desc = "4星",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5113,
        hp = "100+level*20+(level-20)*level*3",
        id = 11004,
        is_boss = 0,
        level = "LV",
        magAttack = "level*10+(level-30)*7+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4200}, {["lv"] = 5, ["pfid"] = 4250}},
        phyAttack = "level*13+(level-30)*7+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*7",
    },

    [11005] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 70}, {["lv"] = 5, ["pfid"] = 1104, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "5星",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5106,
        hp = "100+level*50+(level-20)*level*3*star*0.3",
        id = 11005,
        is_boss = 0,
        level = "LV",
        magAttack = "level*11+(level-30)*7+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "$npc",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 4200}, {["lv"] = 5, ["pfid"] = 4250}},
        phyAttack = "level*15+(level-30)*7+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*7",
    },

    [11020] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "1星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5101,
        hp = "100+level*50+(level-20)*level/2",
        id = 11020,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "哈士奇喽啰",
        passiveSkills = {},
        phyAttack = "level*11+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

    [11021] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "1星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5111,
        hp = "100+level*50+(level-20)*level/2",
        id = 11021,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "秋田犬喽啰",
        passiveSkills = {},
        phyAttack = "level*11+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

    [11022] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "2星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5113,
        hp = "100+level*50+(level-20)*level/2",
        id = 11022,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "飞羽将军喽啰",
        passiveSkills = {},
        phyAttack = "level*12+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

    [11023] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "2星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5104,
        hp = "100+level*50+(level-20)*level/2",
        id = 11023,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "兔精喽啰",
        passiveSkills = {},
        phyAttack = "level*12+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

    [11024] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "3星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5101,
        hp = "100+level*50+(level-20)*level/2",
        id = 11024,
        is_boss = 0,
        level = "LV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "哈士奇喽啰",
        passiveSkills = {},
        phyAttack = "level*12+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

    [11025] = {
        activeSkills = {},
        aitype = 401,
        critRate = "0",
        desc = "3星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5111,
        hp = "100+level*50+(level-20)*level/2",
        id = 11025,
        is_boss = 0,
        level = "LV",
        magAttack = "level*10+10",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "秋田犬喽啰",
        passiveSkills = {},
        phyAttack = "level*12+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

    [11026] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 401,
        critRate = "0",
        desc = "4星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5113,
        hp = "100+level*60+(level-20)*level/2",
        id = 11026,
        is_boss = 0,
        level = "LV",
        magAttack = "level*7+(level-30)*7+20",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "飞羽将军喽啰",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 5137}},
        phyAttack = "level*9+(level-30)*7+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

    [11027] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1305, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "4星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5116,
        hp = "100+level*60+(level-20)*level/2",
        id = 11027,
        is_boss = 0,
        level = "LV",
        magAttack = "level*7+(level-30)*7+20",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "如意喽啰",
        passiveSkills = {},
        phyAttack = "level*9+(level-30)*7+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

    [11028] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1101, ["ai_target"] = 2, ["ratio"] = 70}},
        aitype = 401,
        critRate = "0",
        desc = "5星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5113,
        hp = "100+level*60+(level-20)*level/2",
        id = 11028,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+(level-30)*7+20",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "飞羽将军喽啰",
        passiveSkills = {{["lv"] = 5, ["pfid"] = 5137}},
        phyAttack = "level*10+(level-30)*7+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

    [11029] = {
        activeSkills = {{["lv"] = 5, ["pfid"] = 1301, ["ai_target"] = 2, ["ratio"] = 40}, {["lv"] = 5, ["pfid"] = 1305, ["ai_target"] = 2, ["ratio"] = 30}, {["lv"] = 5, ["pfid"] = 1303, ["ai_target"] = 2, ["ratio"] = 30}},
        aitype = 401,
        critRate = "0",
        desc = "5星小怪",
        dodgeRate = "0",
        expertskill = {"math.floor(level/5-4)", "math.floor(level/5-4)", "math.floor(level/5-4)", "0"},
        figureid = 5116,
        hp = "100+level*60+(level-20)*level/2",
        id = 11029,
        is_boss = 0,
        level = "LV",
        magAttack = "level*8+(level-30)*7+20",
        magDefense = "level*1+5",
        mag_hit_ratio = "100",
        mag_hit_res_ratio = "0",
        mp = "100000",
        name = "如意喽啰",
        passiveSkills = {},
        phyAttack = "level*10+(level-30)*7+20",
        phyDefense = "level*2+5",
        phy_hit_ratio = "100+level*0.5",
        phy_hit_res_ratio = "5+level*0.5",
        speed = "level*4",
    },

}
