-- ./excel/fight/yibao.xlsx
return {

    [71103] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "1星",
        friend = {},
        id = 71103,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11001, ["count"] = 1}, {["monsterid"] = 11020, ["count"] = 1}, {["monsterid"] = 11021, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [71104] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "2星",
        friend = {},
        id = 71104,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11002, ["count"] = 1}, {["monsterid"] = 11022, ["count"] = 1}, {["monsterid"] = 11023, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [71105] = {
        auto_start = 1,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "3星",
        friend = {},
        id = 71105,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11003, ["count"] = 1}, {["monsterid"] = 11024, ["count"] = 1}, {["monsterid"] = 11025, ["count"] = 2}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [71106] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "4星",
        friend = {},
        id = 71106,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11004, ["count"] = 1}, {["monsterid"] = 11026, ["count"] = 2}, {["monsterid"] = 11027, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [71107] = {
        auto_start = 0,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "5星",
        friend = {},
        id = 71107,
        lineup = {1, 1},
        monster = {{["monsterid"] = 11005, ["count"] = 1}, {["monsterid"] = 11028, ["count"] = 2}, {["monsterid"] = 11029, ["count"] = 1}},
        monster_pos = {},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

}
