-- ./excel/fight/zhenmo.xlsx
return {

    [1001] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "泥石人",
        friend = {},
        id = 1001,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10001, ["count"] = 1}, {["monsterid"] = 10002, ["count"] = 2}, {["monsterid"] = 10003, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1002] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "蛤蟆精",
        friend = {},
        id = 1002,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10010, ["count"] = 1}, {["monsterid"] = 10011, ["count"] = 1}, {["monsterid"] = 10012, ["count"] = 1}, {["monsterid"] = 10013, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1003] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "兔精",
        friend = {},
        id = 1003,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10020, ["count"] = 1}, {["monsterid"] = 10021, ["count"] = 2}, {["monsterid"] = 10022, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1004] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "笋精",
        friend = {},
        id = 1004,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10030, ["count"] = 1}, {["monsterid"] = 10031, ["count"] = 1}, {["monsterid"] = 10032, ["count"] = 1}, {["monsterid"] = 10033, ["count"] = 1}, {["monsterid"] = 10034, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [1005] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "神犬奇兵",
        friend = {},
        id = 1005,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 10040, ["count"] = 1}, {["monsterid"] = 10041, ["count"] = 1}, {["monsterid"] = 10045, ["count"] = 1}, {["monsterid"] = 10043, ["count"] = 1}, {["monsterid"] = 10044, ["count"] = 1}, {["monsterid"] = 10042, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 2,
    },

    [2001] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "机关兽",
        friend = {},
        id = 2001,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20001, ["count"] = 1}, {["monsterid"] = 20002, ["count"] = 3}, {["monsterid"] = 20003, ["count"] = 1}, {["monsterid"] = 20004, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [2002] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "插翅虎",
        friend = {},
        id = 2002,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20010, ["count"] = 1}, {["monsterid"] = 20011, ["count"] = 1}, {["monsterid"] = 20012, ["count"] = 2}, {["monsterid"] = 20013, ["count"] = 1}, {["monsterid"] = 20015, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [2003] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "熊猫武师",
        friend = {},
        id = 2003,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20020, ["count"] = 1}, {["monsterid"] = 20021, ["count"] = 2}, {["monsterid"] = 20022, ["count"] = 1}, {["monsterid"] = 20023, ["count"] = 1}, {["monsterid"] = 20025, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [2004] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "机关虎",
        friend = {},
        id = 2004,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20030, ["count"] = 1}, {["monsterid"] = 20031, ["count"] = 1}, {["monsterid"] = 20032, ["count"] = 1}, {["monsterid"] = 20033, ["count"] = 1}, {["monsterid"] = 20035, ["count"] = 1}, {["monsterid"] = 20036, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [2005] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "熊猫剑侠",
        friend = {},
        id = 2005,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 20040, ["count"] = 1}, {["monsterid"] = 20042, ["count"] = 1}, {["monsterid"] = 20043, ["count"] = 1}, {["monsterid"] = 20044, ["count"] = 1}, {["monsterid"] = 20045, ["count"] = 1}, {["monsterid"] = 20046, ["count"] = 1}, {["monsterid"] = 20047, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 2,
    },

    [3001] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "浪人",
        friend = {},
        id = 3001,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 30001, ["count"] = 1}, {["monsterid"] = 30002, ["count"] = 2}, {["monsterid"] = 30003, ["count"] = 1}, {["monsterid"] = 30004, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [3002] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "桃花妖",
        friend = {},
        id = 3002,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 30010, ["count"] = 1}, {["monsterid"] = 30011, ["count"] = 2}, {["monsterid"] = 30012, ["count"] = 1}, {["monsterid"] = 30013, ["count"] = 1}, {["monsterid"] = 30015, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [3003] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "阴阳师",
        friend = {},
        id = 3003,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 30020, ["count"] = 1}, {["monsterid"] = 30021, ["count"] = 1}, {["monsterid"] = 30022, ["count"] = 2}, {["monsterid"] = 30023, ["count"] = 1}, {["monsterid"] = 30025, ["count"] = 2}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [3004] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "剑灵",
        friend = {},
        id = 3004,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 30030, ["count"] = 1}, {["monsterid"] = 30031, ["count"] = 1}, {["monsterid"] = 30032, ["count"] = 2}, {["monsterid"] = 30033, ["count"] = 2}, {["monsterid"] = 30034, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [3005] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "花神君",
        friend = {},
        id = 3005,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 30040, ["count"] = 1}, {["monsterid"] = 30041, ["count"] = 1}, {["monsterid"] = 30042, ["count"] = 1}, {["monsterid"] = 30043, ["count"] = 1}, {["monsterid"] = 30044, ["count"] = 1}, {["monsterid"] = 30045, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 2,
    },

    [4001] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "飞羽将军",
        friend = {},
        id = 4001,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 40001, ["count"] = 1}, {["monsterid"] = 40002, ["count"] = 2}, {["monsterid"] = 40003, ["count"] = 2}, {["monsterid"] = 40004, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [4002] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "剑侠",
        friend = {},
        id = 4002,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 40010, ["count"] = 1}, {["monsterid"] = 40011, ["count"] = 2}, {["monsterid"] = 40012, ["count"] = 2}, {["monsterid"] = 40013, ["count"] = 1}, {["monsterid"] = 40014, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [4003] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "如意",
        friend = {},
        id = 4003,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 40020, ["count"] = 1}, {["monsterid"] = 40021, ["count"] = 2}, {["monsterid"] = 40022, ["count"] = 2}, {["monsterid"] = 40023, ["count"] = 1}, {["monsterid"] = 40024, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [4004] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "天璇仙子",
        friend = {},
        id = 4004,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 40030, ["count"] = 1}, {["monsterid"] = 40031, ["count"] = 1}, {["monsterid"] = 40032, ["count"] = 2}, {["monsterid"] = 40033, ["count"] = 2}, {["monsterid"] = 40034, ["count"] = 1}, {["monsterid"] = 40035, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [4005] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "瑶光圣女",
        friend = {},
        id = 4005,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 40040, ["count"] = 1}, {["monsterid"] = 40041, ["count"] = 1}, {["monsterid"] = 40042, ["count"] = 1}, {["monsterid"] = 40043, ["count"] = 2}, {["monsterid"] = 40044, ["count"] = 1}, {["monsterid"] = 40045, ["count"] = 1}, {["monsterid"] = 40046, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 2,
    },

    [5001] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "仙鹤童子",
        friend = {},
        id = 5001,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 50001, ["count"] = 1}, {["monsterid"] = 50002, ["count"] = 2}, {["monsterid"] = 50002, ["count"] = 2}, {["monsterid"] = 50003, ["count"] = 2}, {["monsterid"] = 50004, ["count"] = 1}, {["monsterid"] = 50005, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [5002] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "机关虎",
        friend = {},
        id = 5002,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 50010, ["count"] = 1}, {["monsterid"] = 50011, ["count"] = 2}, {["monsterid"] = 50012, ["count"] = 2}, {["monsterid"] = 50013, ["count"] = 1}, {["monsterid"] = 50014, ["count"] = 1}, {["monsterid"] = 50015, ["count"] = 1}, {["monsterid"] = 50016, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [5003] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "大鹏鸟",
        friend = {},
        id = 5003,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 50020, ["count"] = 1}, {["monsterid"] = 50021, ["count"] = 2}, {["monsterid"] = 50022, ["count"] = 2}, {["monsterid"] = 50023, ["count"] = 2}, {["monsterid"] = 50024, ["count"] = 1}, {["monsterid"] = 50025, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [5004] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "天师道人",
        friend = {},
        id = 5004,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 50030, ["count"] = 1}, {["monsterid"] = 50031, ["count"] = 2}, {["monsterid"] = 50032, ["count"] = 2}, {["monsterid"] = 50033, ["count"] = 2}, {["monsterid"] = 50034, ["count"] = 1}, {["monsterid"] = 50035, ["count"] = 1}, {["monsterid"] = 50036, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [5005] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "迦楼罗",
        friend = {},
        id = 5005,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 50040, ["count"] = 1}, {["monsterid"] = 50041, ["count"] = 2}, {["monsterid"] = 50042, ["count"] = 2}, {["monsterid"] = 50043, ["count"] = 2}, {["monsterid"] = 50044, ["count"] = 1}, {["monsterid"] = 50045, ["count"] = 1}, {["monsterid"] = 50046, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 2,
    },

    [6001] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "剑灵",
        friend = {},
        id = 6001,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 60001, ["count"] = 1}, {["monsterid"] = 60002, ["count"] = 1}, {["monsterid"] = 60003, ["count"] = 1}, {["monsterid"] = 60004, ["count"] = 1}, {["monsterid"] = 60005, ["count"] = 1}, {["monsterid"] = 60006, ["count"] = 1}, {["monsterid"] = 60007, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [6002] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "桃花妖",
        friend = {},
        id = 6002,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 60010, ["count"] = 1}, {["monsterid"] = 60011, ["count"] = 2}, {["monsterid"] = 60012, ["count"] = 1}, {["monsterid"] = 60013, ["count"] = 1}, {["monsterid"] = 60014, ["count"] = 1}, {["monsterid"] = 60015, ["count"] = 1}, {["monsterid"] = 60016, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [6003] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "花神君",
        friend = {},
        id = 6003,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 60020, ["count"] = 1}, {["monsterid"] = 60021, ["count"] = 2}, {["monsterid"] = 60022, ["count"] = 2}, {["monsterid"] = 60023, ["count"] = 1}, {["monsterid"] = 60024, ["count"] = 1}, {["monsterid"] = 60025, ["count"] = 1}, {["monsterid"] = 60026, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [6004] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "阴阳师",
        friend = {},
        id = 6004,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 60030, ["count"] = 1}, {["monsterid"] = 60031, ["count"] = 2}, {["monsterid"] = 60032, ["count"] = 2}, {["monsterid"] = 60033, ["count"] = 1}, {["monsterid"] = 60034, ["count"] = 1}, {["monsterid"] = 60035, ["count"] = 1}, {["monsterid"] = 60036, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 0,
    },

    [6005] = {
        action_id = {},
        auto_start = 2,
        barrage_send = 0,
        barrage_show = 0,
        boss_war_type = 0,
        desc = "南方鬼帝",
        friend = {},
        id = 6005,
        lineup = {-1, 1},
        monster = {{["monsterid"] = 60040, ["count"] = 1}, {["monsterid"] = 60041, ["count"] = 2}, {["monsterid"] = 60042, ["count"] = 2}, {["monsterid"] = 60043, ["count"] = 1}, {["monsterid"] = 60044, ["count"] = 1}, {["monsterid"] = 60045, ["count"] = 1}, {["monsterid"] = 60046, ["count"] = 1}},
        sky_war = 0,
        speek_id = 0,
        weather = 2,
    },

}
