module(..., package.seeall)
function main()
	local d1 = require("system.artifact.config")
	local d2 = require("system.artifact.equip_attr")
	local d3 = require("system.artifact.equip_score")
	local d4 = require("system.artifact.spirit_info")
	local d5 = require("system.artifact.strength")
	local d6 = require("system.artifact.strength_limit")
	local d7 = require("system.artifact.strength_effect")
	local d8 = require("system.artifact.text")
	local d9 = require("system.artifact.upgrade")
	local d10 = require("system.artifact.upgrade_limit")
	local d11 = require("skill.artifact")
	local d12 = require("system.artifact.school_spirit_effect")
	
	local s = table.dump(d1, "CONFIG").. "\n" .. table.dump(d2, "EQUIPATTR").. "\n" .. table.dump(d3, "EQUIPSCORE").. "\n" .. table.dump(d4, "SPIRITINFO")
	.. "\n" .. table.dump(d5, "STRENGTH").. "\n" .. table.dump(d6, "STRENGTHLIMIT").. "\n" .. table.dump(d7, "STRENGTHEFFECT").. "\n" .. table.dump(d8, "TEXT")
	.. "\n" .. table.dump(d9, "UPGRADE").. "\n" .. table.dump(d10, "UPGRADELIMIT").. "\n" .. table.dump(d11, "SKILL").. "\n" .. table.dump(d12, "SPIRITATTR")
	SaveToFile("artifact", s)
end