module(..., package.seeall)

function main()
	local d1 = require("system.fabao.choose")
	local d2 = require("system.fabao.combine")
	local d3 = require("system.fabao.config")
	local d4 = require("system.fabao.decompose")
	local d5 = require("system.fabao.equip")
	local d6 = require("system.fabao.hun")
	local d7 = require("system.fabao.info")
	local d8 = require("system.fabao.juexing_upgrade")
	local d9 = require("system.fabao.text")
	local d10 = require("system.fabao.upgrade")
	local d11 = require("system.fabao.xianling")

	local s = table.dump(d1, "CHOOSE") 
		.. "\n" .. table.dump(d2, "COMBINE")
		.. "\n" .. table.dump(d3, "CONFIG")
		.. "\n" .. table.dump(d4, "DECOMPOSE")
		.. "\n" .. table.dump(d5, "EQUIP")
		.. "\n" .. table.dump(d6, "HUN")
		.. "\n" .. table.dump(d7, "INFO")
		.. "\n" .. table.dump(d8, "JUEXING_UPGRADE")
		.. "\n" .. table.dump(d9, "TEXT")
		.. "\n" .. table.dump(d10, "UPGRADE")
		.. "\n" .. table.dump(d11, "XIANLING")

	SaveToFile("fabao", s)
end