-- ./excel/task/treasureconvoy/task_treasureconvoy.xlsx
return {

    [622601] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "对话",
        goalDesc = "护送秘宝至{submitnpc}并上交",
        id = 622601,
        initConfig = {"BIAN10"},
        missiondone = {"NT622602"},
        name = "普通秘宝护送",
        quickFindWay = 0,
        submitNpcId = 1002,
        submitRewardStr = {"R1001"},
        tasktype = 1,
        timeout = 0,
        tips = 0,
        type = 19,
    },

    [622602] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "对话",
        goalDesc = "护送秘宝至{submitnpc}并上交",
        id = 622602,
        initConfig = {"BIAN10"},
        missiondone = {"NT622603"},
        name = "普通秘宝护送",
        quickFindWay = 0,
        submitNpcId = 1003,
        submitRewardStr = {"R1002"},
        tasktype = 1,
        timeout = 0,
        tips = 0,
        type = 19,
    },

    [622603] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "对话",
        goalDesc = "护送秘宝至{submitnpc}并上交",
        id = 622603,
        initConfig = {"BIAN10"},
        missiondone = {"CONVOYDONE"},
        name = "普通秘宝护送",
        quickFindWay = 0,
        submitNpcId = 1004,
        submitRewardStr = {"R1003"},
        tasktype = 1,
        timeout = 0,
        tips = 0,
        type = 19,
    },

    [622611] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "对话",
        goalDesc = "护送秘宝至{submitnpc}并上交",
        id = 622611,
        initConfig = {"BIAN10"},
        missiondone = {"NT622612"},
        name = "高级秘宝护送",
        quickFindWay = 0,
        submitNpcId = 1002,
        submitRewardStr = {"R2001"},
        tasktype = 1,
        timeout = 0,
        tips = 0,
        type = 19,
    },

    [622612] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "对话",
        goalDesc = "护送秘宝至{submitnpc}并上交",
        id = 622612,
        initConfig = {"BIAN10"},
        missiondone = {"NT622613"},
        name = "高级秘宝护送",
        quickFindWay = 0,
        submitNpcId = 1003,
        submitRewardStr = {"R2002"},
        tasktype = 1,
        timeout = 0,
        tips = 0,
        type = 19,
    },

    [622613] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "对话",
        goalDesc = "护送秘宝至{submitnpc}并上交",
        id = 622613,
        initConfig = {"BIAN10"},
        missiondone = {"CONVOYDONE"},
        name = "高级秘宝护送",
        quickFindWay = 0,
        submitNpcId = 1004,
        submitRewardStr = {"R2003"},
        tasktype = 1,
        timeout = 0,
        tips = 0,
        type = 19,
    },

}
