-- ./excel/system/partner/partnerinfo.xlsx
return {

    [10001] = {
        aitype = 601,
        character = "群法·法连",
        closeupname = "h7_ming_38",
        cost = {["amount"] = 1, ["id"] = 30600},
        desc = "一介凡人，因前世救过一条白蛇，改变了命运。被道祖选中为破局之人，改变原有的命运，走上修仙之路",
        id = 10001,
        name = "许仙",
        pre_condition = "LV:10",
        quality = 1,
        race = 1,
        ro_aitype = 701,
        school = 3,
        sex = 1,
        shape = 2101,
        silver = 0,
        sound = "xx3",
        style = "法攻型",
        swap_cost = 2000,
        type = 1,
    },

    [10002] = {
        aitype = 602,
        character = "解封·反震",
        closeupname = "h7_ming_1",
        cost = {["amount"] = 1, ["id"] = 30601},
        desc = "太初第十三代弟子，冷感，不为外物所动，在算命方面有白素贞都比不上的天赋",
        id = 10002,
        name = "璃镜",
        pre_condition = "LV:35",
        quality = 1,
        race = 2,
        ro_aitype = 702,
        school = 3,
        sex = 2,
        shape = 2102,
        silver = 0,
        sound = "yxj3",
        style = "法攻型",
        swap_cost = 2000,
        type = 1,
    },

    [10003] = {
        aitype = 603,
        character = "群攻·破防",
        closeupname = "h7_ming_2",
        cost = {["amount"] = 1, ["id"] = 30602},
        desc = "蜀山派大师姐，勤奋刻苦，最见不得懒散不求上进的人。",
        id = 10003,
        name = "洛凝霜",
        pre_condition = "LV:15",
        quality = 1,
        race = 1,
        ro_aitype = 703,
        school = 1,
        sex = 2,
        shape = 2201,
        silver = 0,
        sound = "qr3",
        style = "物攻型",
        swap_cost = 2000,
        type = 2,
    },

    [10004] = {
        aitype = 604,
        character = "点杀·吸血",
        closeupname = "h7_ming_3",
        cost = {["amount"] = 1, ["id"] = 30603},
        desc = "资质平庸，却痴爱剑法，竟成为剑仙，于蜀山独创蜀山派。为人豪迈大方，正义感爆棚。",
        id = 10004,
        name = "渊记",
        pre_condition = "LV:45",
        quality = 1,
        race = 1,
        ro_aitype = 704,
        school = 1,
        sex = 1,
        shape = 2202,
        silver = 0,
        sound = "ycx3",
        style = "物攻型",
        swap_cost = 2000,
        type = 2,
    },

    [10005] = {
        aitype = 605,
        character = "混乱·生存",
        closeupname = "h7_ming_4",
        cost = {["amount"] = 1, ["id"] = 30604},
        desc = "千年蛇妖，各方各面都倾向于完美，为了报恩对许仙以身相许。",
        id = 10005,
        name = "白素贞",
        pre_condition = "LV:1",
        quality = 1,
        race = 3,
        ro_aitype = 705,
        school = 5,
        sex = 2,
        shape = 2301,
        silver = 0,
        sound = "bsz3",
        style = "封印型",
        swap_cost = 2000,
        type = 4,
    },

    [10006] = {
        aitype = 606,
        character = "封印·破防",
        closeupname = "h7_ming_5",
        cost = {["amount"] = 1, ["id"] = 30605},
        desc = "百年竹叶青蛇妖，得到妖神残魂，成为“鸣蛇”，白素贞的侍女兼姐妹。",
        id = 10006,
        name = "小青",
        pre_condition = "LV:35",
        quality = 1,
        race = 3,
        ro_aitype = 706,
        school = 5,
        sex = 2,
        shape = 2302,
        silver = 0,
        sound = "xq3",
        style = "封印型",
        swap_cost = 2000,
        type = 4,
    },

    [10007] = {
        aitype = 607,
        character = "点灯·生存",
        closeupname = "h7_ming_6",
        cost = {["amount"] = 1, ["id"] = 30606},
        desc = "曾被白素贞盗取过舍利，从此结下了深仇大恨，但内心真实的情感却是爱慕。",
        id = 10007,
        name = "法海",
        pre_condition = "LV:25",
        quality = 1,
        race = 1,
        ro_aitype = 707,
        school = 2,
        sex = 1,
        shape = 2401,
        silver = 0,
        sound = "fh3",
        style = "治疗型",
        swap_cost = 2000,
        type = 3,
    },

    [10008] = {
        aitype = 608,
        character = "复活·生存",
        closeupname = "h7_ming_7",
        cost = {["amount"] = 1, ["id"] = 30607},
        desc = "佛界的罗汉，一直游戏人间，渡化世人，在民间拥有很高的威望。",
        id = 10008,
        name = "道济",
        pre_condition = "LV:24",
        quality = 1,
        race = 2,
        ro_aitype = 708,
        school = 2,
        sex = 1,
        shape = 2402,
        silver = 0,
        sound = "dj3",
        style = "治疗型",
        swap_cost = 2000,
        type = 3,
    },

    [10009] = {
        aitype = 609,
        character = "施毒·解封",
        closeupname = "h7_ming_8",
        cost = {["amount"] = 1, ["id"] = 30608},
        desc = "西王母长女，红鸾星，瑶池的代言人，威仪无双。",
        id = 10009,
        name = "龙吉公主",
        pre_condition = "LV:5",
        quality = 1,
        race = 2,
        ro_aitype = 709,
        school = 4,
        sex = 2,
        shape = 2501,
        silver = 0,
        sound = "ljgz3",
        style = "辅助型",
        swap_cost = 2000,
        type = 5,
    },

    [10010] = {
        aitype = 610,
        character = "施毒·解封",
        closeupname = "h7_ming_39",
        cost = {["amount"] = 1, ["id"] = 30609},
        desc = "瑶池最强女仙，天界的女武神，本体玄鸟，一个疯狂的战斗狂人。",
        id = 10010,
        name = "九天玄女",
        pre_condition = "LV:25",
        quality = 1,
        race = 2,
        ro_aitype = 710,
        school = 4,
        sex = 2,
        shape = 2502,
        silver = 0,
        sound = "jtxn3",
        style = "辅助型",
        swap_cost = 2000,
        type = 5,
    },

    [10011] = {
        aitype = 611,
        character = "反击·天眼",
        closeupname = "h7_ming_14",
        cost = {["amount"] = 1, ["id"] = 30610},
        desc = "上古箭神后羿的分身，威武霸气，正直，不苟言笑。",
        id = 10011,
        name = "时未寒",
        pre_condition = "LV:25",
        quality = 1,
        race = 3,
        ro_aitype = 711,
        school = 6,
        sex = 1,
        shape = 2601,
        silver = 0,
        sound = "hy3",
        style = "物攻型",
        swap_cost = 2000,
        type = 2,
    },

    [10012] = {
        aitype = 612,
        character = "先手·加攻",
        closeupname = "h7_ming_22",
        cost = {["amount"] = 1, ["id"] = 30611},
        desc = "东皇太一的分身，曾统领天下所有妖族，与天帝平起平坐。",
        id = 10012,
        name = "昊离归",
        pre_condition = "LV:35",
        quality = 1,
        race = 3,
        ro_aitype = 712,
        school = 6,
        sex = 1,
        shape = 2602,
        silver = 0,
        sound = "dhty3",
        style = "物攻型",
        swap_cost = 2000,
        type = 2,
    },

}
