-- ./excel/system/partner/point.xlsx
return {

    [1] = {
        agility = 1.2,
        endurance = 2.6,
        id = 1,
        magic = 5.2,
        partner = 10001,
        physique = 1.8,
        quality = 1,
        strength = 1.2,
    },

    [2] = {
        agility = 1.3,
        endurance = 2.8,
        id = 2,
        magic = 5.5,
        partner = 10001,
        physique = 1.9,
        quality = 2,
        strength = 1.2,
    },

    [3] = {
        agility = 1.4,
        endurance = 2.9,
        id = 3,
        magic = 5.8,
        partner = 10001,
        physique = 2.0,
        quality = 3,
        strength = 1.3,
    },

    [4] = {
        agility = 1.5,
        endurance = 3.1,
        id = 4,
        magic = 6.1,
        partner = 10001,
        physique = 2.1,
        quality = 4,
        strength = 1.4,
    },

    [5] = {
        agility = 1.6,
        endurance = 3.3,
        id = 5,
        magic = 6.5,
        partner = 10001,
        physique = 2.3,
        quality = 5,
        strength = 1.5,
    },

    [6] = {
        agility = 1.2,
        endurance = 2.6,
        id = 6,
        magic = 5.2,
        partner = 10002,
        physique = 1.8,
        quality = 1,
        strength = 1.2,
    },

    [7] = {
        agility = 1.3,
        endurance = 2.8,
        id = 7,
        magic = 5.5,
        partner = 10002,
        physique = 1.9,
        quality = 2,
        strength = 1.2,
    },

    [8] = {
        agility = 1.4,
        endurance = 2.9,
        id = 8,
        magic = 5.8,
        partner = 10002,
        physique = 2.0,
        quality = 3,
        strength = 1.3,
    },

    [9] = {
        agility = 1.5,
        endurance = 3.1,
        id = 9,
        magic = 6.1,
        partner = 10002,
        physique = 2.1,
        quality = 4,
        strength = 1.4,
    },

    [10] = {
        agility = 1.6,
        endurance = 3.3,
        id = 10,
        magic = 6.5,
        partner = 10002,
        physique = 2.3,
        quality = 5,
        strength = 1.5,
    },

    [11] = {
        agility = 1.2,
        endurance = 1.5,
        id = 11,
        magic = 0.9,
        partner = 10003,
        physique = 1.8,
        quality = 1,
        strength = 5.6,
    },

    [12] = {
        agility = 1.3,
        endurance = 1.6,
        id = 12,
        magic = 1.0,
        partner = 10003,
        physique = 1.9,
        quality = 2,
        strength = 5.9,
    },

    [13] = {
        agility = 1.4,
        endurance = 1.7,
        id = 13,
        magic = 1.0,
        partner = 10003,
        physique = 2.0,
        quality = 3,
        strength = 6.3,
    },

    [14] = {
        agility = 1.5,
        endurance = 1.8,
        id = 14,
        magic = 1.1,
        partner = 10003,
        physique = 2.1,
        quality = 4,
        strength = 6.6,
    },

    [15] = {
        agility = 1.6,
        endurance = 1.9,
        id = 15,
        magic = 1.2,
        partner = 10003,
        physique = 2.3,
        quality = 5,
        strength = 7.0,
    },

    [16] = {
        agility = 1.2,
        endurance = 1.5,
        id = 16,
        magic = 0.9,
        partner = 10004,
        physique = 1.8,
        quality = 1,
        strength = 5.6,
    },

    [17] = {
        agility = 1.3,
        endurance = 1.6,
        id = 17,
        magic = 1.0,
        partner = 10004,
        physique = 1.9,
        quality = 2,
        strength = 5.9,
    },

    [18] = {
        agility = 1.4,
        endurance = 1.7,
        id = 18,
        magic = 1.0,
        partner = 10004,
        physique = 2.0,
        quality = 3,
        strength = 6.3,
    },

    [19] = {
        agility = 1.5,
        endurance = 1.8,
        id = 19,
        magic = 1.1,
        partner = 10004,
        physique = 2.1,
        quality = 4,
        strength = 6.6,
    },

    [20] = {
        agility = 1.6,
        endurance = 1.9,
        id = 20,
        magic = 1.2,
        partner = 10004,
        physique = 2.3,
        quality = 5,
        strength = 7.0,
    },

    [21] = {
        agility = 2.4,
        endurance = 2.2,
        id = 21,
        magic = 2.0,
        partner = 10005,
        physique = 1.8,
        quality = 1,
        strength = 0.1,
    },

    [22] = {
        agility = 2.6,
        endurance = 2.3,
        id = 22,
        magic = 2.1,
        partner = 10005,
        physique = 1.9,
        quality = 2,
        strength = 0.1,
    },

    [23] = {
        agility = 2.7,
        endurance = 2.5,
        id = 23,
        magic = 2.2,
        partner = 10005,
        physique = 2.0,
        quality = 3,
        strength = 0.1,
    },

    [24] = {
        agility = 2.9,
        endurance = 2.6,
        id = 24,
        magic = 2.3,
        partner = 10005,
        physique = 2.1,
        quality = 4,
        strength = 0.1,
    },

    [25] = {
        agility = 3.1,
        endurance = 2.8,
        id = 25,
        magic = 2.5,
        partner = 10005,
        physique = 2.3,
        quality = 5,
        strength = 0.2,
    },

    [26] = {
        agility = 2.4,
        endurance = 2.2,
        id = 26,
        magic = 2.0,
        partner = 10006,
        physique = 1.8,
        quality = 1,
        strength = 0.1,
    },

    [27] = {
        agility = 2.6,
        endurance = 2.3,
        id = 27,
        magic = 2.1,
        partner = 10006,
        physique = 1.9,
        quality = 2,
        strength = 0.1,
    },

    [28] = {
        agility = 2.7,
        endurance = 2.5,
        id = 28,
        magic = 2.2,
        partner = 10006,
        physique = 2.0,
        quality = 3,
        strength = 0.1,
    },

    [29] = {
        agility = 2.9,
        endurance = 2.6,
        id = 29,
        magic = 2.3,
        partner = 10006,
        physique = 2.1,
        quality = 4,
        strength = 0.1,
    },

    [30] = {
        agility = 3.1,
        endurance = 2.8,
        id = 30,
        magic = 2.5,
        partner = 10006,
        physique = 2.3,
        quality = 5,
        strength = 0.2,
    },

    [31] = {
        agility = 2.4,
        endurance = 2.9,
        id = 31,
        magic = 1.4,
        partner = 10007,
        physique = 2.2,
        quality = 1,
        strength = 0.1,
    },

    [32] = {
        agility = 2.5,
        endurance = 3.1,
        id = 32,
        magic = 1.5,
        partner = 10007,
        physique = 2.3,
        quality = 2,
        strength = 0.1,
    },

    [33] = {
        agility = 2.7,
        endurance = 3.3,
        id = 33,
        magic = 1.6,
        partner = 10007,
        physique = 2.5,
        quality = 3,
        strength = 0.1,
    },

    [34] = {
        agility = 2.8,
        endurance = 3.5,
        id = 34,
        magic = 1.7,
        partner = 10007,
        physique = 2.6,
        quality = 4,
        strength = 0.1,
    },

    [35] = {
        agility = 3.0,
        endurance = 3.7,
        id = 35,
        magic = 1.8,
        partner = 10007,
        physique = 2.8,
        quality = 5,
        strength = 0.2,
    },

    [36] = {
        agility = 2.4,
        endurance = 2.9,
        id = 36,
        magic = 1.4,
        partner = 10008,
        physique = 2.2,
        quality = 1,
        strength = 0.1,
    },

    [37] = {
        agility = 2.5,
        endurance = 3.1,
        id = 37,
        magic = 1.5,
        partner = 10008,
        physique = 2.3,
        quality = 2,
        strength = 0.1,
    },

    [38] = {
        agility = 2.7,
        endurance = 3.3,
        id = 38,
        magic = 1.6,
        partner = 10008,
        physique = 2.5,
        quality = 3,
        strength = 0.1,
    },

    [39] = {
        agility = 2.8,
        endurance = 3.5,
        id = 39,
        magic = 1.7,
        partner = 10008,
        physique = 2.6,
        quality = 4,
        strength = 0.1,
    },

    [40] = {
        agility = 3.0,
        endurance = 3.7,
        id = 40,
        magic = 1.8,
        partner = 10008,
        physique = 2.8,
        quality = 5,
        strength = 0.2,
    },

    [41] = {
        agility = 1.7,
        endurance = 3.0,
        id = 41,
        magic = 2.4,
        partner = 10009,
        physique = 2.4,
        quality = 1,
        strength = 0.1,
    },

    [42] = {
        agility = 1.8,
        endurance = 3.2,
        id = 42,
        magic = 2.5,
        partner = 10009,
        physique = 2.6,
        quality = 2,
        strength = 0.1,
    },

    [43] = {
        agility = 1.9,
        endurance = 3.4,
        id = 43,
        magic = 2.7,
        partner = 10009,
        physique = 2.7,
        quality = 3,
        strength = 0.1,
    },

    [44] = {
        agility = 2.0,
        endurance = 3.6,
        id = 44,
        magic = 2.8,
        partner = 10009,
        physique = 2.9,
        quality = 4,
        strength = 0.1,
    },

    [45] = {
        agility = 2.2,
        endurance = 3.8,
        id = 45,
        magic = 3.0,
        partner = 10009,
        physique = 3.1,
        quality = 5,
        strength = 0.2,
    },

    [46] = {
        agility = 1.7,
        endurance = 3.0,
        id = 46,
        magic = 2.4,
        partner = 10010,
        physique = 2.4,
        quality = 1,
        strength = 0.1,
    },

    [47] = {
        agility = 1.8,
        endurance = 3.2,
        id = 47,
        magic = 2.5,
        partner = 10010,
        physique = 2.6,
        quality = 2,
        strength = 0.1,
    },

    [48] = {
        agility = 1.9,
        endurance = 3.4,
        id = 48,
        magic = 2.7,
        partner = 10010,
        physique = 2.7,
        quality = 3,
        strength = 0.1,
    },

    [49] = {
        agility = 2.0,
        endurance = 3.6,
        id = 49,
        magic = 2.8,
        partner = 10010,
        physique = 2.9,
        quality = 4,
        strength = 0.1,
    },

    [50] = {
        agility = 2.2,
        endurance = 3.8,
        id = 50,
        magic = 3.0,
        partner = 10010,
        physique = 3.1,
        quality = 5,
        strength = 0.2,
    },

    [51] = {
        agility = 0.8,
        endurance = 1.5,
        id = 51,
        magic = 1.6,
        partner = 10011,
        physique = 1.8,
        quality = 1,
        strength = 5.8,
    },

    [52] = {
        agility = 0.8,
        endurance = 1.6,
        id = 52,
        magic = 1.7,
        partner = 10011,
        physique = 1.9,
        quality = 2,
        strength = 6.2,
    },

    [53] = {
        agility = 0.9,
        endurance = 1.7,
        id = 53,
        magic = 1.8,
        partner = 10011,
        physique = 2.0,
        quality = 3,
        strength = 6.5,
    },

    [54] = {
        agility = 0.9,
        endurance = 1.8,
        id = 54,
        magic = 1.9,
        partner = 10011,
        physique = 2.1,
        quality = 4,
        strength = 6.9,
    },

    [55] = {
        agility = 1.0,
        endurance = 1.9,
        id = 55,
        magic = 2.0,
        partner = 10011,
        physique = 2.3,
        quality = 5,
        strength = 7.3,
    },

    [56] = {
        agility = 0.8,
        endurance = 1.5,
        id = 56,
        magic = 1.6,
        partner = 10012,
        physique = 1.8,
        quality = 1,
        strength = 5.8,
    },

    [57] = {
        agility = 0.8,
        endurance = 1.6,
        id = 57,
        magic = 1.7,
        partner = 10012,
        physique = 1.9,
        quality = 2,
        strength = 6.2,
    },

    [58] = {
        agility = 0.9,
        endurance = 1.7,
        id = 58,
        magic = 1.8,
        partner = 10012,
        physique = 2.0,
        quality = 3,
        strength = 6.5,
    },

    [59] = {
        agility = 0.9,
        endurance = 1.8,
        id = 59,
        magic = 1.9,
        partner = 10012,
        physique = 2.1,
        quality = 4,
        strength = 6.9,
    },

    [60] = {
        agility = 1.0,
        endurance = 1.9,
        id = 60,
        magic = 2.0,
        partner = 10012,
        physique = 2.3,
        quality = 5,
        strength = 7.3,
    },

}
