-- ./excel/mail.xlsx
return {

    [1001] = {
        audio = "",
        autoextract = 1,
        content = "由于你包裹空间不足，现通过邮件发放以下奖励",
        desc = "包裹满",
        icon = "h7_xinfeng_1",
        id = 1001,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "包裹已满",
        type = 101,
    },

    [1002] = {
        audio = "",
        autoextract = 0,
        content = "您当前金币携带上限是#carrymax，已经超出了#goldover。超出的金币，会在下线后消失。",
        desc = "金币溢出",
        icon = "h7_xinfeng_1",
        id = 1002,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "货币上限",
        type = 101,
    },

    [1003] = {
        audio = "",
        autoextract = 0,
        content = "您当前银币携带上限是#carrymax，已经超出了#silverover。超出的银币，会在下线后消失。",
        desc = "银币溢出",
        icon = "h7_xinfeng_1",
        id = 1003,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "货币上限",
        type = 101,
    },

    [1004] = {
        audio = "",
        autoextract = 0,
        content = "昨日你在擂台的英勇表现，让本官感到欣慰，今日擂主就是你了，迎接强者的挑战吧。",
        desc = "擂台擂主",
        icon = "h7_xinfeng_1",
        id = 1004,
        keepday = 1,
        name = "武举钦差",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "擂主任命",
        type = 101,
    },

    [1005] = {
        audio = "",
        autoextract = 0,
        content = "您竞拍的#item的出价被其他玩家超过，竞拍资金已经返还到您的包裹",
        desc = "拍卖邮件",
        icon = "h7_xinfeng_1",
        id = 1005,
        keepday = 7,
        name = "拍卖行",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "竞拍失败",
        type = 101,
    },

    [1006] = {
        audio = "",
        autoextract = 0,
        content = "#item被您成功以#amount#money的价格成功竞拍，请及时领取",
        desc = "拍卖邮件",
        icon = "h7_xinfeng_1",
        id = 1006,
        keepday = 7,
        name = "拍卖行",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "竞拍成功",
        type = 101,
    },

    [1007] = {
        audio = "",
        autoextract = 0,
        content = "你关注的#item正式拍卖了",
        desc = "拍卖邮件",
        icon = "h7_xinfeng_1",
        id = 1007,
        keepday = 7,
        name = "拍卖行",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "竞拍开启",
        type = 101,
    },

    [1008] = {
        audio = "",
        autoextract = 1,
        content = "由于你的包裹和临时包裹空间不足，以下获得的奖励已通过邮件发送。邮件过期将会被删除，请及时查收！",
        desc = "包裹和临时包裹满",
        icon = "h7_xinfeng_1",
        id = 1008,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "包裹已满",
        type = 101,
    },

    [1009] = {
        audio = "",
        autoextract = 0,
        content = "您购买的礼包已经全部发放完毕，感谢您对我们的支持。",
        desc = "礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1009,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "周卡豪礼",
        type = 101,
    },

    [1010] = {
        audio = "",
        autoextract = 1,
        content = "你购买的礼包今天可领取的#amount元宝没有及时领取，系统已直接发放给您，可以在充值界面查看",
        desc = "礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1010,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "礼包领取",
        type = 101,
    },

    [1011] = {
        audio = "",
        autoextract = 0,
        content = "给您造成了不愉快的体验非常抱歉，这里是一点小小的礼物请您收下。",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1011,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "补偿礼包",
        type = 101,
    },

    [1012] = {
        audio = "",
        autoextract = 0,
        content = "少年，我看你骨骼惊奇，是一个修仙的好材料。",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1012,
        keepday = 7,
        name = "神秘仙人",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "修仙奇遇礼包",
        type = 101,
    },

    [1013] = {
        audio = "",
        autoextract = 0,
        content = "客服小姐姐们凑份子凑出来的礼包，要珍惜一点使用哦~",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1013,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "QQ群入群礼包",
        type = 101,
    },

    [1014] = {
        audio = "",
        autoextract = 0,
        content = "嘿嘿，你已经成功引起了客服妹子们的注意，礼包收好哦~",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1014,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "QQ群活跃礼包",
        type = 101,
    },

    [1015] = {
        audio = "",
        autoextract = 0,
        content = "官博娘觉得你是个人才，来，礼包拿好！",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1015,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "微博话题礼包",
        type = 101,
    },

    [1016] = {
        audio = "",
        autoextract = 0,
        content = "恭喜中奖~豪华礼包奉上！",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1016,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "微博豪华礼包",
        type = 101,
    },

    [1017] = {
        audio = "",
        autoextract = 0,
        content = "微信娘仙儿的一点小心意，请笑纳。",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1017,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "微信日常礼包",
        type = 101,
    },

    [1018] = {
        audio = "",
        autoextract = 0,
        content = "恭喜中奖~豪华礼包奉上！",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1018,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "微信豪华礼包",
        type = 101,
    },

    [1019] = {
        audio = "",
        autoextract = 0,
        content = "恭喜中奖~豪华礼包奉上！",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1019,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "UC论坛活动礼包",
        type = 101,
    },

    [1020] = {
        audio = "",
        autoextract = 0,
        content = "初次见面，要一直关注#gamename微信公众号哟~",
        desc = "渠道礼包邮件",
        icon = "h7_xinfeng_1",
        id = 1020,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "微信公众号礼包",
        type = 101,
    },

    [1021] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢冲级活动中荣获冠军，#gamename运营团队特为您献上大礼一份，以作庆贺。",
        desc = "冲级榜第1名",
        icon = "h7_xinfeng_1",
        id = 1021,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "冲级榜冠军",
        type = 101,
    },

    [1022] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢冲级活动中夺得亚军，#gamename运营团队特为您献上大礼一份，以作庆贺。",
        desc = "冲级榜第2名",
        icon = "h7_xinfeng_1",
        id = 1022,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "冲级榜亚军",
        type = 101,
    },

    [1023] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢冲级活动中获得季军，#gamename运营团队特为您奉上薄礼一份，请您笑纳。",
        desc = "冲级榜第3名",
        icon = "h7_xinfeng_1",
        id = 1023,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "冲级榜季军",
        type = 101,
    },

    [1024] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢冲级活动中进入前十，#gamename运营团队特为您准备小礼一份，以表祝贺。",
        desc = "冲级榜第4~10名",
        icon = "h7_xinfeng_1",
        id = 1024,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "冲级榜前十",
        type = 101,
    },

    [1025] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢冲级活动中进入前一百，#gamename运营团队特为您准备小礼一份，以表祝贺。",
        desc = "冲级榜第11~100名",
        icon = "h7_xinfeng_1",
        id = 1025,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "冲级榜前一百",
        type = 101,
    },

    [1026] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢个人实力评选活动中荣获冠军，#gamename运营团队特为您献上大礼一份，以作庆贺。",
        desc = "实力榜第1名",
        icon = "h7_xinfeng_1",
        id = 1026,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "实力榜冠军",
        type = 101,
    },

    [1027] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢个人实力评选活动中夺得亚军，#gamename运营团队特为您献上大礼一份，以作庆贺。",
        desc = "实力榜第2名",
        icon = "h7_xinfeng_1",
        id = 1027,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "实力榜亚军",
        type = 101,
    },

    [1028] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢个人实力评选活动中获得季军，#gamename运营团队特为您奉上薄礼一份，请您笑纳。",
        desc = "实力榜第3名",
        icon = "h7_xinfeng_1",
        id = 1028,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "实力榜季军",
        type = 101,
    },

    [1029] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢个人实力评选活动中进入前十，#gamename运营团队特为您准备小礼一份，以表祝贺。",
        desc = "实力榜第4~10名",
        icon = "h7_xinfeng_1",
        id = 1029,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "实力榜前十",
        type = 101,
    },

    [1030] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢个人实力评选活动中进入前一百，#gamename运营团队特为您准备小礼一份，以表祝贺。",
        desc = "实力榜第11~100名",
        icon = "h7_xinfeng_1",
        id = 1030,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "冲级榜前一百",
        type = 101,
    },

    [1031] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢神宠评选活动中荣获冠军，#gamename运营团队特为您献上大礼一份，以作庆贺。",
        desc = "神宠榜第1名",
        icon = "h7_xinfeng_1",
        id = 1031,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "神宠榜冠军",
        type = 101,
    },

    [1032] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢神宠评选活动中夺得亚军，#gamename运营团队特为您献上大礼一份，以作庆贺。",
        desc = "神宠榜第2名",
        icon = "h7_xinfeng_1",
        id = 1032,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "神宠榜亚军",
        type = 101,
    },

    [1033] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢神宠评选活动中获得季军，#gamename运营团队特为您奉上薄礼一份，请您笑纳。",
        desc = "神宠榜第3名",
        icon = "h7_xinfeng_1",
        id = 1033,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "神宠榜季军",
        type = 101,
    },

    [1034] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢神宠评选活动中进入前一百，#gamename运营团队特为您准备小礼一份，以表祝贺。",
        desc = "神宠榜第4~100名",
        icon = "h7_xinfeng_1",
        id = 1034,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "神宠榜前一百",
        type = 101,
    },

    [1035] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢头衔排名活动中荣获冠军，#gamename运营团队特为您准备小礼一份，以表祝贺。",
        desc = "头衔榜第1名",
        icon = "h7_xinfeng_1",
        id = 1035,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "头衔榜冠军",
        type = 101,
    },

    [1036] = {
        audio = "",
        autoextract = 0,
        content = "您在开服狂欢头衔排名活动中进入前十，#gamename运营团队特为您准备小礼一份，以表祝贺。",
        desc = "头衔榜第2~10名",
        icon = "h7_xinfeng_1",
        id = 1036,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "头衔榜前十",
        type = 101,
    },

    [1037] = {
        audio = "",
        autoextract = 0,
        content = "你们帮派获得开服帮派威望排名第一，#gamename运营团队特为您献上大礼一份，以作庆贺。",
        desc = "帮派威望榜第1名",
        icon = "h7_xinfeng_1",
        id = 1037,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "帮派威望榜冠军",
        type = 101,
    },

    [1038] = {
        audio = "",
        autoextract = 0,
        content = "你们帮派获得开服帮派威望排名第二，#gamename运营团队特为您献上大礼一份，以作庆贺。",
        desc = "帮派威望榜第1名",
        icon = "h7_xinfeng_1",
        id = 1038,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "帮派威望榜亚军",
        type = 101,
    },

    [1039] = {
        audio = "",
        autoextract = 0,
        content = "你们帮派进入开服帮派威望排名前十，#gamename运营团队特为您准备小礼一份，以表祝贺。",
        desc = "帮派威望榜第2~10名",
        icon = "h7_xinfeng_1",
        id = 1039,
        keepday = 30,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "帮派威望榜前十",
        type = 101,
    },

    [1040] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n    您充值的#G#coin#n#cur_1已到账，还将获得额外赠送的#G#extcoin#n#cur_2。您可以重新打开商城界面，包裹界面点击元宝图标进行查看。若充值过程中出现异常，请联系官方客服提供您的游戏ID进行反馈查询。感谢您的支持，祝您游戏愉快。",
        desc = "充值邮件",
        icon = "h7_xinfeng_1",
        id = 1040,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "充值成功",
        type = 101,
    },

    [1041] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n    您已成功购买#G#rmb#n元礼包,祝您游戏愉快!若充值过程中出现异常，请联系官方客服提供您的游戏ID进行反馈查询。感谢您的支持，祝您游戏愉快。",
        desc = "充值邮件",
        icon = "h7_xinfeng_1",
        id = 1041,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "充值成功",
        type = 101,
    },

    [1042] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n    您已成功购买的#G#rmb#n元的周卡,祝您游戏愉快!若充值过程中出现异常，请联系官方客服提供您的游戏ID进行反馈查询。感谢您的支持，祝您游戏愉快。",
        desc = "充值邮件",
        icon = "h7_xinfeng_1",
        id = 1042,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "充值成功",
        type = 101,
    },

    [1043] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n    您已成功购买的#G#rmb#n元的月卡,祝您游戏愉快!若充值过程中出现异常，请联系官方客服提供您的游戏ID进行反馈查询。感谢您的支持，祝您游戏愉快。",
        desc = "充值邮件",
        icon = "h7_xinfeng_1",
        id = 1043,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "充值成功",
        type = 101,
    },

    [1044] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n    您已成功购买#G#rmb#n元的一本万利,祝您游戏愉快!若充值过程中出现异常，请联系官方客服提供您的游戏ID进行反馈查询。感谢您的支持，祝您游戏愉快。",
        desc = "充值邮件",
        icon = "h7_xinfeng_1",
        id = 1044,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "充值成功",
        type = 101,
    },

    [2] = {
        audio = "",
        autoextract = 1,
        content = "帮派公告的内容{link13, %d,#G[点我点我]#n}#1#1[audio]testspeech_mp3,显示语音翻译内容（需要策划手动配置翻译内容和语音时长）,23[/audio][image]local:h7_sanjiedoufa_1,300,200,http://oa.cilugame.com/redmine[/image]",
        desc = "测试",
        icon = "h7_xinfeng_1",
        id = 2,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "帮派公告",
        type = 101,
    },

    [3] = {
        audio = "Mail/dianji.ogg",
        autoextract = 1,
        content = "测试用的内容",
        desc = "ceshi",
        icon = "h7_xinfeng_1",
        id = 3,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "测试用",
        type = 101,
    },

    [4] = {
        audio = "",
        autoextract = 0,
        content = "帮派公告的内容{link13, %d,#G[点我点我]#n}#1#1[audio]testspeech_mp3,测试（显示语音翻译内容）,23[/audio][image]pp,200,300,http://oa.cilugame.com/redmine[/image]",
        desc = "测试",
        icon = "h7_xinfeng_1",
        id = 4,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "不可一键",
        type = 101,
    },

    [5] = {
        audio = "Mail/xsydy20.mp3",
        autoextract = 0,
        content = "亲爱的玩家，由于你长时间未登录，你的靓号已被系统回收。",
        desc = "靓号回收",
        icon = "h7_xinfeng_1",
        id = 5,
        keepday = 60,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "靓号回收",
        type = 101,
    },

    [2001] = {
        audio = "",
        autoextract = 1,
        content = "上周完成门派修行次数达到100次，为师甚感欣慰，给你准备了一份礼物，希望你再接再厉。",
        desc = "门派周奖励",
        icon = "h7_xinfeng_1",
        id = 2001,
        keepday = 8,
        name = "师傅",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "门派奖励",
        type = 101,
    },

    [2002] = {
        audio = "",
        autoextract = 1,
        content = "这是您昨天没有及时领取的活跃度奖励，请查收！",
        desc = "日程奖励",
        icon = "h7_xinfeng_1",
        id = 2002,
        keepday = 3,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "活跃度奖励",
        type = 101,
    },

    [2003] = {
        audio = "",
        autoextract = 0,
        content = "亲爱玩家，您的称谓【#title】因过期已被系统回收。",
        desc = "称谓邮件",
        icon = "h7_xinfeng_1",
        id = 2003,
        keepday = 3,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "到期称谓",
        type = 101,
    },

    [2004] = {
        audio = "",
        autoextract = 0,
        content = "你的好友#oname已把名字修改为#nname了，特此通知。",
        desc = "改名通知",
        icon = "h7_xinfeng_1",
        id = 2004,
        keepday = 3,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "改名通知",
        type = 101,
    },

    [2005] = {
        audio = "",
        autoextract = 1,
        content = "截止本赛季您在竞技场中的最终排名为#rank名，请从附件中收取您的排名奖励，请您再接再厉！",
        desc = "竞技场赛季奖励",
        icon = "h7_xinfeng_1",
        id = 2005,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "竞技赛季奖励",
        type = 101,
    },

    [2006] = {
        audio = "",
        autoextract = 1,
        content = "截止到今天22点整，您在竞技场中的排名为#rank名，请从附件中收取您的每日排名奖励，请您再接再厉！",
        desc = "竞技场日奖励",
        icon = "h7_xinfeng_1",
        id = 2006,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "竞技场日奖励",
        type = 101,
    },

    [2007] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的连续挑战奖励，请从附件中查收！",
        desc = "连续挑战奖励",
        icon = "h7_xinfeng_1",
        id = 2007,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "连续挑战奖励",
        type = 101,
    },

    [2008] = {
        audio = "",
        autoextract = 1,
        content = "由于你协助#role完成了探险任务，获得了#item，请注意查收。",
        desc = "连续挑战奖励",
        icon = "h7_xinfeng_1",
        id = 2008,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "异宝协助奖励",
        type = 101,
    },

    [2009] = {
        audio = "",
        autoextract = 0,
        content = "你关注的#item正式拍卖了",
        desc = "拍卖",
        icon = "h7_xinfeng_1",
        id = 2009,
        keepday = 7,
        name = "拍卖行",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "拍卖开始",
        type = 101,
    },

    [2010] = {
        audio = "",
        autoextract = 0,
        content = "亲爱的玩家，由于特殊原因#item的拍卖取消，您的#amount#money已经返还到您的包裹。",
        desc = "拍卖",
        icon = "h7_xinfeng_1",
        id = 2010,
        keepday = 7,
        name = "拍卖行",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "拍卖取消",
        type = 101,
    },

    [2011] = {
        audio = "",
        autoextract = 0,
        content = "你以#amount#money的价格成功竞拍到#item",
        desc = "拍卖",
        icon = "h7_xinfeng_1",
        id = 2011,
        keepday = 7,
        name = "拍卖行",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "拍卖成功",
        type = 101,
    },

    [2012] = {
        audio = "",
        autoextract = 1,
        content = "骰子玩法中获得的奖励以由邮件发放给您，请注意查收。",
        desc = "骰子",
        icon = "h7_xinfeng_1",
        id = 2012,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "骰子奖励",
        type = 101,
    },

    [2014] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届门派试炼中夺得冠军，曜日星君特送上一份礼物给您，祝您下次继续蝉联冠军",
        desc = "门派试炼",
        icon = "h7_xinfeng_1",
        id = 2014,
        keepday = 7,
        name = "曜日星君",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "试炼冠军",
        type = 101,
    },

    [2015] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届门派试炼中夺得第二名，曜日星君特送上一份礼物给您，祝您下次夺得冠军",
        desc = "门派试炼",
        icon = "h7_xinfeng_1",
        id = 2015,
        keepday = 7,
        name = "曜日星君",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "试炼亚军",
        type = 101,
    },

    [2016] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届门派试炼中夺得第三名，曜日星君特送上一份礼物给您，祝您下次夺得冠军",
        desc = "门派试炼",
        icon = "h7_xinfeng_1",
        id = 2016,
        keepday = 7,
        name = "曜日星君",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "试炼季军",
        type = 101,
    },

    [2017] = {
        audio = "",
        autoextract = 1,
        content = "感谢您参与本届门派试炼，送上一份参与奖给您，希望您下届取得更好的成绩",
        desc = "门派试炼",
        icon = "h7_xinfeng_1",
        id = 2017,
        keepday = 7,
        name = "曜日星君",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "试炼礼包",
        type = 101,
    },

    [2018] = {
        audio = "",
        autoextract = 1,
        content = "徒儿，为师先恭喜你达到20级，修为更进一步，现在你可以回来找为师开始门派修行了，奖励很丰厚。你的天赋很高，令道祖都感到惊艳。但在仙路上会有无数阻碍和难关，需要你一步步地走下来，坚持才能登上顶峰。",
        desc = "主线",
        icon = "h7_xinfeng_1",
        id = 2018,
        keepday = 7,
        name = "门派掌门",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "掌门的传音",
        type = 101,
    },

    [2019] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届三界斗法中夺得冠军，斗法组委会特送上一份礼物给您，祝您下次继续蝉联冠军",
        desc = "三界斗法",
        icon = "h7_xinfeng_1",
        id = 2019,
        keepday = 7,
        name = "斗法组委会",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "三界斗法冠军",
        type = 101,
    },

    [2020] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届三界斗法中夺得第二名，斗法组委会特送上一份礼物给您，祝您下次夺得冠军",
        desc = "三界斗法",
        icon = "h7_xinfeng_1",
        id = 2020,
        keepday = 7,
        name = "斗法组委会",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "三界斗法亚军",
        type = 101,
    },

    [2021] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届三界斗法中夺得第三名，斗法组委会特送上一份礼物给您，祝您下次夺得冠军",
        desc = "三界斗法",
        icon = "h7_xinfeng_1",
        id = 2021,
        keepday = 7,
        name = "斗法组委会",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "三界斗法季军",
        type = 101,
    },

    [2022] = {
        audio = "",
        autoextract = 1,
        content = "感谢您参与本届三界斗法，送上一份参与奖给您，希望您下届取得更好的成绩",
        desc = "三界斗法",
        icon = "h7_xinfeng_1",
        id = 2022,
        keepday = 7,
        name = "斗法组委会",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "三界斗法礼包",
        type = 101,
    },

    [2023] = {
        audio = "",
        autoextract = 1,
        content = "本次“帮派封魔”活动中您的帮派排名#rank_idx，您个人伤害排名#rank_idx，帮派总管甚感欣慰，特送您以下礼物：",
        desc = "帮派封魔奖励",
        icon = "h7_xinfeng_1",
        id = 2023,
        keepday = 7,
        name = "帮派总管",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "帮派封魔奖励",
        type = 101,
    },

    [2024] = {
        audio = "",
        autoextract = 1,
        content = "#G《#gamename》#n首测耀世开启，白蛇传说经典重新演绎，宏大的仙侠世界欢迎道友的到来。首次测试还有诸多需要改善之处，欢迎道友加入官方QQ群提出宝贵建议和我们一起改善，#O500元宝#n创号福利先行奉上，请笑纳",
        desc = "创号福利",
        icon = "h7_xinfeng_1",
        id = 2024,
        keepday = 7,
        name = "新手指导员",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "欢迎来到《#gamename》",
        type = 101,
    },

    [2025] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在全民答题单轮榜中夺得#rank名！",
        desc = "全民答题",
        icon = "h7_xinfeng_1",
        id = 2025,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "全民答题单轮排行奖励",
        type = 101,
    },

    [2026] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在全民答题总榜中夺得#rank名！",
        desc = "全民答题",
        icon = "h7_xinfeng_1",
        id = 2026,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "全民答题总榜排行奖励",
        type = 101,
    },

    [2027] = {
        audio = "",
        autoextract = 1,
        content = "感谢你对全民答题的贡献，奉上薄礼一份！",
        desc = "全民答题",
        icon = "h7_xinfeng_1",
        id = 2027,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "全民答题单轮参与奖励",
        type = 101,
    },

    [2028] = {
        audio = "",
        autoextract = 1,
        content = "您在英雄试炼中击败了对手，但未领取奖励，特此为您奉上。",
        desc = "英雄试炼",
        icon = "h7_xinfeng_1",
        id = 2028,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "英雄试炼未领取奖励",
        type = 101,
    },

    [2029] = {
        audio = "",
        autoextract = 1,
        content = "您在画舫灯谜中答对了题，奖励未能及时领取，已通过本邮件附件邮寄。请注意查收",
        desc = "画舫灯谜",
        icon = "h7_xinfeng_1",
        id = 2029,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "画舫灯谜答对题未领取奖励",
        type = 101,
    },

    [2030] = {
        audio = "",
        autoextract = 1,
        content = "您在画舫灯谜中参与答题活动，奖励未能及时领取，已通过本邮件附件邮寄。请注意查收",
        desc = "画舫灯谜",
        icon = "h7_xinfeng_1",
        id = 2030,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "画舫灯谜答错题未领取奖励",
        type = 101,
    },

    [2031] = {
        audio = "",
        autoextract = 1,
        content = "您在画舫灯谜中累计答对5题，奖励未能及时领取，已通过本邮件附件邮寄。请注意查收",
        desc = "画舫灯谜",
        icon = "h7_xinfeng_1",
        id = 2031,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "画舫灯谜累计答对题未领取奖励",
        type = 101,
    },

    [2032] = {
        audio = "",
        autoextract = 1,
        content = "\n亲爱的玩家：\n  <<#gamename>>已正式开启公测！为感谢您对我们游戏的支持，您这个账号下的角色达到10级后，可前往【福利界面】-【公测返利】处领取您在封测期间充值返还的元宝。我们还为您准备了神秘大礼，请记得领取哦。\n  感谢您一直以来对<<#gamename>>的支持与厚爱！",
        desc = "公测返利",
        icon = "h7_xinfeng_1",
        id = 2032,
        keepday = 7,
        name = "#gamename运营团队",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "公测返利",
        type = 101,
    },

    [2033] = {
        audio = "",
        autoextract = 0,
        content = "在本届三界斗法活动中，您获得了点武勋值",
        desc = "三界斗法",
        icon = "h7_xinfeng_1",
        id = 2033,
        keepday = 7,
        name = "斗法组委会",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "武勋奖励",
        type = 101,
    },

    [2034] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的七星宝箱活动奖励，请查收！连续登陆天数越长，获得的奖励越丰富，记得登陆领取哦！",
        desc = "七星宝箱",
        icon = "h7_xinfeng_1",
        id = 2034,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "七星宝箱奖励",
        type = 101,
    },

    [2035] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的每日单充活动奖励，请查收！充值额度越高，获得的奖励越丰富！活动期间，每日的奖励还不一样哦！",
        desc = "每日单充",
        icon = "h7_xinfeng_1",
        id = 2035,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "每日单充奖励",
        type = 101,
    },

    [2036] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的超级返利活动奖励，请查收！充值额度越高，返利越高！",
        desc = "超级返利",
        icon = "h7_xinfeng_1",
        id = 2036,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "超级返利奖励",
        type = 101,
    },

    [2037] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的每日累充活动奖励，请查收！每日充值元宝越多，获得的礼品奖励越丰富！",
        desc = "每日累充",
        icon = "h7_xinfeng_1",
        id = 2037,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "每日累充奖励",
        type = 101,
    },

    [2038] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的每日累消活动奖励，请查收！每日消费元宝越多，获得的礼品奖励越丰富！",
        desc = "每日累消",
        icon = "h7_xinfeng_1",
        id = 2038,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "每日累消奖励",
        type = 101,
    },

    [2039] = {
        audio = "",
        autoextract = 1,
        content = "亲爱的玩家，系统检测到您身上的龙血秘藏已无法使用。现回收您的龙血秘藏道具，并按照商会出售的价格，补偿对应数量的金币。给您带来不便，敬请谅解，祝您游戏愉快。",
        desc = "龙血秘藏回收",
        icon = "h7_xinfeng_1",
        id = 2039,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "龙血秘藏回收",
        type = 101,
    },

    [2040] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届九州争霸中夺得冠军，请查收您的奖励，祝您下次继续蝉联冠军",
        desc = "三人比武",
        icon = "h7_xinfeng_1",
        id = 2040,
        keepday = 7,
        name = "九州联盟",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "九州争霸冠军",
        type = 101,
    },

    [2041] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届九州争霸中夺得第二名，请查收您的奖励，祝您下次夺得冠军",
        desc = "三人比武",
        icon = "h7_xinfeng_1",
        id = 2041,
        keepday = 7,
        name = "九州联盟",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "九州争霸亚军",
        type = 101,
    },

    [2042] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届九州争霸中夺得第三名，请查收您的奖励，祝您下次夺得冠军",
        desc = "三人比武",
        icon = "h7_xinfeng_1",
        id = 2042,
        keepday = 7,
        name = "九州联盟",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "九州争霸季军",
        type = 101,
    },

    [2043] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本届九州争霸成功上榜，请查收您的奖励，祝您下次夺得冠军",
        desc = "三人比武",
        icon = "h7_xinfeng_1",
        id = 2043,
        keepday = 7,
        name = "九州联盟",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "九州争霸上榜",
        type = 101,
    },

    [2044] = {
        audio = "",
        autoextract = 1,
        content = "感谢您参与本届九州争霸，并获得首胜，送上一份参与奖给您，希望您下届取得更好的成绩",
        desc = "三人比武",
        icon = "h7_xinfeng_1",
        id = 2044,
        keepday = 7,
        name = "九州联盟",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "九州争霸首胜",
        type = 101,
    },

    [2045] = {
        audio = "",
        autoextract = 1,
        content = "感谢您参与本届九州争霸，并完成五战，送上一份参与奖给您，希望您下届取得更好的成绩",
        desc = "三人比武",
        icon = "h7_xinfeng_1",
        id = 2045,
        keepday = 7,
        name = "九州联盟",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "九州争霸五战",
        type = 101,
    },

    [2046] = {
        audio = "",
        autoextract = 1,
        content = "您开服狂欢活动中目标奖励未领取，已通过邮件快递给少侠了，请查收！",
        desc = "开服狂欢",
        icon = "h7_xinfeng_1",
        id = 2046,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "开服狂欢",
        type = 101,
    },

    [2047] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的河神祈福活动奖励，请查收！",
        desc = "河神祈福",
        icon = "h7_xinfeng_1",
        id = 2047,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "河神祈福奖励",
        type = 101,
    },

    [2048] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的活跃礼包活动奖励，请查收",
        desc = "活跃礼包",
        icon = "h7_xinfeng_1",
        id = 2048,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "活跃礼包",
        type = 101,
    },

    [2049] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的聚宝盆积分奖励，请查收",
        desc = "聚宝盆",
        icon = "h7_xinfeng_1",
        id = 2049,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "聚宝盆积分",
        type = 101,
    },

    [2050] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本次聚宝盆活动中获得第#rank名，请查收您的奖励！",
        desc = "聚宝盆",
        icon = "h7_xinfeng_1",
        id = 2050,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "聚宝盆排行",
        type = 101,
    },

    [2051] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的连环充值奖励，请查收",
        desc = "连环充值",
        icon = "h7_xinfeng_1",
        id = 2051,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "连环充值",
        type = 101,
    },

    [2052] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的连环充值累计奖励，请查收",
        desc = "连环充值",
        icon = "h7_xinfeng_1",
        id = 2052,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "连环充值",
        type = 101,
    },

    [2053] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的连环消费奖励，请查收",
        desc = "连环消费",
        icon = "h7_xinfeng_1",
        id = 2053,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "连环消费",
        type = 101,
    },

    [2054] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的连环消费累计奖励，请查收",
        desc = "连环消费",
        icon = "h7_xinfeng_1",
        id = 2054,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "连环消费",
        type = 101,
    },

    [2055] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在#rank榜中成功问鼎三甲，恭喜您获得#title称谓，请查收",
        desc = "每日冲榜",
        icon = "h7_xinfeng_1",
        id = 2055,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "#rank榜称谓奖励  ",
        type = 101,
    },

    [2056] = {
        audio = "",
        autoextract = 1,
        content = "亲爱的玩家您好！感谢您对《#gamename》的支持，春节期间（2018年2月12日00:00-2018年2月23日00:00）使用折扣券后可限时打折购买商城道具",
        desc = "商城限时打折",
        icon = "h7_xinfeng_1",
        id = 2056,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "商城限时打折",
        type = 101,
    },

    [2057] = {
        audio = "",
        autoextract = 1,
        content = "您有未领取的元宝狂欢活动奖励，请查收 ！",
        desc = "元宝狂欢",
        icon = "h7_xinfeng_1",
        id = 2057,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "元宝狂欢奖励 ",
        type = 101,
    },

    [2058] = {
        audio = "",
        autoextract = 1,
        content = "你已收#role为徒，请以后多多照顾他哦！",
        desc = "师徒系统",
        icon = "h7_xinfeng_1",
        id = 2058,
        keepday = 7,
        name = "国子监",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "拜师信息",
        type = 101,
    },

    [2059] = {
        audio = "",
        autoextract = 1,
        content = "你已拜#role为师，以后要多向师傅请教哦！",
        desc = "师徒系统",
        icon = "h7_xinfeng_1",
        id = 2059,
        keepday = 7,
        name = "国子监",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "拜师信息",
        type = 101,
    },

    [2060] = {
        audio = "",
        autoextract = 1,
        content = "你的徒弟#role已达到出师条件，可以和徒弟组队前往国子监祭酒处出师。注意：教学成绩越高师傅的出师奖励越高！",
        desc = "师徒系统",
        icon = "h7_xinfeng_1",
        id = 2060,
        keepday = 7,
        name = "国子监",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "出师提醒",
        type = 101,
    },

    [2061] = {
        audio = "",
        autoextract = 1,
        content = "恭喜你已达到出师条件，可以出师了。和师傅组队前往国子监祭酒处出师吧。",
        desc = "师徒系统",
        icon = "h7_xinfeng_1",
        id = 2061,
        keepday = 7,
        name = "国子监",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "出师提醒",
        type = 101,
    },

    [2062] = {
        audio = "",
        autoextract = 1,
        content = "由于你长期未上线，你的徒弟#role申请了强制出师",
        desc = "师徒系统",
        icon = "h7_xinfeng_1",
        id = 2062,
        keepday = 7,
        name = "国子监",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "强制出师申请",
        type = 101,
    },

    [2063] = {
        audio = "",
        autoextract = 1,
        content = "由于你长期未上线，你的师傅#role申请了强制出师",
        desc = "师徒系统",
        icon = "h7_xinfeng_1",
        id = 2063,
        keepday = 7,
        name = "国子监",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "强制出师申请",
        type = 101,
    },

    [2064] = {
        audio = "",
        autoextract = 1,
        content = "你的徒弟#role已强制出师",
        desc = "师徒系统",
        icon = "h7_xinfeng_1",
        id = 2064,
        keepday = 7,
        name = "国子监",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "强制出师",
        type = 101,
    },

    [2065] = {
        audio = "",
        autoextract = 1,
        content = "你的师傅#role已强制出师",
        desc = "师徒系统",
        icon = "h7_xinfeng_1",
        id = 2065,
        keepday = 7,
        name = "国子监",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "强制出师",
        type = 101,
    },

    [2066] = {
        audio = "",
        autoextract = 1,
        content = "#role解除了你们的师徒关系",
        desc = "师徒系统",
        icon = "h7_xinfeng_1",
        id = 2066,
        keepday = 7,
        name = "国子监",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "师徒关系解除",
        type = 101,
    },

    [2067] = {
        audio = "",
        autoextract = 1,
        content = "#role已经取消了结拜仪式",
        desc = "结拜系统",
        icon = "h7_xinfeng_1",
        id = 2067,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "结拜仪式取消",
        type = 101,
    },

    [2068] = {
        audio = "",
        autoextract = 1,
        content = "由于发起者发起结拜仪式失败或发起者取消结拜申请，现返还接受结拜邀请时上交的银币",
        desc = "结拜系统",
        icon = "h7_xinfeng_1",
        id = 2068,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "结拜仪式费用返还",
        type = 101,
    },

    [2069] = {
        audio = "",
        autoextract = 1,
        content = "由于结拜团队没有通过对你的接纳申请，现返还接受结拜邀请时上交的银币",
        desc = "结拜系统",
        icon = "h7_xinfeng_1",
        id = 2069,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "结拜仪式费用返还",
        type = 101,
    },

    [2070] = {
        audio = "",
        autoextract = 1,
        content = "恭喜#role成为了我们团队的一员",
        desc = "结拜系统",
        icon = "h7_xinfeng_1",
        id = 2070,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "接纳新人",
        type = 101,
    },

    [2071] = {
        audio = "",
        autoextract = 1,
        content = "#role发起了割袍断义，他已不再是结义团队一员！",
        desc = "结拜系统",
        icon = "h7_xinfeng_1",
        id = 2071,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "割袍断义",
        type = 101,
    },

    [2072] = {
        audio = "",
        autoextract = 1,
        content = "您使用了#multiple倍充值返利机会并充值了#charge元宝，以下是您本次充值的元宝返还",
        desc = "欢乐返利",
        icon = "h7_xinfeng_1",
        id = 2072,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "欢乐返利元宝返还",
        type = 101,
    },

    [2073] = {
        audio = "",
        autoextract = 1,
        content = "您有之前未领取的欢乐返利活动奖励，请查收！",
        desc = "欢乐返利",
        icon = "h7_xinfeng_1",
        id = 2073,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "欢乐返利每日奖励",
        type = 101,
    },

    [2074] = {
        audio = "",
        autoextract = 1,
        content = "您在蜀山论道活动中，成功完成首胜或五战，有未领取的相应奖励，请查收 ！",
        desc = "蜀山论道",
        icon = "h7_xinfeng_1",
        id = 2074,
        keepday = 7,
        name = "蜀山",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "蜀山论道战斗奖励 ",
        type = 101,
    },

    [2075] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在蜀山论道活动#group组取得#rank名，并获得丰厚的奖励，请查收您的奖励！",
        desc = "蜀山论道",
        icon = "h7_xinfeng_1",
        id = 2075,
        keepday = 7,
        name = "蜀山",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "蜀山论道排名奖励 ",
        type = 101,
    },

    [2076] = {
        audio = "",
        autoextract = 1,
        content = "您有之前未领取的道具投资奖励，请查收！",
        desc = "道具投资",
        icon = "h7_xinfeng_1",
        id = 2076,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "道具投资奖励 ",
        type = 101,
    },

    [2077] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在天问初试中表现突出并获得了天问终试的参与资格，请于今晚#start_time至#end_time期间前往杭州城的#G天问仙人#n处进行天问终试答题。",
        desc = "天问答题",
        icon = "h7_xinfeng_1",
        id = 2077,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "入选天问终试",
        type = 101,
    },

    [2078] = {
        audio = "",
        autoextract = 1,
        content = "您本次并未取得天问终试的参与资格，请下周再接再厉。",
        desc = "天问答题",
        icon = "h7_xinfeng_1",
        id = 2078,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "落选天问终试",
        type = 101,
    },

    [2079] = {
        audio = "",
        autoextract = 1,
        content = "恭喜您在本周的天问终试中表现突出并赢得了【#title】的称号，以下是您本次天问终试的奖励",
        desc = "天问答题",
        icon = "h7_xinfeng_1",
        id = 2079,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "#title奖励",
        type = 101,
    },

    [2080] = {
        audio = "",
        autoextract = 1,
        content = "您在本周的天问终试中未能取得前三名，请下周再接再厉勇夺前三！以下是您本次天问终试的奖励",
        desc = "天问答题",
        icon = "h7_xinfeng_1",
        id = 2080,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "天问终试奖励",
        type = 101,
    },

    [2081] = {
        audio = "",
        autoextract = 1,
        content = "西湖有你更精彩，感谢你对游戏的支持！您在0元购活动中获得#num元宝的返利还未领取，现为您奉上，祝您游戏愉快！",
        desc = "0元大礼包",
        icon = "h7_xinfeng_1",
        id = 2081,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "0元大礼包",
        type = 101,
    },

    [2082] = {
        audio = "",
        autoextract = 1,
        content = "经过多日的角逐，本次甜咸粽子大赛终于分出了胜负，最终甜粽子获得了本次大赛的最终胜利！所有参与活动的玩家均能获得3个甜粽子，请查收！",
        desc = "粽子大赛",
        icon = "h7_xinfeng_1",
        id = 2082,
        keepday = 7,
        name = "大赛组委会",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "粽子大赛",
        type = 101,
    },

    [2083] = {
        audio = "",
        autoextract = 1,
        content = "您在#hometeamvs#awayteam的竞猜中正确命中，获得了以下奖励，请注意查收，",
        desc = "世界杯单场",
        icon = "h7_xinfeng_1",
        id = 2083,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "竞猜命中",
        type = 101,
    },

    [2084] = {
        audio = "",
        autoextract = 1,
        content = "您在#hometeamvs#awayteam的竞猜中不幸失误，获得了以下奖励，请注意查收，",
        desc = "世界杯单场",
        icon = "h7_xinfeng_1",
        id = 2084,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "竞猜失误",
        type = 101,
    },

    [2085] = {
        audio = "",
        autoextract = 1,
        content = "感谢您对#team的大力支持，使本球队赢得了一次又一次胜利。请允许我们奉上一点小小礼物，以示谢意。",
        desc = "世界杯冠军",
        icon = "h7_xinfeng_1",
        id = 2085,
        keepday = 7,
        name = "#team队",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "球队的感谢",
        type = 101,
    },

    [2086] = {
        audio = "",
        autoextract = 1,
        content = "由于不可抗力的影响，世界杯赛程发生了一点小小的改变，我们特地奉上小小礼物，以示歉意！",
        desc = "世界杯冠军",
        icon = "h7_xinfeng_1",
        id = 2086,
        keepday = 7,
        name = "不可抗力组委会",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "赛程变更通知",
        type = 101,
    },

    [2087] = {
        audio = "",
        autoextract = 1,
        content = "经过多日的角逐，本次甜咸粽子大赛终于分出了胜负，最终咸粽子获得了本次大赛的最终胜利！所有参与活动的玩家均能获得3个咸粽子，请查收！",
        desc = "粽子大赛",
        icon = "h7_xinfeng_1",
        id = 2087,
        keepday = 7,
        name = "大赛组委会",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "粽子大赛",
        type = 101,
    },

    [3001] = {
        audio = "",
        autoextract = 0,
        content = "人各有志，#ybzname决定卸任帮主之位，禅让给#jczname，希望帮派能在他的带领和大家的努力下问鼎巅峰。",
        desc = "帮主禅让",
        icon = "h7_xinfeng_1",
        id = 3001,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "帮主禅让",
        type = 102,
    },

    [3002] = {
        audio = "",
        autoextract = 0,
        content = "#ybzname已经4天没上线了，#zjzname自我推荐为帮主。如果#G48小时内#n没人反对，则成为新帮主。希望大家能和他一起努力让我们帮派走向辉煌，走向巅峰。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3002,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "自荐帮主",
        type = 102,
    },

    [3003] = {
        audio = "",
        autoextract = 0,
        content = "#zjzname自我推荐为帮主时。有人反对，自荐失败。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3003,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "反对自荐帮主",
        type = 102,
    },

    [3004] = {
        audio = "",
        autoextract = 0,
        content = "#zjzname自我推荐成为帮主。48小时内没人反对，成为新帮主。希望大家能和他一起努力让我们帮派走向辉煌，走向巅峰。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3004,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "自荐帮主成功",
        type = 102,
    },

    [3005] = {
        audio = "",
        autoextract = 0,
        content = "#kqhdzname上一周累计战力最高，故获得了【客卿】职位。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3005,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "客卿获得者",
        type = 102,
    },

    [3006] = {
        audio = "",
        autoextract = 0,
        content = "#zjshdezname上一周累计战力最高，故获得了【执剑使】职位。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3006,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "执剑使获得者",
        type = 102,
    },

    [3007] = {
        audio = "",
        autoextract = 0,
        content = "你#bpcjtime，创建的帮派，24小时内响应人数不够20人，创建失败！",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3007,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "建帮失败",
        type = 102,
    },

    [3008] = {
        audio = "",
        autoextract = 0,
        content = "恭喜你，创建帮派成功啦，你成了#bpname帮派的帮主，赶紧和小伙伴们一起建设帮派吧~",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3008,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "建帮成功",
        type = 102,
    },

    [3009] = {
        audio = "",
        autoextract = 0,
        content = "恭喜你，加入了#bpname帮派，去和大家打个招呼吧~{link13, %d, #G[立刻打招呼]#n}",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3009,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "加入帮派",
        type = 102,
    },

    [3010] = {
        audio = "",
        autoextract = 0,
        content = "你被#bpname帮派的管理员，踢出了帮派。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3010,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "踢出帮派",
        type = 102,
    },

    [3011] = {
        audio = "",
        autoextract = 0,
        content = "帮派资金已经无法正常维护帮派高达（天数通配符）天。（建筑名字通配符）建筑降低1级。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3011,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "建筑降级",
        type = 102,
    },

    [3012] = {
        audio = "",
        autoextract = 0,
        content = "您的帮派已经连续#O7天#n繁荣度为#R荒芜#n了。如果连续繁荣度连续#O21天#n都为#R荒芜#n！您的帮派将会被自动解散。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3012,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "帮派繁荣度",
        type = 102,
    },

    [3013] = {
        audio = "",
        autoextract = 0,
        content = "您的帮派已经连续#O14天#n繁荣度为#R荒芜#n了。如果连续繁荣度连续#O21天#n都为#R荒芜#n！您的帮派将会被自动解散。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3013,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "帮派繁荣度",
        type = 102,
    },

    [3014] = {
        audio = "",
        autoextract = 0,
        content = "您所在帮派因连续#O21天#n繁荣度都为#R荒芜#n！已经自动解散了。",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3014,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "帮派解散",
        type = 102,
    },

    [3015] = {
        audio = "",
        autoextract = 0,
        content = "你所在的帮派已经成功入选帮派竞赛名单。帮派对战表已经产生，请通过【帮派】-【神殿】-【帮派竞赛】进行查看。\n第一轮战斗将于#G周二20:30#n开启，请满足条件(等级≥30，入帮天数＞2天)的参战人员做好准备！",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3015,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "帮派竞赛通知",
        type = 102,
    },

    [3016] = {
        audio = "",
        autoextract = 0,
        content = "周四的帮派竞赛对战信息已产生，请通过【帮派】-【神殿】-【帮派竞赛】进行查看。\n第二轮战斗将于#G周四20:30#n开启，请满足条件(等级≥30，入帮天数＞2)的参战人员做好准备！",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3016,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "帮派竞赛通知",
        type = 102,
    },

    [3017] = {
        audio = "",
        autoextract = 0,
        content = "因为你累计48小时没有上线，被自动请离帮派，保持活跃才会更容易让大家的喜欢哦",
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3017,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "脱离帮派",
        type = 102,
    },

    [3018] = {
        audio = "",
        autoextract = 0,
        content = "帮派通告",
        desc = "帮派通告",
        icon = "h7_xinfeng_1",
        id = 3018,
        keepday = 7,
        name = "帮派通告",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "帮派通告",
        type = 102,
    },

    [3019] = {
        audio = "",
        autoextract = 0,
        content = "帮主#role把帮派名字修改成了#bpname",
        desc = "帮派通告",
        icon = "h7_xinfeng_1",
        id = 3019,
        keepday = 7,
        name = "帮派通告",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "帮派通告",
        type = 102,
    },

    [3020] = {
        audio = "",
        autoextract = 0,
        content = [=[恭喜你，加入了#bpname帮派，去和大家打个招呼吧~{link13, %d, #G[立刻打招呼]#n}
你目前等级过低，自动成为了帮派学徒。学徒不能享受帮派的个别福利哦~而且连续48小时不上线，还会被系统自动清理出帮派哦！
转为正式成员后，可以领取各种帮派福利，且不会被自动清理出帮派。
【学徒转正方法】
1.等级≥45级，且在本帮获得帮贡≥100，次日凌晨5点自动转正（成员满了不会转正）
2.被帮派管理员手动转正。]=],
        desc = "帮派邮件",
        icon = "h7_xinfeng_1",
        id = 3020,
        keepday = 7,
        name = "帮派管理员",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "加入帮派",
        type = 102,
    },

    [4001] = {
        audio = "",
        autoextract = 0,
        content = [=[恭喜你和#role订婚成功，今天起，#role就是你的未婚夫了。希望接下来的日子，你们能够互相扶持，互相爱护，成为大乾王朝中令人羡慕的一对。
你使用了银戒指礼包与#role的订婚成功获得以下奖励
·银戒指（可以在人物属性界面查看戒指属性和技能）
·订婚专属称号]=],
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4001,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "订婚成功",
        type = 101,
    },

    [4002] = {
        audio = "",
        autoextract = 0,
        content = [=[恭喜你和#role订婚成功，今天起，#role就是你的未婚妻了。希望接下来的日子，你们能够互相扶持，互相爱护，成为大乾王朝中令人羡慕的一对。
#role使用了银戒指礼包与你订婚成功获得以下奖励
·银戒指（可以在人物属性界面查看戒指属性和技能）
·订婚专属称号]=],
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4002,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "订婚成功",
        type = 101,
    },

    [4003] = {
        audio = "",
        autoextract = 0,
        content = [=[恭喜你和#role订婚成功，今天起，#role就是你的未婚夫了。希望接下来的日子，你们能够互相扶持，互相爱护，成为大乾王朝中令人羡慕的一对。
你使用了金戒指礼包与#role的订婚成功获得以下奖励
·金戒指（可以在人物属性界面查看戒指属性和技能）
·5朵红玫瑰
·订婚专属称号]=],
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4003,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "订婚成功",
        type = 101,
    },

    [4004] = {
        audio = "",
        autoextract = 0,
        content = [=[恭喜你和#role订婚成功，今天起，#role就是你的未婚妻了。希望接下来的日子，你们能够互相扶持，互相爱护，成为大乾王朝中令人羡慕的一对。
#role使用了金戒指礼包与你订婚成功获得以下奖励
·金戒指（可以在人物属性界面查看戒指属性和技能）
·5朵红玫瑰
·订婚专属称号]=],
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4004,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "订婚成功",
        type = 101,
    },

    [4005] = {
        audio = "",
        autoextract = 0,
        content = [=[恭喜你和#role订婚成功，今天起，#role就是你的未婚夫了。希望接下来的日子，你们能够互相扶持，互相爱护，成为大乾王朝中令人羡慕的一对。
你使用了钻石戒指礼包与#role的订婚成功获得以下奖励
·钻石戒指（可以在人物属性界面查看戒指属性和技能）
·10朵红玫瑰
·订婚专属称号]=],
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4005,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "订婚成功",
        type = 101,
    },

    [4006] = {
        audio = "",
        autoextract = 0,
        content = [=[恭喜你和#role订婚成功，今天起，#role就是你的未婚妻了。希望接下来的日子，你们能够互相扶持，互相爱护，成为大乾王朝中令人羡慕的一对。
#role使用了钻石戒指礼包与你订婚成功获得以下奖励
·钻石戒指（可以在人物属性界面查看戒指属性和技能）
·10朵红玫瑰
·订婚专属称号]=],
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4006,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "订婚成功",
        type = 101,
    },

    [4007] = {
        audio = "",
        autoextract = 0,
        content = [=[很遗憾！你解除了与#role的订婚关系。
由于订婚关系被解除，以下功能或者道具将会无法使用，并被收回。
• 订婚专属称号失效并消失。
• 戒指被系统回收。
• 同甘共苦技能无法使用。
• 双方恢复单身，即未订婚。
• 队伍中，专属心心相映标示消失。]=],
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4007,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "解除订婚",
        type = 101,
    },

    [4008] = {
        audio = "",
        autoextract = 0,
        content = [=[很遗憾！#role解除了与你的订婚关系。
由于订婚关系被解除，以下功能或者道具将会无法使用，并被收回。
• 订婚专属称号失效并消失。
• 戒指被系统回收。
• 同甘共苦技能无法使用。
• 双方恢复单身，即未订婚。
• 队伍中，专属心心相映标示消失。]=],
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4008,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "解除订婚",
        type = 101,
    },

    [4009] = {
        audio = "",
        autoextract = 0,
        content = "恭喜你和#role在#date喜结良缘，成为本服第#count对夫妻，红娘特别送上贺礼喜糖，可以自己使用或赠送宾朋。红娘相信你们一定会永结同心、白头偕老！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4009,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "喜糖礼盒",
        type = 101,
    },

    [4010] = {
        audio = "",
        autoextract = 0,
        content = [=[恭喜你和#role喜结良缘，结婚以后你们不可以互删好友、互加黑名单喔！
以后会开放更多的玩法，敬请关注。 O(∩_∩)O。]=],
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4010,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "红线童子恭贺新婚",
        type = 101,
    },

    [4011] = {
        audio = "",
        autoextract = 0,
        content = "你的好友#role和#role在#date喜结良缘，成为本服第#count对夫妻！快去为他们送上祝福吧，同时也别忘了讨要喜糖喔！O(∩_∩)O~",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4011,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "你的好友结婚啦！",
        type = 101,
    },

    [4012] = {
        audio = "",
        autoextract = 0,
        content = "你和#role是本服第#count对夫妻，今天是你们喜结良缘第#count年纪念日，红娘特别送上纪念日礼物。愿你们永结同心、白头偕老！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4012,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "结婚纪念日礼物",
        type = 101,
    },

    [4013] = {
        audio = "",
        autoextract = 0,
        content = "您的伴侣取消了离婚申请，看来这段婚姻尚有转机，希望你们好好经营这段感情。",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4013,
        keepday = 30,
        name = "红娘",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "离婚申请取消",
        type = 101,
    },

    [4014] = {
        audio = "",
        autoextract = 0,
        content = "您和伴侣提交协议离婚申请已经10天了，我很欣慰的是你们并没有来确认离婚，看来这段婚姻尚有转机。我已取消了你们的离婚申请，希望你们好好经营这段感情。",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4014,
        keepday = 30,
        name = "红娘",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "协议离婚申请超时取消",
        type = 101,
    },

    [4015] = {
        audio = "",
        autoextract = 0,
        content = "你的伴侣#role已经申请了强制离婚。你还有#count次拒绝机会，如要拒绝对方的离婚申请，请在#date之前找红娘，超时将无法拒绝。",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4015,
        keepday = 30,
        name = "红娘",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "强制离婚通知",
        type = 101,
    },

    [4016] = {
        audio = "",
        autoextract = 0,
        content = "你的伴侣#role已经申请了强制离婚。你已经没有拒绝机会，若对方在3~10天后确认离婚，我将强制解除你们的婚姻关系。",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4016,
        keepday = 30,
        name = "红娘",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "强制离婚通知",
        type = 101,
    },

    [4017] = {
        audio = "",
        autoextract = 0,
        content = "你的伴侣#role已经拒绝了强制离婚。爱情需要经营，努力挽回这段感情吧！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4017,
        keepday = 30,
        name = "红娘",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "强制离婚失败",
        type = 101,
    },

    [4018] = {
        audio = "",
        autoextract = 0,
        content = "你的伴侣#role已经同意了强制离婚。爱情诚可贵，自由价更高，您的婚姻关系已经解除！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4018,
        keepday = 30,
        name = "红娘",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "强制离婚成功",
        type = 101,
    },

    [4019] = {
        audio = "",
        autoextract = 0,
        content = "距离您提交强制离婚申请已经过去了10天，我很欣慰的是你并没有来确认离婚，看来这段婚姻尚有转机。我已取消了你的离婚申请，希望你们好好经营这段感情。",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4019,
        keepday = 30,
        name = "红娘",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "强制离婚申请超时取消",
        type = 101,
    },

    [4020] = {
        audio = "",
        autoextract = 0,
        content = "距离您的伴侣#role提交强制离婚申请已经过去了10天，我很欣慰的是他并没有来确认离婚，看来这段婚姻尚有转机。我已取消了本次离婚申请，希望你们好好经营这段感情。",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4020,
        keepday = 30,
        name = "红娘",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "强制离婚申请超时取消",
        type = 101,
    },

    [4021] = {
        audio = "",
        autoextract = 0,
        content = "喜糖送上以前粘粘喜气",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 4021,
        keepday = 30,
        name = "红娘",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "喜糖赠送",
        type = 101,
    },

    [5001] = {
        audio = "",
        autoextract = 0,
        content = "你现在可以携带新的宠物#B兔精#n、#B笋儿#n和稀有宠物#B神犬骑兵#n（可使用笋儿和秋田犬或哈士奇合成），快去宠物图鉴瞧瞧吧！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 5001,
        keepday = 30,
        name = "御灵仙子",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "有新宠物可携带",
        type = 101,
    },

    [5002] = {
        audio = "",
        autoextract = 0,
        content = "你现在可以携带新的宠物#B机关兽#n、#B剑侠#n、#B仙鹤童子#n，快去宠物图鉴瞧瞧吧！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 5002,
        keepday = 30,
        name = "御灵仙子",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "有新宠物可携带",
        type = 101,
    },

    [5003] = {
        audio = "",
        autoextract = 0,
        content = "你现在可以携带新的宠物#B插翅虎#n、#B剑灵#n、#B如意#n和稀有宠物#B虎傀儡#n（可使用机关兽和插翅虎合宠生成），快去宠物图鉴瞧瞧吧！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 5003,
        keepday = 30,
        name = "御灵仙子",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "有新宠物可携带",
        type = 101,
    },

    [5004] = {
        audio = "",
        autoextract = 0,
        content = "你现在可以携带新的宠物#B熊猫武师#n、#B天璇仙子#n和稀有宠物#B熊猫剑侠#n（可使用剑灵和熊猫武师合宠生成）、#B瑶光圣女#n（可使用如意和天璇仙子合宠生成），快去宠物图鉴瞧瞧吧！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 5004,
        keepday = 30,
        name = "御灵仙子",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "有新宠物可携带",
        type = 101,
    },

    [5005] = {
        audio = "",
        autoextract = 0,
        content = "你现在可以携带新的宠物#B大鹏鸟#n、#B桃花妖#n、#B天师道人#n和稀有宠物#B迦楼罗#n（可使用大鹏鸟和天师道人合宠生成），快去宠物图鉴瞧瞧吧！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 5005,
        keepday = 30,
        name = "御灵仙子",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "有新宠物可携带",
        type = 101,
    },

    [5006] = {
        audio = "",
        autoextract = 0,
        content = "你现在可以携带新的宠物#B阴阳师#n和稀有宠物#B花神君#n（可使用桃花妖和阴阳师合宠生成），快去宠物图鉴瞧瞧吧！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 5006,
        keepday = 30,
        name = "御灵仙子",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "有新宠物可携带",
        type = 101,
    },

    [5101] = {
        audio = "",
        autoextract = 0,
        content = "已为您选择了适合当前设备性能的游戏画面配置，您也可以点击#B主界面的设置按钮#n并选中#B画面设置#n来修改#B游戏画面配置#n，祝您游戏愉快！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 5101,
        keepday = 30,
        name = "三界精灵",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "游戏画面配置",
        type = 101,
    },

    [9001] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n  由于活动系统异常导致您未领取到活跃度达到100的奖励，现在将奖励补发给您，给您造成的不便深表歉意。\n  感谢您一直以来对<<#gamename>>的支持与厚爱！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9001,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "活跃度奖励补发",
        type = 101,
    },

    [9002] = {
        audio = "",
        autoextract = 0,
        content = "\n尊敬的帮主，您好！\n  由于服务器数据互通后您的帮派名称与其他帮派名称重复，现补偿您一个#G帮派改名许可证#n修改帮派名称，祝您游戏愉快！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9002,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "帮派重名补偿",
        type = 101,
    },

    [9003] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家，您好！\n  由于数据互通后您的角色名称与其他玩家名称重复，现在赠送您一个#G改名许可证#n，祝您游戏愉快！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9003,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "角色重名补偿",
        type = 101,
    },

    [9004] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家，您好！\n  您所在的服务器已开启数据互通，将迎来更多的小伙伴。特此奉上小小礼物，祝您游戏愉快！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9004,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "服务器数据互通补偿",
        type = 101,
    },

    [9005] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家，您好！\n  您所在的服务器开启数据互通，所有的拍卖已取消，对您造成的不便深表歉意，您的竞拍资金已返还给您！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9005,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "拍卖取消",
        type = 101,
    },

    [9006] = {
        audio = "",
        autoextract = 0,
        content = "由于您违反用户协议，扣除#total，当前扣除#real，剩余欠款#owe。系统将自动扣除您后续获得金币来抵消欠款，直到全部抵消完。建议您以后遵守用户协议健康游戏，以免受到不必要的损失，祝您游戏愉快！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9006,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "罚款通知",
        type = 101,
    },

    [9007] = {
        audio = "",
        autoextract = 0,
        content = "招式系统升级调整，您当前未使用的招式升级经验已给您兑换成招式秘籍，请在邮件附件查收。祝您游戏愉快~",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9007,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "招式升级调整",
        type = 101,
    },

    [9008] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n  这次更新后，伙伴装备强化消耗的银币做了调整，我们为您返还之前已消耗的超出部分。祝您游戏愉快~",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9008,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "伙伴装备强化银币返还",
        type = 101,
    },

    [9009] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n  这次更新后，珍兽清音仙子兑换进行了调整，我们为您返还之前已消耗的超出部分。祝您游戏愉快~",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9009,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "清音仙子之灵返还",
        type = 101,
    },

    [9010] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n 这次更新后，坐骑升级消耗的瑶池仙露做了调整，我们为您返还之前已消耗的超出部分。祝您游戏愉快~",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9010,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "坐骑升级调整返还",
        type = 101,
    },

    [9011] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家：\n 这次更新后，羽翼进阶消耗的七彩神羽做了调整，我们为您返还之前已消耗的超出部分。祝您游戏愉快~",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9011,
        keepday = 7,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 0,
        subject = "羽翼进阶调整返还",
        type = 101,
    },

    [9012] = {
        audio = "",
        autoextract = 0,
        content = "\n亲爱的玩家，您好！\n  由于数据互通后您所在结拜团队的称号与其他结拜团队的称号重复，现在赠送您一个#G结拜改名许可证#n，祝您游戏愉快！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9012,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "结拜重名补偿",
        type = 101,
    },

    [9013] = {
        audio = "",
        autoextract = 0,
        content = "由于您购买的物品数量繁多，背包已经塞不下了，因此特地由快递送达，请注意查收！",
        desc = "系统邮件",
        icon = "h7_xinfeng_1",
        id = 9013,
        keepday = 30,
        name = "系统",
        openicon = "h7_xinfeng_6",
        readtodel = 1,
        subject = "物品送达",
        type = 101,
    },

}
