-- ./excel/skill/skill_school.xlsx
return {

    [1100] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}, {["range"] = "1.01", ["level"] = 2}, {["range"] = "1.02", ["level"] = 3}, {["range"] = "1.03", ["level"] = 4}, {["range"] = "1.04", ["level"] = 5}, {["range"] = "1.05", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害，3级攻击3个目标"}, {["level"] = 3, ["desc"] = "升级：增加招式伤害"}},
        element_type = "风",
        funcdesc = [=[一剑光寒十九州，领悟了剑道精髓
招式效果:物理攻击多个目标]=],
        icon = 51101,
        id = 1100,
        init_level = 1,
        learn_limit = {{["grade"] = 0, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "剑寒九州",
        open_level = 0,
        pflist = {{["pfid"] = 1101, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[剑寒九州
物理攻击多个目标]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 1,
        top_limit = "6",
        type = "",
    },

    [1101] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}, {["range"] = "1.02", ["level"] = 2}, {["range"] = "1.04", ["level"] = 3}, {["range"] = "1.06", ["level"] = 4}, {["range"] = "1.08", ["level"] = 5}, {["range"] = "1.1", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = "招式效果:提高出手速度攻击目标，并临时提高自身法术躲避，持续4个回合",
        icon = 51102,
        id = 1101,
        init_level = 0,
        learn_limit = {{["grade"] = 15, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "瞬斩",
        open_level = 15,
        pflist = {{["pfid"] = 1102, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[瞬斩
提高出手速度攻击目标]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 2,
        top_limit = "6",
        type = "",
    },

    [1102] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0.9", ["level"] = 1}, {["range"] = "0.92", ["level"] = 2}, {["range"] = "0.94", ["level"] = 3}, {["range"] = "0.96", ["level"] = 4}, {["range"] = "0.98", ["level"] = 5}, {["range"] = "1.1", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = "招式效果:附加5回合剑气爆发状态，增加物理暴击，并且物理攻击敌方单人时，对两个气血最低的敌方单位造成额外伤害",
        icon = 51103,
        id = 1102,
        init_level = 0,
        learn_limit = {{["grade"] = 20, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "剑气爆发",
        open_level = 20,
        pflist = {{["pfid"] = 1103, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[剑气爆发
增加物理暴击]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "10"}, {["lv"] = 4, ["formula"] = "24"}, {["lv"] = 5, ["formula"] = "49"}, {["lv"] = 6, ["formula"] = "86"}},
        sortOrder = 3,
        top_limit = "6",
        type = "",
    },

    [1103] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0.75", ["level"] = 1}, {["range"] = "0.77", ["level"] = 2}, {["range"] = "0.79", ["level"] = 4}, {["range"] = "0.81", ["level"] = 4}, {["range"] = "0.83", ["level"] = 5}, {["range"] = "0.85", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "土",
        funcdesc = "招式效果:对目标发动3次强力攻击，使用后进入休息状态并且自身防御降低,气血低于50%时无法使用",
        icon = 51104,
        id = 1103,
        init_level = 0,
        learn_limit = {{["grade"] = 25, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "狂剑诀",
        open_level = 25,
        pflist = {{["pfid"] = 1104, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[狂剑诀
对目标发动3次强力物理攻击]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 4,
        top_limit = "6",
        type = "",
    },

    [1104] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0.85", ["level"] = 1}, {["range"] = "0.87", ["level"] = 2}, {["range"] = "0.89", ["level"] = 3}, {["range"] = "0.91", ["level"] = 4}, {["range"] = "0.93", ["level"] = 5}, {["range"] = "0.95", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "土",
        funcdesc = [=[以剑为引，汇聚灵气
招式效果:攻击目标,同时获得1点灵气]=],
        icon = 51105,
        id = 1104,
        init_level = 0,
        learn_limit = {{["grade"] = 45, ["level"] = 1}, {["grade"] = 50, ["level"] = 2}, {["grade"] = 60, ["level"] = 3}, {["grade"] = 70, ["level"] = 4}, {["grade"] = 75, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "聚灵剑",
        open_level = 45,
        pflist = {{["pfid"] = 1105, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[聚灵剑
物理攻击目标,同时获得1点灵气]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 6,
        top_limit = "6",
        type = "",
    },

    [1105] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0.8", ["level"] = 1}, {["range"] = "0.82", ["level"] = 2}, {["range"] = "0.84", ["level"] = 3}, {["range"] = "0.86", ["level"] = 4}, {["range"] = "0.88", ["level"] = 5}, {["range"] = "0.9", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "水",
        funcdesc = [=[招式效果:攻击目标，然后进入隐身状态，持续1个回合
技能冷却回合：1]=],
        icon = 51106,
        id = 1105,
        init_level = 0,
        learn_limit = {{["grade"] = 35, ["level"] = 1}, {["grade"] = 40, ["level"] = 2}, {["grade"] = 50, ["level"] = 3}, {["grade"] = 60, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "隐遁",
        open_level = 35,
        pflist = {{["pfid"] = 1106, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[隐遁
物理攻击目标，然后进入隐身状态，持续1个回合]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 5,
        top_limit = "6",
        type = "",
    },

    [1106] = {
        client_aura_resume = {{["range"] = "3", ["level"] = 0}},
        client_damageRatio = {{["range"] = "0.3", ["level"] = 1}, {["range"] = "0.32", ["level"] = 2}, {["range"] = "0.34", ["level"] = 3}, {["range"] = "0.36", ["level"] = 4}, {["range"] = "0.38", ["level"] = 5}, {["range"] = "0.4", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：提升连击概率，增加每次攻击伤害"}},
        element_type = "火",
        funcdesc = "招式效果:消耗所有灵气，对目标造成多段攻击，气血越低，连续攻击概率越高",
        icon = 51107,
        id = 1106,
        init_level = 0,
        learn_limit = {{["grade"] = 50, ["level"] = 1}, {["grade"] = 70, ["level"] = 2}, {["grade"] = 90, ["level"] = 3}},
        name = "绝技·万剑归一",
        open_level = 50,
        pflist = {{["pfid"] = 1107, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[绝技·万剑归一
对目标造成多段物理攻击，气血越低，连续攻击概率越高]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "10"}, {["lv"] = 2, ["formula"] = "30"}, {["lv"] = 3, ["formula"] = "190"}},
        sortOrder = 7,
        top_limit = "3",
        type = "",
    },

    [1200] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害，3级攻击3个目标"}, {["level"] = 3, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = [=[我欲胜天平六界，谁定生死了无心
招式效果:法术攻击多个目标]=],
        icon = 51201,
        id = 1200,
        init_level = 1,
        learn_limit = {{["grade"] = 0, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "金刚伏魔",
        open_level = 0,
        pflist = {{["pfid"] = 1201, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[金刚伏魔
法术攻击多个目标]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 1,
        top_limit = "6",
        type = "",
    },

    [1201] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 4}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：4级治疗3个友方单位，增加回复气血效果"}, {["level"] = 4, ["desc"] = "升级：增加恢复气血效果"}},
        element_type = "火",
        funcdesc = "招式效果:恢复多目标气血，附加持续气血恢复状态，持续多个回合",
        icon = 51202,
        id = 1201,
        init_level = 0,
        learn_limit = {{["grade"] = 35, ["level"] = 1}, {["grade"] = 40, ["level"] = 2}, {["grade"] = 50, ["level"] = 3}, {["grade"] = 60, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "九品莲台",
        open_level = 35,
        pflist = {{["pfid"] = 1202, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[九品莲台
恢复多目标气血]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 5,
        top_limit = "6",
        type = "",
    },

    [1202] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加回复气血效果"}},
        element_type = "火",
        funcdesc = "招式效果:为单体目标回复较多气血，对带有九品莲台状态的单位施放时，会恢复额外气血",
        icon = 51203,
        id = 1202,
        init_level = 0,
        learn_limit = {{["grade"] = 15, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "我佛慈悲",
        open_level = 15,
        pflist = {{["pfid"] = 1203, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[我佛慈悲
为单体目标回复较多气血]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "10"}, {["lv"] = 4, ["formula"] = "24"}, {["lv"] = 5, ["formula"] = "49"}, {["lv"] = 6, ["formula"] = "86"}},
        sortOrder = 2,
        top_limit = "6",
        type = "",
    },

    [1203] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式出手速度"}},
        element_type = "火",
        funcdesc = "招式效果:解除友方单位的封印状态，并随机移除一个增益状态",
        icon = 51204,
        id = 1203,
        init_level = 0,
        learn_limit = {{["grade"] = 20, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "禅心定神",
        open_level = 20,
        pflist = {{["pfid"] = 1204, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[禅心定神
解除友方单位的封印状态，并随机移除一个增益状态]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 3,
        top_limit = "6",
        type = "",
    },

    [1204] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*4", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加气血回复效果"}},
        element_type = "火",
        funcdesc = "招式效果:从轮回六道中将魂魄拉回来。复活死亡队友，并回复一定气血",
        icon = 51205,
        id = 1204,
        init_level = 0,
        learn_limit = {{["grade"] = 25, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "轮回",
        open_level = 25,
        pflist = {{["pfid"] = 1205, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[轮回
复活死亡队友，并回复一定气血]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 4,
        top_limit = "6",
        type = "",
    },

    [1205] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*3", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式免伤效果"}},
        element_type = "火",
        funcdesc = [=[招式效果:为友方单位附加不动明王状态，受到伤害大幅度减少，持续1个回合
技能冷却回合：1]=],
        icon = 51206,
        id = 1205,
        init_level = 0,
        learn_limit = {{["grade"] = 45, ["level"] = 1}, {["grade"] = 50, ["level"] = 2}, {["grade"] = 60, ["level"] = 3}, {["grade"] = 70, ["level"] = 4}, {["grade"] = 75, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "不动明王",
        open_level = 45,
        pflist = {{["pfid"] = 1206, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[不动明王
为友方单位附加不动明王状态，受到伤害大幅度减少，持续1个回合]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 6,
        top_limit = "6",
        type = "",
    },

    [1206] = {
        client_aura_resume = {{["range"] = "3", ["level"] = 0}},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式出手速度，降低防御效果变弱"}},
        element_type = "火",
        funcdesc = "招式效果:消耗所有灵气，让友方目标瞬间回复至满血状态，使用后自身防御大大降低（无法对自己使用）",
        icon = 51207,
        id = 1206,
        init_level = 0,
        learn_limit = {{["grade"] = 50, ["level"] = 1}, {["grade"] = 70, ["level"] = 2}, {["grade"] = 90, ["level"] = 3}},
        name = "绝技·佛法无边",
        open_level = 50,
        pflist = {{["pfid"] = 1207, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[绝技·佛法无边
让友方目标瞬间回满血，使用后自身防御大大降低]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "10"}, {["lv"] = 2, ["formula"] = "30"}, {["lv"] = 3, ["formula"] = "190"}},
        sortOrder = 7,
        top_limit = "3",
        type = "",
    },

    [1300] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}, {["range"] = "1.01", ["level"] = 2}, {["range"] = "1.02", ["level"] = 3}, {["range"] = "1.03", ["level"] = 4}, {["range"] = "1.04", ["level"] = 5}, {["range"] = "1.05", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "3", ["level"] = 1}, {["range"] = "4", ["level"] = 4}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害，3级攻击4个目标"}, {["level"] = 3, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = [=[太初之力流转周身，化为神火
招式效果:法术攻击多个目标]=],
        icon = 51301,
        id = 1300,
        init_level = 1,
        learn_limit = {{["grade"] = 0, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "太初神火",
        open_level = 0,
        pflist = {{["pfid"] = 1301, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[太初神火
法术攻击多个目标]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 1,
        top_limit = "6",
        type = "",
    },

    [1301] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}, {["range"] = "1.02", ["level"] = 2}, {["range"] = "1.04", ["level"] = 3}, {["range"] = "1.06", ["level"] = 4}, {["range"] = "1.08", ["level"] = 5}, {["range"] = "1.1", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "15", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害和法力消耗效果"}},
        element_type = "土",
        funcdesc = [=[霜华一怒天地寒，冰封万里无生机
招式效果:法术攻击敌方全体目标，消耗目标的法力值]=],
        icon = 51302,
        id = 1301,
        init_level = 0,
        learn_limit = {{["grade"] = 15, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "法力冰封",
        open_level = 15,
        pflist = {{["pfid"] = 1302, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[法力冰封
法术攻击敌方全体目标]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 2,
        top_limit = "6",
        type = "",
    },

    [1302] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1.2", ["level"] = 1}, {["range"] = "1.22", ["level"] = 2}, {["range"] = "1.24", ["level"] = 3}, {["range"] = "1.26", ["level"] = 4}, {["range"] = "1.28", ["level"] = 5}, {["range"] = "1.3", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = [=[心火撩体哀嚎苦，神炎真火难消受
招式效果:用火焰法术攻击单体目标]=],
        icon = 51303,
        id = 1302,
        init_level = 0,
        learn_limit = {{["grade"] = 20, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "神炎焚身",
        open_level = 20,
        pflist = {{["pfid"] = 1303, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[神炎焚身
用火焰法术攻击单体目标]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 3,
        top_limit = "6",
        type = "",
    },

    [1303] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式出手速度"}},
        element_type = "土",
        funcdesc = [=[清风玉露一相逢，更胜却人间无数
招式效果:解除友方单位身上的封印状态]=],
        icon = 51304,
        id = 1303,
        init_level = 0,
        learn_limit = {{["grade"] = 25, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "清心",
        open_level = 25,
        pflist = {{["pfid"] = 1304, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[清心
解除友方单位身上的封印状态]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 4,
        top_limit = "6",
        type = "",
    },

    [1304] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式出手速度"}},
        element_type = "水",
        funcdesc = "招式效果:让敌方一个目标被星灵之力禁锢，目标的物理攻击法术或普通攻击有概率自动选择，目标持续3个回合",
        icon = 51305,
        id = 1304,
        init_level = 0,
        learn_limit = {{["grade"] = 45, ["level"] = 1}, {["grade"] = 50, ["level"] = 2}, {["grade"] = 60, ["level"] = 3}, {["grade"] = 70, ["level"] = 4}, {["grade"] = 75, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "星灵禁",
        open_level = 45,
        pflist = {{["pfid"] = 1305, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[星灵禁
让敌方一个目标的物理攻击法术或普通攻击有概率自动选择，目标持续2个回合]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 6,
        top_limit = "6",
        type = "",
    },

    [1305] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0.55", ["level"] = 1}, {["range"] = "0.57", ["level"] = 2}, {["range"] = "0.59", ["level"] = 3}, {["range"] = "0.61", ["level"] = 4}, {["range"] = "0.63", ["level"] = 5}, {["range"] = "0.65", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "2", ["level"] = 1}, {["range"] = "2", ["level"] = 2}, {["range"] = "3", ["level"] = 3}, {["range"] = "3", ["level"] = 4}, {["range"] = "3", ["level"] = 5}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "风",
        funcdesc = [=[九天罡风练道心，三重天下拜何人
招式效果:风刃攻击敌方2个目标]=],
        icon = 51306,
        id = 1305,
        init_level = 0,
        learn_limit = {{["grade"] = 35, ["level"] = 1}, {["grade"] = 40, ["level"] = 2}, {["grade"] = 50, ["level"] = 3}, {["grade"] = 60, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "九天罡风",
        open_level = 35,
        pflist = {{["pfid"] = 1306, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[九天罡风
风刃攻击敌方2个目标造成法术伤害]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "10"}, {["lv"] = 4, ["formula"] = "24"}, {["lv"] = 5, ["formula"] = "49"}, {["lv"] = 6, ["formula"] = "86"}},
        sortOrder = 5,
        top_limit = "6",
        type = "",
    },

    [1306] = {
        client_aura_resume = {{["range"] = "3", ["level"] = 0}},
        client_damageRatio = {{["range"] = "1.75", ["level"] = 1}, {["range"] = "1.8", ["level"] = 2}, {["range"] = "1.85", ["level"] = 3}, {["range"] = "1.9", ["level"] = 4}, {["range"] = "1.95", ["level"] = 5}, {["range"] = "2", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = "招式效果:消耗所有灵气，汇聚星辰之力攻击目标，随机获得一定伤害加成，且目标法力值越低，伤害越高。使用后休息一回合",
        icon = 51307,
        id = 1306,
        init_level = 0,
        learn_limit = {{["grade"] = 50, ["level"] = 1}, {["grade"] = 70, ["level"] = 2}, {["grade"] = 90, ["level"] = 3}},
        name = "绝技·星宿审判",
        open_level = 50,
        pflist = {{["pfid"] = 1307, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[绝技·星宿审判
使用法术攻击目标，随机获得一定伤害加成，且目标法力值越低伤害越高]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "10"}, {["lv"] = 2, ["formula"] = "30"}, {["lv"] = 3, ["formula"] = "190"}},
        sortOrder = 7,
        top_limit = "3",
        type = "",
    },

    [1400] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害，3级攻击3个目标"}, {["level"] = 3, ["desc"] = "升级：增加招式伤害"}},
        element_type = "风",
        funcdesc = [=[九天雷动震云霄，风云聚变谁独逃
招式效果:法术攻击多个目标]=],
        icon = 51401,
        id = 1400,
        init_level = 1,
        learn_limit = {{["grade"] = 0, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "风云雷动",
        open_level = 0,
        pflist = {{["pfid"] = 1401, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[风云雷动
法术攻击多个目标]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 1,
        top_limit = "6",
        type = "",
    },

    [1401] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*3", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加杏黄旗继承属性比例和治疗效果"}},
        element_type = "火",
        funcdesc = [=[招式效果:召唤杏黄旗，治疗友方单位，并增加物理防御，效果持续数回合
技能冷却回合：2]=],
        icon = 51402,
        id = 1401,
        init_level = 0,
        learn_limit = {{["grade"] = 25, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "杏黄旗",
        open_level = 25,
        pflist = {{["pfid"] = 1402, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[杏黄旗
召唤杏黄旗，治疗友方单位，并提高友方物理防御]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 4,
        top_limit = "6",
        type = "",
    },

    [1402] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0.95", ["level"] = 1}, {["range"] = "0.98", ["level"] = 2}, {["range"] = "1.01", ["level"] = 3}, {["range"] = "1.04", ["level"] = 4}, {["range"] = "1.07", ["level"] = 5}, {["range"] = "1.1", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害和中毒命中概率"}},
        element_type = "火",
        funcdesc = "招式效果:用法术腐蚀敌人，有概率让其进入中毒状态，每回合损失一定气血,且有概率偷取目标1点灵气",
        icon = 51403,
        id = 1402,
        init_level = 0,
        learn_limit = {{["grade"] = 15, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "木灵蚀心",
        open_level = 15,
        pflist = {{["pfid"] = 1403, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[木灵蚀心
用法术腐蚀敌人，有概率让其进入中毒状态]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 2,
        top_limit = "6",
        type = "",
    },

    [1403] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式出手速度"}},
        element_type = "火",
        funcdesc = [=[招式效果:使自己在接下来1个回合内受到致死攻击时，回复1点气血
技能冷却回合：9]=],
        icon = 51407,
        id = 1403,
        init_level = 0,
        learn_limit = {{["grade"] = 20, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "天神法相",
        open_level = 20,
        pflist = {{["pfid"] = 1404, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[天神法相
使自己在接下来1个回合内受到致死攻击时，回复1点气血]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 3,
        top_limit = "6",
        type = "",
    },

    [1404] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {{["range"] = "grade*2", ["level"] = 1}},
        client_mpResume = {},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加天兵继承属性比例，4级攻击3个目标"}, {["level"] = 4, ["desc"] = "升级：增加天兵继承属性比例"}},
        element_type = "土",
        funcdesc = [=[招式效果:召唤天兵，每回合会使用法术攻击敌人，并且让目标的物理防御降低
技能冷却回合：3]=],
        icon = 51405,
        id = 1404,
        init_level = 0,
        learn_limit = {{["grade"] = 45, ["level"] = 1}, {["grade"] = 50, ["level"] = 2}, {["grade"] = 60, ["level"] = 3}, {["grade"] = 70, ["level"] = 4}, {["grade"] = 75, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "神兵天降",
        open_level = 45,
        pflist = {{["pfid"] = 1405, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[神兵天降
召唤天兵，每回合会使用法术攻击敌人，并且让目标的物理防御降低]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "10"}, {["lv"] = 4, ["formula"] = "24"}, {["lv"] = 5, ["formula"] = "49"}, {["lv"] = 6, ["formula"] = "86"}},
        sortOrder = 6,
        top_limit = "6",
        type = "",
    },

    [1405] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*1", ["level"] = 1}},
        client_range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 4}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加回复法力效果，4级可作用3个友方单位"}, {["level"] = 4, ["desc"] = "升级：增加回复法力效果"}},
        element_type = "水",
        funcdesc = "招式效果:为多个友方单位增加仙气灌顶状态，每回合恢复一定法力",
        icon = 51406,
        id = 1405,
        init_level = 0,
        learn_limit = {{["grade"] = 35, ["level"] = 1}, {["grade"] = 40, ["level"] = 2}, {["grade"] = 50, ["level"] = 3}, {["grade"] = 60, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "仙气灌顶",
        open_level = 35,
        pflist = {{["pfid"] = 1406, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[仙气灌顶
为多个友方单位增加仙气灌顶状态，每回合恢复一定法力]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 5,
        top_limit = "6",
        type = "",
    },

    [1406] = {
        client_aura_resume = {{["range"] = "3", ["level"] = 0}},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：提升友方单位伤害和治疗效果"}},
        element_type = "土",
        funcdesc = "招式效果:消耗所有灵气，鼓舞队友，使队友本回合伤害治疗效果提升",
        icon = 51404,
        id = 1406,
        init_level = 0,
        learn_limit = {{["grade"] = 50, ["level"] = 1}, {["grade"] = 70, ["level"] = 2}, {["grade"] = 90, ["level"] = 3}},
        name = "绝技·神威",
        open_level = 50,
        pflist = {{["pfid"] = 1407, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[绝技·神威
鼓舞队友，使队友本回合的伤害和治疗效果提升]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "10"}, {["lv"] = 2, ["formula"] = "30"}, {["lv"] = 3, ["formula"] = "190"}},
        sortOrder = 7,
        top_limit = "3",
        type = "",
    },

    [1500] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害，3级攻击3个目标"}, {["level"] = 3, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = [=[化蛇成龙缥缈间，瞬息成败定乾坤
招式效果:法术攻击多个目标]=],
        icon = 51501,
        id = 1500,
        init_level = 1,
        learn_limit = {{["grade"] = 0, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "龙蛇吐息",
        open_level = 0,
        pflist = {{["pfid"] = 1501, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[龙蛇吐息
法术攻击多个目标]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 1,
        top_limit = "6",
        type = "",
    },

    [1501] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 0}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式出手速度和命中"}},
        element_type = "火",
        funcdesc = "招式效果:封印目标，使目标无法使用法术，持续3回合，并降低目标的防御",
        icon = 51502,
        id = 1501,
        init_level = 0,
        learn_limit = {{["grade"] = 15, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "封灵咒",
        open_level = 15,
        pflist = {{["pfid"] = 1502, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[封灵咒
封印目标，使目标无法使用法术]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 2,
        top_limit = "6",
        type = "",
    },

    [1502] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 0}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式出手速度和命中"}},
        element_type = "火",
        funcdesc = "招式效果:使目标进入混乱状态，不分敌我攻击，持续2回合，此法术较难命中玩家单位",
        icon = 51503,
        id = 1502,
        init_level = 0,
        learn_limit = {{["grade"] = 25, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "迷魂",
        open_level = 25,
        pflist = {{["pfid"] = 1503, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[迷魂
使目标进入混乱状态，不分敌我攻击]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "10"}, {["lv"] = 4, ["formula"] = "24"}, {["lv"] = 5, ["formula"] = "49"}, {["lv"] = 6, ["formula"] = "86"}},
        sortOrder = 4,
        top_limit = "6",
        type = "",
    },

    [1503] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {{["range"] = "grade*2", ["level"] = 1}},
        client_mpResume = {},
        client_range = {{["range"] = "1", ["level"] = 0}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式恢复的法力值"}},
        element_type = "火",
        funcdesc = "招式效果:牺牲自身气血，恢复一定法力",
        icon = 51504,
        id = 1503,
        init_level = 0,
        learn_limit = {{["grade"] = 20, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "妖气归元",
        open_level = 20,
        pflist = {{["pfid"] = 1504, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[妖气归元
牺牲自身气血，恢复一定法力]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 3,
        top_limit = "6",
        type = "",
    },

    [1504] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 0}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式的出手速度"}},
        element_type = "火",
        funcdesc = [=[招式效果:封印目标，使其无法使用攻击和法术，持续3回合，但下回合封印命中降低
技能冷却回合：1]=],
        icon = 51505,
        id = 1504,
        init_level = 0,
        learn_limit = {{["grade"] = 45, ["level"] = 1}, {["grade"] = 50, ["level"] = 2}, {["grade"] = 60, ["level"] = 3}, {["grade"] = 70, ["level"] = 4}, {["grade"] = 75, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "封神咒",
        open_level = 45,
        pflist = {{["pfid"] = 1505, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[封神咒
封印目标，使其无法使用攻击和法术，持续4回合，但下回合封印命中降低]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 6,
        top_limit = "6",
        type = "",
    },

    [1505] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*3", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 0}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = [=[召唤恶灵，吞噬目标的灵魂
招式效果:对单个目标造成较大伤害]=],
        icon = 51506,
        id = 1505,
        init_level = 0,
        learn_limit = {{["grade"] = 35, ["level"] = 1}, {["grade"] = 40, ["level"] = 2}, {["grade"] = 50, ["level"] = 3}, {["grade"] = 60, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "噬灵",
        open_level = 35,
        pflist = {{["pfid"] = 1506, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[噬灵
对单个目标造成较大伤害]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 5,
        top_limit = "6",
        type = "",
    },

    [1506] = {
        client_aura_resume = {{["range"] = "3", ["level"] = 0}},
        client_damageRatio = {{["range"] = "0", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {},
        client_range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 4}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式出手速度和命中"}},
        element_type = "火",
        funcdesc = "招式效果:消耗所有灵气，对多个目标进行封印，使目标无法使用攻击和法术",
        icon = 51507,
        id = 1506,
        init_level = 0,
        learn_limit = {{["grade"] = 50, ["level"] = 1}, {["grade"] = 70, ["level"] = 2}, {["grade"] = 90, ["level"] = 3}},
        name = "绝技·禁断万古",
        open_level = 50,
        pflist = {{["pfid"] = 1507, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[绝技·禁断万古
对多个目标进行封印，使目标无法使用攻击和法术]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "10"}, {["lv"] = 2, ["formula"] = "30"}, {["lv"] = 3, ["formula"] = "190"}},
        sortOrder = 7,
        top_limit = "3",
        type = "",
    },

    [1600] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}, {["range"] = "1.01", ["level"] = 2}, {["range"] = "1.02", ["level"] = 3}, {["range"] = "1.03", ["level"] = 4}, {["range"] = "1.04", ["level"] = 5}, {["range"] = "1.05", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害，3级攻击3个目标"}, {["level"] = 3, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = [=[虽千万人吾往矣，力破千军
招式效果:攻击多个目标]=],
        icon = 51601,
        id = 1600,
        init_level = 1,
        learn_limit = {{["grade"] = 0, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "千军破",
        open_level = 0,
        pflist = {{["pfid"] = 1601, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[千军破
攻击多个目标造成物理伤害]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "10"}, {["lv"] = 4, ["formula"] = "24"}, {["lv"] = 5, ["formula"] = "49"}, {["lv"] = 6, ["formula"] = "86"}},
        sortOrder = 1,
        top_limit = "6",
        type = "",
    },

    [1601] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1.05", ["level"] = 1}, {["range"] = "1.07", ["level"] = 2}, {["range"] = "1.09", ["level"] = 3}, {["range"] = "1.11", ["level"] = 4}, {["range"] = "1.13", ["level"] = 5}, {["range"] = "1.15", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害和降低防御效果"}},
        element_type = "土",
        funcdesc = "招式效果:攻击目标，并且削弱目标防御2回合",
        icon = 51602,
        id = 1601,
        init_level = 0,
        learn_limit = {{["grade"] = 15, ["level"] = 1}, {["grade"] = 20, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "卸甲",
        open_level = 15,
        pflist = {{["pfid"] = 1602, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[卸甲
攻击单个目标造成物理伤害，并且削弱目标防御2回合]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 2,
        top_limit = "6",
        type = "",
    },

    [1602] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "0.9", ["level"] = 1}, {["range"] = "0.92", ["level"] = 2}, {["range"] = "0.94", ["level"] = 3}, {["range"] = "0.96", ["level"] = 4}, {["range"] = "0.98", ["level"] = 5}, {["range"] = "1", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = "招式效果:攻击敌方前排目标，后排单位也会受到100%伤害",
        icon = 51603,
        id = 1602,
        init_level = 0,
        learn_limit = {{["grade"] = 45, ["level"] = 1}, {["grade"] = 50, ["level"] = 2}, {["grade"] = 60, ["level"] = 3}, {["grade"] = 70, ["level"] = 4}, {["grade"] = 75, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "破阵冲击",
        open_level = 45,
        pflist = {{["pfid"] = 1603, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[破阵冲击
物理攻击敌方前排目标，后排单位也会受到伤害]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "2"}, {["lv"] = 3, ["formula"] = "14"}, {["lv"] = 4, ["formula"] = "36"}, {["lv"] = 5, ["formula"] = "74"}, {["lv"] = 6, ["formula"] = "128"}},
        sortOrder = 6,
        top_limit = "6",
        type = "",
    },

    [1603] = {
        client_aura_resume = {{["range"] = "1", ["level"] = 0}},
        client_damageRatio = {{["range"] = "1", ["level"] = 2}, {["range"] = "2", ["level"] = 3}, {["range"] = "3", ["level"] = 3}, {["range"] = "4", ["level"] = 4}, {["range"] = "5", ["level"] = 4}, {["range"] = "6", ["level"] = 5}},
        client_hpResume = {},
        client_mpResume = {},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：1级攻击目标2次"}, {["level"] = 1, ["desc"] = "升级：2级攻击目标3次"}, {["level"] = 2, ["desc"] = "升级：增加招式伤害"}, {["level"] = 3, ["desc"] = "升级：增加招式伤害"}, {["level"] = 4, ["desc"] = "升级：5级攻击目标4次"}, {["level"] = 5, ["desc"] = "升级：6级攻击目标5次"}},
        element_type = "土",
        funcdesc = "招式效果:消耗1点灵气对目标造成多次伤害，攻击次数受技能等级影响，使用后休息1回合(战神效果对该技能无效)",
        icon = 51604,
        id = 1603,
        init_level = 0,
        learn_limit = {{["grade"] = 20, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "妖月连斩",
        open_level = 20,
        pflist = {{["pfid"] = 1608, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[妖月连斩
对目标造成多次物理伤害，攻击次数受技能等级影响，使用后休息1回合]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 3,
        top_limit = "6",
        type = "",
    },

    [1604] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "法术",
        desc = {{["level"] = 0, ["desc"] = "升级：牺牲更少的物理伤害能力"}},
        element_type = "水",
        funcdesc = "招式效果:牺牲一定物理伤害能力，下回合物理伤害技能会释放两次。",
        icon = 51605,
        id = 1604,
        init_level = 0,
        learn_limit = {{["grade"] = 35, ["level"] = 1}, {["grade"] = 40, ["level"] = 2}, {["grade"] = 50, ["level"] = 3}, {["grade"] = 60, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "战神",
        open_level = 35,
        pflist = {{["pfid"] = 1605, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[战神
牺牲一定物理伤害能力，下回合物理伤害技能会释放两次。]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 5,
        top_limit = "6",
        type = "",
    },

    [1605] = {
        client_aura_resume = {},
        client_damageRatio = {{["range"] = "1.15", ["level"] = 1}, {["range"] = "1.17", ["level"] = 2}, {["range"] = "1.19", ["level"] = 3}, {["range"] = "1.21", ["level"] = 4}, {["range"] = "1.23", ["level"] = 5}, {["range"] = "1.25", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {{["range"] = "grade*2.5", ["level"] = 1}},
        client_range = {{["range"] = "3", ["level"] = 1}, {["range"] = "4", ["level"] = 4}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害，4级攻击4个目标"}, {["level"] = 4, ["desc"] = "升级：增加招式伤害"}},
        element_type = "风",
        funcdesc = "招式效果:引用杀破狼三凶星的气势，使用物理攻击多个敌方单位,使用后休息1回合",
        icon = 51606,
        id = 1605,
        init_level = 0,
        learn_limit = {{["grade"] = 25, ["level"] = 1}, {["grade"] = 30, ["level"] = 2}, {["grade"] = 40, ["level"] = 3}, {["grade"] = 50, ["level"] = 4}, {["grade"] = 65, ["level"] = 5}, {["grade"] = 80, ["level"] = 6}},
        name = "杀破狼",
        open_level = 25,
        pflist = {{["pfid"] = 1606, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[杀破狼
使用物理攻击多个敌方单位,使用后休息1回合]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "1"}, {["lv"] = 2, ["formula"] = "3"}, {["lv"] = 3, ["formula"] = "19"}, {["lv"] = 4, ["formula"] = "48"}, {["lv"] = 5, ["formula"] = "98"}, {["lv"] = 6, ["formula"] = "171"}},
        sortOrder = 4,
        top_limit = "6",
        type = "",
    },

    [1606] = {
        client_aura_resume = {{["range"] = "3", ["level"] = 0}},
        client_damageRatio = {{["range"] = "1", ["level"] = 1}, {["range"] = "1.02", ["level"] = 2}, {["range"] = "1.04", ["level"] = 3}, {["range"] = "1.06", ["level"] = 4}, {["range"] = "1.08", ["level"] = 5}, {["range"] = "1.1", ["level"] = 6}},
        client_hpResume = {},
        client_mpResume = {},
        client_range = {{["range"] = "1", ["level"] = 1}},
        client_skillAttackType = "物理",
        desc = {{["level"] = 0, ["desc"] = "升级：增加招式伤害"}},
        element_type = "火",
        funcdesc = "招式效果:消耗所有灵气，攻击目标，附带吸血效果。若击杀目标，则会再次释放唯我独尊，最多额外释放3次",
        icon = 51607,
        id = 1606,
        init_level = 0,
        learn_limit = {{["grade"] = 50, ["level"] = 1}, {["grade"] = 70, ["level"] = 2}, {["grade"] = 90, ["level"] = 3}},
        name = "绝技·唯我独尊",
        open_level = 50,
        pflist = {{["pfid"] = 1607, ["level"] = 1}},
        reset_resume = {},
        rolecreatedesc = [=[绝技·唯我独尊
物理攻击目标附带吸血效果。若击杀目标，则会再次释放唯我独尊]=],
        score = "100*lv",
        silver_learn = {},
        skill_effect = {},
        skillpoint_learn = {{["lv"] = 1, ["formula"] = "10"}, {["lv"] = 2, ["formula"] = "30"}, {["lv"] = 3, ["formula"] = "190"}},
        sortOrder = 7,
        top_limit = "3",
        type = "",
    },

}
