-- ./excel/skill/artifact.xlsx
return {

    [9501] = {
        desc = "自身法攻和法防属性各提升50点",
        icon = 57000,
        id = 9501,
        name = "术法强化",
        pflist = {},
        skill_effect = "{mag_attack=50,mag_defense=50}",
        skill_effect_ratio = "",
        type = 2,
    },

    [9502] = {
        desc = "物防及法防提高5%",
        icon = 57001,
        id = 9502,
        name = "勇猛",
        pflist = {},
        skill_effect = "",
        skill_effect_ratio = "{phy_defense=5,mag_defense=5}",
        type = 2,
    },

    [9503] = {
        desc = "使用恢复系法术魔法值及控制点消耗减少25%，给召唤兽恢复气血效果增加20%",
        icon = 57002,
        id = 9503,
        name = "治疗掌控",
        pflist = {9503},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9504] = {
        desc = "所有减益和封印类技能成功率提高5%，上限由70%提高到80%。",
        icon = 57003,
        id = 9504,
        name = "封印强化",
        pflist = {9504},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9505] = {
        desc = "召唤的杏黄旗和天兵的所有属性提高5%",
        icon = 57004,
        id = 9505,
        name = "傀儡师",
        pflist = {9505},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9506] = {
        desc = "与普通NPC战斗时，逃跑成功几率增加20%",
        icon = 57005,
        id = 9506,
        name = "影遁",
        pflist = {9506},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9507] = {
        desc = "有5%几率躲避封印",
        icon = 57006,
        id = 9507,
        name = "驱法",
        pflist = {},
        skill_effect = "{res_seal_ratio=5}",
        skill_effect_ratio = "",
        type = 2,
    },

    [9508] = {
        desc = "躲避率增加5%",
        icon = 57007,
        id = 9508,
        name = "闪避",
        pflist = {},
        skill_effect = "{mag_hit_res_ratio=5,phy_hit_res_ratio=5}",
        skill_effect_ratio = "",
        type = 2,
    },

    [9509] = {
        desc = "每次受击时愤怒获得额外增加2点",
        icon = 57008,
        id = 9509,
        name = "坚韧",
        pflist = {9509},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9510] = {
        desc = "每次受到异常状态时，愤怒值增加5；持续状态中不增加",
        icon = 57009,
        id = 9510,
        name = "怒火",
        pflist = {9510},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9511] = {
        desc = "增加气血上限5%",
        icon = 57010,
        id = 9511,
        name = "气血强化",
        pflist = {},
        skill_effect = "",
        skill_effect_ratio = "{max_hp=5}",
        type = 2,
    },

    [9512] = {
        desc = "增加气血上限10%",
        icon = 57011,
        id = 9512,
        name = "气血强化Ⅱ",
        pflist = {},
        skill_effect = "",
        skill_effect_ratio = "{max_hp=10}",
        type = 2,
    },

    [9513] = {
        desc = "将亡魂性质生物打倒时，有50%几率可以将其打出战斗",
        icon = 57012,
        id = 9513,
        name = "驱魔",
        pflist = {9513},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9514] = {
        desc = "亡魂性质生物死亡时，复活需要的回合数-1",
        icon = 57013,
        id = 9514,
        name = "操魂者",
        pflist = {9514},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9515] = {
        desc = "增加人物5%速度",
        icon = 57014,
        id = 9515,
        name = "先手",
        pflist = {},
        skill_effect = "",
        skill_effect_ratio = "{speed=5}",
        type = 2,
    },

    [9516] = {
        desc = "减少人物5%速度",
        icon = 57015,
        id = 9516,
        name = "伺机",
        pflist = {},
        skill_effect = "",
        skill_effect_ratio = "{speed=-5}",
        type = 2,
    },

    [9517] = {
        desc = "当前气血>上限50%时，伤害结果降低5%；气血≤上限50%时，伤害结果增加10%",
        icon = 57016,
        id = 9517,
        name = "隐忍术",
        pflist = {9517},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9518] = {
        desc = "使用封印类法术命中时有20%使其持续回合数+1",
        icon = 57017,
        id = 9518,
        name = "信仰",
        pflist = {9518},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9519] = {
        desc = "在被封印类法术命中时有20%使其持续回合数-1",
        icon = 57018,
        id = 9519,
        name = "聚神",
        pflist = {9519},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9520] = {
        desc = "在使用回复类法术时有20%造成200%的治疗效果",
        icon = 57019,
        id = 9520,
        name = "扶伤",
        pflist = {9520},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9521] = {
        desc = "每次受击时愤怒获得额外增加4点",
        icon = 57020,
        id = 9521,
        name = "忍耐",
        pflist = {9521},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9522] = {
        desc = "增加法力值上限5%",
        icon = 57021,
        id = 9522,
        name = "法力强化",
        pflist = {},
        skill_effect = "",
        skill_effect_ratio = "{max_mp=5}",
        type = 2,
    },

    [9523] = {
        desc = "增加法力值上限10%",
        icon = 57022,
        id = 9523,
        name = "法力强化Ⅱ",
        pflist = {},
        skill_effect = "",
        skill_effect_ratio = "{max_mp=10}",
        type = 2,
    },

    [9524] = {
        desc = "担任队长时，所有队友速度增加2%",
        icon = 57023,
        id = 9524,
        name = "队长光环",
        pflist = {9524},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9525] = {
        desc = "普通攻击有5%概率反击",
        icon = 57024,
        id = 9525,
        name = "反击",
        pflist = {9525},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9526] = {
        desc = "施展招式时，有5%的概率使本回合的速率提高10%。",
        icon = 57025,
        id = 9526,
        name = "冲锋",
        pflist = {9526},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9527] = {
        desc = "被毒时受到的损失降低至20%，但被毒回合加倍。",
        icon = 57026,
        id = 9527,
        name = "抗毒",
        pflist = {9527},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9528] = {
        desc = "可以攻击隐身目标，但对其伤害结果降低50%。",
        icon = 57027,
        id = 9528,
        name = "感知",
        pflist = {9528},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9529] = {
        desc = "倒地时有10%的概率自动复活并恢复一定量气血",
        icon = 57028,
        id = 9529,
        name = "神佑",
        pflist = {9529},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

    [9530] = {
        desc = "战斗中使用药物效果提高至110%",
        icon = 57029,
        id = 9530,
        name = "药物强化",
        pflist = {9530},
        skill_effect = "",
        skill_effect_ratio = "",
        type = 2,
    },

}
