-- ./excel/skill/skill_school.xlsx
return {

    [2101] = {
        desc = "蜀山被动技能，加物理攻击",
        element_type = "火",
        icon = 52001,
        id = 2101,
        limit_level = 150,
        name = "剑体",
        open_level = 5,
        score = "lv*10",
        skill_effect = {"phy_attack=level*1"},
        type = "物理攻击",
    },

    [2102] = {
        desc = "蜀山被动技能，加气血上限",
        element_type = "火",
        icon = 52002,
        id = 2102,
        limit_level = 150,
        name = "剑心",
        open_level = 10,
        score = "lv*10",
        skill_effect = {"max_hp=level*2"},
        type = "气血上限",
    },

    [2103] = {
        desc = "蜀山被动技能，加物理攻击",
        element_type = "火",
        icon = 52003,
        id = 2103,
        limit_level = 150,
        name = "剑魄",
        open_level = 15,
        score = "lv*10",
        skill_effect = {"phy_attack=level*1.5"},
        type = "物理攻击",
    },

    [2104] = {
        desc = "蜀山被动技能，加物理命中和闪避",
        element_type = "火",
        icon = 52004,
        id = 2104,
        limit_level = 150,
        name = "剑眼",
        open_level = 20,
        score = "lv*10",
        skill_effect = {"phy_hit_ratio=math.floor(level*0.5)", "phy_hit_res_ratio=math.floor((level+1)*0.5)"},
        type = "物理命中物理闪避",
    },

    [2105] = {
        desc = "蜀山被动技能，加法力上限",
        element_type = "火",
        icon = 52005,
        id = 2105,
        limit_level = 150,
        name = "剑魂",
        open_level = 30,
        score = "lv*10",
        skill_effect = {"max_mp=level*2"},
        type = "法力上限",
    },

    [2106] = {
        desc = "蜀山被动技能，加速度",
        element_type = "火",
        icon = 52006,
        id = 2106,
        limit_level = 150,
        name = "剑翼",
        open_level = 40,
        score = "lv*10",
        skill_effect = {"speed=level"},
        type = "速度",
    },

    [2201] = {
        desc = "金山寺被动技能，加气血上限",
        element_type = "火",
        icon = 52007,
        id = 2201,
        limit_level = 150,
        name = "佛体",
        open_level = 5,
        score = "lv*10",
        skill_effect = {"max_hp=level*7"},
        type = "气血上限",
    },

    [2202] = {
        desc = "金山寺被动技能，加法术攻击",
        element_type = "火",
        icon = 52008,
        id = 2202,
        limit_level = 150,
        name = "佛心",
        open_level = 10,
        score = "lv*10",
        skill_effect = {"mag_attack=level*1"},
        type = "法术攻击",
    },

    [2203] = {
        desc = "金山寺被动技能，加气血上限",
        element_type = "火",
        icon = 52009,
        id = 2203,
        limit_level = 150,
        name = "真言",
        open_level = 15,
        score = "lv*10",
        skill_effect = {"max_hp=level*9"},
        type = "气血上限",
    },

    [2204] = {
        desc = "金山寺被动技能，加命中和闪避",
        element_type = "火",
        icon = 52010,
        id = 2204,
        limit_level = 150,
        name = "天眼通",
        open_level = 20,
        score = "lv*10",
        skill_effect = {"phy_hit_ratio=math.floor(level*0.5)", "phy_hit_res_ratio=math.floor((level+1)*0.5)"},
        type = "物理命中物理闪避",
    },

    [2205] = {
        desc = "金山寺被动技能，加法力上限",
        element_type = "火",
        icon = 52011,
        id = 2205,
        limit_level = 150,
        name = "灵光",
        open_level = 30,
        score = "lv*10",
        skill_effect = {"max_mp=level*2"},
        type = "法力上限",
    },

    [2206] = {
        desc = "金山寺被动技能，加速度",
        element_type = "火",
        icon = 52012,
        id = 2206,
        limit_level = 150,
        name = "祥云",
        open_level = 40,
        score = "lv*10",
        skill_effect = {"speed=level"},
        type = "速度",
    },

    [2301] = {
        desc = "太初被动技能，加气血上限",
        element_type = "火",
        icon = 52013,
        id = 2301,
        limit_level = 150,
        name = "星体",
        open_level = 5,
        score = "lv*10",
        skill_effect = {"max_hp=level*2"},
        type = "气血上限",
    },

    [2302] = {
        desc = "太初被动技能，加法术攻击",
        element_type = "火",
        icon = 52014,
        id = 2302,
        limit_level = 150,
        name = "太初之力",
        open_level = 10,
        score = "lv*10",
        skill_effect = {"mag_attack=level*2"},
        type = "法术攻击",
    },

    [2303] = {
        desc = "太初被动技能，加法术防御",
        element_type = "火",
        icon = 52015,
        id = 2303,
        limit_level = 150,
        name = "星神护体",
        open_level = 15,
        score = "lv*10",
        skill_effect = {"mag_defense=level*2"},
        type = "法术防御",
    },

    [2304] = {
        desc = "太初被动技能，加命中和闪避",
        element_type = "火",
        icon = 52016,
        id = 2304,
        limit_level = 150,
        name = "灵视",
        open_level = 20,
        score = "lv*10",
        skill_effect = {"phy_hit_ratio=math.floor(level*0.5)", "phy_hit_res_ratio=math.floor((level+1)*0.5)"},
        type = "物理命中物理闪避",
    },

    [2305] = {
        desc = "太初被动技能，加法力上限",
        element_type = "火",
        icon = 52017,
        id = 2305,
        limit_level = 150,
        name = "元始",
        open_level = 30,
        score = "lv*10",
        skill_effect = {"max_mp=level*2"},
        type = "法力上限",
    },

    [2306] = {
        desc = "太初被动技能，加速度",
        element_type = "火",
        icon = 52018,
        id = 2306,
        limit_level = 150,
        name = "缩地成寸",
        open_level = 40,
        score = "lv*10",
        skill_effect = {"speed=level"},
        type = "速度",
    },

    [2401] = {
        desc = "瑶池被动技能，加气血上限",
        element_type = "火",
        icon = 52019,
        id = 2401,
        limit_level = 150,
        name = "神体",
        open_level = 5,
        score = "lv*10",
        skill_effect = {"max_hp=level*7"},
        type = "气血上限",
    },

    [2402] = {
        desc = "瑶池被动技能，加法术攻击",
        element_type = "火",
        icon = 52020,
        id = 2402,
        limit_level = 150,
        name = "凤凰之力",
        open_level = 10,
        score = "lv*10",
        skill_effect = {"mag_attack=level*1"},
        type = "法术攻击",
    },

    [2403] = {
        desc = "瑶池被动技能，加气血上限",
        element_type = "火",
        icon = 52021,
        id = 2403,
        limit_level = 150,
        name = "仙气护体",
        open_level = 15,
        score = "lv*10",
        skill_effect = {"max_hp=level*9"},
        type = "气血上限",
    },

    [2404] = {
        desc = "瑶池被动技能，加命中和闪避",
        element_type = "火",
        icon = 52022,
        id = 2404,
        limit_level = 150,
        name = "神眼",
        open_level = 20,
        score = "lv*10",
        skill_effect = {"phy_hit_ratio=math.floor(level*0.5)", "phy_hit_res_ratio=math.floor((level+1)*0.5)"},
        type = "物理命中物理闪避",
    },

    [2405] = {
        desc = "瑶池被动技能，加法力上限",
        element_type = "火",
        icon = 52023,
        id = 2405,
        limit_level = 150,
        name = "灵气蕴心",
        open_level = 30,
        score = "lv*10",
        skill_effect = {"max_mp=level*2"},
        type = "法力上限",
    },

    [2406] = {
        desc = "瑶池被动技能，加速度",
        element_type = "火",
        icon = 52024,
        id = 2406,
        limit_level = 150,
        name = "金光纵地",
        open_level = 40,
        score = "lv*10",
        skill_effect = {"speed=level"},
        type = "速度",
    },

    [2501] = {
        desc = "青城山被动技能，加气血上限",
        element_type = "火",
        icon = 52025,
        id = 2501,
        limit_level = 150,
        name = "妖气护身",
        open_level = 5,
        score = "lv*10",
        skill_effect = {"max_hp=level*4"},
        type = "气血上限",
    },

    [2502] = {
        desc = "青城山被动技能，加气血上限",
        element_type = "火",
        icon = 52026,
        id = 2502,
        limit_level = 150,
        name = "妖力通天",
        open_level = 10,
        score = "lv*10",
        skill_effect = {"max_hp=level*5"},
        type = "气血上限",
    },

    [2503] = {
        desc = "青城山被动技能，加物理防御",
        element_type = "火",
        icon = 52027,
        id = 2503,
        limit_level = 150,
        name = "妖体",
        open_level = 15,
        score = "lv*10",
        skill_effect = {"phy_defense=level*1"},
        type = "物理防御",
    },

    [2504] = {
        desc = "青城山被动技能，加命中和闪避",
        element_type = "火",
        icon = 52028,
        id = 2504,
        limit_level = 150,
        name = "妖目",
        open_level = 20,
        score = "lv*10",
        skill_effect = {"phy_hit_ratio=math.floor(level*0.5)", "phy_hit_res_ratio=math.floor((level+1)*0.5)"},
        type = "物理命中物理闪避",
    },

    [2505] = {
        desc = "青城山被动技能，加法力上限",
        element_type = "火",
        icon = 52029,
        id = 2505,
        limit_level = 150,
        name = "妖心永恒",
        open_level = 30,
        score = "lv*10",
        skill_effect = {"max_mp=level*2"},
        type = "法力上限",
    },

    [2506] = {
        desc = "青城山被动技能，加速度",
        element_type = "火",
        icon = 52030,
        id = 2506,
        limit_level = 150,
        name = "万里独行",
        open_level = 40,
        score = "lv*10",
        skill_effect = {"speed=level"},
        type = "速度",
    },

    [2601] = {
        desc = "妖神宫被动技能，加气血上限",
        element_type = "火",
        icon = 52031,
        id = 2601,
        limit_level = 150,
        name = "火之体",
        open_level = 5,
        score = "lv*10",
        skill_effect = {"max_hp=level*4"},
        type = "气血上限",
    },

    [2602] = {
        desc = "妖神宫被动技能，加物理攻击",
        element_type = "火",
        icon = 52032,
        id = 2602,
        limit_level = 150,
        name = "狂之力",
        open_level = 10,
        score = "lv*10",
        skill_effect = {"phy_attack=level*2"},
        type = "物理攻击",
    },

    [2603] = {
        desc = "妖神宫被动技能，加气血上限",
        element_type = "火",
        icon = 52033,
        id = 2603,
        limit_level = 150,
        name = "皇之气",
        open_level = 15,
        score = "lv*10",
        skill_effect = {"max_hp=level*5"},
        type = "气血上限",
    },

    [2604] = {
        desc = "妖神宫被动技能，加命中和闪避",
        element_type = "火",
        icon = 52034,
        id = 2604,
        limit_level = 150,
        name = "刀之技",
        open_level = 20,
        score = "lv*10",
        skill_effect = {"phy_hit_ratio=math.floor(level*0.5)", "phy_hit_res_ratio=math.floor((level+1)*0.5)"},
        type = "物理命中物理闪避",
    },

    [2605] = {
        desc = "妖神宫被动技能，加法力上限",
        element_type = "火",
        icon = 52035,
        id = 2605,
        limit_level = 150,
        name = "霸之道",
        open_level = 30,
        score = "lv*10",
        skill_effect = {"max_mp=level*2"},
        type = "法力上限",
    },

    [2606] = {
        desc = "妖神宫被动技能，加速度",
        element_type = "火",
        icon = 52036,
        id = 2606,
        limit_level = 150,
        name = "风之火",
        open_level = 40,
        score = "lv*10",
        skill_effect = {"speed=level"},
        type = "速度",
    },

}
