-- ./excel/skill/summon.xlsx
return {

    [5101] = {
        des = "受到物理攻击时，10%几率使用普通攻击对目标复仇",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50016"}},
        id = 5101,
        level = 1,
        name = "复仇",
        pflist = {5101},
        point = 5,
        quality = 2,
        score = 1,
        short_des = "受到物理攻击时，10%几率反击目标",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 10,
        top_skill = 0,
    },

    [5102] = {
        des = "增加宠物少量物攻",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50017"}},
        id = 5102,
        level = 1,
        name = "勇猛",
        pflist = {},
        point = 20,
        quality = 2,
        score = 1,
        short_des = "增加宠物少量物攻",
        skill_effect = {"phy_attack=grade*0.6+level*4"},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 3,
        top_skill = 5402,
    },

    [5103] = {
        des = "物理攻击时忽略目标2%物防",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50018"}},
        id = 5103,
        level = 1,
        name = "进击",
        pflist = {5103},
        point = 10,
        quality = 2,
        score = 1,
        short_des = "物理攻击时忽略目标2%物防",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 7,
        top_skill = 0,
    },

    [5104] = {
        des = "提高物理伤害5%；不会被复仇或震荡",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50019"}},
        id = 5104,
        level = 1,
        name = "暗杀",
        pflist = {5104},
        point = 25,
        quality = 2,
        score = 1,
        short_des = "提高物理伤害5%；不会被复仇或震荡",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 5,
        top_skill = 0,
    },

    [5105] = {
        des = "单体物理攻击时，吸取造成伤害20%的气血",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50020"}},
        id = 5105,
        level = 1,
        name = "生命汲取",
        pflist = {5105},
        point = 25,
        quality = 2,
        score = 1,
        short_des = "单体物理攻击时，吸取造成伤害20%的气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 6,
        top_skill = 0,
    },

    [5106] = {
        des = "物理攻击时，对额外两个单位造成7%的溅射伤害",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50021"}},
        id = 5106,
        level = 1,
        name = "溅射",
        pflist = {5106},
        point = 0,
        quality = 2,
        score = 1,
        short_des = "单体物理攻击时，对额外两个单位造成7%的溅射伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 8,
        top_skill = 0,
    },

    [5107] = {
        des = "普通攻击时，45%几率连续攻击目标2次，拥有此技能物理伤害会降低25%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50022"}},
        id = 5107,
        level = 1,
        name = "连斩",
        pflist = {5107},
        point = 55,
        quality = 2,
        score = 1,
        short_des = "45%几率连续攻击目标2次，但物理伤害降低25%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 2,
        top_skill = 0,
    },

    [5108] = {
        des = "普通攻击时，若击杀目标，则马上对一个随机敌方目标进行普通攻击，造成50%伤害",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50023"}},
        id = 5108,
        level = 1,
        name = "追击",
        pflist = {5108},
        point = 25,
        quality = 2,
        score = 1,
        short_des = "普通攻击击杀目标，则追击随机敌方目标，伤害为正常伤害的50%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 4,
        top_skill = 0,
    },

    [5109] = {
        des = "法术暴击几率提高10%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50024"}},
        id = 5109,
        level = 1,
        name = "法术暴击",
        pflist = {},
        point = 65,
        quality = 2,
        score = 1,
        short_des = "法术暴击几率提高10%",
        skill_effect = {"mag_critical_ratio=10"},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 1,
        top_skill = 5409,
    },

    [5110] = {
        des = "法术攻击时，有20%几率再次使用同样的法术攻击，第二次法术攻击的伤害减半",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50025"}},
        id = 5110,
        level = 1,
        name = "法术连斩",
        pflist = {5110},
        point = 45,
        quality = 2,
        score = 1,
        short_des = "20%几率法术攻击两次，第二次伤害减半",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 2,
        top_skill = 0,
    },

    [5111] = {
        des = "法术伤害结果在80%～120%范围内波动",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50026"}},
        id = 5111,
        level = 1,
        name = "法力波动",
        pflist = {5111},
        point = 20,
        quality = 2,
        score = 1,
        short_des = "法术伤害结果在80%～120%范围内波动",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 3,
        top_skill = 0,
    },

    [5112] = {
        des = "增加宠物少量法攻",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50027"}},
        id = 5112,
        level = 1,
        name = "法术增幅",
        pflist = {},
        point = 10,
        quality = 2,
        score = 1,
        short_des = "增加宠物少量法攻",
        skill_effect = {"mag_attack=grade*0.4+level*2"},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 6,
        top_skill = 5412,
    },

    [5113] = {
        des = "法术伤害结果提高10%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50028"}},
        id = 5113,
        level = 1,
        name = "魔化",
        pflist = {5113},
        point = 18,
        quality = 2,
        score = 1,
        short_des = "法术伤害结果提高10%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 4,
        top_skill = 0,
    },

    [5114] = {
        des = "法术攻击时忽视目标2%法防",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50029"}},
        id = 5114,
        level = 1,
        name = "法防忽视",
        pflist = {5114},
        point = 6,
        quality = 2,
        score = 1,
        short_des = "法术攻击时忽视目标2%法防",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 5,
        top_skill = 0,
    },

    [5115] = {
        des = "受到单体物理攻击时，30%几率震荡对方，震荡伤害为所受伤害的50%",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50030"}},
        id = 5115,
        level = 1,
        name = "震荡",
        pflist = {5115},
        point = 8,
        quality = 2,
        score = 1,
        short_des = "被单体物理攻击，30%几率震荡对方，震荡伤害为受到伤害的50%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 3,
        top_skill = 0,
    },

    [5116] = {
        des = "死亡后5回合自动复活，无法接受药物和主动技能治疗，不会受到增益/异常状态影响，且生命汲取对其无效",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50031"}},
        id = 5116,
        level = 1,
        name = "亡魂",
        pflist = {5116},
        point = 6,
        quality = 2,
        score = 1,
        short_des = "死亡后5回合自动复活，回复70%气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 13,
        top_skill = 0,
    },

    [5117] = {
        des = "死亡时有几率自动复活，复活气血为60%；复活几率受自身等级和体质影响，最高25%",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50032"}},
        id = 5117,
        level = 1,
        name = "还阳",
        pflist = {5117},
        point = 25,
        quality = 2,
        score = 1,
        short_des = "死亡有几率自动复活，复活气血为60%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 1,
        top_skill = 0,
    },

    [5118] = {
        des = "50%几率在回合末清除负面状态,不包含封印状态",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50033"}},
        id = 5118,
        level = 1,
        name = "定心",
        pflist = {5118},
        point = 5,
        quality = 2,
        score = 1,
        short_des = "50%几率在回合末清除负面状态",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 4,
        top_skill = 5418,
    },

    [5119] = {
        des = "速度增加10%",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50034"}},
        id = 5119,
        level = 1,
        name = "迅捷",
        pflist = {},
        point = 10,
        quality = 2,
        score = 1,
        short_des = "速度增加10%",
        skill_effect = {},
        skill_effect_ratio = {"speed=10"},
        skill_type = 2,
        sort_id = 5,
        top_skill = 5419,
    },

    [5120] = {
        des = "气血上限增加10%",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50035"}},
        id = 5120,
        level = 1,
        name = "健壮",
        pflist = {},
        point = 18,
        quality = 2,
        score = 1,
        short_des = "气血上限增加10%",
        skill_effect = {},
        skill_effect_ratio = {"max_hp=10"},
        skill_type = 2,
        sort_id = 18,
        top_skill = 5420,
    },

    [5121] = {
        des = "增加自身少量物防，受宠物等级影响，降低法术伤害结果10%",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50036"}},
        id = 5121,
        level = 1,
        name = "物理防御",
        pflist = {5121},
        point = 5,
        quality = 2,
        score = 1,
        short_des = "增加少量物防，降低法术伤害结果10%",
        skill_effect = {"phy_defense=0.8*grade"},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 6,
        top_skill = 5421,
    },

    [5122] = {
        des = "增加自身少量法防，受宠物等级影响，降低物理伤害结果10%",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50037"}},
        id = 5122,
        level = 1,
        name = "法术防御",
        pflist = {5122},
        point = 5,
        quality = 2,
        score = 1,
        short_des = "增加少量法防，降低物理伤害结果10%",
        skill_effect = {"mag_defense=0.8*grade"},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 7,
        top_skill = 5422,
    },

    [5123] = {
        des = "降低被物理暴击几率7%",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50038"}},
        id = 5123,
        level = 1,
        name = "物暴抵抗",
        pflist = {5123},
        point = 5,
        quality = 2,
        score = 1,
        short_des = "降低被物理暴击几率7%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 8,
        top_skill = 0,
    },

    [5124] = {
        des = "15%几率免疫土属性伤害，并恢复对应气血",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50039"}},
        id = 5124,
        level = 1,
        name = "土系吸收",
        pflist = {5124},
        point = 2,
        quality = 2,
        score = 1,
        short_des = "15%几率免疫土属性伤害，并恢复对应气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 9,
        top_skill = 0,
    },

    [5125] = {
        des = "15%几率免疫水属性伤害，并恢复对应气血",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50040"}},
        id = 5125,
        level = 1,
        name = "水系吸收",
        pflist = {5125},
        point = 2,
        quality = 2,
        score = 1,
        short_des = "15%几率免疫水属性伤害，并恢复对应气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 10,
        top_skill = 0,
    },

    [5126] = {
        des = "15%几率免疫火属性伤害，并恢复对应气血",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50041"}},
        id = 5126,
        level = 1,
        name = "火系吸收",
        pflist = {5126},
        point = 2,
        quality = 2,
        score = 1,
        short_des = "15%几率免疫火属性伤害，并恢复对应气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 11,
        top_skill = 0,
    },

    [5127] = {
        des = "15%几率免疫风属性伤害，并恢复对应气血",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50042"}},
        id = 5127,
        level = 1,
        name = "风系吸收",
        pflist = {5127},
        point = 2,
        quality = 2,
        score = 1,
        short_des = "15%几率免疫风属性伤害，并恢复对应气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 12,
        top_skill = 0,
    },

    [5128] = {
        des = "对拥有亡魂或高级亡魂的目标伤害增加50%，如果目标被打死，则直接出场",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50043"}},
        id = 5128,
        level = 1,
        name = "伏魔",
        pflist = {5128},
        point = 8,
        quality = 2,
        score = 1,
        short_des = "目标带有亡魂技能的，伤害增加50%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 14,
        top_skill = 0,
    },

    [5129] = {
        des = "可攻击隐身目标",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50004"}},
        id = 5129,
        level = 1,
        name = "天眼",
        pflist = {5129},
        point = 10,
        quality = 2,
        score = 1,
        short_des = "可攻击隐身目标",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 17,
        top_skill = 0,
    },

    [5130] = {
        des = "增加自身50%封印抗性",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50044"}},
        id = 5130,
        level = 1,
        name = "戒心",
        pflist = {5130},
        point = 3,
        quality = 2,
        score = 1,
        short_des = "增加自身50%封印抗性，物理伤害降低20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 15,
        top_skill = 0,
    },

    [5131] = {
        des = "增加物防，受自身当前气血值影响，气血越低，增加的防御越多，最高增加10%的防御",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50045"}},
        id = 5131,
        level = 1,
        name = "坚守",
        pflist = {5131},
        point = 0,
        quality = 2,
        score = 1,
        short_des = "增加物防，气血越低，增加的防御越多，最高增加10%的防御",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 19,
        top_skill = 0,
    },

    [5132] = {
        des = "进入战斗后，隐身2～3回合，降低自身20%物攻，隐身状态不可使用主动技能",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50046"}},
        id = 5132,
        level = 1,
        name = "遁法",
        pflist = {5132},
        point = 23,
        quality = 2,
        score = 1,
        short_des = "隐身2～3回合，降低自身20%物攻",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 16,
        top_skill = 0,
    },

    [5133] = {
        des = "受到物理伤害时，20%几率减免30%的伤害",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50047"}},
        id = 5133,
        level = 1,
        name = "拆招",
        pflist = {5133},
        point = 8,
        quality = 2,
        score = 1,
        short_des = "有20%的几率减免30%的物理伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 2,
        top_skill = 0,
    },

    [5134] = {
        des = "每阵亡一个队友，物理攻击增加1%，最高累计5次",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50048"}},
        id = 5134,
        level = 1,
        name = "同仇敌忾",
        pflist = {5134},
        point = 10,
        quality = 2,
        score = 1,
        short_des = "阵亡一个队友，物理攻击增加1%，最高累计5次",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 11,
        top_skill = 0,
    },

    [5135] = {
        des = "每回合自动恢复少量法力值，与等级相关",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50049"}},
        id = 5135,
        level = 1,
        name = "入定",
        pflist = {5135},
        point = 2,
        quality = 2,
        score = 1,
        short_des = "每回合自动恢复少量法力值，与等级相关",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 20,
        top_skill = 0,
    },

    [5136] = {
        des = "使用技能时有10%几率不消耗法力值",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50050"}},
        id = 5136,
        level = 1,
        name = "灵机一动",
        pflist = {5136},
        point = 3,
        quality = 2,
        score = 1,
        short_des = "使用技能时有10%几率不消耗法力值",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 21,
        top_skill = 0,
    },

    [5137] = {
        des = "物理暴击几率提高10%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50052"}},
        id = 5137,
        level = 1,
        name = "暴击",
        pflist = {5137},
        point = 78,
        quality = 2,
        score = 1,
        short_des = "物理暴击提高10%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 1,
        top_skill = 0,
    },

    [5138] = {
        des = "不会逃跑，受到带有气势或者震慑的宠物攻击时，所受伤害减少10%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50053"}},
        id = 5138,
        level = 1,
        name = "勇敢",
        pflist = {5138},
        point = 26,
        quality = 2,
        score = 1,
        short_des = "不会逃跑，受到带有气势或者震慑的宠物攻击时，所受伤害减少10%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 1,
        top_skill = 0,
    },

    [5139] = {
        des = "出战前两回合物理伤害增加10%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50054"}},
        id = 5139,
        level = 1,
        name = "气势",
        pflist = {5139},
        point = 6,
        quality = 2,
        score = 1,
        short_des = "出战前两回合物理伤害增加10%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 1,
        top_skill = 0,
    },

    [5140] = {
        des = "出战前两回合法术伤害增加10%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50055"}},
        id = 5140,
        level = 1,
        name = "震慑",
        pflist = {5140},
        point = 6,
        quality = 2,
        score = 1,
        short_des = "出战前两回合法术伤害增加10%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 1,
        top_skill = 0,
    },

    [5201] = {
        des = "单体法术攻击，造成土属性法术伤害",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50006"}},
        id = 5201,
        level = 1,
        name = "地动",
        pflist = {5201},
        point = 4,
        quality = 2,
        score = 1,
        short_des = "单体法术攻击，造成土属性法术伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 7,
        top_skill = 0,
    },

    [5202] = {
        des = "单体法术攻击，造成水属性法术伤害",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50007"}},
        id = 5202,
        level = 1,
        name = "水雷",
        pflist = {5202},
        point = 4,
        quality = 2,
        score = 1,
        short_des = "单体法术攻击，造成水属性法术伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 8,
        top_skill = 0,
    },

    [5203] = {
        des = "单体法术攻击，造成火属性法术伤害",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50008"}},
        id = 5203,
        level = 1,
        name = "心火",
        pflist = {5203},
        point = 4,
        quality = 2,
        score = 1,
        short_des = "单体法术攻击，造成火属性法术伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 9,
        top_skill = 0,
    },

    [5204] = {
        des = "单体法术攻击，造成风属性法术伤害",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50009"}},
        id = 5204,
        level = 1,
        name = "龙卷",
        pflist = {5204},
        point = 4,
        quality = 2,
        score = 1,
        short_des = "单体法术攻击，造成风属性法术伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 10,
        top_skill = 0,
    },

    [5205] = {
        des = "群体法术攻击，造成土属性法术伤害；初始作用2个目标，50级作用3个目标",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50210"}},
        id = 5205,
        level = 1,
        name = "山崩地裂",
        pflist = {5205},
        point = 200,
        quality = 5,
        score = 1,
        short_des = "群体法术攻击，造成土属性法术伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 7,
        top_skill = 0,
    },

    [5206] = {
        des = "群体法术攻击，造成水属性法术伤害；初始作用2个目标，50级作用3个目标",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50211"}},
        id = 5206,
        level = 1,
        name = "冰封万里",
        pflist = {5206},
        point = 200,
        quality = 5,
        score = 1,
        short_des = "群体法术攻击，造成水属性法术伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 8,
        top_skill = 0,
    },

    [5207] = {
        des = "群体法术攻击，造成火属性法术伤害；初始作用2个目标，50级作用3个目标",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50212"}},
        id = 5207,
        level = 1,
        name = "焚天怒火",
        pflist = {5207},
        point = 200,
        quality = 5,
        score = 1,
        short_des = "群体法术攻击，造成火属性法术伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 9,
        top_skill = 0,
    },

    [5208] = {
        des = "群体法术攻击，造成风属性法术伤害；初始作用2个目标，50级作用3个目标",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50213"}},
        id = 5208,
        level = 1,
        name = "风卷残云",
        pflist = {5208},
        point = 200,
        quality = 5,
        score = 1,
        short_des = "群体法术攻击，造成风属性法术伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 10,
        top_skill = 0,
    },

    [5209] = {
        des = "单体物理攻击，根据目标气血对目标造成额外伤害，目标气血越低，伤害越高",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50051"}},
        id = 5209,
        level = 1,
        name = "趁势而上",
        pflist = {5209},
        point = 25,
        quality = 2,
        score = 1,
        short_des = "单体物理攻击，目标气血越低，伤害越高",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 219,
        top_skill = 0,
    },

    [5210] = {
        des = "单体物理攻击，根据自身气血对目标造成额外伤害，自身气血越低，伤害越高",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50003"}},
        id = 5210,
        level = 1,
        name = "以牙还牙",
        pflist = {5210},
        point = 25,
        quality = 2,
        score = 1,
        short_des = "单体物理攻击，自身气血越低，伤害越高",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 9,
        top_skill = 0,
    },

    [5211] = {
        des = "群体物理攻击，初始作用2个目标，50级作用3个目标（注：爆破不受吸血、法术连斩、法术暴击影响）",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50205"}},
        id = 5211,
        level = 1,
        name = "爆破",
        pflist = {5211},
        point = 113,
        quality = 5,
        score = 1,
        short_des = "群体物理攻击",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 220,
        top_skill = 0,
    },

    [5212] = {
        des = "群体物理攻击，初始作用2个目标，50级作用3个目标（注：金雷震爆不受吸血、法术连斩、法术暴击影响）",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50202"}},
        id = 5212,
        level = 1,
        name = "金雷震爆",
        pflist = {5212},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "群体物理攻击",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 9,
        top_skill = 0,
    },

    [5213] = {
        des = "单体物理攻击，若目标防御，则伤害增加50%",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50201"}},
        id = 5213,
        level = 1,
        name = "摧心",
        pflist = {5213},
        point = 38,
        quality = 2,
        score = 1,
        short_des = "单体物理攻击，对防御目标造成更高伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 11,
        top_skill = 0,
    },

    [5401] = {
        des = "受到物理攻击时，20%几率使用普通攻击对目标复仇",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50216"}},
        id = 5401,
        level = 5,
        name = "高级复仇",
        pflist = {5101},
        point = 25,
        quality = 5,
        score = 1,
        short_des = "受到物理攻击时，20%几率反击目标",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 10,
        top_skill = 0,
    },

    [5402] = {
        des = "增加宠物的大量的物攻",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50217"}},
        id = 5402,
        level = 5,
        name = "高级勇猛",
        pflist = {},
        point = 100,
        quality = 5,
        score = 1,
        short_des = "增加宠物的大量的物攻",
        skill_effect = {"phy_attack=grade+level*4"},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 3,
        top_skill = 0,
    },

    [5403] = {
        des = "物理攻击时忽略目标5%物防",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50218"}},
        id = 5403,
        level = 5,
        name = "高级进击",
        pflist = {5103},
        point = 50,
        quality = 5,
        score = 1,
        short_des = "物理攻击时忽略目标5%物防",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 7,
        top_skill = 0,
    },

    [5404] = {
        des = "提高物理伤害10%；不会被复仇或震荡",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50219"}},
        id = 5404,
        level = 5,
        name = "高级暗杀",
        pflist = {5104},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "提高物理伤害10%；不会被复仇或震荡",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 5,
        top_skill = 0,
    },

    [5405] = {
        des = "单体物理攻击时，吸取造成伤害30%的气血",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50220"}},
        id = 5405,
        level = 5,
        name = "高级生命汲取",
        pflist = {5105},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "单体物理攻击时，吸取造成伤害30%的气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 6,
        top_skill = 0,
    },

    [5406] = {
        des = "单体物理攻击时，对额外两个单位造成15%的溅射伤害",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50221"}},
        id = 5406,
        level = 5,
        name = "高级溅射",
        pflist = {5106},
        point = 0,
        quality = 5,
        score = 1,
        short_des = "单体物理攻击时，对额外两个单位造成15%的溅射伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 8,
        top_skill = 0,
    },

    [5407] = {
        des = "普通攻击时，55%几率连续攻击目标2次，拥有此技能物理伤害会降低20%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "25-2*level",
        iconlv = {{["icon"] = "50222"}},
        id = 5407,
        level = 5,
        name = "高级连斩",
        pflist = {5107},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "55%几率连续攻击目标2次，物理伤害会降低20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 2,
        top_skill = 0,
    },

    [5408] = {
        des = "普通攻击时，若击杀目标，则马上对一个随机敌方目标进行普通攻击，造成100%伤害",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50223"}},
        id = 5408,
        level = 5,
        name = "高级追击",
        pflist = {5108},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "普通攻击击杀目标，则追击随机敌方目标，伤害为正常伤害的100%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 4,
        top_skill = 0,
    },

    [5409] = {
        des = "法术暴击几率提高20%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50224"}},
        id = 5409,
        level = 5,
        name = "高级法术暴击",
        pflist = {},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "法术暴击几率提高20%",
        skill_effect = {"mag_critical_ratio=20"},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 1,
        top_skill = 0,
    },

    [5410] = {
        des = "法术攻击时，有30%几率再次使用同样的法术攻击，第二次法术攻击的伤害减半",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50225"}},
        id = 5410,
        level = 5,
        name = "高级法术连斩",
        pflist = {5110},
        point = 225,
        quality = 5,
        score = 1,
        short_des = "30%几率法术攻击两次，第二次伤害减半",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 2,
        top_skill = 0,
    },

    [5411] = {
        des = "法术伤害结果在60%～140%范围内波动",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "120+level*4",
        iconlv = {{["icon"] = "50226"}},
        id = 5411,
        level = 5,
        name = "高级法力波动",
        pflist = {5111},
        point = 75,
        quality = 5,
        score = 1,
        short_des = "法术伤害结果在60%～140%范围内波动",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 3,
        top_skill = 0,
    },

    [5412] = {
        des = "增加宠物大量法攻",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50227"}},
        id = 5412,
        level = 5,
        name = "高级法术增幅",
        pflist = {},
        point = 50,
        quality = 5,
        score = 1,
        short_des = "增加宠物大量法攻",
        skill_effect = {"mag_attack=grade*0.6+level*2"},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 6,
        top_skill = 0,
    },

    [5413] = {
        des = "法术伤害结果提高20%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50228"}},
        id = 5413,
        level = 5,
        name = "高级魔化",
        pflist = {5113},
        point = 75,
        quality = 5,
        score = 1,
        short_des = "法术伤害结果提高20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 4,
        top_skill = 0,
    },

    [5414] = {
        des = "法术攻击时忽视目标5%法防",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50229"}},
        id = 5414,
        level = 5,
        name = "高级法防忽视",
        pflist = {5114},
        point = 25,
        quality = 5,
        score = 1,
        short_des = "法术攻击时忽视目标5%法防",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 1,
        sort_id = 5,
        top_skill = 0,
    },

    [5415] = {
        des = "受到单体物理攻击时，50%几率震荡对方，震荡伤害为所受伤害的50%",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50230"}},
        id = 5415,
        level = 5,
        name = "高级震荡",
        pflist = {5115},
        point = 38,
        quality = 5,
        score = 1,
        short_des = "被单体物理攻击时，50%几率震荡对方，震荡伤害为受到伤害的50%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 3,
        top_skill = 0,
    },

    [5416] = {
        des = "死亡后5回合自动复活，不会受到异常状态影响，且生命汲取对其无效",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50231"}},
        id = 5416,
        level = 5,
        name = "高级亡魂",
        pflist = {5116},
        point = 25,
        quality = 5,
        score = 1,
        short_des = "死亡后5回合自动复活，回复100%气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 13,
        top_skill = 0,
    },

    [5417] = {
        des = "死亡时有几率自动复活，复活气血为100%；复活几率受自身等级和体质影响，最高25%",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50232"}},
        id = 5417,
        level = 5,
        name = "高级还阳",
        pflist = {5117},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "死亡有几率自动复活，复活气血为100%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 1,
        top_skill = 0,
    },

    [5418] = {
        des = "免疫负面状态,不包含封印状态",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50233"}},
        id = 5418,
        level = 5,
        name = "高级定心",
        pflist = {5418},
        point = 25,
        quality = 5,
        score = 1,
        short_des = "免疫负面状态",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 4,
        top_skill = 0,
    },

    [5419] = {
        des = "速度增加20%",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50234"}},
        id = 5419,
        level = 5,
        name = "高级迅捷",
        pflist = {},
        point = 50,
        quality = 5,
        score = 1,
        short_des = "速度增加20%",
        skill_effect = {},
        skill_effect_ratio = {"speed=20"},
        skill_type = 2,
        sort_id = 5,
        top_skill = 0,
    },

    [5420] = {
        des = "气血上限增加20%",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50235"}},
        id = 5420,
        level = 5,
        name = "高级健壮",
        pflist = {},
        point = 88,
        quality = 5,
        score = 1,
        short_des = "气血上限增加20%",
        skill_effect = {},
        skill_effect_ratio = {"max_hp=20"},
        skill_type = 2,
        sort_id = 18,
        top_skill = 0,
    },

    [5421] = {
        des = "增加自身较多物防，受宠物等级影响，降低法术伤害结果10%",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "10",
        iconlv = {{["icon"] = "50236"}},
        id = 5421,
        level = 5,
        name = "高级物理防御",
        pflist = {5121},
        point = 25,
        quality = 5,
        score = 1,
        short_des = "增加较多物防，降低法术伤害结果10%",
        skill_effect = {"phy_defense=1.2*grade"},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 6,
        top_skill = 0,
    },

    [5422] = {
        des = "增加自身较多法防，受宠物等级影响，降低物理伤害结果10%",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "10",
        iconlv = {{["icon"] = "50237"}},
        id = 5422,
        level = 5,
        name = "高级法术防御",
        pflist = {5122},
        point = 25,
        quality = 5,
        score = 1,
        short_des = "增加较多法防，降低物理伤害结果10%",
        skill_effect = {"mag_defense=1.2*grade"},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 7,
        top_skill = 0,
    },

    [5423] = {
        des = "降低被物理暴击几率15%",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50238"}},
        id = 5423,
        level = 5,
        name = "高级物暴抵抗",
        pflist = {5123},
        point = 25,
        quality = 5,
        score = 1,
        short_des = "降低被物理暴击几率15%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 8,
        top_skill = 0,
    },

    [5424] = {
        des = "30%几率免疫土属性伤害，并恢复对应气血",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50239"}},
        id = 5424,
        level = 5,
        name = "高级土系吸收",
        pflist = {5124},
        point = 8,
        quality = 5,
        score = 1,
        short_des = "30%几率免疫土属性伤害，并恢复对应气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 9,
        top_skill = 0,
    },

    [5425] = {
        des = "30%几率免疫水属性伤害，并恢复对应气血",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50240"}},
        id = 5425,
        level = 5,
        name = "高级水系吸收",
        pflist = {5125},
        point = 8,
        quality = 5,
        score = 1,
        short_des = "30%几率免疫水属性伤害，并恢复对应气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 10,
        top_skill = 0,
    },

    [5426] = {
        des = "30%几率免疫火属性伤害，并恢复对应气血",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50241"}},
        id = 5426,
        level = 5,
        name = "高级火系吸收",
        pflist = {5126},
        point = 8,
        quality = 5,
        score = 1,
        short_des = "30%几率免疫火属性伤害，并恢复对应气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 11,
        top_skill = 0,
    },

    [5427] = {
        des = "30%几率免疫风属性伤害，并恢复对应气血",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50242"}},
        id = 5427,
        level = 5,
        name = "高级风系吸收",
        pflist = {5127},
        point = 8,
        quality = 5,
        score = 1,
        short_des = "30%几率免疫风属性伤害，并恢复对应气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 12,
        top_skill = 0,
    },

    [5428] = {
        des = "对拥有亡魂或高级亡魂的目标伤害增加100%，如果目标被打死，则直接出场",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50243"}},
        id = 5428,
        level = 5,
        name = "高级伏魔",
        pflist = {5128},
        point = 38,
        quality = 5,
        score = 1,
        short_des = "对拥有亡魂技能的目标伤害增加100%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 14,
        top_skill = 0,
    },

    [5429] = {
        des = "可攻击隐身目标，并且造成额外10%伤害",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50204"}},
        id = 5429,
        level = 5,
        name = "高级天眼",
        pflist = {5129},
        point = 50,
        quality = 5,
        score = 1,
        short_des = "可攻击隐身目标，并且造成额外10%伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 17,
        top_skill = 0,
    },

    [5430] = {
        des = "抵抗所有封印状态",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50244"}},
        id = 5430,
        level = 5,
        name = "高级戒心",
        pflist = {5130},
        point = 13,
        quality = 5,
        score = 1,
        short_des = "抵抗所有封印状态，物理伤害降低20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 15,
        top_skill = 0,
    },

    [5431] = {
        des = "增加物防，受自身当前气血值影响，气血越低，增加的防御越多，最高增加20%的防御",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50245"}},
        id = 5431,
        level = 5,
        name = "高级坚守",
        pflist = {5131},
        point = 0,
        quality = 5,
        score = 1,
        short_des = "增加物防，气血越低，增加的防御越多，最高增加20%的防御",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 19,
        top_skill = 0,
    },

    [5432] = {
        des = "进入战斗后，隐身3～5回合，降低自身15%物理攻击，隐身状态不可使用主动技能",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50246"}},
        id = 5432,
        level = 5,
        name = "高级遁法",
        pflist = {5132},
        point = 100,
        quality = 5,
        score = 1,
        short_des = "隐身3～5回合，降低自身15%物理攻击",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 16,
        top_skill = 0,
    },

    [5433] = {
        des = "受到物理伤害时，30%几率减免30%的伤害",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50247"}},
        id = 5433,
        level = 5,
        name = "高级拆招",
        pflist = {5133},
        point = 38,
        quality = 5,
        score = 1,
        short_des = "受到物理伤害时，有30%的几率减免30%的伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 2,
        top_skill = 0,
    },

    [5434] = {
        des = "每阵亡一个队友，物攻增加3%，最高累计5次",
        fight_score = "20*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50248"}},
        id = 5434,
        level = 5,
        name = "高级同仇敌忾",
        pflist = {5134},
        point = 50,
        quality = 5,
        score = 1,
        short_des = "每阵亡一个队友，物攻增加3%，最高累计5次",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 12,
        top_skill = 0,
    },

    [5435] = {
        des = "每回合自动恢复较多法力值，与等级相关",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50249"}},
        id = 5435,
        level = 5,
        name = "高级入定",
        pflist = {5135},
        point = 8,
        quality = 5,
        score = 1,
        short_des = "每回合自动恢复较多法力值，与等级相关",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 20,
        top_skill = 0,
    },

    [5436] = {
        des = "使用技能时有20%几率不消耗法力值",
        fight_score = "10*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50250"}},
        id = 5436,
        level = 5,
        name = "高级灵机一动",
        pflist = {5136},
        point = 13,
        quality = 5,
        score = 1,
        short_des = "使用技能时有20%几率不消耗法力值",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 2,
        sort_id = 21,
        top_skill = 0,
    },

    [5437] = {
        des = "物理暴击几率提高20%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50252"}},
        id = 5437,
        level = 5,
        name = "高级暴击",
        pflist = {5137},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "物理暴击几率提高20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 1,
        top_skill = 0,
    },

    [5438] = {
        des = "不会逃跑，受到带有气势、高级气势、震慑或高级震慑的目标攻击时，所受伤害减少20%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50253"}},
        id = 5438,
        level = 5,
        name = "高级勇敢",
        pflist = {5138},
        point = 200,
        quality = 5,
        score = 1,
        short_des = "不会逃跑，受到带有低高级气势或低高级震慑的目标攻击时，所受伤害减少20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 1,
        top_skill = 0,
    },

    [5439] = {
        des = "出战前两回合物理伤害增加20%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50254"}},
        id = 5439,
        level = 5,
        name = "高级气势",
        pflist = {5139},
        point = 150,
        quality = 5,
        score = 1,
        short_des = "出战前两回合物理伤害增加20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 1,
        top_skill = 0,
    },

    [5440] = {
        des = "出战前两回合法术伤害增加20%",
        fight_score = "50*lv",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50255"}},
        id = 5440,
        level = 5,
        name = "高级震慑",
        pflist = {5140},
        point = 100,
        quality = 5,
        score = 1,
        short_des = "出战前两回合法术伤害增加20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 1,
        top_skill = 0,
    },

    [5301] = {
        des = "单体物理攻击，伤害结果提高50%，自身需承受对应的20%伤害；气血低于上限30%时无法使用",
        fight_score = "250",
        formula1 = "0",
        formula2 = "3",
        iconlv = {{["icon"] = "50126"}},
        id = 5301,
        level = 1,
        name = "背水一战",
        pflist = {5301},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "伤害结果提高50%，自身需承受对应的20%伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 200,
        top_skill = 0,
    },

    [5302] = {
        des = "单体物理攻击，70%几率造成200%伤害，若失败则为目标恢复100%伤害的气血",
        fight_score = "250",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50137"}},
        id = 5302,
        level = 1,
        name = "阎罗令",
        pflist = {5302},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "70%造成200%的伤害，30%为对方恢复伤害100%气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 201,
        top_skill = 0,
    },

    [5303] = {
        des = "增加少量气血和速度",
        fight_score = "150",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50215"}},
        id = 5303,
        level = 1,
        name = "血脉之力",
        pflist = {},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "增加少量气血和速度",
        skill_effect = {"max_hp=0.6*grade", "speed=0.6*grade"},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 202,
        top_skill = 0,
    },

    [5304] = {
        des = "单体物理攻击，目标物攻越低则受到伤害越高",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50117"}},
        id = 5304,
        level = 1,
        name = "降龙伏虎",
        pflist = {5304},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "单体物理攻击，目标物攻越低则受到伤害越高",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 203,
        top_skill = 0,
    },

    [5305] = {
        des = "单体法术攻击，并且有25%几率令目标在4回合内无法复活",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50131"}},
        id = 5305,
        level = 1,
        name = "幽冥噬魂",
        pflist = {5305},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "单体法术攻击，25%几率令目标在4回合内无法复活",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 204,
        top_skill = 0,
    },

    [5306] = {
        des = "群体法术攻击，消耗目标的法力值，如果目标是NPC，则会吸取一定法力值给主人；初始作用2个目标，50级作用3个目标",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "50256"}},
        id = 5306,
        level = 1,
        name = "星华绽放",
        pflist = {5306},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "群体法术攻击，并消耗目标的法力值，如果目标是NPC，则会吸取一定法力值给主人",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 205,
        top_skill = 0,
    },

    [5502] = {
        des = "触发暴击时，有一定的几率将伤害效果由2倍提高到3倍",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54001"}},
        id = 5502,
        level = 1,
        name = "暴击强化",
        pflist = {5502},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "触发暴击时，有一定的几率将伤害效果由2倍提高到3倍",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 205,
        top_skill = 0,
    },

    [5507] = {
        des = "触发连斩时，有几率多攻击一个单位，伤害为正常伤害的50%",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54002"}},
        id = 5507,
        level = 1,
        name = "连斩强化",
        pflist = {5507},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "触发连斩时，有几率多攻击一个单位，伤害为正常伤害的50%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 206,
        top_skill = 0,
    },

    [5509] = {
        des = "若主人普通攻击一个目标，有30%几率触发协同攻击",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54003"}},
        id = 5509,
        level = 1,
        name = "协同",
        pflist = {5509},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "若主人普通攻击一个目标，有30%几率触发协同攻击。",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 207,
        top_skill = 0,
    },

    [5510] = {
        des = "对拥有增益效果的单位伤害增加10%",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54004"}},
        id = 5510,
        level = 1,
        name = "逆击",
        pflist = {5510},
        point = 200,
        quality = 5,
        score = 1,
        short_des = "对拥有增益效果的单位伤害增加10%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 208,
        top_skill = 0,
    },

    [5511] = {
        des = "对气血小于30%的目标伤害增加15%",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54005"}},
        id = 5511,
        level = 1,
        name = "嗜血",
        pflist = {5511},
        point = 150,
        quality = 5,
        score = 1,
        short_des = "对气血小于30%的单位伤害增加15%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 209,
        top_skill = 0,
    },

    [5513] = {
        des = "单体攻击有20%的几率额外造成自身速度与对手速度差的伤害",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54006"}},
        id = 5513,
        level = 1,
        name = "突击",
        pflist = {5513},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "攻击有20%的几率造成自身速度与对手速度差的伤害",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 210,
        top_skill = 0,
    },

    [5514] = {
        des = "攻击同一个目标伤害增加",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54007"}},
        id = 5514,
        level = 1,
        name = "仇恨",
        pflist = {5514},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "攻击同一个目标伤害增加",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 211,
        top_skill = 0,
    },

    [5520] = {
        des = "失去隐身后，有20%几率再次进入隐身",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54008"}},
        id = 5520,
        level = 1,
        name = "隐遁",
        pflist = {5520},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "失去隐身后，有20%的几率再次进入隐身",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 212,
        top_skill = 0,
    },

    [5521] = {
        des = "战斗开始的前3个回合，物防提高20%",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54009"}},
        id = 5521,
        level = 1,
        name = "铁壁",
        pflist = {5521},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "战斗开始的前3个回合，物防提高20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 213,
        top_skill = 0,
    },

    [5522] = {
        des = "击杀目标后，恢复自身20%气血",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54010"}},
        id = 5522,
        level = 1,
        name = "肉食",
        pflist = {5522},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "击杀目标后，恢复自身生命20%的气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 214,
        top_skill = 0,
    },

    [5524] = {
        des = "亡魂复活的回合数-1",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54011"}},
        id = 5524,
        level = 1,
        name = "亡魂强化",
        pflist = {5524},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "亡魂复活的回合数-1",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 215,
        top_skill = 0,
    },

    [5527] = {
        des = "宠物攻击目标，50%几率将伤害的20%转化为主人的气血",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54012"}},
        id = 5527,
        level = 1,
        name = "报恩",
        pflist = {5527},
        point = 250,
        quality = 5,
        score = 1,
        short_des = "宠物攻击目标，50%几率将伤害的20%转化为主人的气血",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 216,
        top_skill = 0,
    },

    [5531] = {
        des = "每次受到伤害，30%几率将伤害的20%转移到一个随机敌方单位身上",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54013"}},
        id = 5531,
        level = 1,
        name = "反伤",
        pflist = {5531},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "每次受到伤害，30%几率将伤害的20%转移到一个随机敌方单位身上",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 217,
        top_skill = 0,
    },

    [5541] = {
        des = "战斗开始的前3个回合，法防提高20%",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54009"}},
        id = 5541,
        level = 1,
        name = "法术抵抗",
        pflist = {5541},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "战斗开始的前3个回合，法防提高20%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 218,
        top_skill = 0,
    },

    [5542] = {
        des = "法术攻击有20%几率去掉目标身上的一个增益状态",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54015"}},
        id = 5542,
        level = 1,
        name = "净化",
        pflist = {5542},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "法术攻击有20%几率去掉目标身上的一项增益状态",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 219,
        top_skill = 0,
    },

    [5543] = {
        des = "法术攻击有20%几率让目标防御下降5%，持续两回合",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54016"}},
        id = 5543,
        level = 1,
        name = "蚀甲",
        pflist = {5543},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "法术攻击有20%几率让目标防御下降5%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 220,
        top_skill = 0,
    },

    [5544] = {
        des = "法术攻击有20%几率让目标速度下降5%，持续两回合",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "54017"}},
        id = 5544,
        level = 1,
        name = "流沙",
        pflist = {5544},
        point = 125,
        quality = 5,
        score = 1,
        short_des = "法术攻击有20%几率让目标速度下降5%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 221,
        top_skill = 0,
    },

    [5701] = {
        des = "拥有亡魂技能的宠物倒地后，下回合开始，每回合获得1个魄，或者有己方单位死亡时（触发亡魂和还阳除外）获得1个魄。累计获得5个魄后提前复活。",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "56100"}},
        id = 5701,
        level = 1,
        name = "凝魄",
        pflist = {5701},
        point = 0,
        quality = 5,
        score = 1,
        short_des = "拥有亡魂技能的宠物倒地后，下回合开始，每回合获得1个魄，或者有己方单位死亡时（触发亡魂和还阳除外）获得1个魄。累计获得5个魄后提前复活。",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 221,
        top_skill = 0,
    },

    [5702] = {
        des = "参加战斗后，前3回合，宠物与主人分摊彼此受到伤害的30%",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "56101"}},
        id = 5702,
        level = 1,
        name = "患难",
        pflist = {5702},
        point = 0,
        quality = 5,
        score = 1,
        short_des = "参加战斗后，前3回合，宠物与主人分摊彼此受到伤害的30%",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 221,
        top_skill = 0,
    },

    [5703] = {
        des = "击倒一个单位后，下次物理攻击附加重伤效果，持续3回合。",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "56102"}},
        id = 5703,
        level = 1,
        name = "狂暴",
        pflist = {5703},
        point = 0,
        quality = 5,
        score = 1,
        short_des = "击倒一个单位后，下次物理攻击附加重伤效果，持续3回合。",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 221,
        top_skill = 0,
    },

    [5704] = {
        des = "参加战斗，前2回合血量提升50%，第2回合结束后，扣除提升的50%气血值和气血上限，可能会导致宠物死亡。",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "56103"}},
        id = 5704,
        level = 1,
        name = "好战",
        pflist = {5704},
        point = 0,
        quality = 5,
        score = 1,
        short_des = "参加战斗，前2回合血量提升50%，第2回合结束后，扣除提升的50%气血值和气血上限，可能会导致宠物死亡。",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 221,
        top_skill = 0,
    },

    [5705] = {
        des = "如果当前回合受到3次物理或者3次法术伤害，则下回合减免20%受到的伤害结果。",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "56104"}},
        id = 5705,
        level = 1,
        name = "石化",
        pflist = {5705},
        point = 0,
        quality = 5,
        score = 1,
        short_des = "如果当前回合受到3次物理或者3次法术伤害，则下回合减免20%受到的伤害结果。",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 221,
        top_skill = 0,
    },

    [5706] = {
        des = "宠物死亡时（触发亡魂和还阳除外），为场上未死的宠物中气血百分比最低的回满气血。",
        fight_score = "200",
        formula1 = "0",
        formula2 = "0",
        iconlv = {{["icon"] = "56105"}},
        id = 5706,
        level = 1,
        name = "不甘",
        pflist = {5706},
        point = 0,
        quality = 5,
        score = 1,
        short_des = "宠物死亡时（触发亡魂和还阳除外），为场上未死的宠物中气血百分比最低的回满气血。",
        skill_effect = {},
        skill_effect_ratio = {},
        skill_type = 0,
        sort_id = 221,
        top_skill = 0,
    },

}
