-- ./excel/system/orgskill/skill.xlsx
return {

    [4101] = {
        cost_energy = "math.min(40, math.floor(level / 10) * 10 + 10)",
        des = "消耗活力可随机制作一种烹饪，烹饪品质受技能等级影响",
        effect_lv = 20,
        exchange_silver = "",
        icon = "5101",
        id = 4101,
        init_lv = 20,
        item = {{["id"] = 10046, ["level"] = 20}, {["id"] = 10047, ["level"] = 20}, {["id"] = 10048, ["level"] = 40}, {["id"] = 10049, ["level"] = 50}, {["id"] = 10050, ["level"] = 60}},
        make_item = {},
        makedes = "可以烹饪以下食物",
        makeitemdes = "",
        max_lv = 100,
        name = "烹饪",
        nextlv_effect = {},
        score = "0",
        skill_effect = {},
        sort = 3,
        type = 1,
        up_cost_type = {1, 2},
    },

    [4102] = {
        cost_energy = "math.min(40, level + 10)",
        des = "消耗活力和二级药可随机炼制药品，药品品质受技能等级影响",
        effect_lv = 20,
        exchange_silver = "",
        icon = "5102",
        id = 4102,
        init_lv = 20,
        item = {{["id"] = 10057, ["level"] = 20}, {["id"] = 10058, ["level"] = 20}, {["id"] = 10059, ["level"] = 20}, {["id"] = 10060, ["level"] = 20}, {["id"] = 10061, ["level"] = 20}, {["id"] = 10062, ["level"] = 20}, {["id"] = 10063, ["level"] = 20}, {["id"] = 10064, ["level"] = 20}},
        make_item = {10051, 10052, 10053, 10054, 10055, 10056},
        makedes = "使用2级药可以炼制以下药品",
        makeitemdes = "定心丹，大还丹，九转还魂丹",
        max_lv = 100,
        name = "炼药",
        nextlv_effect = {},
        score = "0",
        skill_effect = {},
        sort = 4,
        type = 1,
        up_cost_type = {1, 2},
    },

    [4103] = {
        cost_energy = "math.max(math.floor(level / 10 - 3) * 8, 30)",
        des = "可以消耗活力制作打造符，用于制造武器、腰带、项链",
        effect_lv = 40,
        exchange_silver = "",
        icon = "5103",
        id = 4103,
        init_lv = 20,
        item = {{["id"] = 12001, ["level"] = 40}, {["id"] = 12002, ["level"] = 50}, {["id"] = 12003, ["level"] = 60}, {["id"] = 12004, ["level"] = 70}, {["id"] = 12005, ["level"] = 80}, {["id"] = 12006, ["level"] = 90}, {["id"] = 12007, ["level"] = 100}, {["id"] = 12008, ["level"] = 110}},
        make_item = {},
        makedes = "当前制作的打造符最高",
        makeitemdes = "",
        max_lv = 150,
        name = "打造",
        nextlv_effect = {},
        score = "0",
        skill_effect = {},
        sort = 5,
        type = 1,
        up_cost_type = {1, 2},
    },

    [4104] = {
        cost_energy = "math.max(math.floor(level / 10 - 3) * 8, 30)",
        des = "可以消耗活力制作裁缝符，用于制造铠甲、头盔、鞋子",
        effect_lv = 40,
        exchange_silver = "",
        icon = "5201",
        id = 4104,
        init_lv = 20,
        item = {{["id"] = 12031, ["level"] = 40}, {["id"] = 12032, ["level"] = 50}, {["id"] = 12033, ["level"] = 60}, {["id"] = 12034, ["level"] = 70}, {["id"] = 12035, ["level"] = 80}, {["id"] = 12036, ["level"] = 90}, {["id"] = 12037, ["level"] = 100}, {["id"] = 12038, ["level"] = 110}},
        make_item = {},
        makedes = "当前制作的裁缝符最高",
        makeitemdes = "",
        max_lv = 150,
        name = "裁缝",
        nextlv_effect = {},
        score = "0",
        skill_effect = {},
        sort = 6,
        type = 1,
        up_cost_type = {1, 2},
    },

    [4105] = {
        cost_energy = "0",
        des = "习武之人的根本，每学习一级可提高一定气血上限",
        effect_lv = 0,
        exchange_silver = "",
        icon = "5301",
        id = 4105,
        init_lv = 0,
        item = {},
        make_item = {},
        makedes = "技能等级越高，效果越明显",
        makeitemdes = "",
        max_lv = 100,
        name = "强身",
        nextlv_effect = {"nextlv_max_hp=10*(level+1)"},
        score = "lv*5",
        skill_effect = {"max_hp=10*level"},
        sort = 1,
        type = 2,
        up_cost_type = {1, 2},
    },

    [4106] = {
        cost_energy = "0",
        des = "提升精神力的技巧，每学习一级可提高一定法力上限",
        effect_lv = 0,
        exchange_silver = "",
        icon = "5302",
        id = 4106,
        init_lv = 0,
        item = {},
        make_item = {},
        makedes = "技能等级越高，效果越明显",
        makeitemdes = "",
        max_lv = 100,
        name = "冥想",
        nextlv_effect = {"nextlv_max_mp=10*(level+1)"},
        score = "lv*5",
        skill_effect = {"max_mp=10*level"},
        sort = 2,
        type = 2,
        up_cost_type = {1, 2},
    },

    [4107] = {
        cost_energy = "math.max(math.floor(level - 3) * 8, 30)",
        des = "消耗活力制作【宝石转化符】，用于转化宝石属性",
        effect_lv = 1,
        exchange_silver = "",
        icon = "5303",
        id = 4107,
        init_lv = 0,
        item = {{["id"] = 11182, ["level"] = 48}},
        make_item = {},
        makedes = "当前制作的转化符最高",
        makeitemdes = "",
        max_lv = 10,
        name = "转化符",
        nextlv_effect = {},
        score = "0",
        skill_effect = {},
        sort = 7,
        type = 4,
        up_cost_type = {1, 2},
    },

    [4120] = {
        cost_energy = "50",
        des = "消耗活力兑换舞会邀请函",
        effect_lv = 0,
        exchange_silver = "",
        icon = "10031",
        id = 4120,
        init_lv = 0,
        item = {},
        make_item = {},
        makedes = "消耗活力兑换舞会邀请函",
        makeitemdes = "",
        max_lv = 0,
        name = "舞会邀请函",
        nextlv_effect = {},
        score = "0",
        skill_effect = {},
        sort = 0,
        type = 3,
        up_cost_type = {1, 2},
    },

    [4121] = {
        cost_energy = "50",
        des = "打工兑换银币",
        effect_lv = 0,
        exchange_silver = "(SLV*35)+25000",
        icon = "10003",
        id = 4121,
        init_lv = 0,
        item = {},
        make_item = {},
        makedes = "消耗活力兑换银币",
        makeitemdes = "",
        max_lv = 0,
        name = "打工",
        nextlv_effect = {},
        score = "0",
        skill_effect = {},
        sort = 8,
        type = 3,
        up_cost_type = {1, 2},
    },

}
