-- ./excel/task/runring/task_runring.xlsx
return {

    [63001] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {"DI63001"},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "替{grantnpc}看望下{submitnpc}",
        donePlots = {},
        goalDesc = "去探望下{submitnpc}",
        id = 63001,
        initConfig = {"$RTarget12", "$ETarget63001"},
        missiondone = {"$NextRing"},
        name = "寻人",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 1,
        timeout = 0,
        tips = 0,
        type = 14,
    },

    [63002] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {"DI63002"},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "{submitnpc}丢失了{item}，你去找一个给他吧！",
        donePlots = {},
        goalDesc = "帮{submitnpc}找{item}{C.bag_counting}",
        id = 63002,
        initConfig = {"$RTarget13", "$ETarget63002", "$RTargetItem", "$InitLegend63005"},
        missiondone = {"$NextRing"},
        name = "寻物",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 2,
        timeout = 0,
        tips = 0,
        type = 14,
    },

    [63003] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {"DI63003"},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "听说{submitnpc}正需要一个{summon}作为帮手，你去送一个给他吧！",
        donePlots = {},
        goalDesc = "给{submitnpc}送一个{summon}{C.bag_counting}",
        id = 63003,
        initConfig = {"$RTarget14", "$ETarget63003", "$RTargetSumm"},
        missiondone = {"$NextRing"},
        name = "寻宠",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 3,
        timeout = 0,
        tips = 0,
        type = 14,
    },

    [63004] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {"DI63004"},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "{submitnpc}自恃武功高强，从来不把别人放在眼里，你去切磋一下，让他知道山外有山。",
        donePlots = {},
        goalDesc = "去教训下{submitnpc}",
        id = 63004,
        initConfig = {"$RTarget15", "$ETarget63004", "$SetTargetFight"},
        missiondone = {"$NextRing"},
        name = "战斗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 14,
    },

}
