-- ./excel/reward/welfare.xlsx
return {

    [1001] = {
        exp = "0",
        gold = "8888",
        goldcoin = "188",
        id = 1001,
        item = {1001, 1002, 1003},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "500000",
        summexp = "0",
        summon = {2028},
    },

    [1002] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 1002,
        item = {},
        partner = "10005",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [1003] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 1003,
        item = {4002, 4001, 4003, 4004, 4005},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [1004] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 1004,
        item = {3011, 1010, 1011, 1012},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "600000",
        summexp = "0",
        summon = {},
    },

    [1005] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 1005,
        item = {1009},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [1006] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 1006,
        item = {1013, 1015, 1016, 1017},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "800000",
        summexp = "0",
        summon = {},
    },

    [1007] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 1007,
        item = {1014},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [2001] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 2001,
        item = {2001, 2002},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [2002] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 2002,
        item = {2005, 2006},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [2003] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 2003,
        item = {2009, 2010, 2011},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [2004] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 2004,
        item = {2013, 2014, 2015},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [2005] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 2005,
        item = {2017, 2018, 2019},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [2006] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 2006,
        item = {2021, 2022, 2023},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [2007] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 2007,
        item = {2025, 2027},
        partner = "",
        partnerexp = "0",
        ride = "1005",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [2008] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 2008,
        item = {2029, 2030, 2031},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [2009] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 2009,
        item = {2033, 2034, 2035},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [3001] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 3001,
        item = {3001, 3010},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [3002] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 3002,
        item = {3012},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {2029},
    },

    [3003] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 3003,
        item = {},
        partner = "10007",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [3004] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 3004,
        item = {3002, 3003},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [3005] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 3005,
        item = {3004, 3005},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [3006] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 3006,
        item = {3006, 3007},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [3007] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 3007,
        item = {},
        partner = "",
        partnerexp = "0",
        ride = "1007",
        silver = "0",
        summexp = "0",
        summon = {},
    },

    [3008] = {
        exp = "0",
        gold = "0",
        goldcoin = "0",
        id = 3008,
        item = {3008, 3009},
        partner = "",
        partnerexp = "0",
        ride = "",
        silver = "0",
        summexp = "0",
        summon = {},
    },

}
