-- ./excel/reward/yibao.xlsx
return {

    [1001] = {
        compen_cultivateexp = "5",
        compen_exp = "0",
        cultivateexp = "100*(1+star*0.5)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "1",
        id = 1001,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1002] = {
        compen_cultivateexp = "50",
        compen_exp = "0",
        cultivateexp = "100",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1002,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1003] = {
        compen_cultivateexp = "50",
        compen_exp = "0",
        cultivateexp = "100",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1003,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1004] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1004,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1005] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1005,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1006] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1006,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1007] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1007,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1008] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1008,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1009] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1009,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1010] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1010,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1011] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1011,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1012] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1012,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1104] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1104,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [1105] = {
        compen_cultivateexp = "math.max(stallprice/20000*20*1.5,10)*0.1",
        compen_exp = "0",
        cultivateexp = "math.max(stallprice/20000*20*1.5,10)",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "2",
        id = 1105,
        item = {0},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

    [2001] = {
        compen_cultivateexp = "0",
        compen_exp = "0",
        cultivateexp = "0",
        exp = "0",
        gold = "0",
        help_exp = "0",
        help_org_offer = "0",
        id = 2001,
        item = {1001},
        partnerexp = "0",
        silver = "0",
        summexp = "0",
    },

}
