-- 需要统计的类型 如果是物品直接用物品id
COLUMNS_TYPE = {
    ["name"] = "统计名称",
    ["totalCnt"] = "次数",
    ["playerCnt"] = "人数",
    ["avgCnt"] = "人均次数",
    ["silverCnt"] = "消耗银币",
    ["goldCnt"] = "消耗金币",
    ["amtCnt"] = "消耗元宝",
    ["c10004"] = "消耗洗髓丹",
    ["c10005"] = "消耗轮回丹",
    ["c10007"] = "消耗仙灵丹",
    ["c10008"] = "消耗炼体丹",
    ["c10033"] = "消耗经验丹",
    ["c10038"] = "消耗长寿丹",
    ["c10047"] = "消耗糖酥鲤鱼",
    ["c10036"] = "消耗返元丹",
    ["c10037"] = "消耗归原丹",
    ["c10031"] = "消耗洗点丹",
    ["c10032"] = "消耗技能石",
    ["c10034"] = "消耗资质丹",
    ["c30661"] = "消耗初级辟谷丹",
    ["c30662"] = "消耗中级辟谷丹",
    ["c30663"] = "消耗高级辟谷丹",
    ["c30663"] = "消耗高级辟谷丹",
    ["c30664"] = "消耗突破石",
    ["c30665"] = "消耗突破精华",
    ["c30660"] = "消耗进阶石",
    ["c30600"] = "许仙信物",
    ["c30601"] = "璃镜信物",
    ["c30602"] = "洛凝霜信物",
    ["c30603"] = "渊记信物",
    ["c30604"] = "白素贞信物",
    ["c30605"] = "小青信物",
    ["c30606"] = "法海信物",
    ["c30607"] = "道济信物",
    ["c30608"] = "龙吉公主信物",
    ["c30609"] = "九天玄女信物",
    ["c30610"] = "时未寒信物",
    ["c30611"] = "昊离归信物",
    ["c1020"] = "消耗技能点",
    ["c11092"] = "白色强化石",
    ["c11093"] = "绿色强化石",
    ["c11094"] = "蓝色强化石",
    ["c11095"] = "紫色强化石",
    ["c11096"] = "橙色强化石",
    ["c11097"] = "洗炼石",
    ["r1001"] = "金币",
    ["r1002"] = "银币",
    ["r1003"] = "元宝",
    ["r1009"] = "竞技场积分",
    ["r100"] = "总活跃点",
    ["a100"] = "人均活跃点",
    ["r10001"] = "银袋子",
    ["r10007"] = "仙灵丹",
    ["r10008"] = "炼体丹",
    ["r11090"] = "阵法碎片",
    ["r11092"] = "白色强化石",
    ["r11093"] = "绿色强化石",
    ["r11094"] = "蓝色强化石",
    ["r11095"] = "紫色强化石",
    ["r11096"] = "橙色强化石",
    ["r11143"] = "境界丹",
    ["r10031"] = "重生丹",
    ["r10032"] = "龙血秘藏",
    ["r10033"] = "龙虎金丹",
    ["r10034"] = "紫韵龙王参",
    ["r10035"] = "龙魂秘宝",
    ["r10036"] = "返元丹",
    ["r10037"] = "归原丹",
    ["r10038"] = "长寿丹",
    ["r11076"] = "藏宝图",
    ["r11077"] = "寻龙令",
    ["r11078"] = "摸金符",
    ["r11079"] = "阴阳秘术",
    ["r11080"] = "风水罗盘",
    
}

-- 统计的对应的名称
BEHAVIOR_NAME = {
    ["player_wash_point"] = "角色洗点",
    ["player_all_wash"] = "角色全部洗点",
    ["learn_school_active"] = "学习门派主动",
    ["reset_school_active"] = "重置门派主动",
    ["learn_school_passive"] = "学习门派被动",
    ["fast_school_passive"] = "快速学习被动",
    ["sliver_learn_cultivate"] = "银币修炼",
    ["item_learn_cultivate"] = "丹药修炼",
    ["equip_make"] = "装备打造",
    ["equip_strength"] = "装备强化",
    ["equip_wash"] = "装备洗练",
    ["equip_fuhun"] = "装备附魂",
    ["summon_upgrade"] = "宠物升级",
    ["summon_life"] = "宠物寿命",
    ["reset_summon_point"] = "重置潜力",
    ["reset_summon_all_point"] = "重置全部潜力",
    ["summon_wash"] = "洗点",
    ["summon_combine"] = "合成",
    ["summon_skill_upgrade"] = "技能升级",
    ["summon_skill_learn"] = "技能学习",
    ["summon_aptitude"] = "升级资质",
    ["partner_upgrade"] = "升级",
    ["partner_upper"] = "突破",
    ["partner_quality1"] = "1阶",
    ["partner_quality2"] = "2阶",
    ["partner_quality3"] = "3阶",
    ["partner_quality4"] = "4阶",
    ["partner_quality5"] = "5阶",
    ["partner_fmt1"] = "无阵",
    ["partner_fmt2"] = "天极阵",
    ["partner_fmt3"] = "地覆阵",
    ["partner_fmt4"] = "风吼阵",
    ["partner_fmt5"] = "云迷阵",
    ["partner_fmt6"] = "水灵阵",
    ["partner_fmt7"] = "火绝阵",
    ["partner_fmt8"] = "山崩阵",
    ["partner_fmt9"] = "雷暴阵",
    ["item_extend_size"] = "开背包格子",
    ["buy_ware_house"] = "开仓库",
    ["stall_refresh"] = "摆摊刷新",
    ["stall_upsize"] = "摆摊扩充",
    ["sys_jjc"] = "竞技场",
    ["task_shimen"] = "门派修行",
    ["task_ghost"] = "抓鬼任务",
    ["task_xunbao"] = "寻宝任务",
    ["task_yibao"] = "异宝收集",
    ["hd_fengyao"] = "封妖",
    ["hd_yaowang"] = "妖王",
    ["hd_tianmo"] = "天魔",
    ["fuben"] = "副本",
    ["signin"] = "每日签到",
    ["world_chat"] = "世界聊天",
    ["team_chat"] = "组队聊天",
    ["org_chat"] = "帮派聊天",
}

-- 系统行为分析
BEHAVIOR_MAP = {
    [1] = {["title"] = "角色系统",
           ["subtype"] = {"player_wash_point", "player_all_wash"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c10004", "c10005"}, 
          },
    [2] = {["title"] = "门派主动",
           ["subtype"] = {"learn_school_active", "reset_school_active"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "silverCnt", "c1020"}, 
          },
    [3] = {["title"] = "门派被动",
           ["subtype"] = {"learn_school_passive", "fast_school_passive"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "silverCnt"}, 
          },          
    [4] = {["title"] = "修炼技能",
           ["subtype"] = {"sliver_learn_cultivate", "item_learn_cultivate"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "silverCnt", "c10007", "c10008"}, 
          },                    
    [5] = {["title"] = "背包系统",
           ["subtype"] = {"item_extend_size", "buy_ware_house"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "silverCnt"}, 
          },
    [6] = {["title"] = "交易系统",
           ["subtype"] = {"stall_refresh", "stall_upsize"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "goldCnt", "amtCnt"}, 
          },                               
    [7] = {["title"] = "每日签到",
           ["subtype"] = {"signin"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt"}, 
          },                                      
    [8] = {["title"] = "聊天系统",
           ["subtype"] = {"world_chat", "team_chat", "org_chat"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt"}, 
          },                                              
    [15] = {["title"] = "装备打造",
           ["subtype"] = {"equip_make"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "silverCnt"}, 
          },
    [16] = {["title"] = "装备强化",
           ["subtype"] = {"equip_strength"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "silverCnt", "c11092", "c11093", "c11094", "c11095", "c11096"}, 
          },
    [17] = {["title"] = "装备洗练",
           ["subtype"] = {"equip_wash"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "silverCnt", "c11097"}, 
          },                                 
    [18] = {["title"] = "装备附魂",
           ["subtype"] = {"equip_fuhun"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt"}, 
          },
    [21] = {["title"] = "宠物升级",
           ["subtype"] = {"summon_upgrade"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c10033"}, 
          },          
    [22] = {["title"] = "宠物寿命",
           ["subtype"] = {"summon_life"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c10038", "c10047"}, 
          },          
    [23] = {["title"] = "宠物潜力",
           ["subtype"] = {"reset_summon_point", "reset_summon_all_point"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c10036", "c10037"}, 
          },             
    [24] = {["title"] = "宠物洗点",
           ["subtype"] = {"summon_wash"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c10031"}, 
          },             
    [25] = {["title"] = "宠物合成",
           ["subtype"] = {"summon_combine"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt"}, 
          },             
    [26] = {["title"] = "宠物技能",
           ["subtype"] = {"summon_skill_upgrade", "summon_skill_learn"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c10032"}, 
          },             
    [27] = {["title"] = "宠物培养",
           ["subtype"] = {"summon_aptitude"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c10034"}, 
          },       
    [31] = {["title"] = "伙伴升级",
           ["subtype"] = {"partner_upgrade"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c30661", "c30662", "c30663"}, 
          },
    [32] = {["title"] = "伙伴突破",
           ["subtype"] = {"partner_upper"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c30664", "c30665"}, 
          },
    [33] = {["title"] = "伙伴进阶",
           ["subtype"] = {"partner_quality1", "partner_quality2", "partner_quality3", "partner_quality4", "partner_quality5"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "c30660", "c30601", "c30602", "c30603", "c30604", 
                          "c30605", "c30606", "c30607", "c30608", "c30609", "c30610", "c30611"}, 
          },
    [34] = {["title"] = "阵法",
           ["subtype"] = {"partner_fmt1", "partner_fmt2", "partner_fmt3", "partner_fmt4", "partner_fmt5",
                          "partner_fmt6", "partner_fmt7", "partner_fmt8", "partner_fmt9"},
           ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt"}, 
          },

}

EQUIP_MAKE_ITEM = {
                    {12600, 12608},
                    {12620, 12628},
                    {12640, 12648},
                    {12660, 12668},
                    {12680, 12688},
                    {12700, 12708},
                    {12720, 12728},
                    {12740, 12748},
                    {12760, 12768},
                    {12780, 12788},
                    {12800, 12808},
                    {12820, 12828},
                    {12840, 12848}
                  }

-- 游戏玩法分析
GAME_SYS_MAP = {
    ["title"] = "玩法分析",
    ["subtype"] = {"sys_jjc", "task_shimen", "task_ghost", "task_yibao",
                   "hd_fengyao", "hd_tianmo", "fuben"
                  },
    ["columns"] = {"name", "totalCnt", "playerCnt", "avgCnt", "r100", "r1001", "r1002", "r1009", "r10001", "r10007", 
                   "r10008", "r11090", "r11092", "r11093", "r11094", "r11095", "r11096", "r11143", "r10031", "r10032" , 
                   "r10033", "r10034", "r10035", "r10036", "r10037", "r10038", "r11076", "r11077", "r11078", "r11079", "r11080"}, 
}
