-- ./excel/huodong/luanshimoying/npc.xlsx
return {

    [1001] = {
        diglogface = 0,
        event = 1001,
        figureid = 61012,
        grade = 0,
        id = 1001,
        mapid = 0,
        name = "魔帝幻象",
        nameType = 2,
        rotateY = 0.0,
        title = "",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1002] = {
        diglogface = 0,
        event = 1001,
        figureid = 61042,
        grade = 0,
        id = 1002,
        mapid = 0,
        name = "南方鬼帝",
        nameType = 2,
        rotateY = 0.0,
        title = "",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1003] = {
        diglogface = 0,
        event = 1001,
        figureid = 61052,
        grade = 0,
        id = 1003,
        mapid = 0,
        name = "法海魔相",
        nameType = 2,
        rotateY = 0.0,
        title = "",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1004] = {
        diglogface = 0,
        event = 1001,
        figureid = 61022,
        grade = 0,
        id = 1004,
        mapid = 0,
        name = "金钹法王",
        nameType = 2,
        rotateY = 0.0,
        title = "",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [2001] = {
        diglogface = 0,
        event = 2001,
        figureid = 8236,
        grade = 0,
        id = 2001,
        mapid = 0,
        name = "宝箱",
        nameType = 1,
        rotateY = 0.0,
        title = "",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

}
