-- ./excel/task/tasktype.xlsx
return {

    [1] = {
        appenddes = "单人",
        desc = "",
        dropable = 1,
        grade_limit = 0,
        id = 1,
        name = "测试",
        npcid = 0,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [2] = {
        appenddes = "单人",
        desc = "",
        dropable = 0,
        grade_limit = 0,
        id = 2,
        name = "主线",
        npcid = 0,
        showinfo = 1,
        teamsize_condi = "teamsize==0",
    },

    [3] = {
        appenddes = "单人",
        desc = "",
        dropable = 0,
        grade_limit = 0,
        id = 3,
        name = "支线",
        npcid = 0,
        showinfo = 1,
        teamsize_condi = "teamsize==0",
    },

    [4] = {
        appenddes = "单人",
        desc = "师傅似乎有事找你，快回门派看看吧~",
        dropable = 0,
        grade_limit = 0,
        id = 4,
        name = "门派",
        npcid = 1,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [5] = {
        appenddes = "三人以上组队",
        desc = "妖魔作乱，判官实在忙不过来，正在寻求各路英豪的帮助，快去一展身手吧！",
        dropable = 1,
        grade_limit = 25,
        id = 5,
        name = "伏魔",
        npcid = 5234,
        showinfo = 0,
        teamsize_condi = "teamsize>=3",
    },

    [6] = {
        appenddes = "单人",
        desc = "",
        dropable = 0,
        grade_limit = 40,
        id = 6,
        name = "异宝",
        npcid = 0,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [7] = {
        appenddes = "三人以上组队",
        desc = "",
        dropable = 0,
        grade_limit = 0,
        id = 7,
        name = "侠影副本",
        npcid = 0,
        showinfo = 0,
        teamsize_condi = "teamsize>=3",
    },

    [8] = {
        appenddes = "三人以上组队",
        desc = "",
        dropable = 1,
        grade_limit = 40,
        id = 8,
        name = "门派试炼",
        npcid = 1,
        showinfo = 0,
        teamsize_condi = "teamsize>=3",
    },

    [9] = {
        appenddes = "单人",
        desc = "",
        dropable = 1,
        grade_limit = 40,
        id = 9,
        name = "帮派内政",
        npcid = 0,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [10] = {
        appenddes = "异性两人组队",
        desc = "",
        dropable = 1,
        grade_limit = 15,
        id = 10,
        name = "灵犀",
        npcid = 5229,
        showinfo = 0,
        teamsize_condi = "teamsize==2",
    },

    [11] = {
        appenddes = "单人",
        desc = "",
        dropable = 1,
        grade_limit = 0,
        id = 11,
        name = "火眼金睛",
        npcid = 5284,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [12] = {
        appenddes = "三人以上组队",
        desc = "",
        dropable = 1,
        grade_limit = 50,
        id = 12,
        name = "六道传说",
        npcid = 0,
        showinfo = 0,
        teamsize_condi = "teamsize>=3",
    },

    [13] = {
        appenddes = "单人",
        desc = "",
        dropable = 0,
        grade_limit = 0,
        id = 13,
        name = "引导任务",
        npcid = 0,
        showinfo = 1,
        teamsize_condi = "teamsize==0",
    },

    [14] = {
        appenddes = "单人",
        desc = "",
        dropable = 0,
        grade_limit = 0,
        id = 14,
        name = "历练",
        npcid = 5278,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [15] = {
        appenddes = "单人",
        desc = "击败盗宝贼，夺回藏宝图。",
        dropable = 0,
        grade_limit = 0,
        id = 15,
        name = "摸金寻龙",
        npcid = 5227,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [16] = {
        appenddes = "单人",
        desc = "悬赏任务",
        dropable = 1,
        grade_limit = 0,
        id = 16,
        name = "悬赏任务",
        npcid = 5201,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [17] = {
        appenddes = "单人",
        desc = "镇魔塔",
        dropable = 1,
        grade_limit = 0,
        id = 17,
        name = "镇魔塔",
        npcid = 5296,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [18] = {
        appenddes = "单人",
        desc = "天问仙人携题目下凡寻找有缘人，参与答题可获丰厚奖励",
        dropable = 1,
        grade_limit = 20,
        id = 18,
        name = "天问答题",
        npcid = 5304,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

    [19] = {
        appenddes = "单人",
        desc = "秘宝护送",
        dropable = 1,
        grade_limit = 40,
        id = 19,
        name = "秘宝护送",
        npcid = 0,
        showinfo = 0,
        teamsize_condi = "teamsize==0",
    },

}
