-- ./excel/task/taskitem.xlsx
return {

    [1001] = {
        countTime = -1,
        description = "测试任务使用物品",
        effect = "",
        finishTip = "使用完成",
        icon = 10001,
        id = 1001,
        name = "测试",
        qteid = 0,
        useTime = 3,
        usedTip = "使用中",
    },

    [1002] = {
        countTime = -1,
        description = "测试任务使用物品",
        effect = "",
        finishTip = "使用完成",
        icon = 10001,
        id = 1002,
        name = "测试",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [1003] = {
        countTime = -1,
        description = "测试任务使用物品",
        effect = "",
        finishTip = "使用完成",
        icon = 10001,
        id = 1003,
        name = "测试",
        qteid = 0,
        useTime = 1,
        usedTip = "使用中",
    },

    [10046] = {
        countTime = -1,
        description = "具有神秘力量的符纸",
        effect = "",
        finishTip = "使用完成",
        icon = 13301,
        id = 10046,
        name = "符篆",
        qteid = 1,
        useTime = 2,
        usedTip = "使用中",
    },

    [10047] = {
        countTime = -1,
        description = "回溯时光，玄天宝镜",
        effect = "",
        finishTip = "使用完成",
        icon = 10039,
        id = 10047,
        name = "溯光宝镜",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10048] = {
        countTime = -1,
        description = "蛛丝现形，马迹露踪",
        effect = "",
        finishTip = "使用完成",
        icon = 10022,
        id = 10048,
        name = "查探符",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10049] = {
        countTime = -1,
        description = "轻烟搜魂，苍天明示",
        effect = "",
        finishTip = "使用完成",
        icon = 10036,
        id = 10049,
        name = "搜魂香",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10050] = {
        countTime = -1,
        description = "九天十地，无限神魔",
        effect = "",
        finishTip = "使用完成",
        icon = 10031,
        id = 10050,
        name = "魔族画卷",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10051] = {
        countTime = -1,
        description = "万法空幻，一石破之",
        effect = "",
        finishTip = "使用完成",
        icon = 10084,
        id = 10051,
        name = "破幻石",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10052] = {
        countTime = -1,
        description = "喜怒哀愁，尽皆遗忘",
        effect = "ui_eff_0053",
        finishTip = "使用完成",
        icon = 10129,
        id = 10052,
        name = "忘忧水",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10053] = {
        countTime = -1,
        description = "天地无极，破！",
        effect = "",
        finishTip = "使用完成",
        icon = 10023,
        id = 10053,
        name = "破界石",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10054] = {
        countTime = -1,
        description = "世间神木不过一刨而已",
        effect = "",
        finishTip = "使用完成",
        icon = 10267,
        id = 10054,
        name = "木刨",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10055] = {
        countTime = -1,
        description = "铃~仔细听，这铃声可以将你引向黄泉",
        effect = "",
        finishTip = "使用完成",
        icon = 10141,
        id = 10055,
        name = "魔铃",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10056] = {
        countTime = -1,
        description = "千年白，百年青，青白双剑斩阴魔",
        effect = "",
        finishTip = "使用完成",
        icon = 10115,
        id = 10056,
        name = "青白双剑",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10057] = {
        countTime = -1,
        description = "随身的小玩意，用来标记地形",
        effect = "",
        finishTip = "使用完成",
        icon = 10038,
        id = 10057,
        name = "地形标记",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10058] = {
        countTime = -1,
        description = "三生三世，缘深缘浅",
        effect = "",
        finishTip = "感应到张秀才前世与白素贞有关联",
        icon = 10026,
        id = 10058,
        name = "三生石",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10059] = {
        countTime = -1,
        description = "阴阳相隔，此物可通",
        effect = "",
        finishTip = "使用完成",
        icon = 10025,
        id = 10059,
        name = "阴阳石",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10060] = {
        countTime = -1,
        description = "三生三世，缘深缘浅",
        effect = "",
        finishTip = "感应到丫丫前世与白素贞有关联",
        icon = 10026,
        id = 10060,
        name = "三生石",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10061] = {
        countTime = -1,
        description = "三生三世，缘深缘浅",
        effect = "",
        finishTip = "感应到赵铁匠前世与白素贞有关联",
        icon = 10026,
        id = 10061,
        name = "三生石",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10062] = {
        countTime = -1,
        description = "三生三世，缘深缘浅",
        effect = "",
        finishTip = "感应到许仙前世与白素贞有关联",
        icon = 10026,
        id = 10062,
        name = "三生石",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10063] = {
        countTime = 5,
        description = "仙粮丸",
        effect = "",
        finishTip = "喂食完成",
        icon = 10011,
        id = 10063,
        name = "仙粮丸",
        qteid = 0,
        useTime = 2,
        usedTip = "喂食中",
    },

    [10064] = {
        countTime = 5,
        description = "道祖传信",
        effect = "",
        finishTip = "阅读完毕",
        icon = 10030,
        id = 10064,
        name = "道祖传信",
        qteid = 0,
        useTime = 2,
        usedTip = "阅读中",
    },

    [10065] = {
        countTime = 5,
        description = "萤火虫包",
        effect = "ui_eff_0052",
        finishTip = "萤火虫漫天飞舞！",
        icon = 10057,
        id = 10065,
        name = "萤火虫包",
        qteid = 0,
        useTime = 2,
        usedTip = "放飞萤火虫",
    },

    [10066] = {
        countTime = 5,
        description = "回魂草",
        effect = "",
        finishTip = "喂食完毕",
        icon = 10132,
        id = 10066,
        name = "回魂草",
        qteid = 0,
        useTime = 2,
        usedTip = "喂食中",
    },

    [10067] = {
        countTime = 5,
        description = "蝶香石",
        effect = "ui_eff_0053",
        finishTip = "蝴蝶漫天飞舞！",
        icon = 10088,
        id = 10067,
        name = "蝶香石",
        qteid = 0,
        useTime = 2,
        usedTip = "等待中",
    },

    [10068] = {
        countTime = 5,
        description = "阳石粉",
        effect = "",
        finishTip = "喂食完毕",
        icon = 10054,
        id = 10068,
        name = "阳石粉",
        qteid = 0,
        useTime = 2,
        usedTip = "喂食中",
    },

    [10069] = {
        countTime = 5,
        description = "护身符",
        effect = "",
        finishTip = "符咒化为一道光融入体内！",
        icon = 10054,
        id = 10069,
        name = "护身符",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10070] = {
        countTime = 5,
        description = "画心传情",
        effect = "ui_eff_0056",
        finishTip = "一缕幽魂寄托情思！",
        icon = 10054,
        id = 10070,
        name = "画心传情",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10071] = {
        countTime = -1,
        description = "情花种子",
        effect = "",
        finishTip = "使用完成",
        icon = 10132,
        id = 10071,
        name = "情花种子",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10072] = {
        countTime = -1,
        description = "情花",
        effect = "",
        finishTip = "使用完成",
        icon = 10235,
        id = 10072,
        name = "情花",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10073] = {
        countTime = -1,
        description = "承载白素贞所有的爱意与歉意",
        effect = "",
        finishTip = "礼轻情意重，愿许仙早日康复",
        icon = 10008,
        id = 10073,
        name = "礼物",
        qteid = 0,
        useTime = 2,
        usedTip = "轻轻放下",
    },

    [10074] = {
        countTime = -1,
        description = "文火慢煎，三碗煎一碗",
        effect = "",
        finishTip = "药香四逸",
        icon = 10155,
        id = 10074,
        name = "熬药",
        qteid = 0,
        useTime = 2,
        usedTip = "煎药中",
    },

    [10075] = {
        countTime = -1,
        description = "瑶池仙草，起死回生",
        effect = "",
        finishTip = "研磨完毕",
        icon = 10035,
        id = 10075,
        name = "研药",
        qteid = 0,
        useTime = 2,
        usedTip = "细细研磨",
    },

    [10076] = {
        countTime = 5,
        description = "永结同心好，共成连理枝",
        effect = "ui_eff_0056",
        finishTip = "妾心似君心，岁岁长相依",
        icon = 10161,
        id = 10076,
        name = "同心结",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10077] = {
        countTime = 5,
        description = "是真是假，来摸一把",
        effect = "ui_eff_0052",
        finishTip = "真言石发出淡淡的光芒",
        icon = 10197,
        id = 10077,
        name = "真言石",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10078] = {
        countTime = -1,
        description = "没有钱是万万不能的",
        effect = "",
        finishTip = "使用完成",
        icon = 10001,
        id = 10078,
        name = "媒金",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10079] = {
        countTime = -1,
        description = "神鬼相通，可见阴阳",
        effect = "",
        finishTip = "本月十五，月老牵线，宜嫁娶",
        icon = 10263,
        id = 10079,
        name = "黄历",
        qteid = 0,
        useTime = 2,
        usedTip = "翻看中",
    },

    [10080] = {
        countTime = -1,
        description = "拜帖",
        effect = "",
        finishTip = "不才许仙求见山长！",
        icon = 10030,
        id = 10080,
        name = "拜帖",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10081] = {
        countTime = -1,
        description = "品茶",
        effect = "",
        finishTip = "清香丝滑，不过不够爽口。",
        icon = 10135,
        id = 10081,
        name = "品茶",
        qteid = 0,
        useTime = 2,
        usedTip = "喝茶中",
    },

    [10082] = {
        countTime = -1,
        description = "迷烟",
        effect = "",
        finishTip = "奇怪的香味，头好像有点晕",
        icon = 10016,
        id = 10082,
        name = "迷烟",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10083] = {
        countTime = -1,
        description = "指纹是唯一的",
        effect = "",
        finishTip = "指纹不一致！",
        icon = 10147,
        id = 10083,
        name = "指纹",
        qteid = 0,
        useTime = 2,
        usedTip = "对比中",
    },

    [10084] = {
        countTime = -1,
        description = "忘情绝恋",
        effect = "",
        finishTip = "好像忘了什么。",
        icon = 10129,
        id = 10084,
        name = "忘情水",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [10085] = {
        countTime = -1,
        description = "静心经神。",
        effect = "",
        finishTip = "终于抄完了，感觉手快断了",
        icon = 10030,
        id = 10085,
        name = "经书",
        qteid = 0,
        useTime = 3,
        usedTip = "抄写中",
    },

    [10086] = {
        countTime = -1,
        description = "酒壮怂人胆。",
        effect = "",
        finishTip = "好像没那么害怕了！",
        icon = 10162,
        id = 10086,
        name = "喝酒",
        qteid = 0,
        useTime = 2,
        usedTip = "喝酒中",
    },

    [10087] = {
        countTime = -1,
        description = "一缕幽魂化白骨，兰若古槐谁怜生。",
        effect = "",
        finishTip = "挖掘完成",
        icon = 10159,
        id = 10087,
        name = "尸骨",
        qteid = 0,
        useTime = 2,
        usedTip = "挖掘中",
    },

    [10088] = {
        countTime = 5,
        description = "安葬",
        effect = "ui_eff_0052",
        finishTip = "入土为满",
        icon = 10321,
        id = 10088,
        name = "安葬",
        qteid = 0,
        useTime = 2,
        usedTip = "安葬中",
    },

    [10089] = {
        countTime = 5,
        description = "施展媚术",
        effect = "ui_eff_0053",
        finishTip = "施法完成！",
        icon = 10010,
        id = 10089,
        name = "媚术",
        qteid = 0,
        useTime = 2,
        usedTip = "施法中",
    },

    [20001] = {
        countTime = -1,
        description = "灵韵天成，万物破法",
        effect = "",
        finishTip = "使用完成",
        icon = 10129,
        id = 20001,
        name = "玉灵花液",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [20002] = {
        countTime = -1,
        description = "天机难测，天命谁知",
        effect = "",
        finishTip = "使用完成",
        icon = 10138,
        id = 20002,
        name = "紫龙参须",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [20003] = {
        countTime = -1,
        description = "九重灵泉，万魔寂灭",
        effect = "",
        finishTip = "使用完成",
        icon = 10129,
        id = 20003,
        name = "银河水",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [20004] = {
        countTime = -1,
        description = "风鸣啸谷，轻音难觅",
        effect = "",
        finishTip = "使用完成",
        icon = 10129,
        id = 20004,
        name = "虚风瓶",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [20005] = {
        countTime = -1,
        description = "风鸣啸谷，轻音难觅",
        effect = "",
        finishTip = "使用完成",
        icon = 10129,
        id = 20005,
        name = "灵山圣水",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [20006] = {
        countTime = -1,
        description = "回溯时光，玄天宝镜",
        effect = "",
        finishTip = "使用完成",
        icon = 10039,
        id = 20006,
        name = "溯光宝镜",
        qteid = 0,
        useTime = 2,
        usedTip = "讲诉经过",
    },

    [20007] = {
        countTime = -1,
        description = "等待",
        effect = "ui_eff_0052",
        finishTip = "哇，一群萤火虫飞过~",
        icon = 10088,
        id = 20007,
        name = "等待",
        qteid = 0,
        useTime = 3,
        usedTip = "等待中",
    },

    [20008] = {
        countTime = -2,
        description = "隔空传话，无视阻碍",
        effect = "",
        finishTip = "传音完成",
        icon = 10028,
        id = 20008,
        name = "千里传音",
        qteid = 0,
        useTime = 2,
        usedTip = "传音中",
    },

    [20009] = {
        countTime = -1,
        description = "回溯时光，玄天宝镜",
        effect = "",
        finishTip = "使用完成",
        icon = 10039,
        id = 20009,
        name = "溯光宝镜",
        qteid = 0,
        useTime = 2,
        usedTip = "打开洪荒大门",
    },

    [20010] = {
        countTime = -1,
        description = "锦囊妙计",
        effect = "",
        finishTip = "一只癞蛤蟆跳出来，上当了！",
        icon = 10057,
        id = 20010,
        name = "锦囊",
        qteid = 0,
        useTime = 2,
        usedTip = "打开锦囊",
    },

    [20011] = {
        countTime = -1,
        description = "偷得浮生半日闲",
        effect = "",
        finishTip = "煮好了",
        icon = 10142,
        id = 20011,
        name = "喝茶",
        qteid = 0,
        useTime = 2,
        usedTip = "煮茶中",
    },

    [20012] = {
        countTime = -1,
        description = "一壶清水",
        effect = "",
        finishTip = "感觉好多了！",
        icon = 10129,
        id = 20012,
        name = "喝水",
        qteid = 0,
        useTime = 2,
        usedTip = "喝水中",
    },

    [20013] = {
        countTime = -1,
        description = "混沌迷尘归于清源",
        effect = "",
        finishTip = "迷雾散开！",
        icon = 10203,
        id = 20013,
        name = "破阵石",
        qteid = 0,
        useTime = 2,
        usedTip = "使用中",
    },

    [20014] = {
        countTime = -1,
        description = "修复阵法",
        effect = "",
        finishTip = "展示抑制阵法",
        icon = 10129,
        id = 20014,
        name = "修复阵法",
        qteid = 0,
        useTime = 2,
        usedTip = "修复中",
    },

    [20015] = {
        countTime = -1,
        description = "道祖锦囊，关键时刻可以打开。",
        effect = "",
        finishTip = "杀掉笙月！",
        icon = 10057,
        id = 20015,
        name = "道祖锦囊",
        qteid = 0,
        useTime = 2,
        usedTip = "打开中",
    },

    [20016] = {
        countTime = -1,
        description = "仙力传承，移魂重生",
        effect = "ui_eff_0052",
        finishTip = "传承完成",
        icon = 10036,
        id = 20016,
        name = "桃园甘露",
        qteid = 0,
        useTime = 2,
        usedTip = "传承中",
    },

}
