-- ./excel/buff/buff.xlsx
return {

    [1] = {
        attr_ratio_list = {"mag_attack=10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damage_ratio=10"},
        buffEvent = "攻击开始",
        buffType = "",
        color = 0,
        desc = "",
        groupType = 1,
        icon = 0,
        id = 1,
        name = "测试",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [101] = {
        attr_ratio_list = {"mag_defense=-10", "phy_defense=-10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "受击动作",
        buffType = "",
        color = 1,
        desc = "物防、法防下降",
        groupType = 6,
        icon = 51104,
        id = 101,
        name = "狂剑诀",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [103] = {
        attr_ratio_list = {},
        attr_set = {"ghost=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "死亡5回合自动复活，不受异常状态影响",
        groupType = 1,
        icon = 51304,
        id = 103,
        name = "魂兮归来",
        trans = 2,
        type = 4,
        updateType = 2,
    },

    [105] = {
        attr_ratio_list = {},
        attr_set = {"command_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "受击动作",
        buffType = "",
        color = 0,
        desc = "休息",
        groupType = 2,
        icon = 51107,
        id = 105,
        name = "万剑归一",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [114] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "受击动作",
        buffType = "",
        color = 0,
        desc = "回复气血",
        groupType = 2,
        icon = 51202,
        id = 114,
        name = "九品莲台",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [111] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damaged_addratio=-(level*2+48)"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "受到伤害降低",
        groupType = 3,
        icon = 51206,
        id = 111,
        name = "不动明王",
        trans = 3,
        type = 1,
        updateType = 2,
    },

    [112] = {
        attr_ratio_list = {"phy_defense=-(10+level*1)"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物防下降",
        groupType = 2,
        icon = 51602,
        id = 112,
        name = "卸甲",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [113] = {
        attr_ratio_list = {},
        attr_set = {"mag_disable=1", "phy_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "封印",
        color = 0,
        desc = "封印普攻和技能",
        groupType = 2,
        icon = 51603,
        id = 113,
        name = "震慑",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [115] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"damage_ratio=-36+level"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "连击,伤害降低",
        groupType = 4,
        icon = 51605,
        id = 115,
        name = "战神",
        trans = 2,
        type = 1,
        updateType = 2,
    },

    [116] = {
        attr_ratio_list = {"phy_defense=-15", "mag_defense=-15"},
        attr_set = {"mag_disable=1", "phy_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "封印",
        color = 1,
        desc = "封印法术、降低双防",
        groupType = 3,
        icon = 51502,
        id = 116,
        name = "封灵咒",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [117] = {
        attr_ratio_list = {},
        attr_set = {"mag_disable=1", "phy_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "封印",
        color = 1,
        desc = "混乱",
        groupType = 4,
        icon = 51503,
        id = 117,
        name = "迷魂",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [119] = {
        attr_ratio_list = {},
        attr_set = {"phy_disable=1", "attack_disable=1", "mag_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "封印",
        color = 1,
        desc = "封印物法",
        groupType = 3,
        icon = 50033,
        id = 119,
        name = "封神咒",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [120] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"seal_ratio=-10"},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "封印命中降低",
        groupType = 5,
        icon = 50033,
        id = 120,
        name = "封神咒",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [121] = {
        attr_ratio_list = {},
        attr_set = {"phy_disable=1", "attack_disable=1", "mag_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "封印",
        color = 1,
        desc = "封印物法",
        groupType = 3,
        icon = 51507,
        id = 121,
        name = "禁断万古",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [122] = {
        attr_ratio_list = {},
        attr_set = {"command_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "休息",
        groupType = 4,
        icon = 50149,
        id = 122,
        name = "休息",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [123] = {
        attr_ratio_list = {},
        attr_set = {"aura_ratio=10"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "中毒",
        color = 1,
        desc = "中毒",
        groupType = 7,
        icon = 51403,
        id = 123,
        name = "木灵蚀心",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [124] = {
        attr_ratio_list = {"mag_attack=(level+24)", "phy_attack=(level+24)"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"cure_ratio=(level+94)"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "提高攻击和治疗",
        groupType = 5,
        icon = 51404,
        id = 124,
        name = "神威",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [125] = {
        attr_ratio_list = {"phy_defense=-(9+level*1)"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物防下降",
        groupType = 8,
        icon = 51405,
        id = 125,
        name = "天雷蚀甲",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [127] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "免疫死亡",
        groupType = 5,
        icon = 51407,
        id = 127,
        name = "天神法相",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [129] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"phy_defense=grade*1.5+5"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "物防上升",
        groupType = 70,
        icon = 51402,
        id = 129,
        name = "杏黄旗",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [130] = {
        attr_ratio_list = {},
        attr_set = {"stealth=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "隐身",
        groupType = 7,
        icon = 50150,
        id = 130,
        name = "遁法",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [131] = {
        attr_ratio_list = {},
        attr_set = {"ignore_stealth=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "发现隐形单位",
        groupType = 8,
        icon = 50004,
        id = 131,
        name = "天眼",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [132] = {
        attr_ratio_list = {},
        attr_set = {"stealth=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "隐身",
        groupType = 9,
        icon = 51106,
        id = 132,
        name = "剑遁",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [133] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物理攻击偏差",
        groupType = 6,
        icon = 51305,
        id = 133,
        name = "星灵禁锢",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [134] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damaged_addratio=20"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "受到伤害增加",
        groupType = 10,
        icon = 51103,
        id = 134,
        name = "斗剑",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [135] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "受到斗剑者的伤害提高",
        groupType = 11,
        icon = 51103,
        id = 135,
        name = "被斗剑",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [136] = {
        attr_ratio_list = {},
        attr_set = {"mp_add=level*50"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "回复法力",
        groupType = 7,
        icon = 51406,
        id = 136,
        name = "仙气灌顶",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [137] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "降低速度",
        groupType = 31,
        icon = 50020,
        id = 137,
        name = "降低速度",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [138] = {
        attr_ratio_list = {"mag_defense=-31+level", "phy_defense=-31+level"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物防、法防大量降低",
        groupType = 12,
        icon = 51207,
        id = 138,
        name = "佛法无边",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [139] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "抗药性",
        groupType = 13,
        icon = 50005,
        id = 139,
        name = "抗药性",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [140] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "",
        groupType = 14,
        icon = 50047,
        id = 140,
        name = "降低攻击",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [141] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "",
        groupType = 15,
        icon = 50021,
        id = 141,
        name = "提升攻击",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [142] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "",
        groupType = 16,
        icon = 50118,
        id = 142,
        name = "提升速度",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [143] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "",
        groupType = 17,
        icon = 50136,
        id = 143,
        name = "提升防御",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [144] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "中毒",
        color = 1,
        desc = "持续减少气血",
        groupType = 10,
        icon = 50131,
        id = 144,
        name = "中毒",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [145] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "",
        groupType = 18,
        icon = 50240,
        id = 145,
        name = "降低防御",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [146] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damage_addratio=1*level+5"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "攻击力上升",
        groupType = 8,
        icon = 50152,
        id = 146,
        name = "提升伤害",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [147] = {
        attr_ratio_list = {},
        attr_set = {"phy_disable=1", "attack_disable=1", "mag_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "封印",
        color = 1,
        desc = "昏睡,无法行动",
        groupType = 4,
        icon = 50149,
        id = 147,
        name = "昏睡",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [148] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "受击动作",
        buffType = "",
        color = 0,
        desc = "攻击该单位会受到伤害",
        groupType = 9,
        icon = 50139,
        id = 148,
        name = "剑棘",
        trans = 3,
        type = 1,
        updateType = 2,
    },

    [149] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "持续减少气血",
        groupType = 19,
        icon = 50131,
        id = 149,
        name = "蛇牙击",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [150] = {
        attr_ratio_list = {"phy_defense=-5-level", "mag_defense=-5-level"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物防、法防下降",
        groupType = 20,
        icon = 50051,
        id = 150,
        name = "蛇毒",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [151] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "中毒",
        color = 1,
        desc = "持续减少气血",
        groupType = 11,
        icon = 50251,
        id = 151,
        name = "灼烧",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [152] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "攻击该单位会受到伤害",
        groupType = 10,
        icon = 50241,
        id = 152,
        name = "炎盾",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [153] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "回合结束攻击一个目标",
        groupType = 21,
        icon = 50221,
        id = 153,
        name = "剑令",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [154] = {
        attr_ratio_list = {"phy_attack=level*4+20", "phy_defense=level*4+20"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "攻击防御上升",
        groupType = 22,
        icon = 51605,
        id = 154,
        name = "妖皇之怒",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [155] = {
        attr_ratio_list = {"phy_critical_ratio=level*4+10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "气血暴击上升",
        groupType = 23,
        icon = 51605,
        id = 155,
        name = "妖皇降临",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [156] = {
        attr_ratio_list = {"phy_critical_ratio=level*2"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "暴击上升",
        groupType = 11,
        icon = 50232,
        id = 156,
        name = "狂暴",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [158] = {
        attr_ratio_list = {"phy_defense=-12+level*2"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物防降低",
        groupType = 12,
        icon = 51104,
        id = 158,
        name = "狂剑诀",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [159] = {
        attr_ratio_list = {"phy_defense=-5-level", "mag_defense=-5-level"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物防、法防下降",
        groupType = 17,
        icon = 50020,
        id = 159,
        name = "剑破流云",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [160] = {
        attr_ratio_list = {"phy_defense=-15", "mag_defense=-15"},
        attr_set = {"mag_disable=1", "attack_disable=1", "phy_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "封印普攻和技能",
        groupType = 14,
        icon = 51502,
        id = 160,
        name = "封灵咒",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [161] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "中毒",
        color = 1,
        desc = "中毒",
        groupType = 7,
        icon = 50131,
        id = 161,
        name = "蜃气",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [162] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "持续恢复气血",
        groupType = 12,
        icon = 51203,
        id = 162,
        name = "我佛慈悲",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [163] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damage_ratio=level*1+5"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "伤害增加",
        groupType = 13,
        icon = 50232,
        id = 163,
        name = "嗜杀",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [164] = {
        attr_ratio_list = {"phy_attack=5"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "物攻增加",
        groupType = 1,
        icon = 50232,
        id = 164,
        name = "狂兽神术",
        trans = 1,
        type = 3,
        updateType = 2,
    },

    [165] = {
        attr_ratio_list = {"phy_attack=-10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物攻降低",
        groupType = 2,
        icon = 50127,
        id = 165,
        name = "回头是岸",
        trans = 1,
        type = 3,
        updateType = 2,
    },

    [166] = {
        attr_ratio_list = {},
        attr_set = {"stealth=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "隐身",
        groupType = 3,
        icon = 50146,
        id = 166,
        name = "隐遁",
        trans = 1,
        type = 3,
        updateType = 2,
    },

    [167] = {
        attr_ratio_list = {},
        attr_set = {"phy_disable=1", "attack_disable=1", "mag_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "封印",
        color = 1,
        desc = "封印普攻和技能",
        groupType = 3,
        icon = 51502,
        id = 167,
        name = "封灵咒",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [168] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "法攻降低",
        groupType = 16,
        icon = 50115,
        id = 168,
        name = "法力削弱",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [169] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"res_abnormal_buff_ratio=2+level*2"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "减益效果概率降低",
        groupType = 3,
        icon = 50245,
        id = 169,
        name = "剑魔",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [170] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "只能攻击攻击者",
        groupType = 24,
        icon = 51104,
        id = 170,
        name = "霸剑诀",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [171] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damaged_ratio=-10*floor"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "受到伤害大幅度降低",
        groupType = 25,
        icon = 50006,
        id = 171,
        name = "魔之气",
        trans = 2,
        type = 4,
        updateType = 2,
    },

    [172] = {
        attr_ratio_list = {"damaged_ratio=-70"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "受到伤害大幅度降低",
        groupType = 26,
        icon = 50026,
        id = 172,
        name = "天佛降世",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [173] = {
        attr_ratio_list = {},
        attr_set = {"ignore_attacked=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "无法被攻击",
        groupType = 27,
        icon = 50229,
        id = 173,
        name = "无敌",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [174] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damaged_ratio=100"},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "受到伤害大幅度增加",
        groupType = 28,
        icon = 50201,
        id = 174,
        name = "易伤",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [175] = {
        attr_ratio_list = {"phy_attack=10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加物攻",
        groupType = 1,
        icon = 50002,
        id = 175,
        name = "狂兽之术",
        trans = 1,
        type = 3,
        updateType = 2,
    },

    [176] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "感化点数显示",
        groupType = 29,
        icon = 50002,
        id = 176,
        name = "感化",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [177] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "点化点数显示",
        groupType = 30,
        icon = 50002,
        id = 177,
        name = "点化",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [178] = {
        attr_ratio_list = {"phy_defense=10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加物防",
        groupType = 4,
        icon = 50002,
        id = 178,
        name = "固甲术",
        trans = 2,
        type = 3,
        updateType = 2,
    },

    [179] = {
        attr_ratio_list = {"phy_defense=5"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加物防",
        groupType = 4,
        icon = 50002,
        id = 179,
        name = "圣甲术",
        trans = 2,
        type = 3,
        updateType = 2,
    },

    [180] = {
        attr_ratio_list = {"speed=10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加速度",
        groupType = 5,
        icon = 50002,
        id = 180,
        name = "狂风诀",
        trans = 3,
        type = 3,
        updateType = 2,
    },

    [181] = {
        attr_ratio_list = {"speed=5"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加速度",
        groupType = 5,
        icon = 50002,
        id = 181,
        name = "神风诀",
        trans = 3,
        type = 3,
        updateType = 2,
    },

    [182] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "反震伤害",
        groupType = 34,
        icon = 50002,
        id = 182,
        name = "摩罗咒",
        trans = 2,
        type = 4,
        updateType = 2,
    },

    [183] = {
        attr_ratio_list = {"phy_attack=-5"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "减少物攻",
        groupType = 2,
        icon = 50002,
        id = 183,
        name = "当头棒喝",
        trans = 2,
        type = 3,
        updateType = 2,
    },

    [184] = {
        attr_ratio_list = {"phy_defense=-10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "减少物防",
        groupType = 7,
        icon = 50002,
        id = 184,
        name = "破甲术",
        trans = 2,
        type = 3,
        updateType = 2,
    },

    [185] = {
        attr_ratio_list = {"phy_defense=-5"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "减少物防",
        groupType = 7,
        icon = 50002,
        id = 185,
        name = "破盾术",
        trans = 2,
        type = 3,
        updateType = 2,
    },

    [186] = {
        attr_ratio_list = {"speed=-10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "减少速度",
        groupType = 8,
        icon = 50002,
        id = 186,
        name = "霜冻术",
        trans = 3,
        type = 3,
        updateType = 2,
    },

    [187] = {
        attr_ratio_list = {"speed=-5"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "减少速度",
        groupType = 8,
        icon = 50002,
        id = 187,
        name = "冰天术",
        trans = 3,
        type = 3,
        updateType = 2,
    },

    [188] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"res_all_buff_ratio=100"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "抵抗所有buff",
        groupType = 40,
        icon = 50002,
        id = 188,
        name = "禅言定心",
        trans = 3,
        type = 3,
        updateType = 2,
    },

    [189] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"damage_ratio=10"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "伤害增加",
        groupType = 9,
        icon = 50002,
        id = 189,
        name = "御灵",
        trans = 2,
        type = 1,
        updateType = 2,
    },

    [190] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "有辅助职业存在则逃离战斗",
        groupType = 42,
        icon = 51502,
        id = 190,
        name = "逃避",
        trans = 3,
        type = 4,
        updateType = 1,
    },

    [191] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "流血",
        groupType = 43,
        icon = 51502,
        id = 191,
        name = "掉血",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [192] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "",
        groupType = 44,
        icon = 51502,
        id = 192,
        name = "亡魂术",
        trans = 2,
        type = 4,
        updateType = 2,
    },

    [193] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"damage_ratio=5"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "造成伤害提高",
        groupType = 45,
        icon = 50052,
        id = 193,
        name = "猛击",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [194] = {
        attr_ratio_list = {"phy_defense=-15", "mag_defense=-15"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物防降低",
        groupType = 46,
        icon = 51602,
        id = 194,
        name = "腐蚀术",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [195] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"damaged_ratio=-20"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "受到伤害减少",
        groupType = 47,
        icon = 51402,
        id = 195,
        name = "装死",
        trans = 3,
        type = 1,
        updateType = 2,
    },

    [196] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"damaged_ratio=-20"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "受到伤害减少",
        groupType = 48,
        icon = 50149,
        id = 196,
        name = "止痛药",
        trans = 2,
        type = 4,
        updateType = 2,
    },

    [197] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"mag_hit_res_ratio=25"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "法术闪避提高",
        groupType = 49,
        icon = 50146,
        id = 197,
        name = "瞬斩",
        trans = 3,
        type = 1,
        updateType = 2,
    },

    [198] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"phy_critical_ratio=4+level"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "暴击提高,溅射",
        groupType = 50,
        icon = 50252,
        id = 198,
        name = "剑气爆发",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [199] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "中毒",
        color = 1,
        desc = "中毒",
        groupType = 7,
        icon = 50131,
        id = 199,
        name = "巫蛊",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [200] = {
        attr_ratio_list = {"phy_attack=-5-level"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物攻下降",
        groupType = 18,
        icon = 51602,
        id = 200,
        name = "蚀骨",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [201] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "物防下降",
        groupType = 51,
        icon = 51602,
        id = 201,
        name = "护主",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [202] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "强制攻击固定目标",
        groupType = 52,
        icon = 50245,
        id = 202,
        name = "嘲讽",
        trans = 3,
        type = 2,
        updateType = 0,
    },

    [203] = {
        attr_ratio_list = {},
        attr_set = {"command_disable=1", "defense=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "受到伤害降低",
        groupType = 53,
        icon = 51402,
        id = 203,
        name = "防御",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [204] = {
        attr_ratio_list = {"phy_defense=-30"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "物防大幅下降",
        groupType = 54,
        icon = 51602,
        id = 204,
        name = "压制",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [205] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damage_addratio=30", "damaged_addratio=30"},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "伤害大幅降低",
        groupType = 55,
        icon = 51605,
        id = 205,
        name = "心魔蚀心",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [206] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "持续掉血",
        groupType = 56,
        icon = 50131,
        id = 206,
        name = "灼烧",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [207] = {
        attr_ratio_list = {"mag_attack=200", "phy_attack=200"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "攻击提高",
        groupType = 57,
        icon = 51404,
        id = 207,
        name = "复仇",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [208] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "持续掉血",
        groupType = 58,
        icon = 50131,
        id = 208,
        name = "箭芒",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [209] = {
        attr_ratio_list = {},
        attr_set = {"phy_disable=1", "attack_disable=1", "mag_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "封印",
        color = 1,
        desc = "眩晕",
        groupType = 59,
        icon = 50102,
        id = 209,
        name = "眩晕",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [210] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"damage_ratio=300"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "攻击提高",
        groupType = 60,
        icon = 51404,
        id = 210,
        name = "剑意",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [211] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "转移伤害",
        groupType = 61,
        icon = 51403,
        id = 211,
        name = "伤害转移",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [212] = {
        attr_ratio_list = {"phy_defense=-30", "mag_defense=-30", "phy_attack=-30", "mag_attack=-30"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "攻击、防御降低",
        groupType = 62,
        icon = 51605,
        id = 212,
        name = "懦弱",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [213] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "混乱",
        groupType = 63,
        icon = 50102,
        id = 213,
        name = "无能",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [214] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "中毒",
        color = 1,
        desc = "中毒",
        groupType = 64,
        icon = 50131,
        id = 214,
        name = "中毒",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [215] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "特殊状态",
        groupType = 65,
        icon = 50129,
        id = 215,
        name = "失聪",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [216] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "特殊状态",
        groupType = 66,
        icon = 50132,
        id = 216,
        name = "失明",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [217] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "特殊状态",
        groupType = 67,
        icon = 50135,
        id = 217,
        name = "体衰",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [218] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "特殊状态",
        groupType = 68,
        icon = 50145,
        id = 218,
        name = "失语",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [219] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "特殊状态",
        groupType = 69,
        icon = 50149,
        id = 219,
        name = "失闻",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [220] = {
        attr_ratio_list = {"mag_attack=50", "phy_attack=50"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "攻击提高",
        groupType = 70,
        icon = 50131,
        id = 220,
        name = "仇恨",
        trans = 3,
        type = 1,
        updateType = 2,
    },

    [221] = {
        attr_ratio_list = {"mag_attack=50", "phy_attack=50"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "攻击提高",
        groupType = 71,
        icon = 50131,
        id = 221,
        name = "仇恨",
        trans = 3,
        type = 1,
        updateType = 2,
    },

    [222] = {
        attr_ratio_list = {},
        attr_set = {"revive_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "不能复活",
        groupType = 72,
        icon = 50131,
        id = 222,
        name = "禁止复活",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [223] = {
        attr_ratio_list = {"mag_attack=10", "phy_attack=10"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "攻击提升",
        groupType = 73,
        icon = 50131,
        id = 223,
        name = "星宿之力",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [224] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "回复气血",
        groupType = 74,
        icon = 51202,
        id = 224,
        name = "星宿之息",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [225] = {
        attr_ratio_list = {"mag_defense=6", "phy_defense=6"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加防御",
        groupType = 75,
        icon = 50131,
        id = 225,
        name = "星宿之御",
        trans = 2,
        type = 4,
        updateType = 2,
    },

    [226] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"phy_critical_ratio=40", "mag_critical_ratio=40"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "暴击大幅增加",
        groupType = 73,
        icon = 50131,
        id = 226,
        name = "星宿之怒",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [227] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"phy_damage_ratio=10+(level-1)/4*10"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "伤害增加",
        groupType = 76,
        icon = 50232,
        id = 227,
        name = "气势",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [228] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"mag_damage_ratio=10+(level-1)/4*10"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "伤害增加",
        groupType = 77,
        icon = 50232,
        id = 228,
        name = "震慑",
        trans = 1,
        type = 1,
        updateType = 2,
    },

    [229] = {
        attr_ratio_list = {"phy_defense=-5", "mag_defense=-5"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "物防、法防下降",
        groupType = 78,
        icon = 50051,
        id = 229,
        name = "蚀甲",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [230] = {
        attr_ratio_list = {"speed=-5"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "降低速度",
        groupType = 79,
        icon = 50020,
        id = 230,
        name = "流沙",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [231] = {
        attr_ratio_list = {},
        attr_set = {"engage_protect=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "特殊状态",
        groupType = 80,
        icon = 50020,
        id = 231,
        name = "同甘共苦",
        trans = 1,
        type = 4,
        updateType = 2,
    },

    [232] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"phy_critical_ratio=40", "mag_critical_ratio=40"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "暴击大幅增加",
        groupType = 73,
        icon = 50131,
        id = 232,
        name = "狂怒",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [233] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damaged_addratio=20"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "伤害加深",
        groupType = 81,
        icon = 50201,
        id = 233,
        name = "重伤",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [234] = {
        attr_ratio_list = {},
        attr_set = {"sp=(5+level*2)"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加愤怒",
        groupType = 82,
        icon = 50102,
        id = 234,
        name = "战神附体",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [235] = {
        attr_ratio_list = {},
        attr_set = {"sp=-(5+level*2)"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "减少愤怒",
        groupType = 83,
        icon = 50102,
        id = 235,
        name = "恶魔诅咒",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [236] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"mag_attack=math.floor(grade*level*5/100)"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加法术攻击",
        groupType = 84,
        icon = 50102,
        id = 236,
        name = "法术强化",
        trans = 3,
        type = 4,
        updateType = 2,
    },

    [237] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"phy_attack=math.floor(grade*level*5/100)"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加物理攻击",
        groupType = 85,
        icon = 50102,
        id = 237,
        name = "攻击强化",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [238] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "物理免疫",
        groupType = 86,
        icon = 50131,
        id = 238,
        name = "物理免疫",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [239] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "法术免疫",
        groupType = 87,
        icon = 50131,
        id = 239,
        name = "法术免疫",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [240] = {
        attr_ratio_list = {},
        attr_set = {"strong_stealth=1", "phy_disable=1"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "超级隐身",
        groupType = 88,
        icon = 50150,
        id = 240,
        name = "超级隐身",
        trans = 1,
        type = 2,
        updateType = 2,
    },

    [241] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {"damaged_ratio=-10"},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "受到伤害降低",
        groupType = 86,
        icon = 50102,
        id = 241,
        name = "抵抗",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [242] = {
        attr_ratio_list = {},
        attr_set = {"fabao_mp_ratio=10"},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "法力消耗降低",
        groupType = 87,
        icon = 50102,
        id = 242,
        name = "冥想",
        trans = 3,
        type = 2,
        updateType = 2,
    },

    [243] = {
        attr_ratio_list = {"phy_defense=8"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 1,
        desc = "增加物防",
        groupType = 88,
        icon = 50002,
        id = 243,
        name = "增加物防",
        trans = 2,
        type = 3,
        updateType = 2,
    },

    [244] = {
        attr_ratio_list = {"phy_attack=-30", "mag_attack=-30"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {"damaged_addratio=30"},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "伤害降低，受伤害增加",
        groupType = 89,
        icon = 50002,
        id = 244,
        name = "走火入魔",
        trans = 2,
        type = 2,
        updateType = 1,
    },

    [245] = {
        attr_ratio_list = {"phy_attack=15", "mag_attack=15"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "增加攻击力",
        groupType = 90,
        icon = 50002,
        id = 245,
        name = "剑斩灵魂",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [246] = {
        attr_ratio_list = {"phy_defense=-90"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "降低物理防御",
        groupType = 91,
        icon = 50002,
        id = 246,
        name = "碎甲",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [247] = {
        attr_ratio_list = {"phy_defense=-50", "mag_defense=-50"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "降低防御力",
        groupType = 92,
        icon = 50002,
        id = 247,
        name = "破甲击",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [248] = {
        attr_ratio_list = {"phy_defense=-90", "mag_defense=-90"},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "降低双防御",
        groupType = 93,
        icon = 50002,
        id = 248,
        name = "破法",
        trans = 2,
        type = 2,
        updateType = 2,
    },

    [249] = {
        attr_ratio_list = {},
        attr_set = {},
        attr_temp_addvalue = {},
        attr_temp_ratio = {},
        attr_value_list = {},
        buffEvent = "",
        buffType = "",
        color = 0,
        desc = "复活",
        groupType = 94,
        icon = 50002,
        id = 249,
        name = "涅槃",
        trans = 2,
        type = 2,
        updateType = 2,
    },

}
