-- ./excel/task/ghost/task_ghost.xlsx
return {

    [62000] = {
        acceptConditionStr = {},
        acceptNpcId = 5201,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "降伏从幽冥地府逃逸的妖魔鬼怪",
        goalDesc = "降伏{submitscene}的{submitnpc}",
        id = 62000,
        initConfig = {"NC1001", "E1001:1001"},
        missiondone = {},
        name = "金刚伏魔",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1004"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 5,
    },

    [62001] = {
        acceptConditionStr = {},
        acceptNpcId = 5201,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "降伏从幽冥地府逃逸的妖魔鬼怪",
        goalDesc = "降伏{submitscene}的{submitnpc}",
        id = 62001,
        initConfig = {"NC1002", "E1002:1001"},
        missiondone = {},
        name = "金刚伏魔",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1004"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 5,
    },

    [62002] = {
        acceptConditionStr = {},
        acceptNpcId = 5201,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "降伏从幽冥地府逃逸的妖魔鬼怪",
        goalDesc = "降伏{submitscene}的{submitnpc}",
        id = 62002,
        initConfig = {"NC1003", "E1003:1001"},
        missiondone = {},
        name = "金刚伏魔",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1004"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 5,
    },

    [62003] = {
        acceptConditionStr = {},
        acceptNpcId = 5201,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "降伏从幽冥地府逃逸的妖魔鬼怪",
        goalDesc = "降伏{submitscene}的{submitnpc}",
        id = 62003,
        initConfig = {"NC1004", "E1004:1001"},
        missiondone = {},
        name = "金刚伏魔",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1004"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 5,
    },

    [62004] = {
        acceptConditionStr = {},
        acceptNpcId = 5201,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "降伏从幽冥地府逃逸的妖魔鬼怪",
        goalDesc = "降伏{submitscene}的{submitnpc}",
        id = 62004,
        initConfig = {"NC1005", "E1005:1001"},
        missiondone = {},
        name = "金刚伏魔",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1004"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 5,
    },

}
