-- ./excel/system/promote/promote.xlsx
return {

    [1001] = {
         opentype = 4,
        des = "",
        go = {"技能", "主动技能"},
        icon = "h7_fengyaotu",
        name = "招式技能",
        open_id = "SKILL_ZD",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1001,
    },

    [1002] = {
         opentype = 4,
        des = "",
        go = {"技能", "被动技能"},
        icon = "h7_fengyaotu",
        name = "心法技能",
        open_id = "SKILL_BD",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1002,
    },

    [1003] = {
         opentype = 4,
        des = "",
        go = {"技能", "修炼技能"},
        icon = "h7_fengyaotu",
        name = "修炼技能",
        open_id = "XIU_LIAN_SYS",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1003,
    },

    [1004] = {
         opentype = 4,
        des = "",
        go = {"技能", "帮派技能"},
        icon = "h7_fengyaotu",
        name = "辅助技能",
        open_id = "ORG_SKILL",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1004,
    },

    [1005] = {
         opentype = 4,
        des = "",
        go = {"打造", "打造"},
        icon = "h7_xiliantu",
        name = "装备打造",
        open_id = "EQUIP_DZ",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1005,
    },

    [1006] = {
         opentype = 4,
        des = "",
        go = {"打造", "强化"},
        icon = "h7_qianghuatu",
        name = "装备强化",
        open_id = "EQUIP_QH",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1006,
    },

    [1007] = {
         opentype = 4,
        des = "",
        go = {"打造", "附魂"},
        icon = "h7_xiliantu",
        name = "装备附魂",
        open_id = "EQUIP_FH",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1007,
    },

    [1008] = {
         opentype = 4,
        des = "",
        go = {"伙伴", "进阶"},
        icon = "h7_huobantu",
        name = "伙伴培养",
        open_id = "PARTNER_SYS",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1008,
    },

    [1009] = {
         opentype = 4,
        des = "",
        go = {"宠物属性", "属性"},
        icon = "h7_huobantu",
        name = "宠物培养",
        open_id = "SUMMON_SYS",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1009,
    },

    [1010] = {
         opentype = 4,
        des = "",
        go = {"徽章"},
        icon = "h7_xiangqiantu",
        name = "头衔升级",
        open_id = "BADGE",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1010,
    },

    [1011] = {
         opentype = 4,
        des = "",
        go = {"坐骑", "升级"},
        icon = "h7_xiangqiantu",
        name = "坐骑培养",
        open_id = "RIDE_UPGRADE",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1011,
    },

    [1012] = {
         opentype = 4,
        des = "",
        go = {"打造", "镶嵌"},
        icon = "h7_xiangqiantu",
        name = "魂石升级",
        open_id = "EQUIP_XQ",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1012,
    },

    [1013] = {
         opentype = 4,
        des = "",
        go = {"法宝", "佩戴"},
        icon = "h7_xiangqiantu",
        name = "法宝培养",
        open_id = "FABAO",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1013,
    },

    [1014] = {
         opentype = 4,
        des = "",
        go = {"神器", "神器"},
        icon = "h7_xiangqiantu",
        name = "神器培养",
        open_id = "ARTIFACT",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1014,
    },

    [1015] = {
         opentype = 4,
        des = "",
        go = {"羽翼", "属性"},
        icon = "h7_xiangqiantu",
        name = "羽翼培养",
        open_id = "WING",
        openid = 0,
        scheduleId = 0,
        star = {},
        type = 1,
        type_id = 1015,
    },

    [2001] = {
         opentype = 3,
        des = "每天20次门派修行可获得大量经验奖励",
        go = {},
        icon = "h7_shimen_tu",
        name = "门派修行",
        open_id = "SHIMEN",
        openid = 4,
        scheduleId = 1001,
        star = {5, 5},
        type = 2,
        type_id = 2001,
    },

    [2002] = {
         opentype = 3,
        des = "每天120次金刚伏魔可获得丰厚的经验奖励",
        go = {},
        icon = "h7_zhuaguitu",
        name = "金刚伏魔",
        open_id = "ZHUAGUI",
        openid = 5,
        scheduleId = 1004,
        star = {5, 5},
        type = 2,
        type_id = 2002,
    },

    [2003] = {
         opentype = 4,
        des = "每天前10次镇妖可获得一定的经验奖励",
        go = {"日程"},
        icon = "h7_fengyaotu",
        name = "野外镇妖",
        open_id = "FENGYAO",
        openid = 0,
        scheduleId = 1003,
        star = {4, 5},
        type = 2,
        type_id = 2003,
    },

    [2004] = {
         opentype = 4,
        des = "每天帮别人完成主线、支线任务可获经验奖励",
        go = {"日程"},
        icon = "h7_huobantu",
        name = "协助他人",
        open_id = "GROW",
        openid = 0,
        scheduleId = 1003,
        star = {5, 5},
        type = 2,
        type_id = 2004,
    },

    [3001] = {
         opentype = 4,
        des = "使用帮派技能生产商品摆摊卖出可获得大量银币",
        go = {"技能", "帮派技能"},
        icon = "h7_fengyaotu",
        name = "帮派技能",
        open_id = "ORG_SKILL",
        openid = 0,
        scheduleId = 0,
        star = {5, 5},
        type = 3,
        type_id = 3001,
    },

    [3002] = {
         opentype = 3,
        des = "每天20次门派修行可获得大量银币",
        go = {},
        icon = "h7_shimen_tu",
        name = "门派修行",
        open_id = "SHIMEN",
        openid = 4,
        scheduleId = 1001,
        star = {4, 5},
        type = 3,
        type_id = 3002,
    },

    [3003] = {
         opentype = 3,
        des = "每天120次金刚伏魔可获得一定银币",
        go = {},
        icon = "h7_zhuaguitu",
        name = "金刚伏魔",
        open_id = "ZHUAGUI",
        openid = 5,
        scheduleId = 1004,
        star = {4, 5},
        type = 3,
        type_id = 3003,
    },

    [3004] = {
         opentype = 4,
        des = "每天两次火眼金睛可获得大量银币",
        go = {"日程"},
        icon = "h7_fengyaotu",
        name = "火眼金睛",
        open_id = "GUESSGAME",
        openid = 0,
        scheduleId = 1024,
        star = {5, 5},
        type = 3,
        type_id = 3004,
    },

    [4001] = {
         opentype = 4,
        des = "活跃度达到100可获得一定金币",
        go = {"日程"},
        icon = "h7_shimen_tu",
        name = "活跃度",
        open_id = "FENGYAO",
        openid = 0,
        scheduleId = 1003,
        star = {4, 5},
        type = 4,
        type_id = 4001,
    },

    [4002] = {
         opentype = 3,
        des = "每天20次门派修行可获得一定金币",
        go = {},
        icon = "h7_zhuaguitu",
        name = "门派修行",
        open_id = "SHIMEN",
        openid = 4,
        scheduleId = 1001,
        star = {2, 5},
        type = 4,
        type_id = 4002,
    },

    [5001] = {
         opentype = 4,
        des = "花费银币学习可获得修炼经验",
        go = {"技能", "修炼技能"},
        icon = "h7_xiliantu",
        name = "银币修炼",
        open_id = "XIU_LIAN_SYS",
        openid = 0,
        scheduleId = 0,
        star = {5, 5},
        type = 5,
        type_id = 5001,
    },

    [5002] = {
         opentype = 4,
        des = "完成异宝收集可获得大量修炼经验",
        go = {"日程"},
        icon = "h7_fengyaotu",
        name = "异宝收集",
        open_id = "YIBAO",
        openid = 0,
        scheduleId = 1015,
        star = {4, 5},
        type = 5,
        type_id = 5002,
    },

}
