-- ./excel/huodong/baike/question.xlsx
return {

    [1001] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1926年",
        choose_text_2 = "1930年",
        choose_text_3 = "1918年",
        choose_text_4 = "1945年",
        id = 1001,
        question = "第一届世界杯于哪一年举行？",
        type = 1,
    },

    [1002] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴西",
        choose_text_2 = "阿根廷",
        choose_text_3 = "葡萄牙",
        choose_text_4 = "意大利",
        id = 1002,
        question = "哪个球队在世界杯中夺得的冠军最多？",
        type = 1,
    },

    [1003] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "雷米特杯",
        choose_text_2 = "大力神杯",
        choose_text_3 = "生命之杯",
        choose_text_4 = "1945年",
        id = 1003,
        question = "前任世界杯的奖杯叫什么名字？",
        type = 1,
    },

    [1004] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "10码",
        choose_text_2 = "12码",
        choose_text_3 = "15码",
        choose_text_4 = "20码",
        id = 1004,
        question = "足球比赛开球时，守方每一位队员需站在开球点几码外？",
        type = 1,
    },

    [1005] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "黄色",
        choose_text_2 = "红色",
        choose_text_3 = "橘色",
        choose_text_4 = "白色",
        id = 1005,
        question = "足球比赛时，驱逐球员出场用的牌子是什么颜色？",
        type = 1,
    },

    [1006] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "90",
        choose_text_2 = "80",
        choose_text_3 = "70",
        choose_text_4 = "60",
        id = 1006,
        question = "一般国际足球赛的比赛时间为多少分钟？",
        type = 1,
    },

    [1007] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "7",
        choose_text_2 = "8",
        choose_text_3 = "9",
        choose_text_4 = "10",
        id = 1007,
        question = "足球比赛少于几人出场时，裁判员有权暂停或终止比赛？",
        type = 1,
    },

    [1008] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1",
        choose_text_2 = "2",
        choose_text_3 = "3",
        choose_text_4 = "4",
        id = 1008,
        question = "足球比赛时，可替换人数为几人？",
        type = 1,
    },

    [1009] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "雷米特是巴西人",
        choose_text_2 = "巴西通过战争获得",
        choose_text_3 = "巴西三夺冠军",
        choose_text_4 = "巴西掷骰子获得",
        id = 1009,
        question = "为什么雷米特杯被巴西永久拥有了?",
        type = 1,
    },

    [1010] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "贝肯鲍尔",
        choose_text_2 = "巴拉克",
        choose_text_3 = "克洛泽",
        choose_text_4 = "克林斯曼",
        id = 1010,
        question = "被称为“足球皇帝”的德国人是谁?",
        type = 1,
    },

    [1011] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "杨旭",
        choose_text_2 = "武磊",
        choose_text_3 = "郜林",
        choose_text_4 = "郑智",
        id = 1011,
        question = "获得过亚洲足球先生的是？",
        type = 1,
    },

    [1012] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "2次",
        choose_text_2 = "1次",
        choose_text_3 = "3次",
        choose_text_4 = "4次",
        id = 1012,
        question = "广州恒大夺得过几次亚冠冠军？",
        type = 1,
    },

    [1013] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "工人体育场",
        choose_text_2 = "黄龙体育中心",
        choose_text_3 = "虹桥体育场",
        choose_text_4 = "老特拉福德",
        id = 1013,
        question = "绿城的主场是?",
        type = 1,
    },

    [1014] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "香蕉球",
        choose_text_2 = "西瓜球",
        choose_text_3 = "苹果球",
        choose_text_4 = "芒果球",
        id = 1014,
        question = "C罗在对阵西班牙时曾将足球踢出一个弧线，绕过人墙成功进球，这种球叫？",
        type = 1,
    },

    [1015] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1次",
        choose_text_2 = "2次",
        choose_text_3 = "3次",
        choose_text_4 = "4次",
        id = 1015,
        question = "绿城足球俱乐部参加过几次亚冠？",
        type = 1,
    },

    [1016] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1999",
        choose_text_2 = "1998",
        choose_text_3 = "2000",
        choose_text_4 = "1995",
        id = 1016,
        question = "绿城俱乐部成立的时间是？",
        type = 1,
    },

    [1017] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "酋长球场",
        choose_text_2 = "斯坦福桥",
        choose_text_3 = "JJB球场",
        choose_text_4 = "老特拉福德",
        id = 1017,
        question = "曼联的主场是?",
        type = 1,
    },

    [1018] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "绿魂",
        choose_text_2 = "绿粉",
        choose_text_3 = "绿迷",
        choose_text_4 = "绿忠",
        id = 1018,
        question = "绿城的球迷组织称为？",
        type = 1,
    },

    [1019] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "红色球场",
        choose_text_2 = "华南虎球场",
        choose_text_3 = "最低消费球场",
        choose_text_4 = "魔鬼主场",
        id = 1019,
        question = "广州恒大的主场被称为?",
        type = 1,
    },

    [1020] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "2012",
        choose_text_2 = "2009",
        choose_text_3 = "2010",
        choose_text_4 = "2008",
        id = 1020,
        question = "广州恒大成立的时间是？",
        type = 1,
    },

    [1021] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴塞罗那",
        choose_text_2 = "尤文图斯",
        choose_text_3 = "利物浦",
        choose_text_4 = "里昂",
        id = 1021,
        question = "法国球星亨利在去阿森纳之前效力于哪支球队?",
        type = 1,
    },

    [1022] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "博卡VS河床",
        choose_text_2 = "博卡VS飓风",
        choose_text_3 = "河床VS科隆",
        choose_text_4 = "科隆VS博卡",
        id = 1022,
        question = "阿根廷最火爆的“德比”是?",
        type = 1,
    },

    [1023] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "酋长球场",
        choose_text_2 = "糖果盒球场",
        choose_text_3 = "JJB球场",
        choose_text_4 = "安菲尔德",
        id = 1023,
        question = "博卡的主场名称?",
        type = 1,
    },

    [1024] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "博格坎普",
        choose_text_2 = "尤文图斯",
        choose_text_3 = "埃因霍温",
        choose_text_4 = "SBV精英",
        id = 1024,
        question = "哪位荷兰的著名球星因为“恐飞”而拒绝为国家队和俱乐部出战?",
        type = 1,
    },

    [1025] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "AC米兰",
        choose_text_2 = "国际米兰",
        choose_text_3 = "尤文图斯",
        choose_text_4 = "SBV精英",
        id = 1025,
        question = "意大利哪支球队获得的冠军杯冠军次数最多?",
        type = 1,
    },

    [1026] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "5次",
        choose_text_2 = "4次",
        choose_text_3 = "3次",
        choose_text_4 = "6次",
        id = 1026,
        question = "巴西获得了几次世界杯冠军?",
        type = 1,
    },

    [2001] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "维拉利尔",
        choose_text_2 = "巴塞罗那",
        choose_text_3 = "马德里竞技",
        choose_text_4 = "皇家马德里",
        id = 2001,
        question = "西甲哪支球队绰号是“黄色潜水艇”?",
        type = 1,
    },

    [2002] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "北京国安",
        choose_text_2 = "杭州绿城",
        choose_text_3 = "长春亚泰",
        choose_text_4 = "上海申花",
        id = 2002,
        question = "哪一家中超俱乐部的绰号叫“御林军”？",
        type = 1,
    },

    [2003] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "欧文",
        choose_text_2 = "特里",
        choose_text_3 = "鲁尼",
        choose_text_4 = "吉格斯",
        id = 2003,
        question = "在1996年足总杯决赛中，谁为曼联队攻入制胜球？",
        type = 1,
    },

    [2004] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "前锋",
        choose_text_2 = "中场",
        choose_text_3 = "后卫",
        choose_text_4 = "门将",
        id = 2004,
        question = "法比恩·巴特兹踢什么位置？",
        type = 1,
    },

    [2005] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "绿城和申花",
        choose_text_2 = "申花和国安",
        choose_text_3 = "申花和上港",
        choose_text_4 = "上港和富力",
        id = 2005,
        question = "中超当中上海德比是？",
        type = 1,
    },

    [2006] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "郜林",
        choose_text_2 = "J.马",
        choose_text_3 = "郑智",
        choose_text_4 = "杨智",
        id = 2006,
        question = "广州恒大最近一次夺得亚冠冠军的队长是谁？",
        type = 1,
    },

    [2007] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "阿根廷",
        choose_text_2 = "巴西",
        choose_text_3 = "意大利",
        choose_text_4 = "德国",
        id = 2007,
        question = "哪个国家夺得了1994年世界杯？",
        type = 1,
    },

    [2008] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1980",
        choose_text_2 = "1984",
        choose_text_3 = "1988",
        choose_text_4 = "1992",
        id = 2008,
        question = "在哪一年的奥运会上国际足联限定参加球员年龄需低于23岁？",
        type = 1,
    },

    [2009] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "本方球门区内",
        choose_text_2 = "本方半场内",
        choose_text_3 = "中圈弧内",
        choose_text_4 = "本方大禁区内",
        id = 2009,
        question = "足球比赛中一方踢球门球，本方接应队员不得在哪接球？",
        type = 1,
    },

    [2010] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "孙葆杰",
        choose_text_2 = "陆俊",
        choose_text_3 = "曹镜鉴",
        choose_text_4 = "侯明亮",
        id = 2010,
        question = "哪位中国裁判作为主裁判执法过世界杯决赛阶段的比赛？",
        type = 1,
    },

    [2011] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "算",
        choose_text_2 = "不算",
        choose_text_3 = "没有明确规定",
        choose_text_4 = "裁判说了算",
        id = 2011,
        question = "足球比赛中球压在边线上算不算出界?",
        type = 1,
    },

    [2012] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "罚任意球",
        choose_text_2 = "掷边线球",
        choose_text_3 = "主裁判坠球",
        choose_text_4 = "罚点球",
        id = 2012,
        question = "足球比赛进行中球出边线，发球方是如何发球的？",
        type = 1,
    },

    [2013] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "英国",
        choose_text_2 = "中国",
        choose_text_3 = "巴西",
        choose_text_4 = "葡萄牙",
        id = 2013,
        question = "足球起源于哪个国家？",
        type = 1,
    },

    [2014] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "19世纪末",
        choose_text_2 = "20世纪初",
        choose_text_3 = "20世纪中期",
        choose_text_4 = "20世纪末",
        id = 2014,
        question = "职业足球出现在什么时代？",
        type = 1,
    },

    [2015] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1982",
        choose_text_2 = "1986",
        choose_text_3 = "1990",
        choose_text_4 = "1994",
        id = 2015,
        question = "神奇教练米卢蒂诺维奇第一次率队参加世界杯是哪一年?",
        type = 1,
    },

    [3001] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "3",
        choose_text_2 = "4",
        choose_text_3 = "5",
        choose_text_4 = "6",
        id = 3001,
        question = "神奇教练米卢蒂诺维奇率队征战过几次世界杯? ",
        type = 1,
    },

    [3002] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "第14届世界杯",
        choose_text_2 = "第16届世界杯",
        choose_text_3 = "第15届世界杯",
        choose_text_4 = "第13届世界杯",
        id = 3002,
        question = "世界杯将参加决赛阶段的球队增加到32支是在哪一届? ",
        type = 1,
    },

    [3003] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴拉圭 ",
        choose_text_2 = "意大利 ",
        choose_text_3 = "德国",
        choose_text_4 = "巴西",
        id = 3003,
        question = "世界杯历史上第1支在非本大陆夺取冠军的球队是?",
        type = 1,
    },

    [3004] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "韩国和中国",
        choose_text_2 = "日本和中国",
        choose_text_3 = "韩国和印尼",
        choose_text_4 = "韩国和日本",
        id = 3004,
        question = "世界杯历史上仅有一次是由两个国家联合主办的，这两个国家是? ",
        type = 1,
    },

    [3005] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "12",
        choose_text_2 = "13",
        choose_text_3 = "14",
        choose_text_4 = "15",
        id = 3005,
        question = "被称为“意大利之夏”的世界杯是第几届?",
        type = 1,
    },

    [3006] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "兰格纽斯",
        choose_text_2 = "科特·特琴塞尔",
        choose_text_3 = "巴巴坎 ",
        choose_text_4 = "索西多",
        id = 3006,
        question = "第一位在世界杯中出示黄牌的裁判是谁? ",
        type = 1,
    },

    [3007] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "葡萄牙",
        choose_text_2 = "苏联",
        choose_text_3 = "德国",
        choose_text_4 = "英格兰",
        id = 3007,
        question = "1966年世界杯冠军是谁? ",
        type = 1,
    },

    [3008] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "乌拉圭一胜一负",
        choose_text_2 = "阿根廷两胜 ",
        choose_text_3 = "乌拉圭两败",
        choose_text_4 = "阿根廷一平",
        id = 3008,
        question = "本届世界杯之前，乌拉圭与阿根廷世界杯史上交锋战绩如何?",
        type = 1,
    },

    [3009] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴西的加林查 ",
        choose_text_2 = "巴西的阿德米尔",
        choose_text_3 = "葡萄牙的欧塞比奥 ",
        choose_text_4 = "德国的穆勒",
        id = 3009,
        question = "1970第九届世界杯金靴奖获得者是谁?",
        type = 1,
    },

    [3010] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "20",
        choose_text_2 = "21",
        choose_text_3 = "22",
        choose_text_4 = "23",
        id = 3010,
        question = "阿根廷著名球星马里奥·肯佩斯共为国家队贡献了多少粒进球? ",
        type = 1,
    },

    [3011] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "A罗",
        choose_text_2 = "B罗",
        choose_text_3 = "C罗",
        choose_text_4 = "D罗",
        id = 3011,
        question = "下列哪个是葡萄牙球星？",
        type = 1,
    },

    [3012] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "梅东",
        choose_text_2 = "梅南",
        choose_text_3 = "梅西",
        choose_text_4 = "梅北",
        id = 3012,
        question = "下列哪个是阿根廷球星？",
        type = 1,
    },

    [3013] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "外牛尔",
        choose_text_2 = "内牛尔",
        choose_text_3 = "外马尔",
        choose_text_4 = "内马尔",
        id = 3013,
        question = "下列哪个是巴西球星？",
        type = 1,
    },

    [3014] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "黑帕德",
        choose_text_2 = "蓝帕德",
        choose_text_3 = "绿帕德",
        choose_text_4 = "红帕德",
        id = 3014,
        question = "下列哪个是英格兰球星？",
        type = 1,
    },

    [3015] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "上贝上",
        choose_text_2 = "下贝下",
        choose_text_3 = "里贝里",
        choose_text_4 = "外贝外",
        id = 3015,
        question = "下列哪个是法国球星？",
        type = 1,
    },

    [3016] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "粥佩西",
        choose_text_2 = "粉佩西",
        choose_text_3 = "面佩西",
        choose_text_4 = "饭佩西",
        id = 3016,
        question = "下列哪个是荷兰球星？",
        type = 1,
    },

    [3017] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "托风斯",
        choose_text_2 = "托火斯",
        choose_text_3 = "托雷斯",
        choose_text_4 = "托电斯",
        id = 3017,
        question = "下列哪个是西班牙球星？",
        type = 1,
    },

    [3018] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "撸管",
        choose_text_2 = "撸面",
        choose_text_3 = "鲁尼",
        choose_text_4 = "鲁大师",
        id = 3018,
        question = "下列哪个是英格兰球星？",
        type = 1,
    },

    [3019] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "苏亚粉丝",
        choose_text_2 = "苏亚肉丝",
        choose_text_3 = "苏亚黑丝",
        choose_text_4 = "苏亚蕾丝",
        id = 3019,
        question = "下列哪个是乌拉圭球星？",
        type = 1,
    },

    [3020] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "毛儿落",
        choose_text_2 = "发儿落",
        choose_text_3 = "皮儿落",
        choose_text_4 = "泪儿落",
        id = 3020,
        question = "下列哪个是意大利球星？",
        type = 1,
    },

    [3021] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "171",
        choose_text_2 = "272",
        choose_text_3 = "373",
        choose_text_4 = "474",
        id = 3021,
        question = "下列哪个是德国球星？",
        type = 1,
    },

    [3022] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "恐怕我",
        choose_text_2 = "恐怕你",
        choose_text_3 = "恐怕他",
        choose_text_4 = "恐怕怕",
        id = 3022,
        question = "下列哪个是比利时球星？",
        type = 1,
    },

    [3023] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "丰田龟左",
        choose_text_2 = "丰田龟右",
        choose_text_3 = "本田龟左",
        choose_text_4 = "本田龟右",
        id = 3023,
        question = "下列哪个是日本球星？",
        type = 1,
    },

    [3024] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "吃智星",
        choose_text_2 = "喝智星",
        choose_text_3 = "嫖智星",
        choose_text_4 = "赌智星",
        id = 3024,
        question = "下列哪个是韩国球星？",
        type = 1,
    },

    [3025] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "慢牛基奇",
        choose_text_2 = "慢马基奇",
        choose_text_3 = "慢猪基奇",
        choose_text_4 = "慢狗基奇",
        id = 3025,
        question = "下列哪个是克罗地亚球星？",
        type = 1,
    },

    [3026] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "法尔烧",
        choose_text_2 = "法尔炖",
        choose_text_3 = "法尔蒸",
        choose_text_4 = "法尔烤",
        id = 3026,
        question = "下列哪个是哥伦比亚球星？",
        type = 1,
    },

    [3027] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "文科",
        choose_text_2 = "理科",
        choose_text_3 = "工科",
        choose_text_4 = "哲科",
        id = 3027,
        question = "下列哪个是波黑球星？",
        type = 1,
    },

    [3028] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "高托奥",
        choose_text_2 = "矮托奥",
        choose_text_3 = "胖托奥",
        choose_text_4 = "瘦托奥",
        id = 3028,
        question = "下列哪个是喀麦隆球星？",
        type = 1,
    },

    [3029] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "373",
        choose_text_2 = "374",
        choose_text_3 = "375",
        choose_text_4 = "376",
        id = 3029,
        question = "下列哪个是智利球星？",
        type = 1,
    },

    [3030] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "拉希尔",
        choose_text_2 = "希拉尔",
        choose_text_3 = "希拉里",
        choose_text_4 = "卡希尔",
        id = 3030,
        question = "下列哪个是澳大利亚球星？",
        type = 1,
    },

    [3031] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "萨马兰奇",
        choose_text_2 = "萨马拉斯",
        choose_text_3 = "萨达姆",
        choose_text_4 = "萨满祭司",
        id = 3031,
        question = "下列哪个是希腊球星？",
        type = 1,
    },

    [3032] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "鸡鸡图雷",
        choose_text_2 = "鸭鸭图雷",
        choose_text_3 = "猫猫图雷",
        choose_text_4 = "狗狗图雷",
        id = 3032,
        question = "下列哪个是科特迪瓦球星？",
        type = 1,
    },

    [3033] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "米克尔",
        choose_text_2 = "麦克尔",
        choose_text_3 = "法克尔",
        choose_text_4 = "乔科尔",
        id = 3033,
        question = "下列哪个是尼日利亚球星？",
        type = 1,
    },

    [3034] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "蒙鼓里",
        choose_text_2 = "蒙被里",
        choose_text_3 = "蒙塔里",
        choose_text_4 = "蒙庙里",
        id = 3034,
        question = "下列哪个是加纳球星？",
        type = 1,
    },

    [3035] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "多一万",
        choose_text_2 = "多两万",
        choose_text_3 = "多几万",
        choose_text_4 = "多诺万",
        id = 3035,
        question = "下列哪个是美国球星？",
        type = 1,
    },

    [3036] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "森德螺丝",
        choose_text_2 = "森德螺母",
        choose_text_3 = "森德螺栓",
        choose_text_4 = "森德螺帽",
        id = 3036,
        question = "下列哪个是瑞士球星？",
        type = 1,
    },

    [3037] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "阿根廷",
        choose_text_2 = "德国",
        choose_text_3 = "乌拉圭",
        choose_text_4 = "巴西",
        id = 3037,
        question = "第一届世界杯在哪里举行?",
        type = 1,
    },

    [3038] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "意大利",
        choose_text_2 = "智利",
        choose_text_3 = "巴西",
        choose_text_4 = "乌拉圭",
        id = 3038,
        question = "第一届世界杯冠军是谁?",
        type = 1,
    },

    [3039] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "雷米特杯",
        choose_text_2 = "德劳内杯",
        choose_text_3 = "斯韦思林杯",
        choose_text_4 = "土伦杯",
        id = 3039,
        question = "大力神杯的前身是什么?",
        type = 1,
    },

    [3040] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴西",
        choose_text_2 = "乌拉圭",
        choose_text_3 = "德国",
        choose_text_4 = "英格兰",
        id = 3040,
        question = "雷米特杯被哪支球队永久拥有了?",
        type = 1,
    },

    [3041] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "雷米特是巴西人",
        choose_text_2 = "巴西通过战争获得",
        choose_text_3 = "巴西三夺冠军",
        choose_text_4 = "巴西掷骰子获得",
        id = 3041,
        question = "为什么雷米特杯被巴西永久拥有了?",
        type = 1,
    },

    [3042] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "贝肯鲍尔",
        choose_text_2 = "巴拉克",
        choose_text_3 = "克洛泽",
        choose_text_4 = "克林斯曼",
        id = 3042,
        question = "被称为“足球皇帝”的德国人是谁?",
        type = 1,
    },

    [3043] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "杨旭",
        choose_text_2 = "武磊",
        choose_text_3 = "郜林",
        choose_text_4 = "郑智",
        id = 3043,
        question = "获得过亚洲足球先生的是？",
        type = 1,
    },

    [3044] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "2次",
        choose_text_2 = "1次",
        choose_text_3 = "3次",
        choose_text_4 = "4次",
        id = 3044,
        question = "广州恒大夺得过几次亚冠冠军？",
        type = 1,
    },

    [3045] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "工人体育场",
        choose_text_2 = "黄龙体育中心",
        choose_text_3 = "虹桥体育场",
        choose_text_4 = "老特拉福德",
        id = 3045,
        question = "绿城的主场是?",
        type = 1,
    },

    [3046] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "俄罗斯",
        choose_text_2 = "巴西",
        choose_text_3 = "瑞士",
        choose_text_4 = "德国",
        id = 3046,
        question = "2018世界杯在哪个国家举行？",
        type = 1,
    },

    [3047] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1次",
        choose_text_2 = "3次",
        choose_text_3 = "无",
        choose_text_4 = "4次",
        id = 3047,
        question = "绿城足球俱乐部的参加过几次亚冠",
        type = 1,
    },

    [3048] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1999",
        choose_text_2 = "1998",
        choose_text_3 = "2000",
        choose_text_4 = "1995",
        id = 3048,
        question = "绿城俱乐部成立的时间是？",
        type = 1,
    },

    [3049] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "酋长球场",
        choose_text_2 = "斯坦福桥",
        choose_text_3 = "JJB球场",
        choose_text_4 = "老特拉福德",
        id = 3049,
        question = "曼联的主场是?",
        type = 1,
    },

    [3050] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "绿魂",
        choose_text_2 = "绿粉",
        choose_text_3 = "绿迷",
        choose_text_4 = "绿忠",
        id = 3050,
        question = "绿城的球迷组织称为？",
        type = 1,
    },

    [3051] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "红色球场",
        choose_text_2 = "华南虎球场",
        choose_text_3 = "最低消费球场",
        choose_text_4 = "魔鬼主场",
        id = 3051,
        question = "广州恒大的主场被称为?",
        type = 1,
    },

    [3052] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "2012",
        choose_text_2 = "2009",
        choose_text_3 = "2010",
        choose_text_4 = "2008",
        id = 3052,
        question = "广州恒大成立的时间是？",
        type = 1,
    },

    [3053] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴塞罗那",
        choose_text_2 = "尤文图斯",
        choose_text_3 = "利物浦",
        choose_text_4 = "里昂",
        id = 3053,
        question = "法国球星亨利在去阿森纳之前效力于哪支球队?",
        type = 1,
    },

    [3054] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "博卡VS河床",
        choose_text_2 = "博卡VS飓风",
        choose_text_3 = "河床VS科隆",
        choose_text_4 = "科隆VS博卡",
        id = 3054,
        question = "阿根廷最火爆的“德比”是?",
        type = 1,
    },

    [3055] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "酋长球场",
        choose_text_2 = "糖果盒球场",
        choose_text_3 = "JJB球场",
        choose_text_4 = "安菲尔德",
        id = 3055,
        question = "博卡的主场名称?",
        type = 1,
    },

    [3056] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "博格坎普",
        choose_text_2 = "尤文图斯",
        choose_text_3 = "埃因霍温",
        choose_text_4 = "SBV精英",
        id = 3056,
        question = "哪位荷兰的著名球星因为“恐飞”而拒绝为国家队和俱乐部出战?",
        type = 1,
    },

    [3057] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "AC米兰",
        choose_text_2 = "国际米兰",
        choose_text_3 = "尤文图斯",
        choose_text_4 = "SBV精英",
        id = 3057,
        question = "意大利哪支球队获得的冠军杯冠军次数最多?",
        type = 1,
    },

    [3058] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "5次",
        choose_text_2 = "4次",
        choose_text_3 = "3次",
        choose_text_4 = "6次",
        id = 3058,
        question = "巴西获得了几次世界杯冠军?",
        type = 1,
    },

    [3059] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "维拉利尔",
        choose_text_2 = "巴塞罗那",
        choose_text_3 = "马德里竞技",
        choose_text_4 = "皇家马德里",
        id = 3059,
        question = "西甲哪支球队绰号是“黄色潜水艇”?",
        type = 1,
    },

    [3060] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "北京国安",
        choose_text_2 = "杭州绿城",
        choose_text_3 = "长春亚泰",
        choose_text_4 = "上海申花",
        id = 3060,
        question = "哪一家中超俱乐部的绰号叫“御林军”？",
        type = 1,
    },

    [3061] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "欧文",
        choose_text_2 = "特里",
        choose_text_3 = "鲁尼",
        choose_text_4 = "吉格斯",
        id = 3061,
        question = "在1996年足总杯决赛中，谁为曼联队攻入制胜球？",
        type = 1,
    },

    [3062] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "前锋",
        choose_text_2 = "中场",
        choose_text_3 = "后卫",
        choose_text_4 = "门将",
        id = 3062,
        question = "法比恩·巴特兹踢什么位置？",
        type = 1,
    },

    [3063] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "绿城和申花",
        choose_text_2 = "申花和国安",
        choose_text_3 = "申花和上港",
        choose_text_4 = "上港和富力",
        id = 3063,
        question = "中超当中上海德比是？",
        type = 1,
    },

    [3064] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "郜林",
        choose_text_2 = "J.马",
        choose_text_3 = "郑智",
        choose_text_4 = "杨智",
        id = 3064,
        question = "广州恒大最近一次夺得亚冠冠军的队长是谁？",
        type = 1,
    },

    [3065] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "阿根廷",
        choose_text_2 = "巴西",
        choose_text_3 = "意大利",
        choose_text_4 = "德国",
        id = 3065,
        question = "哪个国家夺得了1994年世界杯？",
        type = 1,
    },

    [3066] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1980",
        choose_text_2 = "1984",
        choose_text_3 = "1988",
        choose_text_4 = "1992",
        id = 3066,
        question = "在哪一年的奥运会上国际足联限定参加球员年龄需低于23岁？",
        type = 1,
    },

    [3067] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "本方球门区内",
        choose_text_2 = "本方半场内",
        choose_text_3 = "中圈弧内",
        choose_text_4 = "本方大禁区内",
        id = 3067,
        question = "足球比赛中一方踢球门球，本方接应队员不得在哪接球？",
        type = 1,
    },

    [3068] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "孙葆杰",
        choose_text_2 = "陆俊",
        choose_text_3 = "曹镜鉴",
        choose_text_4 = "侯明亮",
        id = 3068,
        question = "哪位中国裁判作为主裁判执法过世界杯决赛阶段的比赛？",
        type = 1,
    },

    [3069] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "算",
        choose_text_2 = "不算",
        choose_text_3 = "没有明确规定",
        choose_text_4 = "裁判说了算",
        id = 3069,
        question = "足球比赛中球压在边线上算不算出界?",
        type = 1,
    },

    [3070] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "罚任意球",
        choose_text_2 = "掷边线球",
        choose_text_3 = "主裁判坠球",
        choose_text_4 = "罚点球",
        id = 3070,
        question = "足球比赛进行中，球出边线，发球方是如何发球的？",
        type = 1,
    },

    [3071] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "英国",
        choose_text_2 = "中国",
        choose_text_3 = "巴西",
        choose_text_4 = "葡萄牙",
        id = 3071,
        question = "足球起源于哪个国家？",
        type = 1,
    },

    [3072] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "19世纪末",
        choose_text_2 = "20世纪初",
        choose_text_3 = "20世纪中期",
        choose_text_4 = "20世纪末",
        id = 3072,
        question = "职业足球出现在什么时代？",
        type = 1,
    },

    [3073] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1982",
        choose_text_2 = "1986",
        choose_text_3 = "1990",
        choose_text_4 = "1994",
        id = 3073,
        question = "神奇教练米卢蒂诺维奇第一次率队参加世界杯是哪一年?",
        type = 1,
    },

    [3074] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "冠军",
        choose_text_2 = "四强",
        choose_text_3 = "亚军",
        choose_text_4 = "八强",
        id = 3074,
        question = "绿城取得中超最好成绩是?",
        type = 1,
    },

    [3075] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "恒大和国安",
        choose_text_2 = "恒大和富力",
        choose_text_3 = "富力和泰达",
        choose_text_4 = "绿城和富力",
        id = 3075,
        question = "广州德比是那两支球队?",
        type = 1,
    },

    [3076] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "12个",
        choose_text_2 = "11个",
        choose_text_3 = "6个",
        choose_text_4 = "8个",
        id = 3076,
        question = "世界杯决赛阶段一场比赛进球最多的纪录是多少?",
        type = 1,
    },

    [3077] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1381",
        choose_text_2 = "1188",
        choose_text_3 = "1288",
        choose_text_4 = "1281",
        id = 3077,
        question = "贝利个人生涯的进球数为多少个?",
        type = 1,
    },

    [3078] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "英国",
        choose_text_2 = "法国",
        choose_text_3 = "德国",
        choose_text_4 = "意大利",
        id = 3078,
        question = "大力神杯的设计者是哪国人?",
        type = 1,
    },

    [3079] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "济科",
        choose_text_2 = "维阿",
        choose_text_3 = "古利特",
        choose_text_4 = "贝利",
        id = 3079,
        question = "“黑珍珠”是指的哪位著名球星?",
        type = 1,
    },

    [3080] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴西两胜",
        choose_text_2 = "巴西三胜",
        choose_text_3 = "意大利三胜",
        choose_text_4 = "巴西两平",
        id = 3080,
        question = "巴西与意大利世界杯史上交锋战绩如何?",
        type = 1,
    },

    [3081] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "5",
        choose_text_2 = "4",
        choose_text_3 = "3",
        choose_text_4 = "2",
        id = 3081,
        question = "意大利与阿根廷世界杯史上有个几次交锋?",
        type = 1,
    },

    [3082] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1994年",
        choose_text_2 = "1998年",
        choose_text_3 = "1990年",
        choose_text_4 = "1896年",
        id = 3082,
        question = "法国队夺得第一个世界杯冠军是在哪一届世界杯?",
        type = 1,
    },

    [3083] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "罗纳尔多",
        choose_text_2 = "贝利",
        choose_text_3 = "盖德·穆勒",
        choose_text_4 = "罗西",
        id = 3083,
        question = "世界杯决赛进球队员最年轻纪录是谁?",
        type = 1,
    },

    [3084] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "斯塔比尔",
        choose_text_2 = "莱昂尼达斯",
        choose_text_3 = "阿尔瓦雷斯",
        choose_text_4 = "蒙蒂",
        id = 3084,
        question = "历史上唯一一个代表不同国家参加世界杯决赛的球员是谁?",
        type = 1,
    },

    [3085] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1954瑞士世界杯",
        choose_text_2 = "1958瑞典世界杯",
        choose_text_3 = "1962智利世界杯",
        choose_text_4 = "1966英格兰世界杯",
        id = 3085,
        question = "中国足球第一次冲击世界杯是在哪一年世界杯?",
        type = 1,
    },

    [3086] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "大力神杯",
        choose_text_2 = "足协杯",
        choose_text_3 = "超级杯",
        choose_text_4 = "火神杯",
        id = 3086,
        question = "中超的冠军奖杯叫做什么?",
        type = 1,
    },

    [3087] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "恒大",
        choose_text_2 = "山东鲁能",
        choose_text_3 = "北京国安",
        choose_text_4 = "天津泰达",
        id = 3087,
        question = "中超历史上夺冠最多的队是?",
        type = 1,
    },

    [3088] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "加斯科因",
        choose_text_2 = "鲁尼",
        choose_text_3 = "迈克·欧文",
        choose_text_4 = "科尔",
        id = 3088,
        question = "1998年法国世界杯，被成为“金童”的英格兰球员是谁?",
        type = 1,
    },

    [3089] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "克劳奇",
        choose_text_2 = "伊布拉西莫维奇",
        choose_text_3 = "扬·科勒",
        choose_text_4 = "日基奇",
        id = 3089,
        question = "德国世界杯将亮相的足坛最高中锋是?",
        type = 1,
    },

    [3090] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "德国",
        choose_text_2 = "意大利",
        choose_text_3 = "巴西",
        choose_text_4 = "英格兰",
        id = 3090,
        question = "布冯是哪国门将?",
        type = 1,
    },

    [3091] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "贝克汉母",
        choose_text_2 = "贝克汉爸",
        choose_text_3 = "贝克汉爷",
        choose_text_4 = "贝克汉儿",
        id = 3091,
        question = "以下哪位是英国球星？",
        type = 1,
    },

    [3092] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "贝肯鲍尔",
        choose_text_2 = "扎加洛",
        choose_text_3 = "雅凯",
        choose_text_4 = "比拉尔多",
        id = 3092,
        question = "历史上第一个以球员和教练身份均夺取世界杯的人是谁?",
        type = 1,
    },

    [3093] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1970年",
        choose_text_2 = "1974年",
        choose_text_3 = "1978年",
        choose_text_4 = "1982年",
        id = 3093,
        question = "每场比赛可以换2人的规则是在哪年世界杯开始的?",
        type = 1,
    },

    [3094] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "雷米特",
        choose_text_2 = "罗伯特·格林",
        choose_text_3 = "丹尼尔",
        choose_text_4 = "阿维拉热",
        id = 3094,
        question = "世界杯的创始人是谁?",
        type = 1,
    },

    [3095] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "罗伯特·格林",
        choose_text_2 = "丹尼尔",
        choose_text_3 = "雷米特",
        choose_text_4 = "阿维拉热",
        id = 3095,
        question = "世界杯之父是谁?",
        type = 1,
    },

    [3096] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "2",
        choose_text_2 = "3",
        choose_text_3 = "4",
        choose_text_4 = "1",
        id = 3096,
        question = "二战前的最后一次世界杯是第几届?",
        type = 1,
    },

    [3097] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "布兰克",
        choose_text_2 = "亨利",
        choose_text_3 = "特雷泽盖",
        choose_text_4 = "杜加里",
        id = 3097,
        question = "引入“金球制胜”赛制后，打入世界杯决赛阶段第一个金球的球员是?",
        type = 1,
    },

    [3098] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴巴坎",
        choose_text_2 = "科特·特琴塞尔",
        choose_text_3 = "玻索西多",
        choose_text_4 = "兰格纽斯",
        id = 3098,
        question = "第一位主哨世界杯总决赛的主裁判是谁?",
        type = 1,
    },

    [3099] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴西",
        choose_text_2 = "意大利",
        choose_text_3 = "阿根廷",
        choose_text_4 = "荷兰",
        id = 3099,
        question = "1978年世界杯冠军是谁?",
        type = 1,
    },

    [3100] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "贝克汉母",
        choose_text_2 = "贝克汉爸",
        choose_text_3 = "贝克汉爷",
        choose_text_4 = "贝克汉儿",
        id = 3100,
        question = "以下哪位是英国球星？",
        type = 1,
    },

    [3101] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "10码",
        choose_text_2 = "12码",
        choose_text_3 = "15码",
        choose_text_4 = "20码以外",
        id = 3101,
        question = "足球比赛开球时,守方每一位队员需站在开球点多少码以外？",
        type = 1,
    },

    [3102] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "黄色",
        choose_text_2 = "红色",
        choose_text_3 = "橘色",
        choose_text_4 = "白色",
        id = 3102,
        question = "足球比赛时,驱逐球员出场用的牌子为?",
        type = 1,
    },

    [3103] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "90分钟",
        choose_text_2 = "80分钟",
        choose_text_3 = "70分钟",
        choose_text_4 = "60分钟",
        id = 3103,
        question = "一般国际足球赛的比赛时间为多长？",
        type = 1,
    },

    [3104] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "七人",
        choose_text_2 = "八人",
        choose_text_3 = "九人",
        choose_text_4 = "十人",
        id = 3104,
        question = "足球比赛时,出场比赛人数为每队十一人,若少于几人出场时,裁判员有权暂停或终止比赛？",
        type = 1,
    },

    [3105] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "一人",
        choose_text_2 = "二人",
        choose_text_3 = "三人",
        choose_text_4 = "四人",
        id = 3105,
        question = "足球比赛时,可替换人数为？",
        type = 1,
    },

    [3106] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "90分钟",
        choose_text_2 = "80分钟",
        choose_text_3 = "70分钟",
        choose_text_4 = "60分钟",
        id = 3106,
        question = "社会组织足球比赛的时间,在我国足球协会的规定是多少分钟？",
        type = 1,
    },

    [3107] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1/2个",
        choose_text_2 = "1/3个",
        choose_text_3 = "3/4个",
        choose_text_4 = "1个",
        id = 3107,
        question = "当球的几个球体,无论在空中或地面越过边线或端线,应判界外球？",
        type = 1,
    },

    [3108] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "重掷",
        choose_text_2 = "由对队掷球",
        choose_text_3 = "公证球",
        choose_text_4 = "获得自由球",
        id = 3108,
        question = "足球比赛时,如掷界外球动作违反规则,则应该怎么判罚？",
        type = 1,
    },

    [3109] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "球门球",
        choose_text_2 = "角球",
        choose_text_3 = "界外球",
        choose_text_4 = "以上皆是",
        id = 3109,
        question = "在何种情况下接球不算越位？",
        type = 1,
    },

    [3110] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "继续",
        choose_text_2 = "停止",
        choose_text_3 = "出界",
        choose_text_4 = "判罚球门球",
        id = 3110,
        question = "足球比赛时,当球碰到球门柱及角旗弹回场内,则比赛应该怎样？",
        type = 1,
    },

    [3111] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "台湾",
        choose_text_2 = "美国",
        choose_text_3 = "韩国",
        choose_text_4 = "中国",
        id = 3111,
        question = "2002年世界杯足球赛由日本和哪个国家共同举办？",
        type = 1,
    },

    [3112] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1年",
        choose_text_2 = "2年",
        choose_text_3 = "3年",
        choose_text_4 = "4年",
        id = 3112,
        question = "世界杯足球赛每几年举行一次？",
        type = 1,
    },

    [3113] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "35分钟",
        choose_text_2 = "40分钟",
        choose_text_3 = "45分钟",
        choose_text_4 = "50分钟",
        id = 3113,
        question = "世界杯足球比赛的时间,为上下半场各多少分钟？",
        type = 1,
    },

    [3114] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "5分钟",
        choose_text_2 = "10分钟",
        choose_text_3 = "15分钟",
        choose_text_4 = "20分钟",
        id = 3114,
        question = "世界杯足球比赛,中场休息的时间为多少分钟？",
        type = 1,
    },

    [3115] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "美洲",
        choose_text_2 = "欧洲",
        choose_text_3 = "亚洲",
        choose_text_4 = "南美洲",
        id = 3115,
        question = "现代足球运动起源于哪个州？",
        type = 1,
    },

    [3116] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "七名",
        choose_text_2 = "八名",
        choose_text_3 = "十名",
        choose_text_4 = "十一名",
        id = 3116,
        question = "一般足球比赛,上场比赛一队需派几名球员？",
        type = 1,
    },

    [3117] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "七名",
        choose_text_2 = "八名",
        choose_text_3 = "十名",
        choose_text_4 = "十一名",
        id = 3117,
        question = "一般足球比赛,下场比赛一队至少几名球员下场方可进行比赛？",
        type = 1,
    },

    [3118] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "曲棍球",
        choose_text_2 = "手球",
        choose_text_3 = "足球",
        choose_text_4 = "以上皆是",
        id = 3118,
        question = "下列何种运动,在位置安排会有一个守门员？",
        type = 1,
    },

    [3119] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "十二码球",
        choose_text_2 = "直接自由球",
        choose_text_3 = "间接自由球",
        choose_text_4 = "球门球",
        id = 3119,
        question = "足球比赛中,在禁区内守方球员严重犯规应怎么判罚？",
        type = 1,
    },

    [3120] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "前锋",
        choose_text_2 = "后卫",
        choose_text_3 = "守门员",
        choose_text_4 = "中场球员",
        id = 3120,
        question = "足球比赛中除发界外球外,只有什么人可以手触球？",
        type = 1,
    },

    [3121] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "脚尖传球",
        choose_text_2 = "脚外侧踢球",
        choose_text_3 = "脚底踢球",
        choose_text_4 = "脚跟踢球",
        id = 3121,
        question = "下列何种足球技术是身体向前移动时,将球传给处于身后队友的方法",
        type = 1,
    },

    [3122] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "脚外侧踢球",
        choose_text_2 = "脚跟踢球",
        choose_text_3 = "脚背踢球",
        choose_text_4 = "脚底踢球",
        id = 3122,
        question = "下列何种足球技术是可以让球产生弯曲飞行弧度的踢球方法",
        type = 1,
    },

    [3123] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "自由球",
        choose_text_2 = "角球",
        choose_text_3 = "边界球",
        choose_text_4 = "12码球",
        id = 3123,
        question = "足球运动员犯规或绊倒时判罚的原地踢球称为什么球？",
        type = 1,
    },

    [3124] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "毽子",
        choose_text_2 = "藤球",
        choose_text_3 = "蹴鞠",
        choose_text_4 = "蹴球",
        id = 3124,
        question = "古代足球称为",
        type = 1,
    },

    [3125] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "直接自由球",
        choose_text_2 = "角球",
        choose_text_3 = "间接自由球",
        choose_text_4 = "十二码球",
        id = 3125,
        question = "足球比赛时,守方球员在己方的十八码区域内,以手触球,应怎么判罚？",
        type = 1,
    },

    [3126] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "九码",
        choose_text_2 = "十码",
        choose_text_3 = "十二码",
        choose_text_4 = "十五码以外",
        id = 3126,
        question = "足球比赛时,罚踢十二码球时,除主罚者和守门员外,其他球员都要离开罚球区及距离罚球点多少码？",
        type = 1,
    },

    [3127] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "顶球",
        choose_text_2 = "抢球",
        choose_text_3 = "控球",
        choose_text_4 = "传球",
        id = 3127,
        question = "足球在合法动作范围内,利用身体部位或动作,逼使对方失去控球能力并取代控制权,称什么球？",
        type = 1,
    },

    [3128] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "角球",
        choose_text_2 = "球门球",
        choose_text_3 = "十二码罚球",
        choose_text_4 = "自由球",
        id = 3128,
        question = "足球比赛时,球由防守者踢出球门线,判什么球？",
        type = 1,
    },

    [3129] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "直接自由球",
        choose_text_2 = "角球",
        choose_text_3 = "球门球",
        choose_text_4 = "界外球",
        id = 3129,
        question = "足球比赛,球从球门范围以外的地方超过端线,而最后触球是攻方球员时,则由守方踢什么球？",
        type = 1,
    },

    [3130] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "5次",
        choose_text_2 = "2次",
        choose_text_3 = "4次",
        choose_text_4 = "3次",
        id = 3130,
        question = "恒大连续夺得了几次中超冠军？",
        type = 1,
    },

    [3131] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "八喜",
        choose_text_2 = "权健",
        choose_text_3 = "毅腾",
        choose_text_4 = "力帆",
        id = 3131,
        question = "浙江最近新增的中甲职业球队是哪只队？",
        type = 1,
    },

    [3132] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "ITTF",
        choose_text_2 = "FIFA",
        choose_text_3 = "GOLF",
        choose_text_4 = "FC",
        id = 3132,
        question = "国际足球联合会的英文缩写为什么？",
        type = 1,
    },

    [3133] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "A罗",
        choose_text_2 = "B罗",
        choose_text_3 = "C罗",
        choose_text_4 = "D罗",
        id = 3133,
        question = "下列哪个是葡萄牙球星？",
        type = 1,
    },

    [3134] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "梅东",
        choose_text_2 = "梅南",
        choose_text_3 = "梅西",
        choose_text_4 = "梅北",
        id = 3134,
        question = "下列哪个是阿根廷球星？",
        type = 1,
    },

    [3135] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "外牛尔",
        choose_text_2 = "内牛尔",
        choose_text_3 = "外马尔",
        choose_text_4 = "内马尔",
        id = 3135,
        question = "下列哪个是巴西球星？",
        type = 1,
    },

    [3136] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "黑帕德",
        choose_text_2 = "蓝帕德",
        choose_text_3 = "绿帕德",
        choose_text_4 = "红帕德",
        id = 3136,
        question = "下列哪个是英格兰球星？",
        type = 1,
    },

    [3137] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "上贝上",
        choose_text_2 = "下贝下",
        choose_text_3 = "里贝里",
        choose_text_4 = "外贝外",
        id = 3137,
        question = "下列哪个是法国球星？",
        type = 1,
    },

    [3138] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "粥佩西",
        choose_text_2 = "粉佩西",
        choose_text_3 = "面佩西",
        choose_text_4 = "饭佩西",
        id = 3138,
        question = "下列哪个是荷兰球星？",
        type = 1,
    },

    [3139] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "托风斯",
        choose_text_2 = "托火斯",
        choose_text_3 = "托雷斯",
        choose_text_4 = "托电斯",
        id = 3139,
        question = "下列哪个是西班牙球星？",
        type = 1,
    },

    [3140] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "撸管",
        choose_text_2 = "撸面",
        choose_text_3 = "鲁尼",
        choose_text_4 = "鲁大师",
        id = 3140,
        question = "下列哪个是英格兰球星？",
        type = 1,
    },

    [3141] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "苏亚粉丝",
        choose_text_2 = "苏亚肉丝",
        choose_text_3 = "苏亚黑丝",
        choose_text_4 = "苏亚蕾丝",
        id = 3141,
        question = "下列哪个是乌拉圭球星？",
        type = 1,
    },

    [3142] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "毛儿落",
        choose_text_2 = "发儿落",
        choose_text_3 = "皮儿落",
        choose_text_4 = "泪儿落",
        id = 3142,
        question = "下列哪个是意大利球星？",
        type = 1,
    },

    [3143] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "171",
        choose_text_2 = "272",
        choose_text_3 = "373",
        choose_text_4 = "474",
        id = 3143,
        question = "下列哪个是德国球星？",
        type = 1,
    },

    [3144] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "恐怕我",
        choose_text_2 = "恐怕你",
        choose_text_3 = "恐怕他",
        choose_text_4 = "恐怕怕",
        id = 3144,
        question = "下列哪个是比利时球星？",
        type = 1,
    },

    [3145] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "丰田龟左",
        choose_text_2 = "丰田龟右",
        choose_text_3 = "本田龟左",
        choose_text_4 = "本田龟右",
        id = 3145,
        question = "下列哪个是日本球星？",
        type = 1,
    },

    [3146] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "吃智星",
        choose_text_2 = "喝智星",
        choose_text_3 = "嫖智星",
        choose_text_4 = "赌智星",
        id = 3146,
        question = "下列哪个是韩国球星？",
        type = 1,
    },

    [3147] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "慢牛基奇",
        choose_text_2 = "慢马基奇",
        choose_text_3 = "慢猪基奇",
        choose_text_4 = "慢狗基奇",
        id = 3147,
        question = "下列哪个是克罗地亚球星？",
        type = 1,
    },

    [3148] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "法尔烧",
        choose_text_2 = "法尔炖",
        choose_text_3 = "法尔蒸",
        choose_text_4 = "法尔烤",
        id = 3148,
        question = "下列哪个是哥伦比亚球星？",
        type = 1,
    },

    [3149] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "文科",
        choose_text_2 = "理科",
        choose_text_3 = "工科",
        choose_text_4 = "哲科",
        id = 3149,
        question = "下列哪个是波黑球星？",
        type = 1,
    },

    [3150] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "高托奥",
        choose_text_2 = "矮托奥",
        choose_text_3 = "胖托奥",
        choose_text_4 = "瘦托奥",
        id = 3150,
        question = "下列哪个是喀麦隆球星？",
        type = 1,
    },

    [3151] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "373",
        choose_text_2 = "374",
        choose_text_3 = "375",
        choose_text_4 = "376",
        id = 3151,
        question = "下列哪个是智利球星？",
        type = 1,
    },

    [3152] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "拉希尔",
        choose_text_2 = "希拉尔",
        choose_text_3 = "希拉里",
        choose_text_4 = "卡希尔",
        id = 3152,
        question = "下列哪个是澳大利亚球星？",
        type = 1,
    },

    [3153] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "萨马兰奇",
        choose_text_2 = "萨马拉斯",
        choose_text_3 = "萨达姆",
        choose_text_4 = "萨满祭司",
        id = 3153,
        question = "下列哪个是希腊球星？",
        type = 1,
    },

    [3154] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "鸡鸡图雷",
        choose_text_2 = "鸭鸭图雷",
        choose_text_3 = "猫猫图雷",
        choose_text_4 = "狗狗图雷",
        id = 3154,
        question = "下列哪个是科特迪瓦球星？",
        type = 1,
    },

    [3155] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "米克尔",
        choose_text_2 = "麦克尔",
        choose_text_3 = "法克尔",
        choose_text_4 = "乔科尔",
        id = 3155,
        question = "下列哪个是尼日利亚球星？",
        type = 1,
    },

    [3156] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "蒙鼓里",
        choose_text_2 = "蒙被里",
        choose_text_3 = "蒙塔里",
        choose_text_4 = "蒙庙里",
        id = 3156,
        question = "下列哪个是加纳球星？",
        type = 1,
    },

    [3157] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "多一万",
        choose_text_2 = "多两万",
        choose_text_3 = "多几万",
        choose_text_4 = "多诺万",
        id = 3157,
        question = "下列哪个是美国球星？",
        type = 1,
    },

    [3158] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "森德螺丝",
        choose_text_2 = "森德螺母",
        choose_text_3 = "森德螺栓",
        choose_text_4 = "森德螺帽",
        id = 3158,
        question = "下列哪个是瑞士球星？",
        type = 1,
    },

    [3159] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "猪拉多纳",
        choose_text_2 = "牛拉多纳",
        choose_text_3 = "马拉多纳",
        choose_text_4 = "羊拉多纳",
        id = 3159,
        question = "阿根廷主教练叫什么？",
        type = 1,
    },

    [3160] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "梅东",
        choose_text_2 = "梅南",
        choose_text_3 = "梅西",
        choose_text_4 = "梅北",
        id = 3160,
        question = "以下哪个是阿根廷球星？",
        type = 1,
    },

    [3161] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "李东国",
        choose_text_2 = "李南国",
        choose_text_3 = "李西国",
        choose_text_4 = "李北国",
        id = 3161,
        question = "以下哪个是韩国球星？",
        type = 1,
    },

    [3162] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "东风破",
        choose_text_2 = "范佩西",
        choose_text_3 = "周结棍",
        choose_text_4 = "千里之外",
        id = 3162,
        question = "以下哪个是荷兰球星？",
        type = 1,
    },

    [3163] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "川口能活",
        choose_text_2 = "川口能死",
        choose_text_3 = "川口不活",
        choose_text_4 = "川口不死",
        id = 3163,
        question = "以下哪个是日本队的球星？",
        type = 1,
    },

    [3164] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "加图索",
        choose_text_2 = "减图索",
        choose_text_3 = "乘图索",
        choose_text_4 = "除图索",
        id = 3164,
        question = "以下哪个是意大利球星？",
        type = 1,
    },

    [3165] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "田中套套王",
        choose_text_2 = "田中雨伞王",
        choose_text_3 = "田中蓑衣王",
        choose_text_4 = "田中斗笠王",
        id = 3165,
        question = "以下哪个是日本球星？",
        type = 1,
    },

    [3166] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "柴卢",
        choose_text_2 = "米卢",
        choose_text_3 = "油卢",
        choose_text_4 = "盐卢",
        id = 3166,
        question = "2002年中国男子国家足球队主教练是？",
        type = 1,
    },

    [3167] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "阿里山",
        choose_text_2 = "阿里汉",
        choose_text_3 = "阿里郎",
        choose_text_4 = "阿里巴巴",
        id = 3167,
        question = "以下哪个教练带过中国队？",
        type = 1,
    },

    [3168] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "弱智",
        choose_text_2 = "郑智",
        choose_text_3 = "政智",
        choose_text_4 = "郑智化",
        id = 3168,
        question = "以下哪个是中国球星？",
        type = 1,
    },

    [3169] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "董卓",
        choose_text_2 = "董方卓",
        choose_text_3 = "方青卓",
        choose_text_4 = "方世玉",
        id = 3169,
        question = "以下哪位中国运动员在曼联队踢过球？",
        type = 1,
    },

    [3170] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "郑中士",
        choose_text_2 = "郑小世",
        choose_text_3 = "郑大世",
        choose_text_4 = "郑则仕",
        id = 3170,
        question = "以下哪个是朝鲜队前锋？",
        type = 1,
    },

    [3171] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "麦库",
        choose_text_2 = "米库",
        choose_text_3 = "水库",
        choose_text_4 = "军火库",
        id = 3171,
        question = "以下哪个是法国球星？",
        type = 1,
    },

    [3172] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "李青龙",
        choose_text_2 = "李白虎",
        choose_text_3 = "李红中",
        choose_text_4 = "李发财",
        id = 3172,
        question = "以下哪个是韩国球星？",
        type = 1,
    },

    [3173] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "阿萨莫阿",
        choose_text_2 = "阿娇莫阿",
        choose_text_3 = "柏芝莫阿",
        choose_text_4 = "冠希莫阿",
        id = 3173,
        question = "以下哪个是德国球星？",
        type = 1,
    },

    [3174] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "猪拉多纳",
        choose_text_2 = "牛拉多纳",
        choose_text_3 = "马拉多纳",
        choose_text_4 = "羊拉多纳",
        id = 3174,
        question = "阿根廷主教练叫什么？",
        type = 1,
    },

    [3175] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "梅东",
        choose_text_2 = "梅南",
        choose_text_3 = "梅西",
        choose_text_4 = "梅北",
        id = 3175,
        question = "以下哪个是阿根廷球星？",
        type = 1,
    },

    [3176] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "李东国",
        choose_text_2 = "李南国",
        choose_text_3 = "李西国",
        choose_text_4 = "李北国",
        id = 3176,
        question = "以下哪个是韩国球星？",
        type = 1,
    },

    [3177] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "东风破",
        choose_text_2 = "范佩西",
        choose_text_3 = "周结棍",
        choose_text_4 = "千里之外",
        id = 3177,
        question = "以下哪个是荷兰球星？",
        type = 1,
    },

    [3178] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "川口能活",
        choose_text_2 = "川口能死",
        choose_text_3 = "川口不活",
        choose_text_4 = "川口不死",
        id = 3178,
        question = "以下哪个是日本队的球星？",
        type = 1,
    },

    [3179] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "加图索",
        choose_text_2 = "减图索",
        choose_text_3 = "乘图索",
        choose_text_4 = "除图索",
        id = 3179,
        question = "以下哪个是意大利球星？",
        type = 1,
    },

    [3180] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "田中套套王",
        choose_text_2 = "田中雨伞王",
        choose_text_3 = "田中蓑衣王",
        choose_text_4 = "田中斗笠王",
        id = 3180,
        question = "以下哪个是日本球星？",
        type = 1,
    },

    [3181] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "柴卢",
        choose_text_2 = "米卢",
        choose_text_3 = "油卢",
        choose_text_4 = "盐卢",
        id = 3181,
        question = "2002年中国男子国家足球队主教练是？",
        type = 1,
    },

    [3182] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "阿里山",
        choose_text_2 = "阿里汉",
        choose_text_3 = "阿里郎",
        choose_text_4 = "阿里巴巴",
        id = 3182,
        question = "以下哪个教练带过中国队？",
        type = 1,
    },

    [3183] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "弱智",
        choose_text_2 = "郑智",
        choose_text_3 = "政智",
        choose_text_4 = "郑智化",
        id = 3183,
        question = "以下哪个是中国球星？",
        type = 1,
    },

    [3184] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "董卓",
        choose_text_2 = "董方卓",
        choose_text_3 = "方青卓",
        choose_text_4 = "方世玉",
        id = 3184,
        question = "以下哪位中国运动员在曼联队踢过球？",
        type = 1,
    },

    [3185] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "郑中士",
        choose_text_2 = "郑小世",
        choose_text_3 = "郑大世",
        choose_text_4 = "郑则仕",
        id = 3185,
        question = "以下哪个是朝鲜队前锋？",
        type = 1,
    },

    [3186] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "麦库",
        choose_text_2 = "米库",
        choose_text_3 = "水库",
        choose_text_4 = "军火库",
        id = 3186,
        question = "以下哪个是法国球星？",
        type = 1,
    },

    [3187] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "李青龙",
        choose_text_2 = "李白虎",
        choose_text_3 = "李红中",
        choose_text_4 = "李发财",
        id = 3187,
        question = "以下哪个是韩国球星？",
        type = 1,
    },

    [3188] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "阿萨莫阿",
        choose_text_2 = "阿娇莫阿",
        choose_text_3 = "柏芝莫阿",
        choose_text_4 = "冠希莫阿",
        id = 3188,
        question = "以下哪个是德国球星？",
        type = 1,
    },

    [3189] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "法国",
        choose_text_2 = "意大利",
        choose_text_3 = "德国",
        choose_text_4 = "巴西",
        id = 3189,
        question = "1998年世界杯在哪里举行？",
        type = 1,
    },

    [3190] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "德国",
        choose_text_2 = "阿根廷",
        choose_text_3 = "巴西",
        choose_text_4 = "意大利",
        id = 3190,
        question = "世界上获得世界杯最多的国家是",
        type = 1,
    },

    [3191] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "舍甫琴科",
        choose_text_2 = "阿莫鲁索",
        choose_text_3 = "比埃尔霍夫",
        choose_text_4 = "罗纳尔多",
        id = 3191,
        question = "1997—1998赛季意甲的最佳射手是",
        type = 1,
    },

    [3192] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "齐达内",
        choose_text_2 = "罗纳尔多",
        choose_text_3 = "菲戈",
        choose_text_4 = "比埃尔霍夫",
        id = 3192,
        question = "2001年世界足球先生是",
        type = 1,
    },

    [3193] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "15次",
        choose_text_2 = "16次",
        choose_text_3 = "18次",
        choose_text_4 = "20次",
        id = 3193,
        question = "利物浦获得过多少次联赛冠军",
        type = 1,
    },

    [3194] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1次",
        choose_text_2 = "2次",
        choose_text_3 = "3次",
        choose_text_4 = "4次",
        id = 3194,
        question = "尤文图斯获得过多少次欧洲优胜者杯",
        type = 1,
    },

    [3195] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "7次",
        choose_text_2 = "9次",
        choose_text_3 = "11次",
        choose_text_4 = "5次",
        id = 3195,
        question = "皇家马德里获得过几次欧洲冠军杯",
        type = 1,
    },

    [3196] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "阿根廷",
        choose_text_2 = "乌拉圭",
        choose_text_3 = "巴拉圭",
        choose_text_4 = "巴西",
        id = 3196,
        question = "门将齐拉维特是哪国人",
        type = 1,
    },

    [3197] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "意大利",
        choose_text_2 = "德国",
        choose_text_3 = "巴西",
        choose_text_4 = "阿根廷",
        id = 3197,
        question = "1990年世界杯冠军是",
        type = 1,
    },

    [3198] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "意大利",
        choose_text_2 = "巴西",
        choose_text_3 = "智利",
        choose_text_4 = "德国",
        id = 3198,
        question = "佩鲁贾前锋阿莫鲁索是那国人",
        type = 1,
    },

    [3199] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "齐达内",
        choose_text_2 = "罗纳尔多",
        choose_text_3 = "菲戈",
        choose_text_4 = "比埃尔霍夫",
        id = 3199,
        question = "2001年世界足球先生是",
        type = 1,
    },

    [3200] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "西赛",
        choose_text_2 = "小罗纳尔多",
        choose_text_3 = "保莱塔",
        choose_text_4 = "卡里埃",
        id = 3200,
        question = "2001—2002法甲联赛最佳球员是",
        type = 1,
    },

    [3201] = {
        answer = {"4"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "巴黎日耳曼",
        choose_text_2 = "摩纳哥",
        choose_text_3 = "皇马",
        choose_text_4 = "塞阿拉",
        id = 3201,
        question = "巴西后卫埃德米尔森效力于",
        type = 1,
    },

    [3202] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "里肯",
        choose_text_2 = "耶里梅斯",
        choose_text_3 = "弗林斯",
        choose_text_4 = "凯尔",
        id = 3202,
        question = "韩日世界杯德国10号球员是",
        type = 1,
    },

    [3203] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "国际米兰",
        choose_text_2 = "AC米兰",
        choose_text_3 = "尤文图斯",
        choose_text_4 = "皇马",
        id = 3203,
        question = "布冯效力于哪个球队",
        type = 1,
    },

    [3204] = {
        answer = {"2"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1995年",
        choose_text_2 = "1996年",
        choose_text_3 = "1997年",
        choose_text_4 = "1998年",
        id = 3204,
        question = "罗纳尔多加盟巴塞罗那的时间是",
        type = 1,
    },

    [3205] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "德国",
        choose_text_2 = "意大利",
        choose_text_3 = "西班牙",
        choose_text_4 = "法国",
        id = 3205,
        question = "世界杯参赛场次最多的国家是",
        type = 1,
    },

    [3206] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "1970年",
        choose_text_2 = "1974年",
        choose_text_3 = "1978年",
        choose_text_4 = "1966年",
        id = 3206,
        question = "那一年的世界杯比赛中，第一次出现红牌与黄牌制度？",
        type = 1,
    },

    [3207] = {
        answer = {"3"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "曲圣卿",
        choose_text_2 = "郝海东",
        choose_text_3 = "李金羽",
        choose_text_4 = "李毅",
        id = 3207,
        question = "2002年甲A最佳射手是",
        type = 1,
    },

    [3208] = {
        answer = {"1"},
        choose_icon_1 = 0,
        choose_icon_2 = 0,
        choose_icon_3 = 0,
        choose_icon_4 = 0,
        choose_text_1 = "德国",
        choose_text_2 = "意大利",
        choose_text_3 = "西班牙",
        choose_text_4 = "法国",
        id = 3208,
        question = "世界杯里进球最多的球队是",
        type = 1,
    },

}
