-- ./excel/system/ride/rideinfo.xlsx
return {

    [1001] = {
        activate_item = {},
        activeText = "主角38级赠送",
        activeType = 2,
        attr_effect = {"phy_defense=10", "mag_defense=10"},
        camSize = 3.5,
        desc = "北海雪山中修炼成精的妖马，浑身雪白，乘坐者会得到冰霜的庇护",
        flySpeed = 0.0,
        flymap = 0,
        height = 0,
        hideEffect = 1,
        id = 1001,
        mapIcon = "h7_zq_6",
        name = "冰灵马",
        player_level = 0,
        quality = 1,
        ride_level = 0,
        score = 20,
        shape = 4003,
        show = "activate_item",
        size = 1.1,
        speed = 3.5,
        talent = {},
        type = 1,
        valid_day = -1,
        walkerDis = 1.5,
    },

    [1002] = {
        activate_item = {},
        activeText = "",
        activeType = 0,
        attr_effect = {"phy_defense=20", "mag_defense=20", "max_hp=120"},
        camSize = 3.5,
        desc = "原本是家养的小猫，因接触到了龙霖产生妖变，成为了妖族，但它还是很亲近人",
        flySpeed = 0.0,
        flymap = 0,
        height = 0,
        hideEffect = 0,
        id = 1002,
        mapIcon = "h7_zq_5",
        name = "九命猫",
        player_level = 0,
        quality = 2,
        ride_level = 0,
        score = 30,
        shape = 4001,
        show = "activate_item",
        size = 1.1,
        speed = 3.5,
        talent = {},
        type = 1,
        valid_day = 7,
        walkerDis = 1.5,
    },

    [1003] = {
        activate_item = {},
        activeText = "",
        activeType = 0,
        attr_effect = {"phy_defense=35", "mag_defense=35", "max_hp=210"},
        camSize = 3.5,
        desc = "在仙山守卫珍宝的灵兽，浑身雷光闪闪，乘坐者会得到雷电的庇护",
        flySpeed = 0.0,
        flymap = 0,
        height = 0,
        hideEffect = 0,
        id = 1003,
        mapIcon = "h7_zq_2",
        name = "怒雷麒麟",
        player_level = 0,
        quality = 2,
        ride_level = 0,
        score = 70,
        shape = 4002,
        show = "activate_item",
        size = 1.1,
        speed = 3.5,
        talent = {},
        type = 1,
        valid_day = 7,
        walkerDis = 1.5,
    },

    [1004] = {
        activate_item = {},
        activeText = "",
        activeType = 0,
        attr_effect = {"phy_defense=40", "mag_defense=40", "max_hp=240"},
        camSize = 3.5,
        desc = "原本是一只机关牛，在主人死后，灵魂就寄存在里面，从而成了一只机械妖牛，神奇无比",
        flySpeed = 0.0,
        flymap = 0,
        height = 0,
        hideEffect = 0,
        id = 1004,
        mapIcon = "h7_zq_4",
        name = "黄金牛",
        player_level = 0,
        quality = 4,
        ride_level = 0,
        score = 80,
        shape = 4004,
        show = "activate_item",
        size = 1.1,
        speed = 3.5,
        talent = {},
        type = 1,
        valid_day = 7,
        walkerDis = 1.5,
    },

    [1005] = {
        activate_item = {},
        activeText = "充值返利赠送",
        activeType = 1,
        attr_effect = {"phy_defense=50", "mag_defense=50", "max_hp=300", "speed=20"},
        camSize = 4.5,
        desc = "翻云鲤本有机会成为一只蛟龙，只因为得罪了天神不得不在源潭中继续生存，拥有强大的水灵之力",
        flySpeed = 3.5,
        flymap = 1,
        height = 1,
        hideEffect = 0,
        id = 1005,
        mapIcon = "h7_zq_3",
        name = "翻云鲤",
        player_level = 0,
        quality = 4,
        ride_level = 0,
        score = 90,
        shape = 4005,
        show = "activate_item",
        size = 1.0,
        speed = 3.5,
        talent = {},
        type = 1,
        valid_day = -1,
        walkerDis = 1.5,
    },

    [1006] = {
        activate_item = {},
        activeText = "通过拍卖获得",
        activeType = 3,
        attr_effect = {"max_hp=100", "seal_ratio=4", "res_seal_ratio=4", "phy_critical_ratio=2", "mag_critical_ratio=2"},
        camSize = 4.5,
        desc = "青鸾原本是传说中的一只仙鸟，会给骑乘者带来奇妙的缘分",
        flySpeed = 3.5,
        flymap = 1,
        height = 1,
        hideEffect = 0,
        id = 1006,
        mapIcon = "h7_zq_1",
        name = "青鸾",
        player_level = 0,
        quality = 3,
        ride_level = 0,
        score = 100,
        shape = 4006,
        show = "activate_item",
        size = 1.0,
        speed = 3.5,
        talent = {},
        type = 1,
        valid_day = -1,
        walkerDis = 1.5,
    },

    [1007] = {
        activate_item = {},
        activeText = "",
        activeType = 0,
        attr_effect = {"phy_defense=15", "mag_defense=15", "max_hp=90"},
        camSize = 4.5,
        desc = "仙家炼制的宝葫芦，内刻飞行阵法，用于代步",
        flySpeed = 3.5,
        flymap = 1,
        height = 1,
        hideEffect = 0,
        id = 1007,
        mapIcon = "h7_zq_0",
        name = "仙葫",
        player_level = 0,
        quality = 1,
        ride_level = 0,
        score = 40,
        shape = 4000,
        show = "activate_item",
        size = 1.0,
        speed = 3.5,
        talent = {},
        type = 1,
        valid_day = 7,
        walkerDis = 1.5,
    },

    [1008] = {
        activate_item = {},
        activeText = "",
        activeType = 0,
        attr_effect = {"phy_defense=15", "mag_defense=15", "max_hp=90"},
        camSize = 4.5,
        desc = "墨家器械巅峰之作",
        flySpeed = 3.5,
        flymap = 1,
        height = 1,
        hideEffect = 0,
        id = 1008,
        mapIcon = "h7_zq_7",
        name = "墨家神鹰",
        player_level = 0,
        quality = 1,
        ride_level = 0,
        score = 40,
        shape = 4007,
        show = "activate_item",
        size = 1.0,
        speed = 3.5,
        talent = {},
        type = 1,
        valid_day = 7,
        walkerDis = 1.5,
    },

    [1009] = {
        activate_item = {},
        activeText = "0元礼包购买",
        activeType = 4,
        attr_effect = {"speed=20", "max_hp=300"},
        camSize = 4.5,
        desc = "蜀山飞剑，极具灵气可飞天入地，御宇海内。",
        flySpeed = 3.5,
        flymap = 1,
        height = 1,
        hideEffect = 0,
        id = 1009,
        mapIcon = "h7_zq_8",
        name = "凌云青霜",
        player_level = 0,
        quality = 1,
        ride_level = 0,
        score = 40,
        shape = 4008,
        show = "activate_item",
        size = 1.0,
        speed = 3.5,
        talent = {},
        type = 1,
        valid_day = -1,
        walkerDis = 1.5,
    },

}
