-- ./excel/system/ride/upgrade.xlsx
return {

    [0] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 1}},
        id = 0,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 1200,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [1] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 1}},
        id = 1,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 4300,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [2] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 2}},
        id = 2,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 9900,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [3] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 3}},
        id = 3,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 18800,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [4] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 4}},
        id = 4,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 32000,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [5] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 5}},
        id = 5,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 50900,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [6] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 6}},
        id = 6,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 77300,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [7] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 7}},
        id = 7,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 113500,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [8] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 8}},
        id = 8,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 162600,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [9] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 9}},
        id = 9,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 228700,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [10] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 10}},
        id = 10,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 317200,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [11] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 11}},
        id = 11,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 435100,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

    [12] = {
        attr_effect = {"0.0"},
        break_cost = {{["itemid"] = 11187, ["cnt"] = 12}},
        id = 12,
        jinshan = {"0.0"},
        qingshan = {"0.0"},
        ride_exp = 591700,
        shushan = {"0.0"},
        xingxiu = {"0.0"},
        yaochi = {"0.0"},
        yaoshen = {"0.0"},
    },

}
