-- ./excel/system/wing/wing.xlsx
return {

    [1] = {
        active_cost = {{["sid"] = 0}},
        buy_times = {},
        days = 0,
        figureid = 60100,
        icon = 27000,
        name = "九天神翼0阶",
        score = "",
        tex_size = 0.45,
        time_wing = 0,
        wing_effect = {},
        wing_id = 1,
    },

    [2] = {
        active_cost = {{["sid"] = 0}},
        buy_times = {},
        days = 0,
        figureid = 60101,
        icon = 27001,
        name = "九天神翼1阶",
        score = "",
        tex_size = 0.45,
        time_wing = 0,
        wing_effect = {},
        wing_id = 2,
    },

    [3] = {
        active_cost = {{["sid"] = 0}},
        buy_times = {},
        days = 0,
        figureid = 60102,
        icon = 27002,
        name = "九天神翼2阶",
        score = "",
        tex_size = 0.45,
        time_wing = 0,
        wing_effect = {},
        wing_id = 3,
    },

    [4] = {
        active_cost = {{["sid"] = 0}},
        buy_times = {},
        days = 0,
        figureid = 60103,
        icon = 27003,
        name = "九天神翼3阶",
        score = "",
        tex_size = 0.55,
        time_wing = 0,
        wing_effect = {},
        wing_id = 4,
    },

    [5] = {
        active_cost = {{["sid"] = 0}},
        buy_times = {},
        days = 0,
        figureid = 60104,
        icon = 27004,
        name = "九天神翼4阶",
        score = "",
        tex_size = 0.65,
        time_wing = 0,
        wing_effect = {},
        wing_id = 5,
    },

    [6] = {
        active_cost = {{["sid"] = 0}},
        buy_times = {},
        days = 0,
        figureid = 60105,
        icon = 27005,
        name = "九天神翼5阶",
        score = "",
        tex_size = 0.75,
        time_wing = 0,
        wing_effect = {},
        wing_id = 6,
    },

    [10] = {
        active_cost = {{["amount"] = 1, ["sid"] = 10149}},
        buy_times = {{["money_type"] = 10147, ["cost"] = 30, ["days"] = -1}, {["money_type"] = 3, ["cost"] = 50, ["days"] = 7}},
        days = 3,
        figureid = 60200,
        icon = 27006,
        name = "远古之翼",
        score = "100",
        tex_size = 0.7,
        time_wing = 1,
        wing_effect = {{["school"] = 1, ["effect_id"] = 5}, {["school"] = 2, ["effect_id"] = 5}, {["school"] = 3, ["effect_id"] = 5}, {["school"] = 4, ["effect_id"] = 5}, {["school"] = 5, ["effect_id"] = 5}, {["school"] = 6, ["effect_id"] = 5}},
        wing_id = 10,
    },

    [11] = {
        active_cost = {{["amount"] = 1, ["sid"] = 10150}},
        buy_times = {},
        days = -1,
        figureid = 60201,
        icon = 27007,
        name = "墨家木鸢",
        score = "100",
        tex_size = 0.7,
        time_wing = 1,
        wing_effect = {{["school"] = 1, ["effect_id"] = 6}, {["school"] = 2, ["effect_id"] = 6}, {["school"] = 3, ["effect_id"] = 6}, {["school"] = 4, ["effect_id"] = 6}, {["school"] = 5, ["effect_id"] = 6}, {["school"] = 6, ["effect_id"] = 6}},
        wing_id = 11,
    },

    [12] = {
        active_cost = {{["amount"] = 1, ["sid"] = 10151}},
        buy_times = {},
        days = -1,
        figureid = 60202,
        icon = 27008,
        name = "幻灵蝶恋",
        score = "100",
        tex_size = 0.7,
        time_wing = 1,
        wing_effect = {{["school"] = 1, ["effect_id"] = 7}, {["school"] = 2, ["effect_id"] = 7}, {["school"] = 3, ["effect_id"] = 7}, {["school"] = 4, ["effect_id"] = 7}, {["school"] = 5, ["effect_id"] = 7}, {["school"] = 6, ["effect_id"] = 7}},
        wing_id = 12,
    },

    [13] = {
        active_cost = {{["amount"] = 1, ["sid"] = 10152}},
        buy_times = {},
        days = -1,
        figureid = 60203,
        icon = 27009,
        name = "龙炎烈焰",
        score = "500",
        tex_size = 0.7,
        time_wing = 1,
        wing_effect = {{["school"] = 1, ["effect_id"] = 8}, {["school"] = 2, ["effect_id"] = 8}, {["school"] = 3, ["effect_id"] = 8}, {["school"] = 4, ["effect_id"] = 8}, {["school"] = 5, ["effect_id"] = 8}, {["school"] = 6, ["effect_id"] = 8}},
        wing_id = 13,
    },

    [14] = {
        active_cost = {{["amount"] = 1, ["sid"] = 10153}},
        buy_times = {},
        days = -1,
        figureid = 60204,
        icon = 27010,
        name = "冰蓝凤羽",
        score = "100",
        tex_size = 0.7,
        time_wing = 1,
        wing_effect = {{["school"] = 1, ["effect_id"] = 9}, {["school"] = 2, ["effect_id"] = 9}, {["school"] = 3, ["effect_id"] = 9}, {["school"] = 4, ["effect_id"] = 9}, {["school"] = 5, ["effect_id"] = 5}, {["school"] = 6, ["effect_id"] = 9}},
        wing_id = 14,
    },

    [15] = {
        active_cost = {{["amount"] = 1, ["sid"] = 10154}},
        buy_times = {{["money_type"] = 3, ["cost"] = 10000, ["days"] = -1}, {["money_type"] = 3, ["cost"] = 1000, ["days"] = 3}, {["money_type"] = 3, ["cost"] = 5000, ["days"] = 7}},
        days = 3,
        figureid = 60205,
        icon = 27011,
        name = "旭日金羽",
        score = "100",
        tex_size = 0.7,
        time_wing = 0,
        wing_effect = {{["school"] = 1, ["effect_id"] = 10}, {["school"] = 2, ["effect_id"] = 10}, {["school"] = 3, ["effect_id"] = 10}, {["school"] = 4, ["effect_id"] = 10}, {["school"] = 5, ["effect_id"] = 10}, {["school"] = 6, ["effect_id"] = 10}},
        wing_id = 15,
    },

    [16] = {
        active_cost = {{["amount"] = 1, ["sid"] = 11202}},
        buy_times = {},
        days = -1,
        figureid = 60207,
        icon = 27011,
        name = "天使之翼",
        score = "100",
        tex_size = 0.7,
        time_wing = 1,
        wing_effect = {{["school"] = 1, ["effect_id"] = 11}, {["school"] = 2, ["effect_id"] = 11}, {["school"] = 3, ["effect_id"] = 11}, {["school"] = 4, ["effect_id"] = 11}, {["school"] = 5, ["effect_id"] = 11}, {["school"] = 6, ["effect_id"] = 11}},
        wing_id = 16,
    },

}
