-- ./excel/system/org/positionauthority.xlsx
return {

    [1] = {
        agree_reject_join = 1,
        authorize_pos = {2, 3, 4, 5, 6},
        ban_talk = {2, 3, 4, 5, 6},
        clear_apply_list = 1,
        del_pos = {2, 3, 4, 5, 6, 7},
        edit_aim = 1,
        pos = "帮主",
        posid = 1,
        quit_leader = 1,
        send_mail = 1,
        set_auto_join = 1,
        start_activity = 1,
        to_formal = 1,
        upgrade_building = 1,
    },

    [2] = {
        agree_reject_join = 1,
        authorize_pos = {3, 4, 5, 6},
        ban_talk = {3, 4, 5, 6},
        clear_apply_list = 1,
        del_pos = {3, 4, 5, 6, 7},
        edit_aim = 1,
        pos = "副帮主",
        posid = 2,
        quit_leader = 0,
        send_mail = 1,
        set_auto_join = 0,
        start_activity = 1,
        to_formal = 1,
        upgrade_building = 1,
    },

    [3] = {
        agree_reject_join = 1,
        authorize_pos = {4, 5, 6},
        ban_talk = {4, 5, 6},
        clear_apply_list = 0,
        del_pos = {4, 5, 6, 7},
        edit_aim = 0,
        pos = "长老",
        posid = 3,
        quit_leader = 0,
        send_mail = 0,
        set_auto_join = 0,
        start_activity = 0,
        to_formal = 1,
        upgrade_building = 0,
    },

    [4] = {
        agree_reject_join = 0,
        authorize_pos = {0},
        ban_talk = {0},
        clear_apply_list = 0,
        del_pos = {0},
        edit_aim = 0,
        pos = "车夫",
        posid = 4,
        quit_leader = 0,
        send_mail = 0,
        set_auto_join = 0,
        start_activity = 0,
        to_formal = 0,
        upgrade_building = 0,
    },

    [5] = {
        agree_reject_join = 0,
        authorize_pos = {0},
        ban_talk = {0},
        clear_apply_list = 0,
        del_pos = {0},
        edit_aim = 0,
        pos = "宝贝",
        posid = 5,
        quit_leader = 0,
        send_mail = 0,
        set_auto_join = 0,
        start_activity = 0,
        to_formal = 0,
        upgrade_building = 0,
    },

    [6] = {
        agree_reject_join = 0,
        authorize_pos = {0},
        ban_talk = {0},
        clear_apply_list = 0,
        del_pos = {0},
        edit_aim = 0,
        pos = "帮众",
        posid = 6,
        quit_leader = 0,
        send_mail = 0,
        set_auto_join = 0,
        start_activity = 0,
        to_formal = 0,
        upgrade_building = 0,
    },

    [7] = {
        agree_reject_join = 0,
        authorize_pos = {0},
        ban_talk = {0},
        clear_apply_list = 0,
        del_pos = {0},
        edit_aim = 0,
        pos = "学徒",
        posid = 7,
        quit_leader = 0,
        send_mail = 0,
        set_auto_join = 0,
        start_activity = 0,
        to_formal = 0,
        upgrade_building = 0,
    },

}
