-- ./excel/perform/perform_artifact.xlsx
return {

    [9503] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用恢复系法术魔法值及控制点消耗减少25%，给召唤兽恢复气血效果增加20%",
        effectType = 1114,
        id = 9503,
        is_active = 2,
        name = "医者之心",
        pflogic = 9503,
        priority = 100,
        skill_icon = 51205,
        type_desc = "辅助",
    },

    [9504] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "所有减益和封印类技能成功率提高5%，上限由70%提高到80%。",
        effectType = 1114,
        id = 9504,
        is_active = 2,
        name = "咒师之心",
        pflogic = 9504,
        priority = 100,
        skill_icon = 51205,
        type_desc = "辅助",
    },

    [9505] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "召唤的杏黄旗和天兵的所有属性提高5%",
        effectType = 1114,
        id = 9505,
        is_active = 2,
        name = "驭者之心",
        pflogic = 9505,
        priority = 100,
        skill_icon = 51205,
        type_desc = "辅助",
    },

    [9506] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "与普通NPC战斗时，逃跑成功几率增加20%",
        effectType = 1114,
        id = 9506,
        is_active = 2,
        name = "影遁",
        pflogic = 9506,
        priority = 100,
        skill_icon = 51205,
        type_desc = "辅助",
    },

    [9509] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "每次受击时愤怒值获得额外增加2",
        effectType = 1114,
        id = 9509,
        is_active = 2,
        name = "忍耐",
        pflogic = 9509,
        priority = 100,
        skill_icon = 51202,
        type_desc = "辅助",
    },

    [9510] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "每次受到异常状态时，愤怒值增加5；持续状态中不增加",
        effectType = 1114,
        id = 9510,
        is_active = 2,
        name = "怒火",
        pflogic = 9510,
        priority = 100,
        skill_icon = 51202,
        type_desc = "辅助",
    },

    [9513] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "将鬼魂性质生物打倒时，有50%几率可以将其打出战斗",
        effectType = 1114,
        id = 9513,
        is_active = 2,
        name = "驱鬼",
        pflogic = 9513,
        priority = 100,
        skill_icon = 51207,
        type_desc = "辅助",
    },

    [9514] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "将鬼魂性质生物打倒时，有50%几率可以将其打出战斗",
        effectType = 1114,
        id = 9514,
        is_active = 2,
        name = "操魂者",
        pflogic = 9514,
        priority = 100,
        skill_icon = 51207,
        type_desc = "辅助",
    },

    [9517] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "当前气血>上限50%时，伤害结果降低5%；气血≤上限50%时，伤害结果增加10%",
        effectType = 1114,
        id = 9517,
        is_active = 2,
        name = "隐忍",
        pflogic = 9517,
        priority = 100,
        skill_icon = 50128,
        type_desc = "辅助",
    },

    [9518] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用封印类法术命中时有20%使其持续回合数+1",
        effectType = 1114,
        id = 9518,
        is_active = 2,
        name = "信仰",
        pflogic = 9518,
        priority = 100,
        skill_icon = 50218,
        type_desc = "辅助",
    },

    [9519] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "在被封印类法术命中时有20%使其持续回合数-1",
        effectType = 1114,
        id = 9519,
        is_active = 2,
        name = "聚神",
        pflogic = 9519,
        priority = 100,
        skill_icon = 50145,
        type_desc = "辅助",
    },

    [9520] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "在使用回复类法术时有20%造成200%的治疗效果",
        effectType = 1114,
        id = 9520,
        is_active = 2,
        name = "扶伤",
        pflogic = 9520,
        priority = 100,
        skill_icon = 50145,
        type_desc = "辅助",
    },

    [9521] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "每次受击时SP获得额外增加2",
        effectType = 1114,
        id = 9521,
        is_active = 2,
        name = "忍耐",
        pflogic = 9521,
        priority = 100,
        skill_icon = 50145,
        type_desc = "辅助",
    },

    [9524] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "担任队长时，所有队友速度增加2%",
        effectType = 1114,
        id = 9524,
        is_active = 2,
        name = "速度光环",
        pflogic = 9524,
        priority = 100,
        skill_icon = 50145,
        type_desc = "辅助",
    },

    [9525] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "普通攻击有5%概率反击",
        effectType = 1114,
        id = 9525,
        is_active = 2,
        name = "反击",
        pflogic = 9525,
        priority = 100,
        skill_icon = 50147,
        type_desc = "辅助",
    },

    [9526] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "施展招式时，有5%的概率使本回合的速率提高10%。",
        effectType = 1114,
        id = 9526,
        is_active = 2,
        name = "冲锋",
        pflogic = 9526,
        priority = 100,
        skill_icon = 50147,
        type_desc = "辅助",
    },

    [9527] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被毒时受到的损失降低至20%，但被毒回合加倍。",
        effectType = 1114,
        id = 9527,
        is_active = 2,
        name = "耐毒",
        pflogic = 9527,
        priority = 100,
        skill_icon = 50147,
        type_desc = "辅助",
    },

    [9528] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "可以攻击隐身目标，但对其伤害结果降低50%。",
        effectType = 1114,
        id = 9528,
        is_active = 2,
        name = "感知",
        pflogic = 9528,
        priority = 100,
        skill_icon = 50147,
        type_desc = "辅助",
    },

    [9529] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "倒地时，10%的概率自动复活并恢复一定量气血",
        effectType = 1114,
        id = 9529,
        is_active = 2,
        name = "神佑",
        pflogic = 9529,
        priority = 100,
        skill_icon = 50147,
        type_desc = "辅助",
    },

    [9530] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "战斗中使用药物效果提高至110%",
        effectType = 1114,
        id = 9530,
        is_active = 2,
        name = "药师",
        pflogic = 9530,
        priority = 100,
        skill_icon = 50147,
        type_desc = "辅助",
    },

}
