-- ./excel/perform/perform_fabao.xlsx
return {

    [4601] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使自身每回合结束时获得5+等级*2点愤怒，持续4回合",
        effectType = 1114,
        id = 4601,
        is_active = 1,
        name = "战神附体",
        pflogic = 4601,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4602] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用时立即获得8点愤怒",
        effectType = 1114,
        id = 4602,
        is_active = 0,
        name = "愤怒强化I",
        pflogic = 4602,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4603] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "每回合额外回复4点愤怒",
        effectType = 1114,
        id = 4603,
        is_active = 0,
        name = "愤怒强化II",
        pflogic = 4603,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4604] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "战神附体持续回合+1",
        effectType = 1114,
        id = 4604,
        is_active = 0,
        name = "愤怒掌控I",
        pflogic = 4604,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4605] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "战神附体有效时间内死亡时保留20%愤怒",
        effectType = 1114,
        id = 4605,
        is_active = 0,
        name = "愤怒掌控II",
        pflogic = 4605,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4606] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "回复我方单体目标(技能等级*1.5+5)%气血和法力",
        effectType = 1114,
        id = 4606,
        is_active = 1,
        name = "春风化雨",
        pflogic = 4606,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4607] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "气血回复量提升5%",
        effectType = 1114,
        id = 4607,
        is_active = 0,
        name = "治疗强化I",
        pflogic = 4607,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4608] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "法力回复量提升5%",
        effectType = 1114,
        id = 4608,
        is_active = 0,
        name = "治疗强化II",
        pflogic = 4608,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4609] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "接下来3回合内受到所有伤害降低10%",
        effectType = 1114,
        id = 4609,
        is_active = 0,
        name = "抵抗",
        pflogic = 4609,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4610] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "接下来3回合内法力消耗降低10%",
        effectType = 1114,
        id = 4610,
        is_active = 0,
        name = "冥想",
        pflogic = 4610,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4611] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使对方单人每回合结束时降低5+技能等级*2点愤怒，持续4回合",
        effectType = 1114,
        id = 4611,
        is_active = 1,
        name = "恶魔诅咒",
        pflogic = 4611,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4612] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "每回合额外降低目标4点愤怒",
        effectType = 1114,
        id = 4612,
        is_active = 0,
        name = "诅咒强化I",
        pflogic = 4612,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4613] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用时立即减少目标8点愤怒",
        effectType = 1114,
        id = 4613,
        is_active = 0,
        name = "诅咒强化II",
        pflogic = 4613,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4614] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "恶魔诅咒持续回合+1",
        effectType = 1114,
        id = 4614,
        is_active = 0,
        name = "诅咒掌控I",
        pflogic = 4614,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4615] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "恶魔诅咒持续回合内，使用特技消耗提高10%",
        effectType = 1114,
        id = 4615,
        is_active = 0,
        name = "诅咒掌控II",
        pflogic = 4615,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4616] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "提高人物等级*技能等级*5%的法术攻击",
        effectType = 1114,
        id = 4616,
        is_active = 1,
        name = "法术强化",
        pflogic = 4616,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4617] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "额外提升人物等级*0.15法术攻击",
        effectType = 1114,
        id = 4617,
        is_active = 0,
        name = "法攻强化",
        pflogic = 4617,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4618] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "法术伤害结果提升人物等级*0.25",
        effectType = 1114,
        id = 4618,
        is_active = 0,
        name = "法伤强化",
        pflogic = 4618,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4619] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "法术暴击几率提高3%",
        effectType = 1114,
        id = 4619,
        is_active = 0,
        name = "法爆强化",
        pflogic = 4619,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4620] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "忽视5%法术防御",
        effectType = 1114,
        id = 4620,
        is_active = 0,
        name = "法防忽视",
        pflogic = 4620,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4621] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "提高人物等级*技能等级*5%的物理攻击",
        effectType = 1114,
        id = 4621,
        is_active = 1,
        name = "攻击强化",
        pflogic = 4621,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4622] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "额外提升人物等级*0.15物理攻击",
        effectType = 1114,
        id = 4622,
        is_active = 0,
        name = "物攻强化",
        pflogic = 4622,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4623] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "物理伤害结果提升人物等级*0.25",
        effectType = 1114,
        id = 4623,
        is_active = 0,
        name = "物攻强化",
        pflogic = 4623,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4624] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "物理暴击几率提高3%",
        effectType = 1114,
        id = 4624,
        is_active = 0,
        name = "暴击强化",
        pflogic = 4624,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4625] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "忽视5%物理防御",
        effectType = 1114,
        id = 4625,
        is_active = 0,
        name = "物防忽视",
        pflogic = 4625,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4626] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "提高(人物等级*(0.03*技能等级)+10)的速度",
        effectType = 1114,
        id = 4626,
        is_active = 0,
        name = "迅捷",
        pflogic = 4626,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4627] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "额外提高人物等级*0.1的速度",
        effectType = 1114,
        id = 4627,
        is_active = 0,
        name = "速度强化",
        pflogic = 4627,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4628] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "封印命中提高1%",
        effectType = 1114,
        id = 4628,
        is_active = 0,
        name = "命中强化",
        pflogic = 4628,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4629] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "迅捷技能等级+2",
        effectType = 1114,
        id = 4629,
        is_active = 0,
        name = "迅捷强化",
        pflogic = 4629,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4630] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "提高3%封印抵抗和封印命中",
        effectType = 1114,
        id = 4630,
        is_active = 0,
        name = "封印强化",
        pflogic = 4630,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4631] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "有(3.5%+技能等级*1.5%)概率抵消35%物理伤害",
        effectType = 1114,
        id = 4631,
        is_active = 0,
        name = "物伤减免",
        pflogic = 4631,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4632] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "触发物伤减免概率提高2%",
        effectType = 1114,
        id = 4632,
        is_active = 0,
        name = "减免强化I",
        pflogic = 4632,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4633] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "物伤减免抵消的物理伤害效果提高5%",
        effectType = 1114,
        id = 4633,
        is_active = 0,
        name = "减免强化II",
        pflogic = 4633,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4634] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "物伤减免触发时，临时提升物理防御8%，持续2回合",
        effectType = 1114,
        id = 4634,
        is_active = 0,
        name = "固守",
        pflogic = 4634,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4635] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "生命低于33%，物伤减免触发几率提高10%",
        effectType = 1114,
        id = 4635,
        is_active = 0,
        name = "潜力觉醒",
        pflogic = 4635,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4636] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "提升(人物等级*(0.03*技能等级)+10)的治疗强度",
        effectType = 1114,
        id = 4636,
        is_active = 0,
        name = "潜能爆发",
        pflogic = 4636,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4637] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "额外提高0.1*人物等级的治疗强度",
        effectType = 1114,
        id = 4637,
        is_active = 0,
        name = "治疗强化I",
        pflogic = 4637,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4638] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用治疗法术时，魔法消耗降低7%",
        effectType = 1114,
        id = 4638,
        is_active = 0,
        name = "治疗强化II",
        pflogic = 4638,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4639] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "觉醒技能等级+2",
        effectType = 1114,
        id = 4639,
        is_active = 0,
        name = "潜力掌控",
        pflogic = 4639,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4640] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "治疗暴击几率提高3%",
        effectType = 1114,
        id = 4640,
        is_active = 0,
        name = "神医在世",
        pflogic = 4640,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4641] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "受到法术伤害时，有技能等级*1.5%+4.5%的概率将伤害的35%转化为自身气血",
        effectType = 1114,
        id = 4641,
        is_active = 0,
        name = "法伤减免",
        pflogic = 4641,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4642] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "法伤减免触发概率提高2%",
        effectType = 1114,
        id = 4642,
        is_active = 0,
        name = "减免强化I",
        pflogic = 4642,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4643] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "法伤减免转化效果提高2%",
        effectType = 1114,
        id = 4643,
        is_active = 0,
        name = "减免强化II",
        pflogic = 4643,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4644] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "法伤减免有10%概率使转化效果加倍",
        effectType = 1114,
        id = 4644,
        is_active = 0,
        name = "转化强化",
        pflogic = 4644,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [4645] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "法伤减免触发时，为自身回复魔法，数量为伤害吸收量的35%",
        effectType = 1114,
        id = 4645,
        is_active = 0,
        name = "潜力觉醒",
        pflogic = 4645,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

}
