-- ./excel/perform/perform_npc.xlsx
return {

    [3000] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "连续攻击目标3次",
        effectType = 1104,
        id = 3000,
        is_active = 1,
        name = "三连击",
        passiveIcon = "",
        pflogic = 3000,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [3001] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "对目标造成较高伤害",
        effectType = 1102,
        id = 3001,
        is_active = 1,
        name = "武痴的愤怒",
        passiveIcon = "",
        pflogic = 3001,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [3002] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "极高伤害",
        effectType = 1102,
        id = 3002,
        is_active = 1,
        name = "射虎之弓",
        passiveIcon = "",
        pflogic = 3002,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [3003] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对2目标使用迷魂（1503）",
        effectType = 1203,
        id = 3003,
        is_active = 1,
        name = "情殇",
        passiveIcon = "",
        pflogic = 3003,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [3004] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "单体物理攻击，造成目标血量上限10%的伤害。",
        effectType = 1102,
        id = 3004,
        is_active = 1,
        name = "斩情",
        passiveIcon = "",
        pflogic = 3004,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [3005] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "该技能只能对己方许仙使用",
        effectType = 1204,
        id = 3005,
        is_active = 0,
        name = "点化",
        passiveIcon = "",
        pflogic = 3005,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [3006] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对敌方7个目标造成【skill*200+300】的固定伤害。",
        effectType = 1201,
        id = 3006,
        is_active = 1,
        name = "真·金刚伏魔",
        passiveIcon = "",
        pflogic = 3006,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3007] = {
        ai_action_type = 207,
        ai_target = 2,
        cd = 0,
        desc = "群体复活，复活2个目标，并恢复30%气血",
        effectType = 1205,
        id = 3007,
        is_active = 1,
        name = "真·轮回",
        passiveIcon = "",
        pflogic = 3007,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体复活",
    },

    [3008] = {
        ai_action_type = 104,
        ai_target = 3,
        cd = 0,
        desc = "单体恢复，使友方目标恢复至气血上限100%；此技能无法对自己使用",
        effectType = 1207,
        id = 3008,
        is_active = 1,
        name = "真·佛法无边",
        passiveIcon = "",
        pflogic = 3008,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体恢复",
    },

    [3009] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对敌方全体造成一次固定伤害，【100+skill*20】，并扣除20%伤害量的法力值。",
        effectType = 1102,
        id = 3009,
        is_active = 1,
        name = "天地无极",
        passiveIcon = "",
        pflogic = 3009,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3010] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "受到的所有伤害降低70%，持续1回合。存在此BUFF时，有特殊的效果标识。",
        effectType = 0,
        id = 3010,
        is_active = 1,
        name = "天佛降世",
        passiveIcon = "",
        pflogic = 3010,
        priority = 100,
        skill_icon = 0,
        type_desc = "减伤",
    },

    [3011] = {
        ai_action_type = 202,
        ai_target = 2,
        cd = 0,
        desc = "随机对敌方三个目标使用封印技能，百分百命中，封印效果同青城山技能1502，有效回合3回合",
        effectType = 1207,
        id = 3011,
        is_active = 1,
        name = "秘法封印",
        passiveIcon = "",
        pflogic = 3011,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体封印",
    },

    [3012] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "对敌方许仙使用",
        effectType = 1202,
        id = 3012,
        is_active = 1,
        name = "感化",
        passiveIcon = "",
        pflogic = 3012,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [3013] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "偷取敌方一定银币",
        effectType = 0,
        id = 3013,
        is_active = 1,
        name = "妙手空空",
        passiveIcon = "",
        pflogic = 3013,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [3014] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "死亡后尸体保留在原地不飞出战斗场景，能被复活技能复活",
        effectType = 0,
        id = 3014,
        is_active = 0,
        name = "尸体保留 ",
        passiveIcon = "",
        pflogic = 3014,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [3015] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3015,
        is_active = 1,
        name = "噬魂血球",
        passiveIcon = "",
        pflogic = 3015,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3016] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3016,
        is_active = 1,
        name = "九幽地狱",
        passiveIcon = "",
        pflogic = 3016,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3017] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3017,
        is_active = 1,
        name = "鬼斩心神",
        passiveIcon = "",
        pflogic = 3017,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3018] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3018,
        is_active = 1,
        name = "地焰燃身",
        passiveIcon = "",
        pflogic = 3018,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3019] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3019,
        is_active = 1,
        name = "混沌初开",
        passiveIcon = "",
        pflogic = 3019,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3020] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3020,
        is_active = 1,
        name = "魔音贯脑",
        passiveIcon = "",
        pflogic = 3020,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3021] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3021,
        is_active = 1,
        name = "万法皆空",
        passiveIcon = "",
        pflogic = 3021,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3022] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3022,
        is_active = 1,
        name = "一剑西来",
        passiveIcon = "",
        pflogic = 3022,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3023] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3023,
        is_active = 1,
        name = "金乌真火",
        passiveIcon = "",
        pflogic = 3023,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3024] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "召唤小怪",
        effectType = 0,
        id = 3024,
        is_active = 0,
        name = "召唤",
        passiveIcon = "",
        pflogic = 3024,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [3025] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对多目标造成伤害",
        effectType = 0,
        id = 3025,
        is_active = 0,
        name = "自爆",
        passiveIcon = "",
        pflogic = 3025,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [3026] = {
        ai_action_type = 202,
        ai_target = 2,
        cd = 0,
        desc = "对多目标封印",
        effectType = 0,
        id = 3026,
        is_active = 1,
        name = "封灵两次",
        passiveIcon = "",
        pflogic = 3026,
        priority = 100,
        skill_icon = 0,
        type_desc = "封印",
    },

    [4200] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "免疫一切封印技能",
        effectType = 0,
        id = 4200,
        is_active = 0,
        name = "定心",
        passiveIcon = "",
        pflogic = 4200,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4201] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "自身死亡之后，将射虎之弓遗传给场上随机一个活着的具有“李广意志”技能的队友，使队友获得“射虎之弓”技能",
        effectType = 0,
        id = 4201,
        is_active = 0,
        name = "遗失之弓",
        passiveIcon = "",
        pflogic = 4201,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4202] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被赋予“射虎之弓”之后，则只使用“射虎之弓”技能",
        effectType = 0,
        id = 4202,
        is_active = 0,
        name = "李广意志",
        passiveIcon = "",
        pflogic = 4202,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4204] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "若妖道死亡，则立即进入复仇状态，复仇状态下伤害为正常的2倍，封印技能作用目标增加1个",
        effectType = 0,
        id = 4204,
        is_active = 0,
        name = "复仇1",
        passiveIcon = "",
        pflogic = 4204,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4205] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "若情妖死亡，则立即进入复仇状态，复仇状态下伤害为正常的2倍",
        effectType = 0,
        id = 4205,
        is_active = 0,
        name = "复仇2",
        passiveIcon = "",
        pflogic = 4205,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4206] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "每回合初，自动解除自身一切封印状态",
        effectType = 0,
        id = 4206,
        is_active = 0,
        name = "清心",
        passiveIcon = "",
        pflogic = 4206,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4207] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "回合初下达指挥指令：集火XXX（XXX为随机一个敌方目标），则本回合所有队友攻击集火目标，本行动不占用回合",
        effectType = 0,
        id = 4207,
        is_active = 0,
        name = "指挥",
        passiveIcon = "",
        pflogic = 4207,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4208] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "物理攻击和法术攻击增加50%",
        effectType = 0,
        id = 4208,
        is_active = 0,
        name = "狂暴",
        passiveIcon = "",
        pflogic = 4208,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4209] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "若死亡则2回后合自动复活，恢复50%气血",
        effectType = 0,
        id = 4209,
        is_active = 0,
        name = "回春术",
        passiveIcon = "",
        pflogic = 4209,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4211] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "受到单体攻击（无论法术物理，法术）后立刻使用技能反击目标，且必定暴击，有偷袭技能的目标不会被反击",
        effectType = 0,
        id = 4211,
        is_active = 0,
        name = "究极反击",
        passiveIcon = "",
        pflogic = 4211,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4212] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "攻击伤害减少30%",
        effectType = 0,
        id = 4212,
        is_active = 0,
        name = "迷失",
        passiveIcon = "",
        pflogic = 4212,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4213] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "姐妹情深1",
        effectType = 0,
        id = 4213,
        is_active = 0,
        name = "姐妹情深1",
        passiveIcon = "",
        pflogic = 4213,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4214] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "姐妹情深2",
        effectType = 0,
        id = 4214,
        is_active = 0,
        name = "姐妹情深2",
        passiveIcon = "",
        pflogic = 4214,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4215] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "当血量低于0时，恢复100%血量。",
        effectType = 0,
        id = 4215,
        is_active = 0,
        name = "重生",
        passiveIcon = "",
        pflogic = 4215,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4216] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "战斗开始，法海身上携带5层魔之气。每层魔之气减免10%的伤害。",
        effectType = 0,
        id = 4216,
        is_active = 0,
        name = "魔气缠身",
        passiveIcon = "",
        pflogic = 4216,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4217] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "怪物死亡时，会触发一次自爆，自爆会削弱己方BOSS一层【魔之气】BUFF，该技能不受封印影响，若主怪还存活，该怪物会100%状态复活。",
        effectType = 0,
        id = 4217,
        is_active = 0,
        name = "反噬",
        passiveIcon = "",
        pflogic = 4217,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4218] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "携带该技能的小怪被封印后，立刻解除异常状态，并承受30%的气血上限的伤害。若主怪存活，该角色气血低于0时，恢复100%气血。",
        effectType = 0,
        id = 4218,
        is_active = 0,
        name = "闭口禅",
        passiveIcon = "",
        pflogic = 4218,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4219] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "收到攻击时，反震伤害",
        effectType = 0,
        id = 4219,
        is_active = 0,
        name = "炸弹人",
        passiveIcon = "",
        pflogic = 4219,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4220] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "召唤神雷，攻击敌方全体目标",
        effectType = 1201,
        id = 4220,
        is_active = 1,
        name = "召唤天雷",
        passiveIcon = "",
        pflogic = 4220,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [4221] = {
        ai_action_type = 109,
        ai_target = 2,
        cd = 0,
        desc = "召唤小怪",
        effectType = 1202,
        id = 4221,
        is_active = 1,
        name = "金玉满堂",
        passiveIcon = "",
        pflogic = 4221,
        priority = 3000,
        skill_icon = 0,
        type_desc = "召唤",
    },

    [4222] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "受到群体攻击伤害减半",
        effectType = 0,
        id = 4222,
        is_active = 0,
        name = "群伤抵抗",
        passiveIcon = "",
        pflogic = 4222,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4250] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "受到治疗和封印使用门派群攻技能时伤害加倍",
        effectType = 0,
        id = 4250,
        is_active = 0,
        name = "门派弱点",
        passiveIcon = "",
        pflogic = 4250,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4251] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "受到攻击时必定触发全体反击，每个目标受到伤害为自身气血上限的30%",
        effectType = 0,
        id = 4251,
        is_active = 0,
        name = "超级反击",
        passiveIcon = "",
        pflogic = 4251,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4252] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被封印后第二回合必定逃跑，未被封印则第4回初合必定逃跑",
        effectType = 0,
        id = 4252,
        is_active = 0,
        name = "逃逸",
        passiveIcon = "",
        pflogic = 4252,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4253] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "每回合都执行防御操作",
        effectType = 0,
        id = 4253,
        is_active = 0,
        name = "防御",
        passiveIcon = "",
        pflogic = 4253,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4254] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "随机作用敌方5个目标，附加嘲讽buff，使用后自身当前回合处于防御状态，有嘲讽buff的目标则优先攻击释放技能的目标",
        effectType = 0,
        id = 4254,
        is_active = 1,
        name = "嘲讽",
        passiveIcon = "",
        pflogic = 4254,
        priority = 100,
        skill_icon = 0,
        type_desc = "嘲讽",
    },

    [4255] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被封印数量＞2时主怪不占用回合数立即使用玉清诀解除全体封印",
        effectType = 0,
        id = 4255,
        is_active = 0,
        name = "封印解除",
        passiveIcon = "",
        pflogic = 4255,
        priority = 100,
        skill_icon = 0,
        type_desc = "解封印",
    },

    [4256] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被攻击目标增加心魔蚀心buff，3回合内伤害降低30%，受到的伤害增加30%",
        effectType = 0,
        id = 4256,
        is_active = 0,
        name = "压制",
        passiveIcon = "",
        pflogic = 4256,
        priority = 100,
        skill_icon = 0,
        type_desc = "压制",
    },

    [4257] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被攻击目标增加衰弱buff，3回合内物理防御降低30%",
        effectType = 0,
        id = 4257,
        is_active = 0,
        name = "心魔蚀心",
        passiveIcon = "",
        pflogic = 4257,
        priority = 100,
        skill_icon = 0,
        type_desc = "心魔蚀心",
    },

    [4258] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "被命中目标眩晕2回合，并附加眩晕buff",
        effectType = 0,
        id = 4258,
        is_active = 1,
        name = "落星箭",
        passiveIcon = "",
        pflogic = 4258,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [4259] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "触发后增加buff，增加伤害",
        effectType = 0,
        id = 4259,
        is_active = 0,
        name = "仇恨1",
        passiveIcon = "",
        pflogic = 4259,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4260] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被命中增加buff，持续掉血",
        effectType = 0,
        id = 4260,
        is_active = 0,
        name = "箭芒",
        passiveIcon = "",
        pflogic = 4260,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4261] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "触发后增加buff，增加伤害",
        effectType = 0,
        id = 4261,
        is_active = 0,
        name = "复仇",
        passiveIcon = "",
        pflogic = 4261,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4262] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "连续攻击目标，每次攻击后有75%几率触发",
        effectType = 0,
        id = 4262,
        is_active = 0,
        name = "超级连击",
        passiveIcon = "",
        pflogic = 4262,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4263] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "触发后增加buff，增加伤害",
        effectType = 0,
        id = 4263,
        is_active = 0,
        name = "仇恨2",
        passiveIcon = "",
        pflogic = 4263,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4264] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "克隆自身，气血最高为自身的50%",
        effectType = 0,
        id = 4264,
        is_active = 0,
        name = "分身",
        passiveIcon = "",
        pflogic = 4264,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4265] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被命中目标增加攻击buff，1回合内攻击增加300%",
        effectType = 0,
        id = 4265,
        is_active = 0,
        name = "点化2",
        passiveIcon = "",
        pflogic = 4265,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4266] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "伤害转移给存活的小怪",
        effectType = 0,
        id = 4266,
        is_active = 0,
        name = "伤害转移",
        passiveIcon = "",
        pflogic = 4266,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4267] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "每回合除恢复固定血量",
        effectType = 0,
        id = 4267,
        is_active = 0,
        name = "再生",
        passiveIcon = "",
        pflogic = 4267,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4268] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "被攻击目标增加衰弱buff，物理防御、攻击降低30%",
        effectType = 0,
        id = 4268,
        is_active = 1,
        name = "懦弱",
        passiveIcon = "",
        pflogic = 4268,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [4269] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "混乱目标2回合",
        effectType = 0,
        id = 4269,
        is_active = 1,
        name = "无能",
        passiveIcon = "",
        pflogic = 4269,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [4270] = {
        ai_action_type = 104,
        ai_target = 2,
        cd = 0,
        desc = "满血复活死亡目标",
        effectType = 0,
        id = 4270,
        is_active = 1,
        name = "命运之光",
        passiveIcon = "",
        pflogic = 4270,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [4271] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "攻击全体目标",
        effectType = 0,
        id = 4271,
        is_active = 1,
        name = "寂灭神雷",
        passiveIcon = "",
        pflogic = 4271,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [4272] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "召唤技能，召唤2个小怪",
        effectType = 0,
        id = 4272,
        is_active = 0,
        name = "因果循环",
        passiveIcon = "",
        pflogic = 4272,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4273] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "将自身受到的伤害反击给攻击者",
        effectType = 0,
        id = 4273,
        is_active = 0,
        name = "反射",
        passiveIcon = "",
        pflogic = 4273,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4274] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "被命中目标随机获得一种特殊buff",
        effectType = 0,
        id = 4274,
        is_active = 1,
        name = "天人五衰",
        passiveIcon = "",
        pflogic = 4274,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [4275] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "被命中目标随机获得一种特殊buff",
        effectType = 0,
        id = 4275,
        is_active = 1,
        name = "天人五衰",
        passiveIcon = "",
        pflogic = 4275,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体攻击",
    },

    [4276] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被攻击目标增加衰弱buff，3回合内物理防御降低30%",
        effectType = 0,
        id = 4276,
        is_active = 0,
        name = "回复",
        passiveIcon = "",
        pflogic = 4276,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4277] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被攻击目标增加衰弱buff，3回合内物理防御降低30%",
        effectType = 0,
        id = 4277,
        is_active = 0,
        name = "超级召唤",
        passiveIcon = "",
        pflogic = 4277,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4278] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被攻击目标增加衰弱buff，3回合内物理防御降低30%",
        effectType = 0,
        id = 4278,
        is_active = 0,
        name = "真诀召唤",
        passiveIcon = "",
        pflogic = 4278,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4279] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被攻击目标增加衰弱buff，3回合内物理防御降低30%",
        effectType = 0,
        id = 4279,
        is_active = 0,
        name = "真诀吞噬",
        passiveIcon = "",
        pflogic = 4279,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4280] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "死亡后有概率复活",
        effectType = 0,
        id = 4280,
        is_active = 0,
        name = "星宿(不死)",
        passiveIcon = "",
        pflogic = 4280,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4281] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "血量低于30%增加暴击率",
        effectType = 0,
        id = 4281,
        is_active = 0,
        name = "星宿(狂怒)",
        passiveIcon = "",
        pflogic = 4281,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4282] = {
        ai_action_type = 109,
        ai_target = 2,
        cd = 0,
        desc = "召唤天兵",
        effectType = 0,
        id = 4282,
        is_active = 0,
        name = "星宿(召唤)",
        passiveIcon = "",
        pflogic = 4282,
        priority = 100,
        skill_icon = 0,
        type_desc = "召唤",
    },

    [4283] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "门派弱点（受到金山寺，瑶池，青城的伤害加倍）",
        effectType = 0,
        id = 4283,
        is_active = 0,
        name = "职业弱点（金玉）",
        passiveIcon = "",
        pflogic = 4283,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4284] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "门派弱点（受到金山寺，瑶池，青城的伤害加倍）",
        effectType = 0,
        id = 4284,
        is_active = 0,
        name = "鞭炮",
        passiveIcon = "",
        pflogic = 4284,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4285] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "门派弱点（受到金山寺，瑶池，青城的伤害加倍）",
        effectType = 0,
        id = 4285,
        is_active = 1,
        name = "年兽咆哮",
        passiveIcon = "",
        pflogic = 4285,
        priority = 100,
        skill_icon = 0,
        type_desc = "主动",
    },

    [4286] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "门派弱点（受到金山寺，瑶池，青城的伤害加倍）",
        effectType = 0,
        id = 4286,
        is_active = 0,
        name = "鞭炮恐惧",
        passiveIcon = "",
        pflogic = 4286,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4287] = {
        ai_action_type = 109,
        ai_target = 2,
        cd = 0,
        desc = "召唤天兵",
        effectType = 0,
        id = 4287,
        is_active = 0,
        name = "年兽(召唤)",
        passiveIcon = "",
        pflogic = 4287,
        priority = 100,
        skill_icon = 0,
        type_desc = "召唤",
    },

    [4288] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "死亡后有概率复活",
        effectType = 0,
        id = 4288,
        is_active = 0,
        name = "不死",
        passiveIcon = "",
        pflogic = 4288,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4289] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "血量低于30%增加暴击率",
        effectType = 0,
        id = 4289,
        is_active = 0,
        name = "狂怒",
        passiveIcon = "",
        pflogic = 4289,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4290] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用后全体己方目标免疫所有物理伤害，全体目标附加物理免疫buff，3回合有效，使用技能时喊话：现在大家不用惧怕物理攻击啦~",
        effectType = 0,
        id = 4290,
        is_active = 1,
        name = "物理免疫",
        passiveIcon = "",
        pflogic = 4290,
        priority = 100,
        skill_icon = 0,
        type_desc = "减伤",
    },

    [4291] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用后全体己方目标免疫所有法术伤害，全体目标附加物理免疫buff，3回合有效，使用技能时喊话：现在大家不用惧法术理攻击啦~",
        effectType = 0,
        id = 4291,
        is_active = 1,
        name = "法术免疫",
        passiveIcon = "",
        pflogic = 4291,
        priority = 100,
        skill_icon = 0,
        type_desc = "减伤",
    },

    [4292] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对敌方7个目标造成【skill*100+200】的固定伤害",
        effectType = 0,
        id = 4292,
        is_active = 1,
        name = "愤怒之击",
        passiveIcon = "",
        pflogic = 4292,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [4293] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "隐身状态下可以使用法术攻击，处于隐身状态下5回合",
        effectType = 0,
        id = 4293,
        is_active = 1,
        name = "超级隐身",
        passiveIcon = "",
        pflogic = 4293,
        priority = 100,
        skill_icon = 0,
        type_desc = "主动",
    },

    [4294] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "死亡时80%几率满血复活",
        effectType = 0,
        id = 4294,
        is_active = 0,
        name = "超级神佑",
        passiveIcon = "",
        pflogic = 4294,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [4295] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "普通攻击打死目标后随机追击对方一个目标，最多追击次数为5次",
        effectType = 0,
        id = 4295,
        is_active = 0,
        name = "超级追击",
        passiveIcon = "",
        pflogic = 4295,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [3027] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "无论何种攻击，只要命中，即为目标增加走火入魔debuff 3回合内伤害降低30%，受到的伤害增加30%，buff效果可以叠加，回合数不叠加",
        effectType = 0,
        id = 3027,
        is_active = 0,
        name = "走火入魔",
        passiveIcon = "",
        pflogic = 3027,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [3028] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "使用后，可增加攻击力15%，持续2回合",
        effectType = 0,
        id = 3028,
        is_active = 1,
        name = "剑斩灵魂",
        passiveIcon = "",
        pflogic = 3028,
        priority = 100,
        skill_icon = 0,
        type_desc = "主动",
    },

    [3029] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "攻击时，15%的概率降低目标90%的物理防御，持续2回合",
        effectType = 0,
        id = 3029,
        is_active = 0,
        name = "碎甲",
        passiveIcon = "",
        pflogic = 3029,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [3030] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "使用时速度最快，被命中的目标防御力下降50%，持续3回合",
        effectType = 0,
        id = 3030,
        is_active = 1,
        name = "破甲击",
        passiveIcon = "",
        pflogic = 3030,
        priority = 100,
        skill_icon = 0,
        type_desc = "主动",
    },

    [3031] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "攻击时有15%的概率降低目标90%的双防御，持续2回合",
        effectType = 0,
        id = 3031,
        is_active = 0,
        name = "破法",
        passiveIcon = "",
        pflogic = 3031,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [3032] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "首回合开始，每2回合初自动使用，随机选择一个的队友使用，使其获得“涅槃”BUFF，持续3回合。不选择已有涅槃技能的为目标。此技能不消耗回合",
        effectType = 0,
        id = 3032,
        is_active = 1,
        name = "魔新转生",
        passiveIcon = "",
        pflogic = 3032,
        priority = 100,
        skill_icon = 0,
        type_desc = "主动",
    },

    [3033] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被攻击，则自动爆炸，自爆自己死亡，同时对敌方全体造成LV*20+200的伤害，LV为怪物等级",
        effectType = 0,
        id = 3033,
        is_active = 0,
        name = "同归于尽",
        passiveIcon = "",
        pflogic = 3033,
        priority = 100,
        skill_icon = 0,
        type_desc = "被动",
    },

    [3034] = {
        ai_action_type = 204,
        ai_target = 3,
        cd = 0,
        desc = "恢复目标气血，附加持续气血恢复状态",
        effectType = 1202,
        id = 3034,
        is_active = 1,
        name = "雨露均沾",
        passiveIcon = "",
        pflogic = 1202,
        priority = 4000,
        skill_icon = 0,
        type_desc = "群疗",
    },

    [3035] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "法术攻击敌方全体，并且消耗目标法力值",
        effectType = 1302,
        id = 3035,
        is_active = 1,
        name = "雨后春笋",
        passiveIcon = "",
        pflogic = 1302,
        priority = 100,
        skill_icon = 51302,
        type_desc = "烧蓝",
    },

    [3036] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "召唤神雷，攻击敌方全体目标",
        effectType = 1201,
        id = 3036,
        is_active = 1,
        name = "天雷",
        passiveIcon = "",
        pflogic = 3036,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体攻击",
    },

    [3037] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "法术攻击敌方全体，并且消耗目标法力值",
        effectType = 1302,
        id = 3037,
        is_active = 1,
        name = "落花无情",
        passiveIcon = "",
        pflogic = 1302,
        priority = 100,
        skill_icon = 51302,
        type_desc = "烧蓝",
    },

}
