-- ./excel/perform/perform_artifact.xlsx
return {

    [9503] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{add_hp_ratio=20,resume_mp_ratio=25}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9503,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9504] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{seal_ratio_max=80, seal_ratio_add=5}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9504,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9505] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{attr_add_ratio=5}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9505,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9506] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{escape_ratio=20}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9506,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9509] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{sp_add_ext=2}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9509,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9510] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{sp_add=5}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9510,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9513] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{kick_ghost_out_ratio=50}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9513,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "12", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9514] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{summon_ghost_bout=-1}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9514,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9517] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{hp_ratio=50, damaged_sub=5,damaged_add=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9517,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9518] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{buff_bout_add_ratio=20, buff_bout_add=1}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9518,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9519] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{buff_bout_sub_ratio=20,buff_bout_sub=1}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9519,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "12", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9520] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{cure_critical_ratio=20,mp_critical_ratio=20}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9520,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9521] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{sp_add_ext=4}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9521,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9524] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{speed_ratio=2}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9524,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9525] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=5}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9525,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "12", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9526] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=5,speed_add_ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9526,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9527] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{res_poison_ratio=80}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9527,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9528] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=50}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9528,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9529] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{hp_add=100,ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9529,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9530] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9530,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

}
