-- ./excel/perform/perform_npc.xlsx
return {

    [3000] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3000,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3001] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3001,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3002] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "300", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3002,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3003] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3003,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 52,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 117, ["bout"] = "2", ["level"] = 1}},
        victimDelBuff = {},
    },

    [3004] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3004,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3005] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3005,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3006] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3006,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "7", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "300+level*100",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3007] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3007,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "max_hp*30/100",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 2,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3008] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3008,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "max_hp",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3009] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{sub_mp=max_mp*5/100}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3009,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "12", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "100+level*20",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3010] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3010,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 172, ["bout"] = "1", ["level"] = 1}},
        victimDelBuff = {},
    },

    [3011] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3011,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "3", ["level"] = 1}},
        skillActionType = 52,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 116, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [3012] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3012,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3013] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "{['math.random(5000,5000)']=20,['math.random(8000,lv*40+8000)']=30,['math.random(10000,lv*60+10000)']=30,['math.random(13000,lv*80+13000)']=15,['math.random(19000,lv*100+19000)']=5}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3013,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3014] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3014,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3015] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3015,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3016] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3016,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "5", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3017] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "200", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3017,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3018] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3018,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3019] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3019,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "5", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3020] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3020,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3021] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3021,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3022] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "300", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3022,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3023] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3023,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "5", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 206, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [3024] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3024,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3025] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3025,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "200",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3026] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3026,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 52,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 116, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4200] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4200,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4201] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4201,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4202] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4202,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4204] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4204,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4205] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4205,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4206] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4206,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4207] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4207,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4208] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4208,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4209] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4209,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4211] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4211,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4212] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4212,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4213] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4213,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4214] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4214,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4215] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4215,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4216] = {
        attackBuff = {{["buffid"] = 171, ["bout"] = 99, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4216,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4217] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4217,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 2,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4218] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4218,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4219] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{sub_hp=math.floor(max_hp*25/100)}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4219,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4220] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "{ratio=30}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4220,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "120+40*level",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4221] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4221,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4222] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=-50}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4222,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4250] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4250,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "level*20",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4251] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4251,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "30",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4252] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4252,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4253] = {
        attackBuff = {{["buffid"] = 203, ["bout"] = 99, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4253,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4254] = {
        attackBuff = {{["buffid"] = 203, ["bout"] = 3, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4254,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "5", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 202, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4255] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4255,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "5", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4256] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4256,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 204, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4257] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4257,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 205, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4258] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4258,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 209, ["bout"] = "1", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4259] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4259,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4260] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4260,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4261] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4261,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4262] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4262,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4263] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4263,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4264] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4264,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4265] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4265,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 210, ["bout"] = "1", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4266] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4266,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4267] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4267,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4268] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4268,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 212, ["bout"] = "5", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4269] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4269,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 213, ["bout"] = "2", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4270] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4270,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "max_hp",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4271] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4271,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "5", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 214, ["bout"] = "2", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4272] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4272,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4273] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4273,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4274] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4274,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "5", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4275] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4275,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "3", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4276] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4276,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4277] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4277,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4278] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4278,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4279] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4279,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4280] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=30,hp=300}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4280,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 2,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4281] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{hp_ratio=30,phy_critical_ratio=30,mag_critical_ratio=30}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4281,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4282] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4282,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4283] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4283,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "level*20",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4284] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4284,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "0",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "10000",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4285] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4285,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4286] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4286,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4287] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4287,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4288] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=30,hp=300}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4288,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 2,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4289] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{hp_ratio=30,phy_critical_ratio=30,mag_critical_ratio=30}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4289,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4290] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4290,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "12", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 238, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4291] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4291,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "12", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 239, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [4292] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4292,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "7", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "200+level*100",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4293] = {
        attackBuff = {{["buffid"] = 240, ["bout"] = 5, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4293,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4294] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=80}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4294,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [4295] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4295,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3027] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3027,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3028] = {
        attackBuff = {{["buffid"] = 245, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "110", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3028,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3029] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=50}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3029,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 246, ["bout"] = "2", ["level"] = 1}},
        victimDelBuff = {},
    },

    [3030] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3030,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 247, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [3031] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=50}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3031,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 248, ["bout"] = "2", ["level"] = 1}},
        victimDelBuff = {},
    },

    [3032] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3032,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3033] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3033,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "level*2",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1202] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1202,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 4}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "50*level+20+cure_power*0.18+grade+2*expert_skill_1",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 114, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1302] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{sub_mp=level*20+20}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1302,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "level*30",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [3036] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 3036,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "level*2",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

}
