-- ./excel/perform/perform_school.xlsx
return {

    [1] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [2] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 2,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [101] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 101,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [102] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 102,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1001] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 0}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 0}},
        hpResume = "",
        id = 1001,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1101] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "90", ["level"] = 1}, {["ratio"] = "92", ["level"] = 2}, {["ratio"] = "94", ["level"] = 3}, {["ratio"] = "96", ["level"] = 4}, {["ratio"] = "98", ["level"] = 5}, {["ratio"] = "100", ["level"] = 6}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1101,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1102] = {
        attackBuff = {{["buffid"] = 197, ["bout"] = 4, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}, {["ratio"] = "101", ["level"] = 2}, {["ratio"] = "102", ["level"] = 3}, {["ratio"] = "103", ["level"] = 4}, {["ratio"] = "104", ["level"] = 5}, {["ratio"] = "105", ["level"] = 6}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1102,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1103] = {
        attackBuff = {{["buffid"] = 198, ["bout"] = 5, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{sub_ratio=25}",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1103,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1104] = {
        attackBuff = {{["buffid"] = 101, ["bout"] = 2, ["level"] = 1}, {["buffid"] = 122, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "90", ["level"] = 1}, {["ratio"] = "91", ["level"] = 2}, {["ratio"] = "92", ["level"] = 4}, {["ratio"] = "93", ["level"] = 4}, {["ratio"] = "94", ["level"] = 5}, {["ratio"] = "95", ["level"] = 6}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1104,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 1,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1105] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "1",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}, {["ratio"] = "101", ["level"] = 2}, {["ratio"] = "102", ["level"] = 3}, {["ratio"] = "103", ["level"] = 4}, {["ratio"] = "104", ["level"] = 5}, {["ratio"] = "105", ["level"] = 6}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1105,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 1,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1106] = {
        attackBuff = {{["buffid"] = 132, ["bout"] = 1, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "1",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}, {["ratio"] = "101", ["level"] = 2}, {["ratio"] = "102", ["level"] = 3}, {["ratio"] = "103", ["level"] = 4}, {["ratio"] = "104", ["level"] = 5}, {["ratio"] = "105", ["level"] = 6}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1106,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1107] = {
        attackBuff = {{["buffid"] = 122, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "3",
        damageRatio = {{["ratio"] = "35+math.random(20)", ["level"] = 1}, {["ratio"] = "37+math.random(20)", ["level"] = 2}, {["ratio"] = "39+math.random(20)", ["level"] = 3}, {["ratio"] = "41+math.random(20)", ["level"] = 4}, {["ratio"] = "43+math.random(20)", ["level"] = 5}, {["ratio"] = "45+math.random(20)", ["level"] = 6}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "{attack_ratio=30+(maxhp-hp)/maxhp*70}",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1107,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1201] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "90", ["level"] = 1}, {["ratio"] = "92", ["level"] = 2}, {["ratio"] = "94", ["level"] = 3}, {["ratio"] = "96", ["level"] = 4}, {["ratio"] = "98", ["level"] = 5}, {["ratio"] = "100", ["level"] = 6}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1201,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "math.max(level*25+grade+20, level*25+grade+math.random(95,105)/100*(mag_attack-mag_defense))",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1202] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1202,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 4}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "25*level+20+cure_power*0.18+grade+2*expert_skill_1",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 114, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1203] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{buff_effect=20}",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1203,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "60*level+80+cure_power*0.73+grade*2+5*expert_skill_1",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1204] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1204,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}, {["speed"] = 6, ["level"] = 2}, {["speed"] = 7, ["level"] = 3}, {["speed"] = 8, ["level"] = 4}, {["speed"] = 9, ["level"] = 5}, {["speed"] = 10, ["level"] = 6}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1205] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1205,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*4",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "40*level+80+cure_power*0.4+grade*1.5+4*expert_skill_1",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 2,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1206] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1206,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*3",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 111, ["bout"] = "1", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1207] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "3",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1207,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}, {["speed"] = 6, ["level"] = 2}, {["speed"] = 7, ["level"] = 3}, {["speed"] = 8, ["level"] = 4}, {["speed"] = 9, ["level"] = 5}, {["speed"] = 10, ["level"] = 6}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1301] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "90", ["level"] = 1}, {["ratio"] = "92", ["level"] = 2}, {["ratio"] = "94", ["level"] = 3}, {["ratio"] = "96", ["level"] = 4}, {["ratio"] = "98", ["level"] = 5}, {["ratio"] = "100", ["level"] = 6}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1301,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "3", ["level"] = 1}, {["range"] = "4", ["level"] = 3}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense)+grade*5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1302] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{sub_mp=level*20+20}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1302,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "level*30",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1303] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}, {["ratio"] = "101", ["level"] = 2}, {["ratio"] = "102", ["level"] = 3}, {["ratio"] = "103", ["level"] = 4}, {["ratio"] = "104", ["level"] = 5}, {["ratio"] = "105", ["level"] = 6}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1303,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense)+grade*8",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1304] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1304,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}, {["speed"] = 1, ["level"] = 2}, {["speed"] = 2, ["level"] = 3}, {["speed"] = 3, ["level"] = 4}, {["speed"] = 4, ["level"] = 5}, {["speed"] = 5, ["level"] = 6}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1305] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1305,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}, {["speed"] = 2, ["level"] = 2}, {["speed"] = 4, ["level"] = 3}, {["speed"] = 6, ["level"] = 4}, {["speed"] = 8, ["level"] = 5}, {["speed"] = 10, ["level"] = 6}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 133, ["bout"] = "2", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1306] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "90", ["level"] = 1}, {["ratio"] = "92", ["level"] = 2}, {["ratio"] = "94", ["level"] = 3}, {["ratio"] = "96", ["level"] = 4}, {["ratio"] = "98", ["level"] = 5}, {["ratio"] = "100", ["level"] = 6}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1306,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "2", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense)+grade*6",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1307] = {
        attackBuff = {{["buffid"] = 122, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "3",
        damageRatio = {{["ratio"] = "130+(victim_max_mp-victim_mp)/victim_max_mp*60", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1307,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense)+grade*10",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1401] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "90", ["level"] = 1}, {["ratio"] = "92", ["level"] = 2}, {["ratio"] = "94", ["level"] = 3}, {["ratio"] = "96", ["level"] = 4}, {["ratio"] = "98", ["level"] = 5}, {["ratio"] = "100", ["level"] = 6}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1401,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "math.max(level*25+grade+20, level*25+grade+math.random(95,105)/100*(mag_attack-mag_defense))",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1402] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{grade=100,max_hp=44+level,max_mp=100,phy_defense=28+level*2,mag_defense=28+level*2,phy_hit_ratio=100,phy_hit_res_ratio=100,mag_hit_ratio=100,mag_hit_res_ratio=100,phy_attack=50,mag_attack=50,speed=100,cure_power=100+level*2}",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1402,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*3",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "90+level",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1403] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "{ratio=90+level*2}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1403,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "math.min(grade*15,hp*math.random(7,12)/100+grade*2)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 123, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1404] = {
        attackBuff = {{["buffid"] = 127, ["bout"] = 1, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1404,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}, {["speed"] = 6, ["level"] = 2}, {["speed"] = 7, ["level"] = 3}, {["speed"] = 8, ["level"] = 4}, {["speed"] = 9, ["level"] = 5}, {["speed"] = 10, ["level"] = 6}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1405] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{model={[1]={name='天兵',model_info={shape=3119},type=1405,skill={1409},},[3]={name='天兵',model_info={shape=3119},type=1405,skill={1409},},[5]={name='天兵',model_info={shape=3119},type=1405,skill={1409},},},grade=100,max_hp=35+level,max_mp=100,phy_defense=12+level*2,mag_defense=18+level*2,phy_hit_ratio=100,phy_hit_res_ratio=100,mag_hit_ratio=100,mag_hit_res_ratio=100,phy_attack=58+level*2,mag_attack=48+level*2,speed=100,cure_power=0}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "grade*2",
        id = 1405,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1406] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "",
        id = 1406,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "grade*1",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 4}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 136, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1407] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "3",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1407,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 10, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 124, ["bout"] = "1", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1408] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1408,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*3",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 4}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "30*level+30+cure_power*0.18+grade*2+2*expert_skill_1",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 129, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1409] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1409,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*3",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 4}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "math.max(level*25+grade+20, level*25+grade+math.random(95,105)/100*(mag_attack-mag_defense))",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 125, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1501] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "90", ["level"] = 1}, {["ratio"] = "92", ["level"] = 2}, {["ratio"] = "94", ["level"] = 3}, {["ratio"] = "96", ["level"] = 4}, {["ratio"] = "98", ["level"] = 5}, {["ratio"] = "100", ["level"] = 6}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1501,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "math.max(level*25+grade+20, level*25+grade+math.random(95,105)/100*(mag_attack-mag_defense))",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1502] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "60", ["level"] = 1}, {["rate"] = "61", ["level"] = 2}, {["rate"] = "62", ["level"] = 3}, {["rate"] = "63", ["level"] = 4}, {["rate"] = "64", ["level"] = 5}, {["rate"] = "65", ["level"] = 6}},
        hpResume = "",
        id = 1502,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 52,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}, {["speed"] = 6, ["level"] = 2}, {["speed"] = 7, ["level"] = 3}, {["speed"] = 8, ["level"] = 4}, {["speed"] = 9, ["level"] = 5}, {["speed"] = 10, ["level"] = 6}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 116, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1503] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "50", ["level"] = 1}, {["rate"] = "51", ["level"] = 2}, {["rate"] = "52", ["level"] = 3}, {["rate"] = "53", ["level"] = 4}, {["rate"] = "54", ["level"] = 5}, {["rate"] = "55", ["level"] = 6}},
        hpResume = "",
        id = 1503,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 52,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}, {["speed"] = 6, ["level"] = 2}, {["speed"] = 7, ["level"] = 3}, {["speed"] = 8, ["level"] = 4}, {["speed"] = 9, ["level"] = 5}, {["speed"] = 10, ["level"] = 6}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 117, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1504] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "0", ["level"] = 1}},
        hpResume = "grade*2",
        id = 1504,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "40+level*60",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1505] = {
        attackBuff = {{["buffid"] = 120, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "65", ["level"] = 1}},
        hpResume = "",
        id = 1505,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 52,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}, {["speed"] = 6, ["level"] = 2}, {["speed"] = 7, ["level"] = 3}, {["speed"] = 8, ["level"] = 4}, {["speed"] = 9, ["level"] = 5}, {["speed"] = 10, ["level"] = 6}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 119, ["bout"] = "4", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1506] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1506,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "grade*3",
        range = {{["range"] = "1", ["level"] = 0}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "math.max(level*40+grade*2+50, level*40+grade+math.random(95,105)/100*(mag_attack-mag_defense))",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1507] = {
        attackBuff = {{["buffid"] = 122, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "3",
        damageRatio = {{["ratio"] = "0", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "60", ["level"] = 1}, {["rate"] = "62", ["level"] = 2}, {["rate"] = "64", ["level"] = 3}, {["rate"] = "66", ["level"] = 4}, {["rate"] = "68", ["level"] = 5}, {["rate"] = "70", ["level"] = 6}},
        hpResume = "",
        id = 1507,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 4}},
        skillActionType = 52,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 5, ["level"] = 1}, {["speed"] = 6, ["level"] = 2}, {["speed"] = 7, ["level"] = 3}, {["speed"] = 8, ["level"] = 4}, {["speed"] = 9, ["level"] = 5}, {["speed"] = 10, ["level"] = 6}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 121, ["bout"] = "4", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1601] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "90", ["level"] = 1}, {["ratio"] = "92", ["level"] = 2}, {["ratio"] = "94", ["level"] = 3}, {["ratio"] = "96", ["level"] = 4}, {["ratio"] = "98", ["level"] = 5}, {["ratio"] = "100", ["level"] = 6}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "105", ["level"] = 1}},
        hpResume = "",
        id = 1601,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 3}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 1,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1602] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}, {["ratio"] = "101", ["level"] = 2}, {["ratio"] = "102", ["level"] = 3}, {["ratio"] = "103", ["level"] = 4}, {["ratio"] = "104", ["level"] = 5}, {["ratio"] = "105", ["level"] = 6}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1602,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 112, ["bout"] = "2", ["level"] = 1}},
        victimDelBuff = {},
    },

    [1603] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "95", ["level"] = 1}, {["ratio"] = "96", ["level"] = 2}, {["ratio"] = "97", ["level"] = 3}, {["ratio"] = "98", ["level"] = 4}, {["ratio"] = "99", ["level"] = 5}, {["ratio"] = "100", ["level"] = 6}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "{ratio=100}",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1603,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 4,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1604] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "110", ["level"] = 1}, {["ratio"] = "112", ["level"] = 2}, {["ratio"] = "114", ["level"] = 3}, {["ratio"] = "116", ["level"] = 4}, {["ratio"] = "118", ["level"] = 5}, {["ratio"] = "120", ["level"] = 6}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "{ratio=20}",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1604,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 10, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1605] = {
        attackBuff = {{["buffid"] = 115, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1605,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "grade*2.5",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1606] = {
        attackBuff = {{["buffid"] = 122, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "0",
        damageRatio = {{["ratio"] = "90", ["level"] = 1}, {["ratio"] = "92", ["level"] = 2}, {["ratio"] = "94", ["level"] = 4}, {["ratio"] = "96", ["level"] = 4}, {["ratio"] = "98", ["level"] = 5}, {["ratio"] = "100", ["level"] = 6}},
        do_group_ratio = 1,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 1606,
        is_constant_damage = 0,
        is_group_perform = 1,
        mpResume = "grade*2.5",
        range = {{["range"] = "3", ["level"] = 1}, {["range"] = "4", ["level"] = 4}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1607] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "3",
        damageRatio = {{["ratio"] = "130", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "{ratio=50}",
        hitRate = {{["rate"] = "115", ["level"] = 1}},
        hpResume = "",
        id = 1607,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [1608] = {
        attackBuff = {{["buffid"] = 122, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "1",
        damageRatio = {{["ratio"] = "68", ["level"] = 1}, {["ratio"] = "68", ["level"] = 2}, {["ratio"] = "69", ["level"] = 3}, {["ratio"] = "70", ["level"] = 4}, {["ratio"] = "70", ["level"] = 5}, {["ratio"] = "70", ["level"] = 6}},
        do_group_ratio = 1,
        effectAction = 1,
        extArgs = "{ratio=20,attack_cnt=level}",
        hitRate = {{["rate"] = "110", ["level"] = 1}},
        hpResume = "",
        id = 1608,
        is_constant_damage = 0,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "2", ["level"] = 1}, {["range"] = "3", ["level"] = 2}, {["range"] = "4", ["level"] = 5}, {["range"] = "5", ["level"] = 6}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

}
