-- ./excel/perform/perform_ride.xlsx
return {

    [5901] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{phy_damage_ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5901,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5902] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=50,sub_mp=grade*1}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5902,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5903] = {
        attackBuff = {{["buffid"] = 193, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5903,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5904] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{bout_freq=9,pf_choose={[1]=1104,[2]=1201,[3]=1303,[4]=1401,[5]=1501,[6]=1606},speek='垂死一击'}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5904,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5906] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{phy_damaged_ratio=-10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5906,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5907] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10,sub_damage=math.random(50,200)}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5907,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5908] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{defense_factor=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5908,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5909] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10,hp_ratio=30}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5909,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5911] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{mag_damage_ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5911,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5912] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{sub_mag_defense=mag_defense*0.01}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5912,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5914] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=15,ext_cnt=1}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5914,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5916] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{mag_damaged_ratio=-10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5916,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5917] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10,sub_damage=math.random(50,200)}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5917,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5918] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{add_mp=damage*20//100}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5918,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5919] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{hp_ratio=30,hp_add=damage*30//100,bout_freq=9}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5919,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5921] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=30}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5921,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 194, ["bout"] = "2", ["level"] = 1}},
        victimDelBuff = {},
    },

    [5922] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ext_damage=grade*2}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5922,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5923] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10,speed_ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5923,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5924] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10, ext_cnt=1}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5924,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5925] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{usedrug_add_ratio=3+2*level}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5925,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5926] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{usedrug_free_ratio=10,usedrug_free_list={10062,10063,10064},}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5926,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5927] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{usedrug_add_ratio=30,res_drug_add_ratio=150}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5927,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5928] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=100}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5928,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 196, ["bout"] = "1", ["level"] = 1}},
        victimDelBuff = {},
    },

    [5929] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{usedrug_add_ratio=30}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5929,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5931] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{cure_critical_ratio=5}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5931,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5932] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=50,mp_sub_ratio=math.random(10,20)}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5932,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5933] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{res_drug=-20}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5933,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5934] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{cure_ratio=50}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5934,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5936] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{phy_critical_ratio=6}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5936,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5937] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5937,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5938] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{add_ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5938,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5939] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5939,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5941] = {
        attackBuff = {{["buffid"] = 195, ["bout"] = 2, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{res_phy_critical_ratio=8}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5941,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5943] = {
        attackBuff = {{["buffid"] = 195, ["bout"] = 1, ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5943,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5944] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{damage_ratio=-15}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5944,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5945] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "50", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=level*5}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5945,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "math.floor(grade+math.random(95,105)/100*phy_attack-phy_defense), grade+math.random(95,105)/100*mag_attack-mag_defense))",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5947] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{res_hit_back_ratio=100}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5947,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5948] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=3,grade_limit=grade+5}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5948,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5949] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=50}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5949,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

}
