-- ./excel/perform/perform_se.xlsx
return {

    [9000] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9000,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "200+max_hp*3/100",
        sp_resume = "30",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9001] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9001,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "400+max_hp*6/100",
        sp_resume = "60",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9002] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9002,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "600+max_hp*9/100",
        sp_resume = "90",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9003] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9003,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*5+max_mp*10/100",
        sp_resume = "50",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9004] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9004,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*10+max_mp*15/100",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9005] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9005,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "math.min(grade*12, max_hp*25/100)",
        sp_resume = "60",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9006] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9006,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "math.min(grade*20, max_hp*50/100)",
        sp_resume = "130",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9007] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9007,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "12", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "math.min(grade*12,max_hp*25/100)",
        sp_resume = "140",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9008] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9008,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "math.min(grade*12,max_mp*25/100)",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9009] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9009,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "150",
        sp_resume = "100",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 2,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9010] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9010,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "max_hp*50/100",
        sp_resume = "120",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 2,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9011] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9011,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "12", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "max_hp",
        sp_resume = "150",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 2,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9012] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9012,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "40",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9013] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9013,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "math.min(grade*12,max_hp*25/100)",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9014] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9014,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "110",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9015] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9015,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "12", ["level"] = 1}},
        skillActionType = 54,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "max_hp*15/100",
        sp_resume = "150",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9016] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9016,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "70",
        sp_resume = "40",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9017] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9017,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "40",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 175, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9018] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9018,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "70",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 164, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9019] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9019,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "40",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 178, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9020] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9020,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 179, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9021] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9021,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "40",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 180, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9022] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9022,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 181, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9023] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9023,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "120",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 182, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9024] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9024,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "45",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 165, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9025] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9025,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 183, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9026] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9026,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "40",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 184, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9027] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9027,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 185, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9028] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9028,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "40",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 186, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9029] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9029,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "15", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 187, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9030] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9030,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9031] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "75"}, {["ratio"] = "85"}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9031,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "80",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9032] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "60", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "{phy_attack_ratio=50}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9032,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "50",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9033] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{limit=grade*15}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9033,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "hp*20/100",
        sp_resume = "70",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9034] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{limit=grade*10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9034,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "mp*30/100",
        sp_resume = "90",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9035] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9035,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 2,
        skill_formula = "math.max(grade*7+100,100)",
        sp_resume = "60",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9036] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9036,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "5", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "math.max(grade*5+100,100)",
        sp_resume = "110",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9037] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "{sub_mp=math.floor(hp/2)}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9037,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "60",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9038] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9038,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "90",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 3,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 188, ["bout"] = "4", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9039] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9039,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "40",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 166, ["bout"] = "1", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9203] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=3,damage_ratio=-20}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9203,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9204] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=20, hp_limit=grade*20}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9204,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9205] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{factor=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9205,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9206] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{hp_add=math.floor(level/3)}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9206,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9207] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=15}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9207,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9208] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{bout_limit=8}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9208,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 189, ["bout"] = "8-cur_bout", ["level"] = 1}},
        victimDelBuff = {},
    },

    [9209] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=20}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9209,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9210] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=-20}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9210,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9212] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=20,hp_add=math.floor(max_hp*30/100)}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9212,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9213] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9213,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9214] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9214,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9215] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=3,speed_ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9215,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [9211] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 9211,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

}
