-- ./excel/perform/perform_summon.xlsx
return {

    [5129] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5129,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "grade*2",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "(level-1)/4*10",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 131, ["bout"] = "3", ["level"] = 1}},
        victimDelBuff = {},
    },

    [5201] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "99+level", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5201,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "grade*2",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense*0.9+185)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5202] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "99+level", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5202,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "grade*2",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense*0.9+185)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5203] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "99+level", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5203,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "grade*2",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense*0.9+185)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5204] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "99+level", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5204,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "grade*2",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense*0.9+185)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5205] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "99+level", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5205,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "2"}, {["grade"] = 50, ["range"] = "3"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 1,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense*0.9+30)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5206] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "99+level", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5206,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "2"}, {["grade"] = 50, ["range"] = "3"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense*0.9+30)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5207] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "99+level", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5207,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "2"}, {["grade"] = 50, ["range"] = "3"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense*0.9+30)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5208] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "99+level", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5208,
        is_constant_damage = 1,
        is_group_perform = 1,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "2"}, {["grade"] = 50, ["range"] = "3"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 4,
        skill_formula = "math.random(95,105)/100*(mag_attack-mag_defense*0.9+30)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5209] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5209,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "grade*2",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5210] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5210,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "grade*2",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5211] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "60",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5211,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "2"}, {["grade"] = 50, ["range"] = "3"}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "100",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5212] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "70+level*5", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5212,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "2"}, {["grade"] = 50, ["range"] = "3"}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5213] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5213,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "50+level* 10",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5301] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "20",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5301,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "50",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5302] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "200",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5302,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "70",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5304] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5304,
        is_constant_damage = 1,
        is_group_perform = 2,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 1,
        skillElementType = 3,
        skill_formula = "self_attack*2.35-(tar_attact+tar_defense)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

    [5305] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 1,
        extArgs = "{buff_ratio=25}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5305,
        is_constant_damage = 2,
        is_group_perform = 2,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "1"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "math.random(95,105)/100*(self_attack-0.9*iTarDefense+70)",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 222, ["bout"] = "4", ["level"] = 1}},
        victimDelBuff = {},
    },

    [5306] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 1,
        effectAction = 0,
        extArgs = "{sub_mp=50+attack_grade,add_mp=150}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 5306,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "grade*3",
        range = {{["grade"] = 0, ["range"] = "2"}, {["grade"] = 50, ["range"] = "3"}},
        skillActionType = 51,
        skillAttackType = 2,
        skillElementType = 3,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
    },

}
