-- ./excel/perform/perform_fabao.xlsx
return {

    [4601] = {
        attackBuff = {{["buffid"] = 234, ["bout"] = "4+extra", ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4601,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "10",
    },

    [4602] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4602,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "8",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4603] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4603,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "4",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4604] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4604,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "1",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4605] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4605,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "20",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4606] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4606,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "level*1.5+5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "10",
    },

    [4607] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4607,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4608] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4608,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4609] = {
        attackBuff = {{["buffid"] = 241, ["bout"] = "3", ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4609,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "10",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4610] = {
        attackBuff = {{["buffid"] = 242, ["bout"] = "3", ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4610,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "10",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4611] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4611,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 2,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 235, ["bout"] = "4+extra", ["level"] = 1}},
        victimDelBuff = {},
        zhengqi_formula = "10",
    },

    [4612] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4612,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "-4",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4613] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4613,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "-8",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4614] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4614,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "1",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4615] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4615,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "10",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "10",
    },

    [4616] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4616,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*level*5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 236, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
        zhengqi_formula = "10",
    },

    [4617] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4617,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*0.15",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4618] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4618,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*0.25",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4619] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4619,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "3",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4620] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4620,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4621] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4621,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*level*5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {{["buffid"] = 237, ["bout"] = "99", ["level"] = 1}},
        victimDelBuff = {},
        zhengqi_formula = "10",
    },

    [4622] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4622,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*0.15",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4623] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4623,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*0.25",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4624] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4624,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "3",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4625] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4625,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4626] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4626,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*level*0.03+10",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4627] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4627,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "10",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4628] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4628,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "1",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4629] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4629,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "2",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4630] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4630,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "3",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4631] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=35}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4631,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "level*1.5+3.5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4632] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=2}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4632,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4633] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=5}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4633,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4634] = {
        attackBuff = {{["buffid"] = 243, ["bout"] = "2", ["level"] = 1}},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=8}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4634,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "2",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4635] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=10,hp_ratio=33}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4635,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4636] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4636,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*level*0.03+10",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4637] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4637,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "grade*0.1",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4638] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4638,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "7",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4639] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4639,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "2",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4640] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4640,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "3",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4641] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=35}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4641,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "level*1.5+4.5",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4642] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=2}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4642,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4643] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio=2}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4643,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4644] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "{ratio_self=2,ratio=10}",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4644,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

    [4645] = {
        attackBuff = {},
        attackDelBuff = {},
        aura_add = "",
        aura_resume = "",
        damageRatio = {{["ratio"] = "100", ["level"] = 1}},
        do_group_ratio = 2,
        effectAction = 0,
        extArgs = "",
        hitRate = {{["rate"] = "100", ["level"] = 1}},
        hpResume = "",
        id = 4645,
        is_constant_damage = 2,
        is_group_perform = 1,
        mpResume = "",
        range = {{["range"] = "1", ["level"] = 1}},
        skillActionType = 53,
        skillAttackType = 2,
        skillElementType = 2,
        skill_formula = "35",
        sp_resume = "",
        speedRatio = {{["speed"] = 0, ["level"] = 1}},
        targetType = 1,
        useTargetStatus = 1,
        victimBuff = {},
        victimDelBuff = {},
        zhengqi_formula = "",
    },

}
