-- ./excel/perform/perform_ride.xlsx
return {

    [5901] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "增加宠物的物理伤害结果",
        effectType = 1114,
        id = 5901,
        is_active = 0,
        name = "驯兽术",
        pflogic = 5901,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5902] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "攻击对方时，50%概率扣除目标自身等级X1点法力",
        effectType = 1114,
        id = 5902,
        is_active = 0,
        name = "内力损毁",
        pflogic = 5902,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5903] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "击杀一个目标后，下一个回合伤害提升5%",
        effectType = 1114,
        id = 5903,
        is_active = 0,
        name = "猛击",
        pflogic = 5903,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5904] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = [=[角色死亡时，使用指定招式随机攻击敌人1次，10回合内不会再次触发，使用后必定死亡（即使攻击吸血）
蜀山：狂剑诀\金山寺：金刚伏魔\太初：神炎焚身\青城山：龙蛇吐息\瑶池：风雷云动\妖神宫：杀破狼
]=],
        effectType = 1114,
        id = 5904,
        is_active = 0,
        name = "垂死一击",
        pflogic = 5904,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5906] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "降低宠物受到的物理伤害",
        effectType = 1114,
        id = 5906,
        is_active = 0,
        name = "野兽装甲",
        pflogic = 5906,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5907] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "受到物理伤害时，10%概率减少50-200点伤害",
        effectType = 1114,
        id = 5907,
        is_active = 0,
        name = "坚韧",
        pflogic = 5907,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5908] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "防御时，伤害减少10%，若有强化防御的装备特效时，效果减半",
        effectType = 1114,
        id = 5908,
        is_active = 0,
        name = "坚盾术",
        pflogic = 5908,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5909] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "当角色气血低于30%，坚韧的触发几率增加10%",
        effectType = 1114,
        id = 5909,
        is_active = 0,
        name = "金刚不坏",
        pflogic = 5909,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5911] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "增加宠物的法术伤害结果",
        effectType = 1114,
        id = 5911,
        is_active = 0,
        name = "野兽智慧",
        pflogic = 5911,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5912] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "角色每次单体法术攻击都可以降低对方1%法术防御",
        effectType = 1114,
        id = 5912,
        is_active = 0,
        name = "集中",
        pflogic = 5912,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5914] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "群体伤害法术有15%概率增加1个目标",
        effectType = 1114,
        id = 5914,
        is_active = 0,
        name = "翻江倒海",
        pflogic = 5914,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5916] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "降低宠物受到的法术伤害",
        effectType = 1114,
        id = 5916,
        is_active = 0,
        name = "兽皮术",
        pflogic = 5916,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5917] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "受到法术伤害时，10%概率减少50-200点伤害",
        effectType = 1114,
        id = 5917,
        is_active = 0,
        name = "法术斗篷",
        pflogic = 5917,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5918] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "防御时，回复受到伤害的20%法力值",
        effectType = 1114,
        id = 5918,
        is_active = 0,
        name = "自然力量",
        pflogic = 5918,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5919] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "当角色气血低于30%时，角色将能免疫下一次法术伤害，并将30%伤害转化为气血吸收，每10回合只能触发1次",
        effectType = 1114,
        id = 5919,
        is_active = 0,
        name = "逆转阴阳",
        pflogic = 5919,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5921] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "封印命中目标，有30%的概率令目标的物理防御降低15%，持续2回合",
        effectType = 1114,
        id = 5921,
        is_active = 0,
        name = "腐蚀术",
        pflogic = 5921,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5922] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "封印命中目标后，立即造成一定伤害=等级*2",
        effectType = 1114,
        id = 5922,
        is_active = 0,
        name = "天雷咒",
        pflogic = 5922,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5923] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "10%概率提高10%出手速度",
        effectType = 1114,
        id = 5923,
        is_active = 0,
        name = "追魂",
        pflogic = 5923,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5924] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用封印法术，有10%概率额外封印一个目标",
        effectType = 1114,
        id = 5924,
        is_active = 0,
        name = "四象封印",
        pflogic = 5924,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5925] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "增加药品治疗5%，每提升一个等级增加2%",
        effectType = 1114,
        id = 5925,
        is_active = 0,
        name = "药理术",
        pflogic = 5925,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5926] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用高级药物（生机丹、血灵丹、改命丹）时，有30%概率不消耗药物",
        effectType = 1114,
        id = 5926,
        is_active = 0,
        name = "药物知识",
        pflogic = 5926,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5927] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "药物效果增强30%，但是会为目标额外增加150%抗药性",
        effectType = 1114,
        id = 5927,
        is_active = 0,
        name = "副作用",
        pflogic = 5927,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5928] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "药物复活目标时，有让目标本回合内受到伤害减少20%",
        effectType = 1114,
        id = 5928,
        is_active = 0,
        name = "止痛药",
        pflogic = 5928,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5929] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用任何药物时，自身回复药物效果的30%",
        effectType = 1114,
        id = 5929,
        is_active = 0,
        name = "春暖花开",
        pflogic = 5929,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5931] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "使用治疗技能，增加5%治疗暴击几率",
        effectType = 1114,
        id = 5931,
        is_active = 0,
        name = "启迪",
        pflogic = 5931,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5932] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "治疗法术50%降低10%-20%法力消耗",
        effectType = 1114,
        id = 5932,
        is_active = 0,
        name = "节能施法",
        pflogic = 5932,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5933] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "单体治疗目标将降低目标20%抗药性",
        effectType = 1114,
        id = 5933,
        is_active = 0,
        name = "固本培元",
        pflogic = 5933,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5934] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "在自己没有召唤兽在场时，治疗法术效果+50%",
        effectType = 1114,
        id = 5934,
        is_active = 0,
        name = "摩诃无量",
        pflogic = 5934,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5936] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "宠物物理暴击增加6%",
        effectType = 1114,
        id = 5936,
        is_active = 0,
        name = "超强力量",
        pflogic = 5936,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5937] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "暴击时候，会清除目标身上一个增益状态",
        effectType = 1114,
        id = 5937,
        is_active = 0,
        name = "净化",
        pflogic = 5937,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5938] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "暴击伤害增加10%",
        effectType = 1114,
        id = 5938,
        is_active = 0,
        name = "怒火中烧",
        pflogic = 5938,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5939] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "召唤兽暴击后额外攻击另外1个目标",
        effectType = 1114,
        id = 5939,
        is_active = 0,
        name = "重创追击",
        pflogic = 5939,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5941] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "宠物被物理暴击的概率降低8%",
        effectType = 1114,
        id = 5941,
        is_active = 0,
        name = "野兽幸运",
        pflogic = 5941,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5943] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "被物理暴击或法术暴击后，接下来受到的伤害降低20%，持续1个回合",
        effectType = 1114,
        id = 5943,
        is_active = 0,
        name = "装死",
        pflogic = 5943,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5944] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "受到群体性伤害降低20%",
        effectType = 1114,
        id = 5944,
        is_active = 0,
        name = "飘忽不定",
        pflogic = 5944,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5945] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "受到攻击时，有5%概率进行反击（伤害与自身物理和法术攻击中最高一项相关），每级增加5%",
        effectType = 1114,
        id = 5945,
        is_active = 0,
        name = "反击",
        pflogic = 5945,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5947] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "主角攻击目标，降低10%反击概率",
        effectType = 1114,
        id = 5947,
        is_active = 0,
        name = "偷袭",
        pflogic = 5947,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5948] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "有3%几率，将目标等级≤主角等级+5的目标击飞出场，对玩家和BOSS无效",
        effectType = 1114,
        id = 5948,
        is_active = 0,
        name = "击退",
        pflogic = 5948,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

    [5949] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "反击攻击会附带50%吸血效果（法术攻击也会有吸血效果）",
        effectType = 1114,
        id = 5949,
        is_active = 0,
        name = "勇气之刹",
        pflogic = 5949,
        priority = 100,
        skill_icon = 50218,
        type_desc = "单体辅助",
    },

}
