-- ./excel/perform/perform_school.xlsx
return {

    [1] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "测试用(不要删)",
        effectType = 0,
        id = 1,
        is_active = 1,
        name = "普通法术",
        pflogic = 1,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体法术",
    },

    [2] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "测试用(不要删)",
        effectType = 0,
        id = 2,
        is_active = 1,
        name = "物理法术",
        pflogic = 2,
        priority = 100,
        skill_icon = 0,
        type_desc = "群体法术",
    },

    [101] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "自动战斗指令攻击",
        effectType = 0,
        id = 101,
        is_active = 1,
        name = "攻击",
        pflogic = 101,
        priority = 100,
        skill_icon = 0,
        type_desc = "自动战斗",
    },

    [102] = {
        ai_action_type = 53,
        ai_target = 2,
        cd = 0,
        desc = "自动战斗指令防御",
        effectType = 0,
        id = 102,
        is_active = 1,
        name = "防御",
        pflogic = 102,
        priority = 10,
        skill_icon = 0,
        type_desc = "自动战斗",
    },

    [1001] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "普通攻击（法术)",
        effectType = 0,
        id = 1001,
        is_active = 1,
        name = "普通法术",
        pflogic = 1001,
        priority = 100,
        skill_icon = 0,
        type_desc = "单体法术",
    },

    [1101] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "剑气汇成漩涡，一次性攻击多个敌人。",
        effectType = 1101,
        id = 1101,
        is_active = 1,
        name = "剑寒九州",
        pflogic = 1101,
        priority = 1000,
        skill_icon = 51101,
        type_desc = "群攻",
    },

    [1102] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "物理单体攻击，并提高自身的法术闪避（25%)，持续4回合",
        effectType = 1102,
        id = 1102,
        is_active = 1,
        name = "瞬斩",
        pflogic = 1102,
        priority = 500,
        skill_icon = 51102,
        type_desc = "先手",
    },

    [1103] = {
        ai_action_type = 106,
        ai_target = 2,
        cd = 0,
        desc = "附加5回合【剑气爆发】状态，物理攻击敌方单人时，对两个气血最低的敌方单位造成额外伤害",
        effectType = 1103,
        id = 1103,
        is_active = 1,
        name = "剑气爆发",
        pflogic = 1103,
        priority = 1000,
        skill_icon = 51103,
        type_desc = "溅射",
    },

    [1104] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "对目标发动3次强力攻击，使用后自身防御降低,使用后休息1回合",
        effectType = 1104,
        id = 1104,
        is_active = 1,
        name = "狂剑诀",
        pflogic = 1104,
        priority = 3000,
        skill_icon = 51104,
        type_desc = "三刀",
    },

    [1105] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "攻击目标,获得1点灵气",
        effectType = 1105,
        id = 1105,
        is_active = 1,
        name = "聚灵剑",
        pflogic = 1105,
        priority = 500,
        skill_icon = 51105,
        type_desc = "灵气",
    },

    [1106] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 1,
        desc = [=[攻击目标，然后进入隐身状态，持续1个回合
技能冷却回合：1]=],
        effectType = 1106,
        id = 1106,
        is_active = 1,
        name = "隐遁",
        pflogic = 1106,
        priority = 500,
        skill_icon = 51106,
        type_desc = "隐身",
    },

    [1107] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "消耗所有灵力，对目标造成多段攻击，气血越低，连续攻击概率越高",
        effectType = 1107,
        id = 1107,
        is_active = 1,
        name = "万剑归一",
        pflogic = 1107,
        priority = 0,
        skill_icon = 51107,
        type_desc = "绝技",
    },

    [1201] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "对多目标造成固定伤害",
        effectType = 1201,
        id = 1201,
        is_active = 1,
        name = "金刚伏魔",
        pflogic = 1201,
        priority = 1000,
        skill_icon = 51201,
        type_desc = "群攻",
    },

    [1202] = {
        ai_action_type = 204,
        ai_target = 3,
        cd = 0,
        desc = "恢复目标气血，附加持续气血恢复状态",
        effectType = 1202,
        id = 1202,
        is_active = 1,
        name = "九品莲台",
        pflogic = 1202,
        priority = 4000,
        skill_icon = 51202,
        type_desc = "群疗",
    },

    [1203] = {
        ai_action_type = 104,
        ai_target = 3,
        cd = 0,
        desc = "为单体目标回复较多气血，对带有九品莲台状态的单位施放时，会恢复额外气血",
        effectType = 1203,
        id = 1203,
        is_active = 1,
        name = "我佛慈悲",
        pflogic = 1203,
        priority = 2000,
        skill_icon = 51203,
        type_desc = "单疗",
    },

    [1204] = {
        ai_action_type = 105,
        ai_target = 7,
        cd = 0,
        desc = "解除友方单位的封印状态，并随机移除一个增益状态",
        effectType = 1204,
        id = 1204,
        is_active = 1,
        name = "禅心定神",
        pflogic = 1204,
        priority = 500,
        skill_icon = 51204,
        type_desc = "解异常",
    },

    [1205] = {
        ai_action_type = 107,
        ai_target = 2,
        cd = 0,
        desc = "复活死亡队友，并回复一定气血",
        effectType = 1205,
        id = 1205,
        is_active = 1,
        name = "轮回",
        pflogic = 1205,
        priority = 1000,
        skill_icon = 51205,
        type_desc = "复活",
    },

    [1206] = {
        ai_action_type = 106,
        ai_target = 2,
        cd = 1,
        desc = [=[为友方单位附加不动明王状态，受到伤害大幅度减少，持续1个回合
技能冷却回合：1]=],
        effectType = 1206,
        id = 1206,
        is_active = 1,
        name = "不动明王",
        pflogic = 1206,
        priority = 500,
        skill_icon = 51206,
        type_desc = "减伤",
    },

    [1207] = {
        ai_action_type = 104,
        ai_target = 6,
        cd = 0,
        desc = "消耗所有灵气,让友方目标瞬间回复至满血状态，使用后自身防御大大降低（无法对自己使用）",
        effectType = 1207,
        id = 1207,
        is_active = 1,
        name = "佛法无边",
        pflogic = 1207,
        priority = 0,
        skill_icon = 51207,
        type_desc = "绝技",
    },

    [1301] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "法术攻击多个目标",
        effectType = 1301,
        id = 1301,
        is_active = 1,
        name = "太初神火",
        pflogic = 1301,
        priority = 2000,
        skill_icon = 51301,
        type_desc = "群攻",
    },

    [1302] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "法术攻击敌方全体，并且消耗目标法力值",
        effectType = 1302,
        id = 1302,
        is_active = 1,
        name = "法力冰封",
        pflogic = 1302,
        priority = 100,
        skill_icon = 51302,
        type_desc = "烧蓝",
    },

    [1303] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "用火焰法术攻击单体目标，并有几率额外攻击其他目标1次，灵力越高，几率越高",
        effectType = 1303,
        id = 1303,
        is_active = 1,
        name = "神炎焚身",
        pflogic = 1303,
        priority = 3000,
        skill_icon = 51303,
        type_desc = "单攻",
    },

    [1304] = {
        ai_action_type = 105,
        ai_target = 7,
        cd = 0,
        desc = "解除友方单位身上的封印状态",
        effectType = 1304,
        id = 1304,
        is_active = 1,
        name = "清心",
        pflogic = 1304,
        priority = 0,
        skill_icon = 51304,
        type_desc = "解异常",
    },

    [1305] = {
        ai_action_type = 108,
        ai_target = 2,
        cd = 0,
        desc = "让敌方一个目标被星灵之力禁锢，2回合内，目标的物理攻击有概率自动选择目标。",
        effectType = 1305,
        id = 1305,
        is_active = 1,
        name = "星灵禁",
        pflogic = 1305,
        priority = 500,
        skill_icon = 51305,
        type_desc = "偏离",
    },

    [1306] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "风刃攻击敌方2个目标",
        effectType = 1306,
        id = 1306,
        is_active = 1,
        name = "九天罡风",
        pflogic = 1306,
        priority = 500,
        skill_icon = 51306,
        type_desc = "双目标",
    },

    [1307] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "消耗所有灵气,汇聚星辰之力攻击目标，伤害有一定波动，并且目标法力值越低，伤害越高。使用后休息一回合",
        effectType = 1307,
        id = 1307,
        is_active = 1,
        name = "星宿审判",
        pflogic = 1307,
        priority = 0,
        skill_icon = 51307,
        type_desc = "绝技",
    },

    [1401] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "勾连九天之上的神雷，对多目标造成固定伤害",
        effectType = 1201,
        id = 1401,
        is_active = 1,
        name = "风云雷动",
        pflogic = 1401,
        priority = 2000,
        skill_icon = 51401,
        type_desc = "群攻",
    },

    [1402] = {
        ai_action_type = 109,
        ai_target = 2,
        cd = 2,
        desc = [=[召唤杏黄旗，治疗友方单位，并增加物理防御，效果持续数回合
技能冷却回合：2]=],
        effectType = 1202,
        id = 1402,
        is_active = 1,
        name = "杏黄旗",
        pflogic = 1402,
        priority = 3000,
        skill_icon = 51402,
        type_desc = "召唤",
    },

    [1403] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "用法术腐蚀敌人，有概率让其进入中毒状态，每回合损失一定气血,且有概率偷取目标1点灵气",
        effectType = 1203,
        id = 1403,
        is_active = 1,
        name = "木灵蚀心",
        pflogic = 1403,
        priority = 2000,
        skill_icon = 51403,
        type_desc = "毒",
    },

    [1404] = {
        ai_action_type = 106,
        ai_target = 3,
        cd = 9,
        desc = [=[使自己在接下来1个回合内受到致死攻击时，回复1点气血
技能冷却回合：9]=],
        effectType = 1207,
        id = 1404,
        is_active = 1,
        name = "天神法相",
        pflogic = 1404,
        priority = 0,
        skill_icon = 51407,
        type_desc = "免死",
    },

    [1405] = {
        ai_action_type = 109,
        ai_target = 2,
        cd = 3,
        desc = [=[召唤天兵，每回合会使用法术攻击敌人，并且让目标的物理防御降低
技能冷却回合：3]=],
        effectType = 1205,
        id = 1405,
        is_active = 1,
        name = "神兵天降",
        pflogic = 1405,
        priority = 0,
        skill_icon = 51405,
        type_desc = "召唤",
    },

    [1406] = {
        ai_action_type = 106,
        ai_target = 2,
        cd = 0,
        desc = "为多个友方单位增加仙气灌顶状态，每回合恢复一定法力",
        effectType = 1206,
        id = 1406,
        is_active = 1,
        name = "仙气灌顶",
        pflogic = 1406,
        priority = 0,
        skill_icon = 51406,
        type_desc = "回蓝",
    },

    [1407] = {
        ai_action_type = 106,
        ai_target = 2,
        cd = 0,
        desc = "消耗所有灵气,鼓舞队友，使队友本回合伤害治疗效果大幅提升",
        effectType = 1204,
        id = 1407,
        is_active = 1,
        name = "神威",
        pflogic = 1407,
        priority = 0,
        skill_icon = 51404,
        type_desc = "绝技",
    },

    [1408] = {
        ai_action_type = 204,
        ai_target = 3,
        cd = 0,
        desc = "为全队回复少量血量",
        effectType = 1207,
        id = 1408,
        is_active = 1,
        name = "仙气萦绕",
        pflogic = 1408,
        priority = 0,
        skill_icon = 51407,
        type_desc = "群疗",
    },

    [1409] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "对2个目标造成伤害，并降低他们的物理防御",
        effectType = 1201,
        id = 1409,
        is_active = 1,
        name = "天雷蚀甲",
        pflogic = 1409,
        priority = 2000,
        skill_icon = 51401,
        type_desc = "群攻",
    },

    [1501] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "召唤即将化龙的千年蛇妖，对多目标造成固定伤害",
        effectType = 1201,
        id = 1501,
        is_active = 1,
        name = "龙蛇吐息",
        pflogic = 1501,
        priority = 1000,
        skill_icon = 51501,
        type_desc = "群攻",
    },

    [1502] = {
        ai_action_type = 102,
        ai_target = 2,
        cd = 0,
        desc = "封印目标，使目标无法使用法术",
        effectType = 1202,
        id = 1502,
        is_active = 1,
        name = "封灵咒",
        pflogic = 1502,
        priority = 3000,
        skill_icon = 51502,
        type_desc = "单封",
    },

    [1503] = {
        ai_action_type = 102,
        ai_target = 2,
        cd = 0,
        desc = "使目标进入混乱状态，不分敌我攻击。此法术较难命中玩家单位",
        effectType = 1203,
        id = 1503,
        is_active = 1,
        name = "迷魂",
        pflogic = 1503,
        priority = 500,
        skill_icon = 51503,
        type_desc = "混乱",
    },

    [1504] = {
        ai_action_type = 106,
        ai_target = 2,
        cd = 0,
        desc = "牺牲自身气血，恢复一定法术",
        effectType = 1204,
        id = 1504,
        is_active = 1,
        name = "妖气归元",
        pflogic = 1504,
        priority = 0,
        skill_icon = 51504,
        type_desc = "回蓝",
    },

    [1505] = {
        ai_action_type = 102,
        ai_target = 2,
        cd = 1,
        desc = [=[封印目标，使目标无法使攻击和法术，但下个回合封印命中降低
技能冷却回合：1]=],
        effectType = 1205,
        id = 1505,
        is_active = 1,
        name = "封神咒",
        pflogic = 1505,
        priority = 1000,
        skill_icon = 51505,
        type_desc = "双封",
    },

    [1506] = {
        ai_action_type = 101,
        ai_target = 2,
        cd = 0,
        desc = "对单个目标造成较大伤害",
        effectType = 1206,
        id = 1506,
        is_active = 1,
        name = "噬灵",
        pflogic = 1506,
        priority = 0,
        skill_icon = 51506,
        type_desc = "单攻",
    },

    [1507] = {
        ai_action_type = 202,
        ai_target = 2,
        cd = 0,
        desc = "消耗所有灵力，对多个目标进行封印，使目标无法使用攻击和法术",
        effectType = 1207,
        id = 1507,
        is_active = 1,
        name = "禁断万古",
        pflogic = 1507,
        priority = 0,
        skill_icon = 51507,
        type_desc = "绝技",
    },

    [1601] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "使用物理攻击多个敌方单位",
        effectType = 1201,
        id = 1601,
        is_active = 1,
        name = "千军破",
        pflogic = 1601,
        priority = 2000,
        skill_icon = 51601,
        type_desc = "群攻",
    },

    [1602] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "攻击目标，并且削弱目标防御2个回合",
        effectType = 1202,
        id = 1602,
        is_active = 1,
        name = "卸甲",
        pflogic = 1602,
        priority = 500,
        skill_icon = 51602,
        type_desc = "破防",
    },

    [1603] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "攻击敌方前排目标，对后排也造成伤害，伤害为前排目标的100%",
        effectType = 1203,
        id = 1603,
        is_active = 1,
        name = "破阵冲击",
        pflogic = 1603,
        priority = 1000,
        skill_icon = 51603,
        type_desc = "前后排",
    },

    [1604] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "对敌方单体造成大量伤害，自己承受本次伤害的20%",
        effectType = 1204,
        id = 1604,
        is_active = 1,
        name = "骁勇冲锋",
        pflogic = 1604,
        priority = 500,
        skill_icon = 51604,
        type_desc = "单攻",
    },

    [1605] = {
        ai_action_type = 110,
        ai_target = 11,
        cd = 3,
        desc = [=[牺牲一定物理伤害能力，下回合物理伤害技能会释放两次。
技能冷却回合：3]=],
        effectType = 1205,
        id = 1605,
        is_active = 1,
        name = "战神",
        pflogic = 1605,
        priority = 2000,
        skill_icon = 51605,
        type_desc = "蓄力",
    },

    [1606] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "引用杀破狼三凶星的气势，使用物理攻击多个敌方单位,使用后休息1回合",
        effectType = 1206,
        id = 1606,
        is_active = 1,
        name = "杀破狼",
        pflogic = 1606,
        priority = 2000,
        skill_icon = 51606,
        type_desc = "群攻",
    },

    [1607] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "消耗所有灵力，攻击目标，若击杀目标，则会再次释放唯我独尊，最多额外释放3次",
        effectType = 1207,
        id = 1607,
        is_active = 1,
        name = "唯我独尊",
        pflogic = 1607,
        priority = 0,
        skill_icon = 51607,
        type_desc = "绝技",
    },

    [1608] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "消耗1点灵气对目标造成多次伤害，攻击次数受技能等级影响，使用后休息1回合(战神效果对该技能无效)",
        effectType = 1204,
        id = 1608,
        is_active = 1,
        name = "妖月连斩",
        pflogic = 1608,
        priority = 500,
        skill_icon = 51604,
        type_desc = "单攻",
    },

}
