-- ./excel/perform/perform_summon.xlsx
return {

    [5101] = {
        desc = "受到物理攻击时，10%+skill*2%几率使用普通攻击对目标反击",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5101,
        name = "复仇",
        passiveDelay = 0,
        passiveIcon = "51001",
        skill_formula = "10+(level-1)/4*10",
        skill_icon = 0,
        timing = 2,
    },

    [5103] = {
        desc = "物理攻击时忽略目标物理防御skill*1%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5103,
        name = "进击",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "2+(level-1)/4*3",
        skill_icon = 0,
        timing = 0,
    },

    [5104] = {
        desc = "提高最终伤害5%+skill*1%；不会受到反击和反震的影响",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5104,
        name = "暗杀",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "5+(level-1)/4*5",
        skill_icon = 0,
        timing = 0,
    },

    [5105] = {
        desc = "物理攻击时，吸收造成伤害15%+skill*3%的气血",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5105,
        name = "生命汲取",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20+(level-1)/4*10",
        skill_icon = 0,
        timing = 0,
    },

    [5106] = {
        desc = "物理攻击时对额外两个单位造成最终伤害5%+skill*2%的伤害",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5106,
        name = "分裂",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "7+(level-1)/4*8",
        skill_icon = 0,
        timing = 0,
    },

    [5107] = {
        desc = "普通攻击时，45%+skill*2%概率连续攻击目标2次，造成的伤害结果减少50%-5%*skill",
        effectTime = {},
        effectType = 0,
        extArgs = "25-(level-1)/4*5",
        id = 5107,
        name = "连斩",
        passiveDelay = 500,
        passiveIcon = "51019",
        skill_formula = "45+(level-1)/4*10",
        skill_icon = 0,
        timing = 2,
    },

    [5108] = {
        desc = "普通攻击时，若击杀目标，则马上对一个随机敌方目标进行普通攻击，伤害为正常的50%+10%*skill",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5108,
        name = "追击",
        passiveDelay = 0,
        passiveIcon = "51004",
        skill_formula = "50+(level-1)/4*50",
        skill_icon = 0,
        timing = 2,
    },

    [5110] = {
        desc = "法术攻击时，有25%+skill使用同样的技能连斩，连斩的伤害减半",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5110,
        name = "法术连斩",
        passiveDelay = 0,
        passiveIcon = "51003",
        skill_formula = "20+(level-1)/4*10",
        skill_icon = 0,
        timing = 2,
    },

    [5111] = {
        desc = "法术攻击伤害结果在[80%-skill*4%，120+skill*4%]范围内波动",
        effectTime = {},
        effectType = 0,
        extArgs = "120+(level-1)/4*20",
        id = 5111,
        name = "法力波动",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "80-(level-1)/4*20",
        skill_icon = 0,
        timing = 1,
    },

    [5113] = {
        desc = "法术伤害结果提高10+2%*skill",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5113,
        name = "魔化",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10+(level-1)/4*10",
        skill_icon = 0,
        timing = 0,
    },

    [5114] = {
        desc = "法术攻击时忽视法术防御1%*skill",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5114,
        name = "法防忽视",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "2+(level-1)/4*3",
        skill_icon = 0,
        timing = 0,
    },

    [5115] = {
        desc = "受到单体物理攻击时，20%+skill*2%几率反震对方，反震伤害为50%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5115,
        name = "震荡",
        passiveDelay = 0,
        passiveIcon = "51005",
        skill_formula = "30+(level-1)/4*20",
        skill_icon = 0,
        timing = 2,
    },

    [5116] = {
        desc = "死亡后5回合自动复活，回复气血上限#1%；（1-3级鬼魂术，无法接受药物和主动技能治疗，以及不会受到任何状态影响，而且不会被吸血；4级或更高的鬼魂术不会受到异常状态，不会被吸血)",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5116,
        name = "亡魂",
        passiveDelay = 1000,
        passiveIcon = "51006",
        skill_formula = "70+(level-1)/4*30",
        skill_icon = 0,
        timing = 1,
    },

    [5117] = {
        desc = "死亡时有几率自动复活，复活气血为50%+skill*10%；复活几率为，20%*((自身等级*2.5+20)/自身体质)，最低15%，最高25%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5117,
        name = "还阳",
        passiveDelay = 1000,
        passiveIcon = "51007",
        skill_formula = "60+(level-1)/4*40",
        skill_icon = 0,
        timing = 2,
    },

    [5118] = {
        desc = "50%+skill*10%几率免疫所有负面状态，包括封印类、debuff类、异常类状态",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5118,
        name = "定心",
        passiveDelay = 0,
        passiveIcon = "51008",
        skill_formula = "50",
        skill_icon = 0,
        timing = 0,
    },

    [5121] = {
        desc = "增加物防7%*skill，降低法攻4%*skill",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5121,
        name = "物理防御",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10",
        skill_icon = 0,
        timing = 0,
    },

    [5122] = {
        desc = "增加法防7%*skill，降低物攻4%*skill",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5122,
        name = "法术防御",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10",
        skill_icon = 0,
        timing = 0,
    },

    [5123] = {
        desc = "降低被物理暴击几率（2*skill+5）%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5123,
        name = "物暴抵抗",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "7+(level-1)/4*8",
        skill_icon = 0,
        timing = 0,
    },

    [5124] = {
        desc = "5%*skill几率免疫土属性伤害，并恢复对应气血",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5124,
        name = "土系吸收",
        passiveDelay = 0,
        passiveIcon = "51009",
        skill_formula = "15+(level-1)/4*15",
        skill_icon = 0,
        timing = 2,
    },

    [5125] = {
        desc = "5%*skill几率免疫水属性伤害，并恢复对应气血",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5125,
        name = "水系吸收",
        passiveDelay = 0,
        passiveIcon = "51010",
        skill_formula = "15+(level-1)/4*15",
        skill_icon = 0,
        timing = 2,
    },

    [5126] = {
        desc = "5%*skill几率免疫火属性伤害，并恢复对应气血",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5126,
        name = "火系吸收",
        passiveDelay = 0,
        passiveIcon = "51011",
        skill_formula = "15+(level-1)/4*15",
        skill_icon = 0,
        timing = 2,
    },

    [5127] = {
        desc = "5%*skill几率免疫风属性伤害，并恢复对应气血",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5127,
        name = "风系吸收",
        passiveDelay = 0,
        passiveIcon = "51012",
        skill_formula = "15+(level-1)/4*15",
        skill_icon = 0,
        timing = 2,
    },

    [5128] = {
        desc = "对拥有鬼魂技能的目标伤害增加50%+skill*10%，如果目标被打死，则直接出场",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5128,
        name = "伏魔",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "50+(level-1)/4*50",
        skill_icon = 0,
        timing = 0,
    },

    [5130] = {
        desc = "抵抗封印技能，增加35%+7%*skill封印抵抗，自身最终物理伤害降低20%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5130,
        name = "戒心",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "50+(level-1)/4*50",
        skill_icon = 0,
        timing = 0,
    },

    [5131] = {
        desc = "增加（自身已损气血/自身最大气血）/（8-skill*0.6）+10%+skill*2%的防御",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5131,
        name = "坚守",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "(1-(hp/maxhp))*(0.1+(level-1)/4*0.1)*100",
        skill_icon = 0,
        timing = 0,
    },

    [5132] = {
        desc = "隐身一定回合，初始2回合，3级2~3回合，4级3~4回合，5级3~5回合；降低自身15%物理攻击，隐身状态不可使用主动技能",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5132,
        name = "隐身",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20-(level-1)/4*5",
        skill_icon = 0,
        timing = 0,
    },

    [5133] = {
        desc = "受到物理伤害时，有20%+skill*2的概率减免30%的伤害",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5133,
        name = "拆招",
        passiveDelay = 0,
        passiveIcon = "51015",
        skill_formula = "20+(level-1)/4*10",
        skill_icon = 0,
        timing = 2,
    },

    [5134] = {
        desc = "每阵亡一个队友，物理攻击增加2%*skill，最高累计5次",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5134,
        name = "同仇敌忾",
        passiveDelay = 0,
        passiveIcon = "51016",
        skill_formula = "1+(level-1)/4*2",
        skill_icon = 0,
        timing = 2,
    },

    [5135] = {
        desc = "每回合自动恢复15*skill+25的MP",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5135,
        name = "入定",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "(math.max(level,3))/10*grade",
        skill_icon = 0,
        timing = 0,
    },

    [5136] = {
        desc = "有10%+skill%*2几率使用技能时不消耗MP",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5136,
        name = "灵机一动",
        passiveDelay = 0,
        passiveIcon = "51018",
        skill_formula = "10+(level-1)/4*10",
        skill_icon = 0,
        timing = 1,
    },

    [5137] = {
        desc = "使用物理攻击时的暴击几率提高10%+skill*2%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5137,
        name = "暴击",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10+(level-1)/4*10",
        skill_icon = 0,
        timing = 0,
    },

    [5138] = {
        desc = "不会逃跑，受到带有气势或者震慑的宠物攻击时，受到伤害减少20%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5138,
        name = "勇敢",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10+(level-1)/4*10",
        skill_icon = 0,
        timing = 0,
    },

    [5139] = {
        desc = "出战前2回合物理伤害增加10%",
        effectTime = {},
        effectType = 0,
        extArgs = "{buff=227,bout=2}",
        id = 5139,
        name = "气势",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10+(level-1)/4*10",
        skill_icon = 0,
        timing = 0,
    },

    [5140] = {
        desc = "出战前2回合法术伤害增加10%",
        effectTime = {},
        effectType = 0,
        extArgs = "{buff=228,bout=2}",
        id = 5140,
        name = "震慑",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10+(level-1)/4*10",
        skill_icon = 0,
        timing = 0,
    },

    [5418] = {
        desc = "50%+skill*10%几率免疫所有负面状态，包括封印类、debuff类、异常类状态",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5418,
        name = "高级定心",
        passiveDelay = 0,
        passiveIcon = "51008",
        skill_formula = "100",
        skill_icon = 0,
        timing = 2,
    },

    [5502] = {
        desc = "触发暴击时，有一定的概率将伤害效果提高的3倍。",
        effectTime = {},
        effectType = 0,
        extArgs = "100",
        id = 5502,
        name = "暴击强化",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10",
        skill_icon = 0,
        timing = 0,
    },

    [5507] = {
        desc = "触发连斩时，有概率多攻击一个单位，伤害为正常伤害的50%",
        effectTime = {},
        effectType = 0,
        extArgs = "50",
        id = 5507,
        name = "连斩强化",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "25",
        skill_icon = 0,
        timing = 0,
    },

    [5509] = {
        desc = "若主人普通攻击一个目标，有30%的概率触发协同攻击。",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5509,
        name = "协同",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "30",
        skill_icon = 0,
        timing = 0,
    },

    [5510] = {
        desc = "对拥有增益效果的单位伤害增加10%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5510,
        name = "逆击",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10",
        skill_icon = 0,
        timing = 0,
    },

    [5511] = {
        desc = "对生命值小于30%的单位伤害增加15%",
        effectTime = {},
        effectType = 0,
        extArgs = "15",
        id = 5511,
        name = "嗜血",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "30",
        skill_icon = 0,
        timing = 0,
    },

    [5513] = {
        desc = "攻击有20%的概率造成自身速度与对手速度差的伤害",
        effectTime = {},
        effectType = 0,
        extArgs = "{min_damage=0.1*att_speed,damage=(att_speed-def_speed)*1}",
        id = 5513,
        name = "突击",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20",
        skill_icon = 0,
        timing = 0,
    },

    [5514] = {
        desc = "攻击同一个目标伤害增加",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5514,
        name = "仇恨",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "10+grade*att_cnt*2",
        skill_icon = 0,
        timing = 0,
    },

    [5520] = {
        desc = "失去隐身后，有20%的概率再次进入影身",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5520,
        name = "隐遁",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20",
        skill_icon = 0,
        timing = 0,
    },

    [5521] = {
        desc = "战斗开始的前3个回合，物防提高20%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5521,
        name = "铁壁",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20",
        skill_icon = 0,
        timing = 0,
    },

    [5522] = {
        desc = "击杀目标后，恢复自身生命20%的气血",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5522,
        name = "血祭",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20",
        skill_icon = 0,
        timing = 0,
    },

    [5524] = {
        desc = "鬼魂复活的回合数-1",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5524,
        name = "鬼魂强化",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "",
        skill_icon = 0,
        timing = 0,
    },

    [5527] = {
        desc = "宠物攻击目标，50%概率将伤害20%转化为主人的生命值",
        effectTime = {},
        effectType = 0,
        extArgs = "20",
        id = 5527,
        name = "报恩",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "50",
        skill_icon = 0,
        timing = 0,
    },

    [5531] = {
        desc = "每次受到伤害，30%概率将伤害的30%转移到一个随机敌方单位身上",
        effectTime = {},
        effectType = 0,
        extArgs = "{res_damage=30, rec_damage=70}",
        id = 5531,
        name = "移花接木",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "30",
        skill_icon = 0,
        timing = 0,
    },

    [5541] = {
        desc = "战斗开始的前3个回合，法术防御力提高20%（不能计入buff最大上限为3的体系）",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5541,
        name = "法术抵抗",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20",
        skill_icon = 0,
        timing = 0,
    },

    [5542] = {
        desc = "法术攻击有20%概率去掉目标身上的一项增益状态",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5542,
        name = "净化",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20",
        skill_icon = 0,
        timing = 0,
    },

    [5543] = {
        desc = "法术攻击有20%概率让目标防御下降5%",
        effectTime = {},
        effectType = 0,
        extArgs = "{buff=229,bout=2}",
        id = 5543,
        name = "蚀甲",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20",
        skill_icon = 0,
        timing = 0,
    },

    [5544] = {
        desc = "法术攻击有20%概率让目标速度下降5%",
        effectTime = {},
        effectType = 0,
        extArgs = "{buff=230,bout=2}",
        id = 5544,
        name = "流沙",
        passiveDelay = 0,
        passiveIcon = "",
        skill_formula = "20",
        skill_icon = 0,
        timing = 0,
    },

    [5701] = {
        desc = "鬼魂宠物倒地后，下回合开始，每回合获得1个魄，或者有己方单位死亡时（触发鬼魂和神佑除外）获得1个魄。累计获得5个魄后提前复活。",
        effectTime = {},
        effectType = 0,
        extArgs = "{ghost_cnt=5,hp_ratio=30}",
        id = 5701,
        name = "凝魄",
        passiveDelay = 0,
        passiveIcon = "51026",
        skill_formula = "",
        skill_icon = 0,
        timing = 0,
    },

    [5702] = {
        desc = "参加战斗后，前3回合，宠物与主人分摊彼此受到伤害的30%",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5702,
        name = "患难",
        passiveDelay = 0,
        passiveIcon = "51027",
        skill_formula = "",
        skill_icon = 0,
        timing = 0,
    },

    [5703] = {
        desc = "击倒一个单位后，下次物理攻击附加重伤效果，持续3回合。",
        effectTime = {},
        effectType = 0,
        extArgs = "{buff=233,bout=3}",
        id = 5703,
        name = "狂暴",
        passiveDelay = 0,
        passiveIcon = "51028",
        skill_formula = "",
        skill_icon = 0,
        timing = 0,
    },

    [5704] = {
        desc = "参加战斗，前2回合血量提升50%，第2回合结束后，扣除提升的50%气血值和气血上限，可能会导致宠物死亡。",
        effectTime = {},
        effectType = 0,
        extArgs = "{hp_percent=50,bout=2}",
        id = 5704,
        name = "好战",
        passiveDelay = 1000,
        passiveIcon = "51029",
        skill_formula = "",
        skill_icon = 0,
        timing = 0,
    },

    [5705] = {
        desc = "如果当前回合收到3次物理或者法术伤害，则下回合减免20%受到的伤害结果。",
        effectTime = {},
        effectType = 0,
        extArgs = "{damage_cnt=3,damaged_ratio=-20}",
        id = 5705,
        name = "石化",
        passiveDelay = 0,
        passiveIcon = "51030",
        skill_formula = "",
        skill_icon = 0,
        timing = 0,
    },

    [5706] = {
        desc = "倒地时，为场上未死的宠物中气血百分比最低的回满气血。",
        effectTime = {},
        effectType = 0,
        extArgs = "",
        id = 5706,
        name = "不甘",
        passiveDelay = 1000,
        passiveIcon = "51031",
        skill_formula = "",
        skill_icon = 0,
        timing = 0,
    },

}
