-- ./excel/perform/perform_summon.xlsx
return {

    [5129] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "无视隐身，且对隐身目标增伤害",
        effectType = 5201,
        id = 5129,
        is_active = 1,
        name = "天眼",
        pflogic = 5129,
        priority = 100,
        skill_icon = 50004,
        type_desc = "无视隐身",
    },

    [5201] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "单体法术攻击，造成土属性法术伤害",
        effectType = 5201,
        id = 5201,
        is_active = 1,
        name = "地动",
        pflogic = 5201,
        priority = 100,
        skill_icon = 50006,
        type_desc = "单体伤害",
    },

    [5202] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "单体法术攻击，造成水属性法术伤害",
        effectType = 5201,
        id = 5202,
        is_active = 1,
        name = "水雷",
        pflogic = 5202,
        priority = 100,
        skill_icon = 50007,
        type_desc = "单体伤害",
    },

    [5203] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "单体法术攻击，造成火属性法术伤害",
        effectType = 5201,
        id = 5203,
        is_active = 1,
        name = "心火",
        pflogic = 5203,
        priority = 100,
        skill_icon = 50008,
        type_desc = "单体伤害",
    },

    [5204] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "单体法术攻击，造成风属性法术伤害",
        effectType = 5201,
        id = 5204,
        is_active = 1,
        name = "龙卷",
        pflogic = 5204,
        priority = 100,
        skill_icon = 50009,
        type_desc = "单体伤害",
    },

    [5205] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "群体法术攻击，造成土属性法术伤害，初始作用2个目标，3级作用3个目标",
        effectType = 5201,
        id = 5205,
        is_active = 1,
        name = "山崩地裂",
        pflogic = 5205,
        priority = 200,
        skill_icon = 50210,
        type_desc = "群体伤害",
    },

    [5206] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "群体法术攻击，造成水属性法术伤害，初始作用2个目标，3级作用3个目标",
        effectType = 5201,
        id = 5206,
        is_active = 1,
        name = "冰封万里",
        pflogic = 5206,
        priority = 200,
        skill_icon = 50211,
        type_desc = "群体伤害",
    },

    [5207] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "群体法术攻击，造成火属性法术伤害，初始作用2个目标，3级作用3个目标",
        effectType = 5201,
        id = 5207,
        is_active = 1,
        name = "焚天怒火",
        pflogic = 5207,
        priority = 200,
        skill_icon = 50212,
        type_desc = "群体伤害",
    },

    [5208] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "群体法术攻击，造成风属性法术伤害，初始作用2个目标，3级作用3个目标",
        effectType = 5201,
        id = 5208,
        is_active = 1,
        name = "风卷残云",
        pflogic = 5208,
        priority = 200,
        skill_icon = 50213,
        type_desc = "群体伤害",
    },

    [5209] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "单体物理攻击，对目标额外造成（目标已损气血/目标最大气血）一定比例的伤害",
        effectType = 5201,
        id = 5209,
        is_active = 1,
        name = "趁势而上",
        pflogic = 5209,
        priority = 200,
        skill_icon = 50051,
        type_desc = "单体伤害",
    },

    [5210] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "单体物理攻击，对目标额外造成（自身已损气血/自身最大气血）一定比例的伤害",
        effectType = 5201,
        id = 5210,
        is_active = 1,
        name = "以牙还牙",
        pflogic = 5210,
        priority = 200,
        skill_icon = 50003,
        type_desc = "单体伤害",
    },

    [5211] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "群体物理攻击，对首目标造成100%伤害，同时对1个随机目标造成一定的伤害；满级后2个额外目标",
        effectType = 5201,
        id = 5211,
        is_active = 1,
        name = "爆破",
        pflogic = 5211,
        priority = 200,
        skill_icon = 50205,
        type_desc = "群体伤害",
    },

    [5212] = {
        ai_action_type = 201,
        ai_target = 2,
        cd = 0,
        desc = "群体物理攻击，初始作用2个目标，3级作用3个目标",
        effectType = 5201,
        id = 5212,
        is_active = 1,
        name = "金雷震爆",
        pflogic = 5212,
        priority = 200,
        skill_icon = 50202,
        type_desc = "群体伤害",
    },

    [5213] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "单体物理攻击，若目标防御，则伤害增加",
        effectType = 5201,
        id = 5213,
        is_active = 1,
        name = "摧心",
        pflogic = 5213,
        priority = 200,
        skill_icon = 50201,
        type_desc = "单体伤害",
    },

    [5301] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "单体物理攻击，临时提高自身攻击，自身损耗相应伤害的气血，伤害结果提高；气血低于上限30%时无法使用",
        effectType = 1102,
        id = 5301,
        is_active = 1,
        name = "背水一战",
        pflogic = 5301,
        priority = 200,
        skill_icon = 50126,
        type_desc = "单体伤害",
    },

    [5302] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "单体物理攻击，几率对目标造成额外伤害，若失败则为对方恢复100%伤害的气血",
        effectType = 1102,
        id = 5302,
        is_active = 1,
        name = "阎罗令",
        pflogic = 5302,
        priority = 200,
        skill_icon = 50215,
        type_desc = "单体伤害",
    },

    [5304] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "目标物攻越低则受到伤害越高",
        effectType = 1102,
        id = 5304,
        is_active = 1,
        name = "降龙伏虎",
        pflogic = 5304,
        priority = 200,
        skill_icon = 50215,
        type_desc = "单体伤害",
    },

    [5305] = {
        ai_action_type = 101,
        ai_target = 3,
        cd = 0,
        desc = "对目标造成法术伤害，并且有概率（25%）令目标在4回合内无法复活",
        effectType = 1102,
        id = 5305,
        is_active = 1,
        name = "幽冥噬魂",
        pflogic = 5305,
        priority = 200,
        skill_icon = 50215,
        type_desc = "单体伤害",
    },

    [5306] = {
        ai_action_type = 201,
        ai_target = 3,
        cd = 0,
        desc = "法术攻击敌方3人，并且消耗目标的法力值，如果目标是NPC，则会吸取一定法力值给主人",
        effectType = 1102,
        id = 5306,
        is_active = 1,
        name = "星华绽放",
        pflogic = 5306,
        priority = 200,
        skill_icon = 50256,
        type_desc = "群体伤害",
    },

}
