-- ./excel/huodong/grow/config.xlsx
return {

    [1] = {
        icon = "10253",
        id = 1,
        level = 1,
        level_index = 1,
        name = "获得任意1只宠物",
        reward = 1001,
        stype = "SUMMON_SYS",
        view = "SUMMON_SYS",
    },

    [2] = {
        icon = "h7_haoyou_1",
        id = 2,
        level = 1,
        level_index = 2,
        name = "拥有第一个好友",
        reward = 1002,
        stype = "",
        view = "CFriendInfoView",
    },

    [3] = {
        icon = "10092",
        id = 3,
        level = 1,
        level_index = 3,
        name = "升级一次心法技能",
        reward = 1003,
        stype = "SKILL_BD",
        view = "SKILL_BD",
    },

    [4] = {
        icon = "h7_jingjie_1",
        id = 4,
        level = 1,
        level_index = 4,
        name = "完成序章命运",
        reward = 1004,
        stype = "",
        view = "CTaskMainView",
    },

    [6] = {
        icon = "10030",
        id = 6,
        level = 2,
        level_index = 2,
        name = "加入一个帮派，并手动在帮派频道发言1次",
        reward = 1006,
        stype = "ORG_SYS",
        view = "CChatMainView",
    },

    [10] = {
        icon = "10159",
        id = 10,
        level = 2,
        level_index = 1,
        name = "完成第一章西湖美人",
        reward = 1010,
        stype = "",
        view = "CTaskMainView",
    },

    [9] = {
        icon = "10115",
        id = 9,
        level = 2,
        level_index = 3,
        name = "一个门派招式升级到2级",
        reward = 1009,
        stype = "SKILL_ZD",
        view = "SKILL_ZD",
    },

    [5] = {
        icon = "10060",
        id = 5,
        level = 3,
        level_index = 4,
        name = "拥有4个伙伴",
        reward = 1005,
        stype = "PARTNER_SYS",
        view = "CPartnerMainView",
    },

    [11] = {
        icon = "10141",
        id = 11,
        level = 3,
        level_index = 2,
        name = "完成10次金刚伏魔",
        reward = 1011,
        stype = "ZHUAGUI",
        view = "ZHUAGUI",
    },

    [7] = {
        icon = "h7_duiwu",
        id = 7,
        level = 3,
        level_index = 1,
        name = "完成10次门派修行",
        reward = 1007,
        stype = "SHIMEN",
        view = "CTaskMainView",
    },

    [43] = {
        icon = "10263",
        id = 43,
        level = 3,
        level_index = 5,
        name = "建立1次师徒关系",
        reward = 1043,
        stype = "MENTORING",
        view = "",
    },

    [13] = {
        icon = "10036",
        id = 13,
        level = 3,
        level_index = 6,
        name = "镇妖1次",
        reward = 1013,
        stype = "FENGYAO",
        view = "FENGYAO",
    },

    [19] = {
        icon = "10167",
        id = 19,
        level = 4,
        level_index = 11,
        name = "获得冰灵马坐骑",
        reward = 1019,
        stype = "RIDE_SYS",
        view = "CHorseMainView",
    },

    [12] = {
        icon = "10022",
        id = 12,
        level = 4,
        level_index = 7,
        name = "升级帮派技能1次",
        reward = 1012,
        stype = "ORG_SKILL",
        view = "ORG_SKILL",
    },

    [14] = {
        icon = "10032",
        id = 14,
        level = 4,
        level_index = 1,
        name = "参加1次全民答题",
        reward = 1014,
        stype = "BAIKE",
        view = "CScheduleMainView",
    },

    [15] = {
        icon = "10239",
        id = 15,
        level = 4,
        level_index = 2,
        name = "强化1次装备",
        reward = 1015,
        stype = "EQUIP_QH",
        view = "CScheduleMainView",
    },

    [16] = {
        icon = "10157",
        id = 16,
        level = 4,
        level_index = 3,
        name = "参与帮派封魔1次",
        reward = 1016,
        stype = "MENGZHU",
        view = "CScheduleMainView",
    },

    [18] = {
        icon = "10155",
        id = 18,
        level = 4,
        level_index = 4,
        name = "进行1次宠物合成",
        reward = 1018,
        stype = "SUMMON_HC",
        view = "SUMMON_SYS",
    },

    [20] = {
        icon = "10115",
        id = 20,
        level = 4,
        level_index = 5,
        name = "竞技场战斗1次",
        reward = 1020,
        stype = "JJC_SYS",
        view = "CJjcMainView",
    },

    [22] = {
        icon = "10018",
        id = 22,
        level = 4,
        level_index = 8,
        name = "完成第二章情劫难解",
        reward = 1022,
        stype = "",
        view = "CTaskMainView",
    },

    [23] = {
        icon = "10027",
        id = 23,
        level = 4,
        level_index = 9,
        name = "完成第三章相爱相杀",
        reward = 1023,
        stype = "",
        view = "CTaskMainView",
    },

    [41] = {
        icon = "10038",
        id = 41,
        level = 4,
        level_index = 10,
        name = "使用藏宝图挖宝1次",
        reward = 1008,
        stype = "BAOTU",
        view = "CScheduleMainView",
    },

    [44] = {
        icon = "10038",
        id = 44,
        level = 4,
        level_index = 17,
        name = "参加1次天问答题",
        reward = 1044,
        stype = "IMPERIALEXAM",
        view = "",
    },

    [45] = {
        icon = "10023",
        id = 45,
        level = 4,
        level_index = 16,
        name = "挑战1次金玉满堂",
        reward = 1045,
        stype = "MONEYTREE",
        view = "",
    },

    [46] = {
        icon = "10004",
        id = 46,
        level = 4,
        level_index = 13,
        name = "完成1次舞动全城",
        reward = 1046,
        stype = "DANCE_STAMPS",
        view = "",
    },

    [47] = {
        icon = "10019",
        id = 47,
        level = 4,
        level_index = 15,
        name = "完成1次门派试炼",
        reward = 1047,
        stype = "SCHOOLPASS",
        view = "",
    },

    [25] = {
        icon = "10117",
        id = 25,
        level = 4,
        level_index = 6,
        name = "打造1次装备",
        reward = 1025,
        stype = "EQUIP_DZ",
        view = "CScheduleMainView",
    },

    [26] = {
        icon = "10147",
        id = 26,
        level = 4,
        level_index = 14,
        name = "完成1次异宝收集",
        reward = 1026,
        stype = "YIBAO",
        view = "CScheduleMainView",
    },

    [21] = {
        icon = "10022",
        id = 21,
        level = 4,
        level_index = 12,
        name = "参加火眼金睛1次",
        reward = 1021,
        stype = "GUESSGAME",
        view = "CScheduleMainView",
    },

    [17] = {
        icon = "10232",
        id = 17,
        level = 5,
        level_index = 3,
        name = "参与英雄试炼1次",
        reward = 1017,
        stype = "HEROTRIAL",
        view = "CScheduleMainView",
    },

    [24] = {
        icon = "10173",
        id = 24,
        level = 5,
        level_index = 1,
        name = "完成灵犀任务1次",
        reward = 1024,
        stype = "LINGXI",
        view = "CScheduleMainView",
    },

    [27] = {
        icon = "10233",
        id = 27,
        level = 5,
        level_index = 4,
        name = "参加1次三界斗法",
        reward = 1027,
        stype = "BIWU",
        view = "CScheduleMainView",
    },

    [28] = {
        icon = "10093",
        id = 28,
        level = 5,
        level_index = 5,
        name = "通关1次雷峰塔幻境副本",
        reward = 1028,
        stype = "FUMO",
        view = "CScheduleMainView",
    },

    [29] = {
        icon = "10150",
        id = 29,
        level = 5,
        level_index = 6,
        name = "升级1次头衔",
        reward = 1029,
        stype = "BADGE",
        view = "CScheduleMainView",
    },

    [30] = {
        icon = "10123",
        id = 30,
        level = 5,
        level_index = 8,
        name = "完成第四章师从紫薇",
        reward = 1030,
        stype = "",
        view = "CTaskMainView",
    },

    [31] = {
        icon = "10065",
        id = 31,
        level = 5,
        level_index = 9,
        name = "完成第五章姐妹情深",
        reward = 1031,
        stype = "",
        view = "CTaskMainView",
    },

    [42] = {
        icon = "10115",
        id = 42,
        level = 5,
        level_index = 10,
        name = "击败1次二十八星宿",
        reward = 1041,
        stype = "XINGXIU",
        view = "CScheduleMainView",
    },

    [48] = {
        icon = "10276",
        id = 48,
        level = 5,
        level_index = 14,
        name = "完成1次订婚",
        reward = 1048,
        stype = "ENGAGE_SYS",
        view = "",
    },

    [49] = {
        icon = "10115",
        id = 49,
        level = 5,
        level_index = 12,
        name = "参加1次蜀山论道",
        reward = 1049,
        stype = "SINGLEWAR",
        view = "",
    },

    [50] = {
        icon = "10117",
        id = 50,
        level = 5,
        level_index = 13,
        name = "参加1次九州争霸",
        reward = 1050,
        stype = "THREEBIWU",
        view = "",
    },

    [32] = {
        icon = "10053",
        id = 32,
        level = 5,
        level_index = 2,
        name = "洗炼1次装备",
        reward = 1032,
        stype = "EQUIP_XL",
        view = "CForgeMainView",
    },

    [33] = {
        icon = "10090",
        id = 33,
        level = 5,
        level_index = 16,
        name = "参加1次六脉会武",
        reward = 1033,
        stype = "LIUMAI",
        view = "CScheduleMainView",
    },

    [51] = {
        icon = "27000",
        id = 51,
        level = 5,
        level_index = 7,
        name = "激活1件羽翼",
        reward = 1051,
        stype = "WING",
        view = "",
    },

    [34] = {
        icon = "10099",
        id = 34,
        level = 6,
        level_index = 3,
        name = "打败1次地煞星",
        reward = 1034,
        stype = "TIANMO",
        view = "CScheduleMainView",
    },

    [35] = {
        icon = "10120",
        id = 35,
        level = 6,
        level_index = 4,
        name = "武器附魂1次",
        reward = 1035,
        stype = "EQUIP_FH",
        view = "CForgeMainView",
    },

    [37] = {
        icon = "10152",
        id = 37,
        level = 6,
        level_index = 5,
        name = "六道传说副本通关1次",
        reward = 1037,
        stype = "JYFUBEN",
        view = "CScheduleMainView",
    },

    [36] = {
        icon = "10064",
        id = 36,
        level = 6,
        level_index = 6,
        name = "完成第六章相逢断桥",
        reward = 1036,
        stype = "",
        view = "CTaskMainView",
    },

    [52] = {
        icon = "10162",
        id = 52,
        level = 6,
        level_index = 10,
        name = "完成1次结拜",
        reward = 1052,
        stype = "JIEBAI",
        view = "",
    },

    [53] = {
        icon = "10115",
        id = 53,
        level = 6,
        level_index = 8,
        name = "通关1次镇魔塔",
        reward = 1053,
        stype = "ZHENMO",
        view = "",
    },

    [54] = {
        icon = "10004",
        id = 54,
        level = 6,
        level_index = 9,
        name = "完成1次三界历练",
        reward = 1054,
        stype = "TASKCHAIN",
        view = "",
    },

    [56] = {
        icon = "26000",
        id = 56,
        level = 6,
        level_index = 7,
        name = "升级1次神器",
        reward = 1056,
        stype = "ARTIFACT",
        view = "",
    },

    [38] = {
        icon = "10066",
        id = 38,
        level = 6,
        level_index = 2,
        name = "通关1次水漫金山副本",
        reward = 1038,
        stype = "JINGSAN",
        view = "CScheduleMainView",
    },

    [39] = {
        icon = "10084",
        id = 39,
        level = 7,
        level_index = 2,
        name = "完成第七章智取王府",
        reward = 1039,
        stype = "",
        view = "CTaskMainView",
    },

    [40] = {
        icon = "10089",
        id = 40,
        level = 7,
        level_index = 3,
        name = "完成第八章三生缘续",
        reward = 1040,
        stype = "",
        view = "CTaskMainView",
    },

    [55] = {
        icon = "10023",
        id = 55,
        level = 7,
        level_index = 4,
        name = "挑战1次乱世魔影",
        reward = 1055,
        stype = "LUANSHIMOYING",
        view = "",
    },

    [57] = {
        icon = "10318",
        id = 57,
        level = 7,
        level_index = 5,
        name = "佩戴1件法宝",
        reward = 1057,
        stype = "FABAO",
        view = "",
    },

}
