-- ./excel/npc/task_xuanshang_npc.xlsx
return {

    [90011] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5106,
        id = 90011,
        mapid = 103,
        name = "裂山拳张海",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

    [90012] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5113,
        id = 90012,
        mapid = 103,
        name = "穿云箭李敢",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

    [90013] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5122,
        id = 90013,
        mapid = 103,
        name = "血剑赵阿四",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

    [90014] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5132,
        id = 90014,
        mapid = 103,
        name = "屠城金光虎",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

    [90015] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5114,
        id = 90015,
        mapid = 103,
        name = "迷城毒花妖",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

    [90016] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5115,
        id = 90016,
        mapid = 103,
        name = "迎风一刀斩",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

    [90017] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5120,
        id = 90017,
        mapid = 103,
        name = "黑魔石人",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

    [90018] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5121,
        id = 90018,
        mapid = 103,
        name = "腾云噬人虎",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

    [90019] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5112,
        id = 90019,
        mapid = 103,
        name = "血手童子",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

    [90020] = {
        dialogId = 0,
        diglogface = 0,
        event = 0,
        figureid = 5131,
        id = 90020,
        mapid = 103,
        name = "恶犬妖女",
        nameType = 1,
        reuse = 1,
        rotateY = 135.0,
        title = "悬赏",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        xunluo_id = 1,
        y = 0.0,
        z = 0.0,
    },

}
