-- ./excel/npc/task_lingxi_npc.xlsx
return {

    [62031] = {
        dialogId = 0,
        diglogface = 10235,
        event = 0,
        figureid = 8233,
        id = 62031,
        mapid = 101000,
        name = "情花幼苗",
        nameType = 1,
        no_turnface = 1,
        reuse = 1,
        rotateY = -120.0,
        title = "",
        tollgateId = 0,
        type = 3,
        x = 1.0,
        xunluo_id = 0,
        y = 1.0,
        z = 0.0,
    },

    [62032] = {
        dialogId = 0,
        diglogface = 10235,
        event = 0,
        figureid = 8234,
        id = 62032,
        mapid = 101000,
        name = "成长中的情花",
        nameType = 1,
        no_turnface = 1,
        reuse = 1,
        rotateY = -120.0,
        title = "",
        tollgateId = 0,
        type = 3,
        x = 1.0,
        xunluo_id = 0,
        y = 1.0,
        z = 0.0,
    },

    [62033] = {
        dialogId = 0,
        diglogface = 10235,
        event = 0,
        figureid = 8235,
        id = 62033,
        mapid = 101000,
        name = "成熟的情花",
        nameType = 1,
        no_turnface = 1,
        reuse = 1,
        rotateY = -120.0,
        title = "",
        tollgateId = 0,
        type = 3,
        x = 1.0,
        xunluo_id = 0,
        y = 1.0,
        z = 0.0,
    },

}
