-- ./excel/task/orgtask/task_orgtask.xlsx
return {

    [62200] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "麻烦你护送小孩安全到家",
        follownpcs = {62200},
        goalDesc = "护送#G小璎#n",
        id = 62200,
        initConfig = {"E5255:62200"},
        missiondone = {},
        name = "护送",
        quickFindWay = 0,
        submitNpcId = 11,
        submitRewardStr = {"R1001"},
        tasktype = 1,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62201] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "找人咨询下如何解决帮派困境",
        follownpcs = {},
        goalDesc = "去{map}请教{submitnpc}",
        id = 62201,
        initConfig = {"E11:62201"},
        missiondone = {},
        name = "请教",
        quickFindWay = 0,
        submitNpcId = 11,
        submitRewardStr = {"R1001"},
        tasktype = 1,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62202] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 1,
        autotype = 1,
        clientExtStr = "",
        description = "帮忙找回帮派发展需要的物资",
        follownpcs = {},
        goalDesc = "帮{submitnpc}收集{item}",
        id = 62202,
        initConfig = {"I104:1", "NC62201", "E62201:62202", "SHOP5002"},
        missiondone = {},
        name = "收集物品",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 2,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62203] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 1,
        autotype = 1,
        clientExtStr = "",
        description = "帮忙找回帮派发展需要的物资",
        follownpcs = {},
        goalDesc = "帮{submitnpc}收集{item}",
        id = 62203,
        initConfig = {"I106:1", "NC62201", "E62201:62203", "SHOP5002"},
        missiondone = {},
        name = "收集物品",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 2,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62204] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 1,
        autotype = 1,
        clientExtStr = "",
        description = "给帮派主殿找回陈设物品",
        follownpcs = {},
        goalDesc = "帮{submitnpc}找回{item}",
        id = 62204,
        initConfig = {"I206:1", "NC62201", "E62201:62204", "SHOP5002"},
        missiondone = {},
        name = "收集古董",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 2,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62205] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 1,
        autotype = 1,
        clientExtStr = "",
        description = "给帮派主殿找回陈设物品",
        follownpcs = {},
        goalDesc = "帮{submitnpc}找回{item}",
        id = 62205,
        initConfig = {"I207:1", "NC62201", "E62201:62205", "SHOP5002"},
        missiondone = {},
        name = "收集古董",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 2,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62206] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 1,
        autotype = 1,
        clientExtStr = "",
        description = "帮派需要一些装备，帮忙找回来",
        follownpcs = {},
        goalDesc = "帮{submitnpc}找回{item}",
        id = 62206,
        initConfig = {"I108:1", "NC62201", "E62201:62206", "SHOP5249"},
        missiondone = {},
        name = "收集装备",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 2,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62207] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 1,
        autotype = 1,
        clientExtStr = "",
        description = "给珍宝阁采集一些药材回来",
        follownpcs = {},
        goalDesc = "帮{submitnpc}采集{item}",
        id = 62207,
        initConfig = {"PICK201000:1001:3:6.9|4.7"},
        missiondone = {},
        name = "采集草药",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 6,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62208] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "赶走偷盗帮派物资的盗贼",
        follownpcs = {},
        goalDesc = "去{map}赶走盗贼{submitnpc}",
        id = 62208,
        initConfig = {"NC62208", "E62208:62208"},
        missiondone = {},
        name = "驱赶盗贼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62209] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "打败山贼夺回帮派物资",
        follownpcs = {},
        goalDesc = "去{map}战胜山贼{submitnpc}",
        id = 62209,
        initConfig = {"NC62209", "E62209:62209"},
        missiondone = {},
        name = "夺回物资",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62210] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "抓回帮派中离家出走的灵兽",
        follownpcs = {},
        goalDesc = "去{map}抓回逃走的{submitnpc}",
        id = 62210,
        initConfig = {"NC62210", "E62210:62210"},
        missiondone = {},
        name = "找回灵兽",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62211] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "去训练下帮派灵兽",
        follownpcs = {},
        goalDesc = "去{map}训练{submitnpc}",
        id = 62211,
        initConfig = {"NC62211", "E62211:62211"},
        missiondone = {},
        name = "训练灵兽",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 9,
    },

    [62212] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "到杭州城为帮派代言，招纳新人",
        follownpcs = {},
        goalDesc = "去{map}为帮派代言",
        id = 62212,
        initConfig = {"TASKSAY4:101000:21:17"},
        missiondone = {},
        name = "代言",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 11,
        timeout = 0,
        tips = 0,
        type = 9,
    },

}
