-- ./excel/economic/shop/jjcpoint.xlsx
return {

    [1001] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1001,
        item_attr = "10001",
        itemsid = 10001,
        money = {[7] = {["count"] = 60, ["id"] = 7}},
        shop_id = 102,
        week_limit = 15,
    },

    [1002] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1002,
        item_attr = "11076",
        itemsid = 11076,
        money = {[7] = {["count"] = 30, ["id"] = 7}},
        shop_id = 102,
        week_limit = 10,
    },

    [1003] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1003,
        item_attr = "10038",
        itemsid = 10038,
        money = {[7] = {["count"] = 48, ["id"] = 7}},
        shop_id = 102,
        week_limit = 5,
    },

    [1004] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1004,
        item_attr = "11077",
        itemsid = 11077,
        money = {[7] = {["count"] = 600, ["id"] = 7}},
        shop_id = 102,
        week_limit = 1,
    },

    [1005] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1005,
        item_attr = "11092",
        itemsid = 11092,
        money = {[7] = {["count"] = 12, ["id"] = 7}},
        shop_id = 102,
        week_limit = 0,
    },

    [1006] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1006,
        item_attr = "11093",
        itemsid = 11093,
        money = {[7] = {["count"] = 48, ["id"] = 7}},
        shop_id = 102,
        week_limit = 0,
    },

    [1007] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1007,
        item_attr = "30634",
        itemsid = 30634,
        money = {[7] = {["count"] = 68, ["id"] = 7}},
        shop_id = 102,
        week_limit = 0,
    },

    [1008] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1008,
        item_attr = "30636",
        itemsid = 30636,
        money = {[7] = {["count"] = 68, ["id"] = 7}},
        shop_id = 102,
        week_limit = 0,
    },

    [1009] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1009,
        item_attr = "11160",
        itemsid = 11160,
        money = {[7] = {["count"] = 100, ["id"] = 7}},
        shop_id = 102,
        week_limit = 0,
    },

}
