-- ./excel/economic/shop/joyexpenseold.xlsx
return {

    [1001] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1001,
        item_attr = "11184",
        itemsid = 11184,
        money = {[12] = {["count"] = 406, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1002] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1002,
        item_attr = "10163",
        itemsid = 10163,
        money = {[12] = {["count"] = 350, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1003] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1003,
        item_attr = "11187",
        itemsid = 11187,
        money = {[12] = {["count"] = 209, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1004] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1004,
        item_attr = "10158",
        itemsid = 10158,
        money = {[12] = {["count"] = 80, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1005] = {
        bind = 1,
        day_limit = 99,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1005,
        item_attr = "11155",
        itemsid = 11155,
        money = {[12] = {["count"] = 16, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1006] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1006,
        item_attr = "11160",
        itemsid = 11160,
        money = {[12] = {["count"] = 40, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1007] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1007,
        item_attr = "11161",
        itemsid = 11161,
        money = {[12] = {["count"] = 160, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1008] = {
        bind = 1,
        day_limit = 99,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1008,
        item_attr = "10009",
        itemsid = 10009,
        money = {[12] = {["count"] = 40, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1009] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1009,
        item_attr = "10180",
        itemsid = 10180,
        money = {[12] = {["count"] = 80, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1010] = {
        bind = 1,
        day_limit = 99,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1010,
        item_attr = "10077",
        itemsid = 10077,
        money = {[12] = {["count"] = 4, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1011] = {
        bind = 1,
        day_limit = 99,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1011,
        item_attr = "10036",
        itemsid = 10036,
        money = {[12] = {["count"] = 4, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1012] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1012,
        item_attr = "10010",
        itemsid = 10010,
        money = {[12] = {["count"] = 16, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1013] = {
        bind = 1,
        day_limit = 99,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1013,
        item_attr = "11140",
        itemsid = 11140,
        money = {[12] = {["count"] = 24, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1014] = {
        bind = 1,
        day_limit = 99,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1014,
        item_attr = "10164",
        itemsid = 10164,
        money = {[12] = {["count"] = 32, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1015] = {
        bind = 1,
        day_limit = 99,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1015,
        item_attr = "11099",
        itemsid = 11099,
        money = {[12] = {["count"] = 4, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1016] = {
        bind = 1,
        day_limit = 10,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1016,
        item_attr = "10197",
        itemsid = 10197,
        money = {[12] = {["count"] = 80, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1017] = {
        bind = 1,
        day_limit = 20,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1017,
        item_attr = "10169",
        itemsid = 10169,
        money = {[12] = {["count"] = 36, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1018] = {
        bind = 1,
        day_limit = 20,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1018,
        item_attr = "10155",
        itemsid = 10155,
        money = {[12] = {["count"] = 80, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1019] = {
        bind = 1,
        day_limit = 50,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1019,
        item_attr = "10156",
        itemsid = 10156,
        money = {[12] = {["count"] = 16, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1020] = {
        bind = 1,
        day_limit = 20,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1020,
        item_attr = "10157",
        itemsid = 10157,
        money = {[12] = {["count"] = 80, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1021] = {
        bind = 1,
        day_limit = 20,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1021,
        item_attr = "12939",
        itemsid = 12939,
        money = {[12] = {["count"] = 32, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1022] = {
        bind = 1,
        day_limit = 20,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1022,
        item_attr = "11176",
        itemsid = 11176,
        money = {[12] = {["count"] = 280, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1023] = {
        bind = 1,
        day_limit = 50,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1023,
        item_attr = "12912",
        itemsid = 12912,
        money = {[12] = {["count"] = 80, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

    [1024] = {
        bind = 1,
        day_limit = 50,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1024,
        item_attr = "11190",
        itemsid = 11190,
        money = {[12] = {["count"] = 134, ["id"] = 12}},
        shop_id = 201,
        week_limit = 0,
    },

}
