-- ./excel/economic/shop/leaderpoint.xlsx
return {

    [1001] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 1,
        grade_limit = 0,
        id = 1001,
        item_attr = "10082",
        itemsid = 10082,
        money = {[8] = {["count"] = 900, ["id"] = 8}},
        shop_id = 103,
        week_limit = 0,
    },

    [1002] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 1,
        grade_limit = 0,
        id = 1002,
        item_attr = "10080",
        itemsid = 10080,
        money = {[8] = {["count"] = 3000, ["id"] = 8}},
        shop_id = 103,
        week_limit = 0,
    },

    [1003] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 1,
        grade_limit = 0,
        id = 1003,
        item_attr = "10081",
        itemsid = 10081,
        money = {[8] = {["count"] = 9000, ["id"] = 8}},
        shop_id = 103,
        week_limit = 0,
    },

    [1004] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1004,
        item_attr = "10182",
        itemsid = 10182,
        money = {[8] = {["count"] = 300, ["id"] = 8}},
        shop_id = 103,
        week_limit = 0,
    },

    [1005] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1005,
        item_attr = "10183",
        itemsid = 10183,
        money = {[8] = {["count"] = 750, ["id"] = 8}},
        shop_id = 103,
        week_limit = 0,
    },

    [1006] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1006,
        item_attr = "11169",
        itemsid = 11169,
        money = {[8] = {["count"] = 150, ["id"] = 8}},
        shop_id = 103,
        week_limit = 0,
    },

    [1007] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1007,
        item_attr = "11170",
        itemsid = 11170,
        money = {[8] = {["count"] = 150, ["id"] = 8}},
        shop_id = 103,
        week_limit = 0,
    },

    [1008] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1008,
        item_attr = "11171",
        itemsid = 11171,
        money = {[8] = {["count"] = 150, ["id"] = 8}},
        shop_id = 103,
        week_limit = 0,
    },

    [1009] = {
        bind = 1,
        day_limit = 20,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1009,
        item_attr = "10031",
        itemsid = 10031,
        money = {[8] = {["count"] = 40, ["id"] = 8}},
        shop_id = 103,
        week_limit = 0,
    },

}
