-- ./excel/economic/shop/rplgoldcoin.xlsx
return {

    [1001] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1001,
        item_attr = "11141",
        itemsid = 11141,
        money = {[4] = {["count"] = 30, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1002] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1002,
        item_attr = "10075",
        itemsid = 10075,
        money = {[4] = {["count"] = 20, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1003] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1003,
        item_attr = "10076",
        itemsid = 10076,
        money = {[4] = {["count"] = 20, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1004] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1004,
        item_attr = "12120",
        itemsid = 12120,
        money = {[4] = {["count"] = 100, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1005] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1005,
        item_attr = "12140",
        itemsid = 12140,
        money = {[4] = {["count"] = 100, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1006] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1006,
        item_attr = "11181",
        itemsid = 11181,
        money = {[4] = {["count"] = 268, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1007] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1007,
        item_attr = "11075",
        itemsid = 11075,
        money = {[4] = {["count"] = 2000, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1008] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1008,
        item_attr = "11187",
        itemsid = 11187,
        money = {[4] = {["count"] = 298, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1009] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1009,
        item_attr = "11144",
        itemsid = 11144,
        money = {[4] = {["count"] = 98, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1010] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1010,
        item_attr = "11190",
        itemsid = 11190,
        money = {[4] = {["count"] = 168, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1011] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1011,
        item_attr = "11092",
        itemsid = 11092,
        money = {[4] = {["count"] = 6, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1012] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1012,
        item_attr = "11038",
        itemsid = 11038,
        money = {[4] = {["count"] = 6, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1013] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1013,
        item_attr = "10079",
        itemsid = 10079,
        money = {[4] = {["count"] = 100, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1014] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1014,
        item_attr = "10078",
        itemsid = 10078,
        money = {[4] = {["count"] = 50, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1015] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1015,
        item_attr = "11093",
        itemsid = 11093,
        money = {[4] = {["count"] = 24, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

    [1016] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1016,
        item_attr = "11094",
        itemsid = 11094,
        money = {[4] = {["count"] = 96, ["id"] = 4}},
        shop_id = 401,
        week_limit = 0,
    },

}
