-- ./excel/economic/shop/xiayipoint.xlsx
return {

    [1001] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1001,
        item_attr = "12120",
        itemsid = 12120,
        money = {[9] = {["count"] = 1000, ["id"] = 9}},
        shop_id = 104,
        week_limit = 0,
    },

    [1002] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1002,
        item_attr = "12140",
        itemsid = 12140,
        money = {[9] = {["count"] = 1000, ["id"] = 9}},
        shop_id = 104,
        week_limit = 0,
    },

    [1003] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1003,
        item_attr = "10007",
        itemsid = 10007,
        money = {[9] = {["count"] = 300, ["id"] = 9}},
        shop_id = 104,
        week_limit = 0,
    },

    [1004] = {
        bind = 1,
        day_limit = 5,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1004,
        item_attr = "10008",
        itemsid = 10008,
        money = {[9] = {["count"] = 300, ["id"] = 9}},
        shop_id = 104,
        week_limit = 0,
    },

    [1005] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1005,
        item_attr = "10161",
        itemsid = 10161,
        money = {[9] = {["count"] = 50, ["id"] = 9}},
        shop_id = 104,
        week_limit = 5,
    },

    [1006] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1006,
        item_attr = "10162",
        itemsid = 10162,
        money = {[9] = {["count"] = 50, ["id"] = 9}},
        shop_id = 104,
        week_limit = 5,
    },

    [1007] = {
        bind = 1,
        day_limit = 0,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1007,
        item_attr = "10166",
        itemsid = 10166,
        money = {[9] = {["count"] = 50, ["id"] = 9}},
        shop_id = 104,
        week_limit = 5,
    },

    [1008] = {
        bind = 1,
        day_limit = 2,
        discount = 0,
        discount_icon = "",
        forever_limit = 0,
        grade_limit = 0,
        id = 1008,
        item_attr = "10160",
        itemsid = 10160,
        money = {[9] = {["count"] = 200, ["id"] = 9}},
        shop_id = 104,
        week_limit = 0,
    },

}
