-- ./excel/item/other.xlsx
return {

    [13500] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "需要消耗一把神秘钥匙来开启，随机获得一份奖励，有可能获得还童丹、强化水晶、随机装备、伙伴材料、银两等奖励",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10180,
        id = 13500,
        introduction = "类型：宝箱",
        itemType = {2},
        item_formula = "",
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 30,
        name = "神秘宝箱",
        nimbus = 0,
        open_cost = {{["amount"] = 1, ["sid"] = 11155}},
        open_reward_id = 1001,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [13501] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 0,
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "需要消耗一把银钥匙来开启，随机获得一份奖励，有可能获得还童丹、强化水晶、随机装备、伙伴材料、银两等奖励",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10005,
        id = 13501,
        introduction = "类型：宝箱",
        itemType = {2},
        item_formula = "",
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 40,
        name = "金宝箱",
        nimbus = 0,
        open_cost = {{["amount"] = 1, ["sid"] = 11156}},
        open_reward_id = 1002,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [13502] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 0,
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "需要消耗XXX，随机获得XXX",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10005,
        id = 13502,
        introduction = "类型：宝箱",
        itemType = {2},
        item_formula = "",
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 40,
        name = "贵族宝箱",
        nimbus = 0,
        open_cost = {},
        open_reward_id = 1003,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

}
