-- ./excel/item/other.xlsx
return {

    [12000] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "10",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造30级以下武器、腰带、项链",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10020,
        id = 12000,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 30,
        name = "30级打造符",
        nimbus = 0,
        quality = 1,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12001] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "20",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造40级以下武器、腰带、项链",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10020,
        id = 12001,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 40,
        name = "40级打造符",
        nimbus = 0,
        quality = 1,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12002] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "40",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造50级以下武器、腰带、项链",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10020,
        id = 12002,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 50,
        name = "50级打造符",
        nimbus = 0,
        quality = 1,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12003] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造60级以下武器、腰带、项链",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10020,
        id = 12003,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "60级打造符",
        nimbus = 0,
        quality = 1,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12004] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "80",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造70级以下武器、腰带、项链",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10020,
        id = 12004,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 70,
        name = "70级打造符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12005] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "100",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造80级以下武器、腰带、项链",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10020,
        id = 12005,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 80,
        name = "80级打造符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12006] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "120",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造90级以下武器、腰带、项链",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10020,
        id = 12006,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 90,
        name = "90级打造符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12007] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "140",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造100级以下武器、腰带、项链",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10020,
        id = 12007,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 100,
        name = "100级打造符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12008] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "160",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造110级以下武器、腰带、项链",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10020,
        id = 12008,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 110,
        name = "110级打造符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12030] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "10",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造30级以下铠甲、头盔、鞋子",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10021,
        id = 12030,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 30,
        name = "30级裁缝符",
        nimbus = 0,
        quality = 1,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12031] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "20",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造40级以下铠甲、头盔、鞋子",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10021,
        id = 12031,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 40,
        name = "40级裁缝符",
        nimbus = 0,
        quality = 1,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12032] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "40",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造50级以下铠甲、头盔、鞋子",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10021,
        id = 12032,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 50,
        name = "50级裁缝符",
        nimbus = 0,
        quality = 1,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12033] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造60级以下铠甲、头盔、鞋子",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10021,
        id = 12033,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "60级裁缝符",
        nimbus = 0,
        quality = 1,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12034] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "80",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造70级以下铠甲、头盔、鞋子",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10021,
        id = 12034,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 70,
        name = "70级裁缝符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12035] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "100",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造80级以下铠甲、头盔、鞋子",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10021,
        id = 12035,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 80,
        name = "80级裁缝符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12036] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "120",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造90级以下铠甲、头盔、鞋子",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10021,
        id = 12036,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 90,
        name = "90级裁缝符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12037] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "140",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造100级以下铠甲、头盔、鞋子",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10021,
        id = 12037,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 100,
        name = "100级裁缝符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12038] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "160",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造110级以下铠甲、头盔、鞋子",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10021,
        id = 12038,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 110,
        name = "110级裁缝符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12060] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "10",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造30级以下装备",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10022,
        id = 12060,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 30,
        name = "30级炼金符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12061] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "20",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造40级以下装备",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10022,
        id = 12061,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 40,
        name = "40级炼金符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12062] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "40",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造50级以下装备",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10022,
        id = 12062,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 50,
        name = "50级炼金符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12063] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造60级以下装备",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10022,
        id = 12063,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "60级炼金符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12064] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "80",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造70级以下装备",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10022,
        id = 12064,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 70,
        name = "70级炼金符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12065] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "100",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造80级以下装备",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10022,
        id = 12065,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 80,
        name = "80级炼金符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12066] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "120",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造90级以下装备",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10022,
        id = 12066,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 90,
        name = "90级炼金符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12067] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "140",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造100级以下装备",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10022,
        id = 12067,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 100,
        name = "100级炼金符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

    [12068] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "160",
        circulationType = 0,
        clientExtra = "use",
        description = "用于打造110级以下装备",
        gainWayIdStr = {2, 5},
        giftPrice = 0,
        giftable = 0,
        icon = 10022,
        id = 12068,
        introduction = [=[类型：制造符
功能：打造装备]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 110,
        name = "110级炼金符",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 1,
        useCost = 1,
    },

}
