-- ./excel/item/other.xlsx
return {

    [30600] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30630}},
        description = "用于招募许仙,或用于许仙升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10090,
        id = 30600,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "许仙元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30601] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30631}},
        description = "用于招募璃镜,或用于璃镜升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10091,
        id = 30601,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "璃镜元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30602] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30632}},
        description = "用于招募洛凝霜,或用于洛凝霜升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10092,
        id = 30602,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "洛凝霜元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30603] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30633}},
        description = "用于招募渊记,或用于渊记升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10093,
        id = 30603,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "渊记元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30604] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30634}},
        description = "用于招募白素贞,或用于白素贞升阶",
        gainWayIdStr = {4, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10094,
        id = 30604,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "白素贞元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30605] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30635}},
        description = "用于招募小青,或用于小青升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10095,
        id = 30605,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "小青元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30606] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30636}},
        description = "用于招募法海,或用于法海升阶",
        gainWayIdStr = {4, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10096,
        id = 30606,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "法海元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30607] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30637}},
        description = "用于招募道济,或用于道济升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10097,
        id = 30607,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "道济元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30608] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30638}},
        description = "用于招募龙吉公主,或用于龙吉公主升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10098,
        id = 30608,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "龙吉公主元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30609] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30639}},
        description = "用于招募九天玄女,或用于九天玄女升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10099,
        id = 30609,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "九天玄女元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30610] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30640}},
        description = "用于招募时未寒,或用于时未寒升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10100,
        id = 30610,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "时未寒元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30611] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 8, ["sid"] = 30641}},
        description = "用于招募昊离归,或用于昊离归升阶",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10101,
        id = 30611,
        introduction = [=[类型：伙伴培养
功能：招募伙伴]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 9,
        minGrade = 60,
        name = "昊离归元神",
        nimbus = 0,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30630] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30600}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个许仙元神碎片可合成1个许仙元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10072,
        id = 30630,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "许仙元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30631] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30601}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个璃镜元神碎片可合成1个璃镜元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10073,
        id = 30631,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "璃镜元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30632] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30602}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个洛凝霜元神碎片可合成1个洛凝霜元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10074,
        id = 30632,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "洛凝霜元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30633] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30603}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个渊记元神碎片可合成1个渊记元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10075,
        id = 30633,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "渊记元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30634] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30604}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个白素贞元神碎片可合成1个白素贞元神",
        gainWayIdStr = {4, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10076,
        id = 30634,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "白素贞元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30635] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30605}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个小青元神碎片可合成1个小青元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10077,
        id = 30635,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "小青元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30636] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30606}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个法海元神碎片可合成1个法海元神",
        gainWayIdStr = {4, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10078,
        id = 30636,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "法海元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30637] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30607}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个道济元神碎片可合成1个道济元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10079,
        id = 30637,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "道济元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30638] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30608}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个龙吉公主元神碎片可合成1个龙吉公主元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10080,
        id = 30638,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "龙吉公主元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30639] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30609}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个九天玄女元神碎片可合成1个九天玄女元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10081,
        id = 30639,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "九天玄女元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30640] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30610}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个时未寒元神碎片可合成1个时未寒元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10082,
        id = 30640,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "时未寒元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30641] = {
        ComposeAmount = 5,
        ComposeItem = {{["amount"] = 1, ["sid"] = 30611}},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "10个昊离归元神碎片可合成1个昊离归元神",
        gainWayIdStr = {6, 30},
        giftPrice = 0,
        giftable = 0,
        icon = 10083,
        id = 30641,
        introduction = [=[类型：伙伴培养
功能：合成伙伴元神]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "昊离归元神碎片",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30660] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "50",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "用于伙伴进阶",
        gainWayIdStr = {6, 8, 25},
        giftPrice = 0,
        giftable = 0,
        icon = 10084,
        id = 30660,
        introduction = [=[类型：伙伴培养
功能：伙伴进阶]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "玄元晶",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30661] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "5",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "可以出售给商会总管换取金币或炼化获得精气",
        gainWayIdStr = {6, 14, 15},
        giftPrice = 0,
        giftable = 0,
        icon = 10085,
        id = 30661,
        introduction = "类型：道具",
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "初级辟谷丹",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30662] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "50",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "可以出售给商会总管换取金币或炼化获得精气",
        gainWayIdStr = {6, 14, 15},
        giftPrice = 0,
        giftable = 0,
        icon = 10086,
        id = 30662,
        introduction = "类型：道具",
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "中级辟谷丹",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30663] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "150",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "可以出售给商会总管换取金币或炼化获得精气",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10087,
        id = 30663,
        introduction = "类型：道具",
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "高级辟谷丹",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30664] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "50",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "伙伴进阶核心材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10088,
        id = 30664,
        introduction = [=[类型：伙伴培养
功能：提升等级]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "突破石",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30665] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "125",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "伙伴进阶辅助材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10089,
        id = 30665,
        introduction = [=[类型：伙伴培养
功能：伙伴进阶]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "突破精华",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30666] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "50",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "伙伴技能升级材料",
        gainWayIdStr = {6, 25},
        giftPrice = 0,
        giftable = 0,
        icon = 10059,
        id = 30666,
        introduction = [=[类型：伙伴培养
功能：伙伴技能升级]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "婆娑丹",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30667] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "伙伴装备升级材料，适用部位：武器，头部",
        gainWayIdStr = {6, 25},
        giftPrice = 0,
        giftable = 0,
        icon = 10290,
        id = 30667,
        introduction = [=[类型：装备材料
功能：提升装备属性]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 0,
        name = "玄铁",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30668] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "伙伴装备升级材料，适用部位：项链，衣服",
        gainWayIdStr = {6, 25},
        giftPrice = 0,
        giftable = 0,
        icon = 10291,
        id = 30668,
        introduction = [=[类型：装备材料
功能：提升装备属性]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 0,
        name = "和田玉",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [30669] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "60",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "伙伴装备升级材料，适用部位：腰带，鞋子",
        gainWayIdStr = {6, 25},
        giftPrice = 0,
        giftable = 0,
        icon = 10292,
        id = 30669,
        introduction = [=[类型：装备材料
功能：提升装备属性]=],
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 0,
        name = "天蚕丝",
        nimbus = 0,
        quality = 2,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

}
