-- ./excel/item/other.xlsx
return {

    [12100] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "300",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 2, ["sid"] = 11091}},
        description = "含有神秘之力,50级装备附魂的材料",
        gainWayIdStr = {23, 13},
        giftPrice = 0,
        giftable = 0,
        icon = 10206,
        id = 12100,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 50,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "50级神魂",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12101] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "600",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 4, ["sid"] = 11091}},
        description = "含有神秘之力,60级装备附魂的材料",
        gainWayIdStr = {23, 13},
        giftPrice = 0,
        giftable = 0,
        icon = 10206,
        id = 12101,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 60,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 70,
        name = "60级神魂",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12102] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "875",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 7, ["sid"] = 11091}},
        description = "含有神秘之力,70级装备附魂的材料",
        gainWayIdStr = {23, 13},
        giftPrice = 0,
        giftable = 0,
        icon = 10206,
        id = 12102,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 70,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 80,
        name = "70级神魂",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12103] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "1080",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 12, ["sid"] = 11091}},
        description = "含有神秘之力,80级装备附魂的材料",
        gainWayIdStr = {23, 13},
        giftPrice = 0,
        giftable = 0,
        icon = 10206,
        id = 12103,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 80,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 90,
        name = "80级神魂",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12104] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "1500",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 20, ["sid"] = 11091}},
        description = "含有神秘之力,90级装备附魂的材料",
        gainWayIdStr = {23, 13},
        giftPrice = 0,
        giftable = 0,
        icon = 10206,
        id = 12104,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 90,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 100,
        name = "90级神魂",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12105] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "1800",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 36, ["sid"] = 11091}},
        description = "含有神秘之力,100级装备附魂的材料",
        gainWayIdStr = {23, 13},
        giftPrice = 0,
        giftable = 0,
        icon = 10206,
        id = 12105,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 100,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 100,
        name = "100级神魂",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12106] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "2000",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {{["amount"] = 40, ["sid"] = 11091}},
        description = "含有神秘之力,110级装备附魂的材料",
        gainWayIdStr = {23, 13},
        giftPrice = 0,
        giftable = 0,
        icon = 10206,
        id = 12106,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 100,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 100,
        name = "110级神魂",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12120] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有青龙之力的强化石,武器、腰带、项链附魂的材料",
        gainWayIdStr = {3, 30, 48, 62},
        giftPrice = 0,
        giftable = 0,
        icon = 10207,
        id = 12120,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 60,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "青龙石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12121] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有青龙之力的强化石,70级装备附魂的材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10207,
        id = 12121,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 70,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 70,
        name = "2阶青龙石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12122] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有青龙之力的强化石,80级装备附魂的材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10207,
        id = 12122,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 80,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 80,
        name = "3阶青龙石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12123] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有青龙之力的强化石,90级装备附魂的材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10207,
        id = 12123,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 90,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 90,
        name = "4阶青龙石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12124] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有青龙之力的强化石,100级装备附魂的材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10207,
        id = 12124,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 100,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 100,
        name = "5阶青龙石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12140] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有朱雀之力的强化石,头盔、铠甲、鞋子附魂的材料",
        gainWayIdStr = {3, 30, 48, 62},
        giftPrice = 0,
        giftable = 0,
        icon = 10208,
        id = 12140,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 60,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 60,
        name = "朱雀石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12141] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有朱雀之力的强化石,70级装备附魂的材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10208,
        id = 12141,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 70,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 70,
        name = "2阶朱雀石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12142] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有朱雀之力的强化石,80级装备附魂的材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10208,
        id = 12142,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 80,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 80,
        name = "3阶朱雀石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12143] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有朱雀之力的强化石,90级装备附魂的材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10208,
        id = 12143,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 90,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 90,
        name = "4阶朱雀石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

    [12144] = {
        buyPrice = 0,
        canStore = 1,
        changeToVigorValue = "250",
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "带有朱雀之力的强化石,100级装备附魂的材料",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10208,
        id = 12144,
        introduction = [=[类型：附魂材料
功能：附魂]=],
        itemType = {2},
        level = 100,
        maxGrade = 200,
        maxOverlay = 99,
        minGrade = 100,
        name = "5阶朱雀石",
        nimbus = 0,
        pos = 3,
        quality = 3,
        quickable = 0,
        salePrice = 0,
        shop_npctype = 0,
        sort = 4,
        stallable = 0,
        useCost = 1,
    },

}
