-- ./excel/item/summskill.xlsx
return {

    [30000] = {
        changeToVigorValue = "1500",
        clientExtra = "use",
        description = "随机学习宠物的一个天生技能(可能替换已有技能)",
        gainWayIdStr = {6, 15, 22},
        icon = 10255,
        id = 30000,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "潜能",
        quality = 3,
        shop_npctype = 0,
        skid = 11100,
    },

    [30001] = {
        changeToVigorValue = "10",
        clientExtra = "use",
        description = "受到物理攻击时，10%几率使用普通攻击对目标复仇",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30001,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "复仇",
        quality = 2,
        shop_npctype = 0,
        skid = 5101,
    },

    [30002] = {
        changeToVigorValue = "40",
        clientExtra = "use",
        description = "增加宠物少量物攻",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30002,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "勇猛",
        quality = 2,
        shop_npctype = 0,
        skid = 5102,
    },

    [30003] = {
        changeToVigorValue = "20",
        clientExtra = "use",
        description = "物理攻击时忽略目标2%物防",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30003,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "进击",
        quality = 2,
        shop_npctype = 0,
        skid = 5103,
    },

    [30004] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "提高物理伤害5%；不会被复仇或震荡",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30004,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "暗杀",
        quality = 2,
        shop_npctype = 0,
        skid = 5104,
    },

    [30005] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "单体物理攻击时，吸取造成伤害20%的气血",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30005,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "生命汲取",
        quality = 2,
        shop_npctype = 0,
        skid = 5105,
    },

    [30006] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "单体物理攻击时，对额外两个单位造成7%的溅射伤害",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30006,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "溅射",
        quality = 2,
        shop_npctype = 0,
        skid = 5106,
    },

    [30007] = {
        changeToVigorValue = "110",
        clientExtra = "use",
        description = "普通攻击时，45%几率连续攻击目标2次，拥有此技能，物理伤害会降低25%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30007,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "连斩",
        quality = 2,
        shop_npctype = 0,
        skid = 5107,
    },

    [30008] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "普通攻击时，若击杀目标，则马上对一个随机敌方目标进行普通攻击，造成50%伤害",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30008,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "追击",
        quality = 2,
        shop_npctype = 0,
        skid = 5108,
    },

    [30009] = {
        changeToVigorValue = "130",
        clientExtra = "use",
        description = "法术暴击几率提高10%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30009,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "法术暴击",
        quality = 2,
        shop_npctype = 0,
        skid = 5109,
    },

    [30010] = {
        changeToVigorValue = "90",
        clientExtra = "use",
        description = "法术攻击时，有20%几率再次使用同样的法术攻击，第二次法术攻击的伤害减半",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30010,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "法术连斩",
        quality = 2,
        shop_npctype = 0,
        skid = 5110,
    },

    [30011] = {
        changeToVigorValue = "40",
        clientExtra = "use",
        description = "法术伤害结果在80%～120%范围内波动",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30011,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "法力波动",
        quality = 2,
        shop_npctype = 0,
        skid = 5111,
    },

    [30012] = {
        changeToVigorValue = "20",
        clientExtra = "use",
        description = "增加宠物少量法攻",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30012,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "法术增幅",
        quality = 2,
        shop_npctype = 0,
        skid = 5112,
    },

    [30013] = {
        changeToVigorValue = "35",
        clientExtra = "use",
        description = "法术伤害结果提高10%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30013,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "魔化",
        quality = 2,
        shop_npctype = 0,
        skid = 5113,
    },

    [30014] = {
        changeToVigorValue = "12",
        clientExtra = "use",
        description = "法术攻击时忽视目标2%法防",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30014,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "法防忽视",
        quality = 2,
        shop_npctype = 0,
        skid = 5114,
    },

    [30015] = {
        changeToVigorValue = "15",
        clientExtra = "use",
        description = "受到单体物理攻击时，30%几率震荡对方，震荡伤害为所受伤害的50%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30015,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "震荡",
        quality = 2,
        shop_npctype = 0,
        skid = 5115,
    },

    [30016] = {
        changeToVigorValue = "12",
        clientExtra = "use",
        description = "死亡后5回合自动复活，复活气血为70%，无法接受药物和主动技能治疗，不会受到增益/异常状态影响，且生命汲取对其无效",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30016,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "亡魂",
        quality = 2,
        shop_npctype = 0,
        skid = 5116,
    },

    [30017] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "死亡时有几率自动复活，复活气血为60%；复活几率受自身等级和体质影响，最高25%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30017,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "还阳",
        quality = 2,
        shop_npctype = 0,
        skid = 5117,
    },

    [30018] = {
        changeToVigorValue = "10",
        clientExtra = "use",
        description = "50%几率在回合末清除负面状态,不包含封印状态",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30018,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "定心",
        quality = 2,
        shop_npctype = 0,
        skid = 5118,
    },

    [30019] = {
        changeToVigorValue = "20",
        clientExtra = "use",
        description = "速度增加10%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30019,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "迅捷",
        quality = 2,
        shop_npctype = 0,
        skid = 5119,
    },

    [30020] = {
        changeToVigorValue = "35",
        clientExtra = "use",
        description = "气血上限增加10%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30020,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "健壮",
        quality = 2,
        shop_npctype = 0,
        skid = 5120,
    },

    [30021] = {
        changeToVigorValue = "10",
        clientExtra = "use",
        description = "增加自身一定物防，受宠物等级影响，降低法术伤害结果10%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30021,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "物理防御",
        quality = 2,
        shop_npctype = 0,
        skid = 5121,
    },

    [30022] = {
        changeToVigorValue = "10",
        clientExtra = "use",
        description = "增加自身一定法防，受宠物等级影响，降低物理伤害结果10%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30022,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "法术防御",
        quality = 2,
        shop_npctype = 0,
        skid = 5122,
    },

    [30023] = {
        changeToVigorValue = "10",
        clientExtra = "use",
        description = "降低被物理暴击几率7%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30023,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "物暴抵抗",
        quality = 2,
        shop_npctype = 0,
        skid = 5123,
    },

    [30024] = {
        changeToVigorValue = "3",
        clientExtra = "use",
        description = "15%几率免疫土属性伤害，并恢复对应气血",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30024,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "土系吸收",
        quality = 2,
        shop_npctype = 0,
        skid = 5124,
    },

    [30025] = {
        changeToVigorValue = "3",
        clientExtra = "use",
        description = "15%几率免疫水属性伤害，并恢复对应气血",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30025,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "水系吸收",
        quality = 2,
        shop_npctype = 0,
        skid = 5125,
    },

    [30026] = {
        changeToVigorValue = "3",
        clientExtra = "use",
        description = "15%几率免疫火属性伤害，并恢复对应气血",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30026,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "火系吸收",
        quality = 2,
        shop_npctype = 0,
        skid = 5126,
    },

    [30027] = {
        changeToVigorValue = "3",
        clientExtra = "use",
        description = "15%几率免疫风属性伤害，并恢复对应气血",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30027,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "风系吸收",
        quality = 2,
        shop_npctype = 0,
        skid = 5127,
    },

    [30028] = {
        changeToVigorValue = "15",
        clientExtra = "use",
        description = "对拥有亡魂或高级亡魂的目标伤害增加50%，如果目标被打死，则直接出场",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30028,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "伏魔",
        quality = 2,
        shop_npctype = 0,
        skid = 5128,
    },

    [30029] = {
        changeToVigorValue = "20",
        clientExtra = "use",
        description = "可攻击隐身目标",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30029,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "天眼",
        quality = 2,
        shop_npctype = 0,
        skid = 5129,
    },

    [30030] = {
        changeToVigorValue = "5",
        clientExtra = "use",
        description = "增加自身50%封印抵抗",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30030,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "戒心",
        quality = 2,
        shop_npctype = 0,
        skid = 5130,
    },

    [30031] = {
        changeToVigorValue = "25",
        clientExtra = "use",
        description = "增加物防，受自身当前气血值影响，气血越低，增加的防御越多，最高增加10%的防御",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30031,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "坚守",
        quality = 2,
        shop_npctype = 0,
        skid = 5131,
    },

    [30032] = {
        changeToVigorValue = "45",
        clientExtra = "use",
        description = "进入战斗后，隐身2～3回合，降低自身20%物攻，隐身状态不可使用主动技能",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30032,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "遁法",
        quality = 2,
        shop_npctype = 0,
        skid = 5132,
    },

    [30033] = {
        changeToVigorValue = "15",
        clientExtra = "use",
        description = "受到物理伤害时，20%几率减免30%的伤害",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30033,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "拆招",
        quality = 2,
        shop_npctype = 0,
        skid = 5133,
    },

    [30034] = {
        changeToVigorValue = "20",
        clientExtra = "use",
        description = "每阵亡一个队友，物理攻击增加1%，最高累计5次",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30034,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "同仇敌忾",
        quality = 2,
        shop_npctype = 0,
        skid = 5134,
    },

    [30035] = {
        changeToVigorValue = "3",
        clientExtra = "use",
        description = "每回合自动恢复少量法力值，与等级相关",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30035,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "入定",
        quality = 2,
        shop_npctype = 0,
        skid = 5135,
    },

    [30036] = {
        changeToVigorValue = "5",
        clientExtra = "use",
        description = "使用技能时有10%几率不消耗法力值",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30036,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "灵机一动",
        quality = 2,
        shop_npctype = 0,
        skid = 5136,
    },

    [30037] = {
        changeToVigorValue = "155",
        clientExtra = "use",
        description = "物理暴击几率提高10%",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30037,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "暴击",
        quality = 2,
        shop_npctype = 0,
        skid = 5137,
    },

    [30038] = {
        changeToVigorValue = "7",
        clientExtra = "use",
        description = "单体法术攻击，造成土属性法术伤害",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30038,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "地动",
        quality = 2,
        shop_npctype = 0,
        skid = 5201,
    },

    [30039] = {
        changeToVigorValue = "7",
        clientExtra = "use",
        description = "单体法术攻击，造成水属性法术伤害",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30039,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "水雷",
        quality = 2,
        shop_npctype = 0,
        skid = 5202,
    },

    [30040] = {
        changeToVigorValue = "7",
        clientExtra = "use",
        description = "单体法术攻击，造成火属性法术伤害",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30040,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "心火",
        quality = 2,
        shop_npctype = 0,
        skid = 5203,
    },

    [30041] = {
        changeToVigorValue = "7",
        clientExtra = "use",
        description = "单体法术攻击，造成风属性法术伤害",
        gainWayIdStr = {6, 15, 22},
        icon = 10254,
        id = 30041,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "龙卷",
        quality = 2,
        shop_npctype = 0,
        skid = 5204,
    },

    [30042] = {
        changeToVigorValue = "400",
        clientExtra = "use",
        description = "群体法术攻击，造成土属性法术伤害；初始作用2个目标，50级作用3个目标",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30042,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "山崩地裂",
        quality = 3,
        shop_npctype = 0,
        skid = 5205,
    },

    [30043] = {
        changeToVigorValue = "400",
        clientExtra = "use",
        description = "群体法术攻击，造成水属性法术伤害；初始作用2个目标，50级作用3个目标",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30043,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "冰封万里",
        quality = 3,
        shop_npctype = 0,
        skid = 5206,
    },

    [30044] = {
        changeToVigorValue = "400",
        clientExtra = "use",
        description = "群体法术攻击，造成火属性法术伤害；初始作用2个目标，50级作用3个目标",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30044,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "焚天怒火",
        quality = 3,
        shop_npctype = 0,
        skid = 5207,
    },

    [30045] = {
        changeToVigorValue = "400",
        clientExtra = "use",
        description = "群体法术攻击，造成风属性法术伤害；初始作用2个目标，50级作用3个目标",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30045,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "风卷残云",
        quality = 3,
        shop_npctype = 0,
        skid = 5208,
    },

    [30046] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "单体物理攻击，根据目标气血对目标造成额外伤害，目标气血越低，伤害越高",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10254,
        id = 30046,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "趁势而上",
        quality = 2,
        shop_npctype = 0,
        skid = 5209,
    },

    [30047] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "单体物理攻击，根据自身气血对目标造成额外伤害，自身气血越低，伤害越高",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10254,
        id = 30047,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "以牙还牙",
        quality = 2,
        shop_npctype = 0,
        skid = 5210,
    },

    [30048] = {
        changeToVigorValue = "225",
        clientExtra = "use",
        description = "群体物理攻击，初始作用2个目标，50级作用3个目标（注：爆破不受吸血、法术连斩、法术暴击影响）",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30048,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "爆破",
        quality = 3,
        shop_npctype = 0,
        skid = 5211,
    },

    [30049] = {
        changeToVigorValue = "600",
        clientExtra = "use",
        description = "群体物理攻击，初始作用2个目标，50级作用3个目标（注：金雷震爆不受吸血、法术连斩、法术暴击影响）",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30049,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "金雷震爆",
        quality = 3,
        shop_npctype = 0,
        skid = 5212,
    },

    [30050] = {
        changeToVigorValue = "75",
        clientExtra = "use",
        description = "单体物理攻击，若目标防御，则伤害增加50%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30050,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "摧心",
        quality = 3,
        shop_npctype = 0,
        skid = 5213,
    },

    [30051] = {
        changeToVigorValue = "1500",
        clientExtra = "use",
        description = "单体物理攻击，伤害结果提高50%，自身需承受造成伤害的20%；气血低于上限30%时无法使用",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30051,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "背水一战",
        quality = 3,
        shop_npctype = 0,
        skid = 5301,
    },

    [30052] = {
        changeToVigorValue = "1500",
        clientExtra = "use",
        description = "单体物理攻击，70%几率对目标造成200%的伤害结果，若失败则为对方恢复100%伤害的气血",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30052,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "阎罗令",
        quality = 3,
        shop_npctype = 0,
        skid = 5302,
    },

    [30053] = {
        changeToVigorValue = "250",
        clientExtra = "use",
        description = "增加小量气血和速度",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30053,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "血脉之力",
        quality = 3,
        shop_npctype = 0,
        skid = 5303,
    },

    [30054] = {
        changeToVigorValue = "250",
        clientExtra = "use",
        description = "群体法术攻击，并且消耗目标的法力值，如果目标是NPC，则会吸取一定法力值给主人；初始作用2个目标，50级作用3个目标",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30054,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "星华绽放",
        quality = 3,
        shop_npctype = 0,
        skid = 5306,
    },

    [30070] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "不会逃跑，受到带有气势或者震慑的宠物攻击时，所受伤害减少10%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10254,
        id = 30070,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "勇敢",
        quality = 2,
        shop_npctype = 0,
        skid = 5138,
    },

    [30071] = {
        changeToVigorValue = "10",
        clientExtra = "use",
        description = "出战前两回合物理伤害增加10%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10254,
        id = 30071,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "气势",
        quality = 2,
        shop_npctype = 0,
        skid = 5139,
    },

    [30072] = {
        changeToVigorValue = "10",
        clientExtra = "use",
        description = "出战前两回合法术伤害增加10%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10254,
        id = 30072,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "威慑",
        quality = 2,
        shop_npctype = 0,
        skid = 5140,
    },

    [30201] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "受到物理攻击时，20%几率使用普通攻击对目标复仇",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30201,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级复仇",
        quality = 3,
        shop_npctype = 0,
        skid = 5401,
    },

    [30202] = {
        changeToVigorValue = "200",
        clientExtra = "use",
        description = "增加宠物大量物攻",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30202,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级勇猛",
        quality = 3,
        shop_npctype = 0,
        skid = 5402,
    },

    [30203] = {
        changeToVigorValue = "100",
        clientExtra = "use",
        description = "物理攻击时忽略目标5%物防",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30203,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级进击",
        quality = 3,
        shop_npctype = 0,
        skid = 5403,
    },

    [30204] = {
        changeToVigorValue = "250",
        clientExtra = "use",
        description = "提高物理伤害10%；不会被复仇或震荡",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30204,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级暗杀",
        quality = 3,
        shop_npctype = 0,
        skid = 5404,
    },

    [30205] = {
        changeToVigorValue = "250",
        clientExtra = "use",
        description = "单体物理攻击时，吸取造成伤害30%的血量",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30205,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级生命汲取",
        quality = 3,
        shop_npctype = 0,
        skid = 5405,
    },

    [30206] = {
        changeToVigorValue = "250",
        clientExtra = "use",
        description = "单体物理攻击时对额外两个单位造成15%的溅射伤害",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30206,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级溅射",
        quality = 3,
        shop_npctype = 0,
        skid = 5406,
    },

    [30207] = {
        changeToVigorValue = "500",
        clientExtra = "use",
        description = "普通攻击时，55%几率连续攻击目标2次，拥有此技能，物理伤害会降低20%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30207,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级连斩",
        quality = 3,
        shop_npctype = 0,
        skid = 5407,
    },

    [30208] = {
        changeToVigorValue = "250",
        clientExtra = "use",
        description = "普通攻击时，若击杀目标，则马上对一个随机敌方目标进行普通攻击，造成100%伤害",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30208,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级追击",
        quality = 3,
        shop_npctype = 0,
        skid = 5408,
    },

    [30209] = {
        changeToVigorValue = "600",
        clientExtra = "use",
        description = "法术暴击几率提高20%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30209,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级法术暴击",
        quality = 3,
        shop_npctype = 0,
        skid = 5409,
    },

    [30210] = {
        changeToVigorValue = "450",
        clientExtra = "use",
        description = "法术攻击时，有30%几率再次使用同样的法术攻击，第二次法术攻击的伤害减半",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30210,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级法术连斩",
        quality = 3,
        shop_npctype = 0,
        skid = 5410,
    },

    [30211] = {
        changeToVigorValue = "150",
        clientExtra = "use",
        description = "法术伤害结果在60%～140%范围内波动",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30211,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级法力波动",
        quality = 3,
        shop_npctype = 0,
        skid = 5411,
    },

    [30212] = {
        changeToVigorValue = "100",
        clientExtra = "use",
        description = "增加宠物大量法攻",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30212,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级法术增幅",
        quality = 3,
        shop_npctype = 0,
        skid = 5412,
    },

    [30213] = {
        changeToVigorValue = "150",
        clientExtra = "use",
        description = "法术伤害结果提高20%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30213,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级魔化",
        quality = 3,
        shop_npctype = 0,
        skid = 5413,
    },

    [30214] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "法术攻击时忽视目标5%法防",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30214,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级法防忽视",
        quality = 3,
        shop_npctype = 0,
        skid = 5414,
    },

    [30215] = {
        changeToVigorValue = "75",
        clientExtra = "use",
        description = "受到单体物理攻击时，50%几率震荡对方，震荡伤害为所受伤害的50%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30215,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级震荡",
        quality = 3,
        shop_npctype = 0,
        skid = 5415,
    },

    [30216] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "死亡后5回合自动复活，复活气血为100%，不会受到异常状态影响，且生命汲取对其无效",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30216,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级亡魂",
        quality = 3,
        shop_npctype = 0,
        skid = 5416,
    },

    [30217] = {
        changeToVigorValue = "250",
        clientExtra = "use",
        description = "死亡时有几率自动复活，复活气血为100%；复活几率受自身等级和体质影响，最高25%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30217,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级还阳",
        quality = 3,
        shop_npctype = 0,
        skid = 5417,
    },

    [30218] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "免疫所有异常状态,不包含封印状态",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30218,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级定心",
        quality = 3,
        shop_npctype = 0,
        skid = 5418,
    },

    [30219] = {
        changeToVigorValue = "100",
        clientExtra = "use",
        description = "速度增加20%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30219,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级迅捷",
        quality = 3,
        shop_npctype = 0,
        skid = 5419,
    },

    [30220] = {
        changeToVigorValue = "175",
        clientExtra = "use",
        description = "气血上限增加20%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30220,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级健壮",
        quality = 3,
        shop_npctype = 0,
        skid = 5420,
    },

    [30221] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "增加自身较多物防，受宠物等级影响，降低法术伤害结果10%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30221,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级物理防御",
        quality = 3,
        shop_npctype = 0,
        skid = 5421,
    },

    [30222] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "增加自身较多法防，受宠物等级影响，降低物理伤害结果10%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30222,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级法术防御",
        quality = 3,
        shop_npctype = 0,
        skid = 5422,
    },

    [30223] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "降低被物理暴击几率15%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30223,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级物暴抵抗",
        quality = 3,
        shop_npctype = 0,
        skid = 5423,
    },

    [30224] = {
        changeToVigorValue = "15",
        clientExtra = "use",
        description = "30%几率免疫土属性伤害，并恢复对应气血",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30224,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级土系吸收",
        quality = 3,
        shop_npctype = 0,
        skid = 5424,
    },

    [30225] = {
        changeToVigorValue = "15",
        clientExtra = "use",
        description = "30%几率免疫水属性伤害，并恢复对应气血",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30225,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级水系吸收",
        quality = 3,
        shop_npctype = 0,
        skid = 5425,
    },

    [30226] = {
        changeToVigorValue = "15",
        clientExtra = "use",
        description = "30%几率免疫火属性伤害，并恢复对应气血",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30226,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级火系吸收",
        quality = 3,
        shop_npctype = 0,
        skid = 5426,
    },

    [30227] = {
        changeToVigorValue = "15",
        clientExtra = "use",
        description = "30%几率免疫风属性伤害，并恢复对应气血",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30227,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级风系吸收",
        quality = 3,
        shop_npctype = 0,
        skid = 5427,
    },

    [30228] = {
        changeToVigorValue = "75",
        clientExtra = "use",
        description = "对拥有亡魂或高级亡魂的目标伤害增加100%，如果目标被打死，则直接出场",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30228,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级伏魔",
        quality = 3,
        shop_npctype = 0,
        skid = 5428,
    },

    [30229] = {
        changeToVigorValue = "100",
        clientExtra = "use",
        description = "可攻击隐身目标，并且造成额外10%伤害",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30229,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级天眼",
        quality = 3,
        shop_npctype = 0,
        skid = 5429,
    },

    [30230] = {
        changeToVigorValue = "25",
        clientExtra = "use",
        description = "抵抗所有封印状态",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30230,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级戒心",
        quality = 3,
        shop_npctype = 0,
        skid = 5430,
    },

    [30231] = {
        changeToVigorValue = "50",
        clientExtra = "use",
        description = "增加物防，受自身当前气血值影响，气血越低，增加的防御越多，最高增加20%的防御",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30231,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级坚守",
        quality = 3,
        shop_npctype = 0,
        skid = 5431,
    },

    [30232] = {
        changeToVigorValue = "200",
        clientExtra = "use",
        description = "进入战斗后，隐身3～5回合，降低自身15%物理攻击，隐身状态不可使用主动技能",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30232,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级遁法",
        quality = 3,
        shop_npctype = 0,
        skid = 5432,
    },

    [30233] = {
        changeToVigorValue = "75",
        clientExtra = "use",
        description = "受到物理伤害时，30%几率减免30%的伤害",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30233,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级拆招",
        quality = 3,
        shop_npctype = 0,
        skid = 5433,
    },

    [30234] = {
        changeToVigorValue = "100",
        clientExtra = "use",
        description = "每阵亡一个队友，物理攻击增加3%，最高累计5次",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30234,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级同仇敌忾",
        quality = 3,
        shop_npctype = 0,
        skid = 5434,
    },

    [30235] = {
        changeToVigorValue = "15",
        clientExtra = "use",
        description = "每回合自动恢复较多法力值，与等级相关",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30235,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级入定",
        quality = 3,
        shop_npctype = 0,
        skid = 5435,
    },

    [30236] = {
        changeToVigorValue = "25",
        clientExtra = "use",
        description = "使用技能时有20%几率不消耗法力值",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30236,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级灵机一动",
        quality = 3,
        shop_npctype = 0,
        skid = 5436,
    },

    [30237] = {
        changeToVigorValue = "750",
        clientExtra = "use",
        description = "物理暴击几率提高20%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30237,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级暴击",
        quality = 3,
        shop_npctype = 0,
        skid = 5437,
    },

    [30238] = {
        changeToVigorValue = "1500",
        clientExtra = "use",
        description = "单体物理攻击，目标物攻越低则受到伤害越高",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30238,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "降龙伏虎",
        quality = 3,
        shop_npctype = 0,
        skid = 5304,
    },

    [30239] = {
        changeToVigorValue = "1500",
        clientExtra = "use",
        description = "对目标造成法术伤害，并且有25%几率令目标在4回合内无法复活",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30239,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "幽冥噬魂",
        quality = 3,
        shop_npctype = 0,
        skid = 5305,
    },

    [30240] = {
        changeToVigorValue = "400",
        clientExtra = "use",
        description = "不会逃跑，受到带有气势/高级气势/震慑/高级震慑的目标攻击时，所受伤害减少20%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30240,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级勇敢",
        quality = 3,
        shop_npctype = 0,
        skid = 5438,
    },

    [30241] = {
        changeToVigorValue = "300",
        clientExtra = "use",
        description = "出战前两回合物理伤害增加20%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30241,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级气势",
        quality = 3,
        shop_npctype = 0,
        skid = 5439,
    },

    [30242] = {
        changeToVigorValue = "200",
        clientExtra = "use",
        description = "出战前两回合法术伤害增加20%",
        gainWayIdStr = {6, 13, 27, 35, 45, 51},
        icon = 10255,
        id = 30242,
        introduction = [=[类型：宠物培养材料
功能：宠物打书]=],
        maxOverlay = 1,
        name = "高级威慑",
        quality = 3,
        shop_npctype = 0,
        skid = 5440,
    },

}
