-- ./excel/item/equip.xlsx
return {

    [29000] = {
        canStore = 1,
        changeToVigorValue = "90",
        description = "宠物需要20级后才能装备，可以增强宠物的属性",
        equip_effect = "{phy_attack=12,phy_defense=9,mag_attack=9,mag_defense=6,speed=7}",
        equippos = 1,
        gainWayIdStr = {26, 13, 17, 48},
        icon = 29001,
        id = 29000,
        introduction = "类型：项圈",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "一级项圈",
        point = 1,
        quality = 1,
        resetcost = 0,
        salePrice = 0,
        score = "35",
        shop_npctype = 0,
        sort = 1,
        useCost = 1,
    },

    [29001] = {
        canStore = 1,
        changeToVigorValue = "150",
        description = "宠物需要20级后才能装备，可以增强宠物的属性",
        equip_effect = "{phy_attack=20,phy_defense=15,mag_attack=15,mag_defense=10,speed=12}",
        equippos = 1,
        gainWayIdStr = {26, 13, 17, 48},
        icon = 29002,
        id = 29001,
        introduction = "类型：项圈",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "二级项圈",
        point = 10,
        quality = 2,
        resetcost = 0,
        salePrice = 0,
        score = "45",
        shop_npctype = 0,
        sort = 2,
        useCost = 1,
    },

    [29002] = {
        canStore = 1,
        changeToVigorValue = "250",
        description = "宠物需要20级后才能装备，可以增强宠物的属性",
        equip_effect = "{phy_attack=28,phy_defense=21,mag_attack=21,mag_defense=14,speed=17}",
        equippos = 1,
        gainWayIdStr = {27, 13, 17, 48},
        icon = 29003,
        id = 29002,
        introduction = "类型：项圈",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "三级项圈",
        point = 20,
        quality = 3,
        resetcost = 0,
        salePrice = 0,
        score = "55",
        shop_npctype = 0,
        sort = 3,
        useCost = 1,
    },

    [29003] = {
        canStore = 1,
        changeToVigorValue = "450",
        description = "宠物需要20级后才能装备，可以增强宠物的属性",
        equip_effect = "{phy_attack=36,phy_defense=27,mag_attack=27,mag_defense=18,speed=22}",
        equippos = 1,
        gainWayIdStr = {27, 13},
        icon = 29004,
        id = 29003,
        introduction = "类型：项圈",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "四级项圈",
        point = 40,
        quality = 4,
        resetcost = 0,
        salePrice = 0,
        score = "65",
        shop_npctype = 0,
        sort = 4,
        useCost = 1,
    },

    [29100] = {
        canStore = 1,
        changeToVigorValue = "90",
        description = "宠物需要20级后才能装备，可以增强宠物的防御属性",
        equip_effect = "{phy_defense=15,mag_defense=11}",
        equippos = 2,
        gainWayIdStr = {26, 13, 17, 48},
        icon = 29101,
        id = 29100,
        introduction = "类型：铠甲",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "一级铠甲",
        point = 1,
        quality = 1,
        resetcost = 0,
        salePrice = 0,
        score = "35",
        shop_npctype = 0,
        sort = 5,
        useCost = 1,
    },

    [29101] = {
        canStore = 1,
        changeToVigorValue = "150",
        description = "宠物需要20级后才能装备，可以增强宠物的防御属性",
        equip_effect = "{phy_defense=25,mag_defense=16}",
        equippos = 2,
        gainWayIdStr = {26, 13, 17, 48},
        icon = 29102,
        id = 29101,
        introduction = "类型：铠甲",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "二级铠甲",
        point = 10,
        quality = 2,
        resetcost = 0,
        salePrice = 0,
        score = "45",
        shop_npctype = 0,
        sort = 6,
        useCost = 1,
    },

    [29102] = {
        canStore = 1,
        changeToVigorValue = "250",
        description = "宠物需要20级后才能装备，可以增强宠物的防御属性",
        equip_effect = "{phy_defense=35,mag_defense=23}",
        equippos = 2,
        gainWayIdStr = {27, 13, 17, 48},
        icon = 29103,
        id = 29102,
        introduction = "类型：铠甲",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "三级铠甲",
        point = 20,
        quality = 3,
        resetcost = 0,
        salePrice = 0,
        score = "55",
        shop_npctype = 0,
        sort = 7,
        useCost = 1,
    },

    [29103] = {
        canStore = 1,
        changeToVigorValue = "450",
        description = "宠物需要20级后才能装备，可以增强宠物的防御属性",
        equip_effect = "{phy_defense=45,mag_defense=30}",
        equippos = 2,
        gainWayIdStr = {27, 13},
        icon = 29104,
        id = 29103,
        introduction = "类型：铠甲",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "四级铠甲",
        point = 40,
        quality = 4,
        resetcost = 0,
        salePrice = 0,
        score = "65",
        shop_npctype = 0,
        sort = 8,
        useCost = 1,
    },

    [29200] = {
        canStore = 1,
        changeToVigorValue = "100",
        description = "宠物需要20级后才能装备，拥有1~2个技能；可消耗一级金刚珠进行重置",
        equip_effect = "{{ratio=100,group={101}},{ratio=20,group={101}}}",
        equippos = 3,
        gainWayIdStr = {26, 13, 8, 12},
        icon = 29201,
        id = 29200,
        introduction = "类型：护符",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "一级护符",
        point = 1,
        quality = 1,
        resetcost = 11177,
        salePrice = 0,
        score = "0",
        shop_npctype = 0,
        sort = 9,
        useCost = 1,
    },

    [29201] = {
        canStore = 1,
        changeToVigorValue = "300",
        description = "宠物需要20级后才能装备，拥有1~2个技能；可消耗二级金刚珠进行重置",
        equip_effect = "{{ratio=100,group={101}},{ratio=20,group={101,103}}}",
        equippos = 3,
        gainWayIdStr = {26, 13, 8, 12},
        icon = 29202,
        id = 29201,
        introduction = "类型：护符",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "二级护符",
        point = 10,
        quality = 2,
        resetcost = 11178,
        salePrice = 0,
        score = "0",
        shop_npctype = 0,
        sort = 10,
        useCost = 1,
    },

    [29202] = {
        canStore = 1,
        changeToVigorValue = "700",
        description = "宠物需要20级后才能装备，拥有1~2个技能；可消耗三级金刚珠进行重置",
        equip_effect = "{{ratio=100,group={101}},{ratio=20,group={102}}}",
        equippos = 3,
        gainWayIdStr = {27, 13, 60},
        icon = 29203,
        id = 29202,
        introduction = "类型：护符",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "三级护符",
        point = 20,
        quality = 3,
        resetcost = 11179,
        salePrice = 0,
        score = "0",
        shop_npctype = 0,
        sort = 11,
        useCost = 1,
    },

    [29203] = {
        canStore = 1,
        changeToVigorValue = "1000",
        description = "宠物需要20级后才能装备，拥有1~2个技能；可消耗四级金刚珠进行重置",
        equip_effect = "{{ratio=100,group={102}},{ratio=20,group={101,103}}}",
        equippos = 3,
        gainWayIdStr = {27, 13},
        icon = 29204,
        id = 29203,
        introduction = "类型：护符",
        itemType = {1},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 20,
        name = "四级护符",
        point = 40,
        quality = 4,
        resetcost = 11180,
        salePrice = 0,
        score = "0",
        shop_npctype = 0,
        sort = 12,
        useCost = 1,
    },

}
