-- ./excel/item/other.xlsx
return {

    [70000] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "发支线任务",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10005,
        id = 70000,
        introduction = "作用：发支线任务",
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 0,
        name = "任务40001",
        nimbus = 0,
        quality = 1,
        quickable = 1,
        salePrice = 0,
        shop_npctype = 0,
        sort = 3,
        stallable = 0,
        taskid = 40001,
        useCost = 1,
    },

    [70001] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "发支线任务",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10004,
        id = 70001,
        introduction = "作用：发支线任务",
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 0,
        name = "任务40003",
        nimbus = 0,
        quality = 1,
        quickable = 1,
        salePrice = 0,
        shop_npctype = 0,
        sort = 3,
        stallable = 0,
        taskid = 40003,
        useCost = 1,
    },

    [70002] = {
        ComposeAmount = 0,
        ComposeItem = {},
        buyPrice = 0,
        canStore = 1,
        circulationType = 0,
        clientExtra = "use",
        deCompose = {},
        description = "发支线任务",
        gainWayIdStr = {},
        giftPrice = 0,
        giftable = 0,
        icon = 10016,
        id = 70002,
        introduction = "作用：发支线任务",
        itemType = {2},
        maxGrade = 200,
        maxOverlay = 1,
        minGrade = 0,
        name = "任务40005",
        nimbus = 0,
        quality = 1,
        quickable = 1,
        salePrice = 0,
        shop_npctype = 0,
        sort = 3,
        stallable = 0,
        taskid = 40005,
        useCost = 1,
    },

}
