-- ./excel/system/redpacket/redpacket.xlsx
return {

    [1001] = {
        bless = "玩家红包",
        cashtype = 101,
        channel = 101,
        condition = "玩家主动发",
        count = 0,
        gameplay = "",
        goldcoin = 0,
        id = 1001,
        menu = 0,
        name = "恭喜发财，大吉大利",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [1002] = {
        bless = "玩家红包",
        cashtype = 101,
        channel = 102,
        condition = "玩家主动发",
        count = 0,
        gameplay = "",
        goldcoin = 0,
        id = 1002,
        menu = 0,
        name = "恭喜发财，大吉大利",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [1003] = {
        bless = "系统红包",
        cashtype = 101,
        channel = 101,
        condition = "帮派提升到2级",
        count = 10,
        gameplay = "",
        goldcoin = 200,
        id = 1003,
        menu = 0,
        name = "恭喜发财，大吉大利",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [1004] = {
        bless = "系统红包",
        cashtype = 101,
        channel = 102,
        condition = "帮派人数达到10",
        count = 10,
        gameplay = "",
        goldcoin = 200,
        id = 1004,
        menu = 0,
        name = "恭喜发财，大吉大利",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [2001] = {
        bless = "感恩回馈，有你更精彩",
        cashtype = 101,
        channel = 101,
        condition = "完成首充",
        count = 10,
        gameplay = "",
        goldcoin = 200,
        id = 2001,
        menu = 0,
        name = "首充红包",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [2002] = {
        bless = "感恩回馈，有你更精彩",
        cashtype = 101,
        channel = 101,
        condition = "充值一本万利1",
        count = 10,
        gameplay = "",
        goldcoin = 200,
        id = 2002,
        menu = 0,
        name = "一本万利红包",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [2003] = {
        bless = "感恩回馈，有你更精彩",
        cashtype = 101,
        channel = 101,
        condition = "购买周卡",
        count = 10,
        gameplay = "",
        goldcoin = 200,
        id = 2003,
        menu = 0,
        name = "周卡红包",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [2004] = {
        bless = "感恩回馈，有你更精彩",
        cashtype = 101,
        channel = 101,
        condition = "购买月卡",
        count = 10,
        gameplay = "",
        goldcoin = 200,
        id = 2004,
        menu = 0,
        name = "月卡红包",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [2005] = {
        bless = "恭喜封魔获得第一名",
        cashtype = 101,
        channel = 101,
        condition = "封魔第一名",
        count = 10,
        gameplay = "",
        goldcoin = 500,
        id = 2005,
        menu = 0,
        name = "封魔有礼",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 1059,
        type = 101,
    },

    [2006] = {
        bless = "恭喜封魔获得第二名",
        cashtype = 101,
        channel = 101,
        condition = "封魔第二名",
        count = 10,
        gameplay = "",
        goldcoin = 400,
        id = 2006,
        menu = 0,
        name = "封魔有礼",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [2007] = {
        bless = "恭喜封魔获得第三名",
        cashtype = 101,
        channel = 101,
        condition = "封魔第三名",
        count = 10,
        gameplay = "",
        goldcoin = 300,
        id = 2007,
        menu = 0,
        name = "封魔有礼",
        ownername = "",
        ownershape = 0,
        se = 0,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [2008] = {
        bless = "恭喜威望榜获得冠军",
        cashtype = 101,
        channel = 101,
        condition = "威望榜第一名",
        count = 100,
        gameplay = "",
        goldcoin = 2000,
        id = 2008,
        menu = 0,
        name = "开服狂欢",
        ownername = "",
        ownershape = 0,
        se = 102,
        submincash = 1,
        text = 0,
        type = 102,
    },

    [2009] = {
        bless = "恭喜威望榜获得亚军",
        cashtype = 101,
        channel = 101,
        condition = "威望榜第二名",
        count = 100,
        gameplay = "",
        goldcoin = 1600,
        id = 2009,
        menu = 0,
        name = "开服狂欢",
        ownername = "",
        ownershape = 0,
        se = 102,
        submincash = 1,
        text = 0,
        type = 102,
    },

    [2010] = {
        bless = "恭喜威望榜进入前十",
        cashtype = 101,
        channel = 101,
        condition = "威望榜前十",
        count = 100,
        gameplay = "",
        goldcoin = 1200,
        id = 2010,
        menu = 0,
        name = "开服狂欢",
        ownername = "",
        ownershape = 0,
        se = 102,
        submincash = 1,
        text = 0,
        type = 102,
    },

    [3001] = {
        bless = "感恩回馈，有你更精彩",
        cashtype = 101,
        channel = 102,
        condition = "充值648",
        count = 20,
        gameplay = "liumai",
        goldcoin = 388,
        id = 3001,
        menu = 0,
        name = "充值有礼",
        ownername = "许仙",
        ownershape = 2101,
        se = 102,
        submincash = 1,
        text = 1058,
        type = 101,
    },

    [3002] = {
        bless = "恭喜#role和#role喜结良缘",
        cashtype = 101,
        channel = 102,
        condition = "订婚成功",
        count = 99,
        gameplay = "",
        goldcoin = 999,
        id = 3002,
        menu = 0,
        name = "恭喜#role和#role喜结良缘",
        ownername = "红娘",
        ownershape = 3115,
        se = 102,
        submincash = 1,
        text = 0,
        type = 101,
    },

    [4101] = {
        bless = "恭喜#role达成五连胜",
        cashtype = 101,
        channel = 103,
        condition = "五连胜",
        count = 20,
        gameplay = "liumai",
        goldcoin = 200,
        id = 4101,
        menu = 0,
        name = "恭喜获得五连胜",
        ownername = "许仙",
        ownershape = 2101,
        se = 102,
        submincash = 1,
        text = 1078,
        type = 101,
    },

    [4102] = {
        bless = "恭喜#role达成十连胜",
        cashtype = 101,
        channel = 103,
        condition = "十连胜",
        count = 20,
        gameplay = "liumai",
        goldcoin = 200,
        id = 4102,
        menu = 0,
        name = "恭喜获得十连胜",
        ownername = "许仙",
        ownershape = 2101,
        se = 102,
        submincash = 1,
        text = 1078,
        type = 101,
    },

    [4103] = {
        bless = "恭喜#role达成十五连胜",
        cashtype = 101,
        channel = 103,
        condition = "十五连胜",
        count = 20,
        gameplay = "liumai",
        goldcoin = 200,
        id = 4103,
        menu = 0,
        name = "恭喜获得十五连胜",
        ownername = "许仙",
        ownershape = 2101,
        se = 102,
        submincash = 1,
        text = 1078,
        type = 101,
    },

    [4104] = {
        bless = "预祝晋级的少侠再创佳绩",
        cashtype = 101,
        channel = 103,
        condition = "晋级8强赛结束",
        count = 20,
        gameplay = "liumai",
        goldcoin = 200,
        id = 4104,
        menu = 0,
        name = "恭喜众少侠晋级八强",
        ownername = "许仙",
        ownershape = 2101,
        se = 102,
        submincash = 1,
        text = 1037,
        type = 101,
    },

    [4105] = {
        bless = "预祝晋级的少侠再创佳绩",
        cashtype = 101,
        channel = 103,
        condition = "晋级4强赛结束",
        count = 20,
        gameplay = "liumai",
        goldcoin = 200,
        id = 4105,
        menu = 0,
        name = "恭喜众少侠晋级四强",
        ownername = "许仙",
        ownershape = 2101,
        se = 102,
        submincash = 1,
        text = 1038,
        type = 101,
    },

    [4106] = {
        bless = "预祝晋级的少侠再创佳绩",
        cashtype = 101,
        channel = 103,
        condition = "晋级半决赛结束",
        count = 20,
        gameplay = "liumai",
        goldcoin = 200,
        id = 4106,
        menu = 0,
        name = "恭喜众少侠晋级半决赛",
        ownername = "许仙",
        ownershape = 2101,
        se = 102,
        submincash = 1,
        text = 1039,
        type = 101,
    },

    [4107] = {
        bless = "恭喜本届会武冠军诞生",
        cashtype = 101,
        channel = 103,
        condition = "决赛结束",
        count = 20,
        gameplay = "liumai",
        goldcoin = 200,
        id = 4107,
        menu = 0,
        name = "恭喜本届冠军诞生",
        ownername = "许仙",
        ownershape = 2101,
        se = 102,
        submincash = 1,
        text = 1040,
        type = 101,
    },

}
