-- ./excel/task/lingxi/task_lingxi.xlsx
return {

    [62031] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "两名异性好友玩家组队参与任务，共同悉心照料情花成长，成功完成任务后，可以获得丰厚的奖励。",
        goalDesc = "",
        id = 62031,
        initConfig = {},
        lingxi_type = 1,
        missiondone = {"NT62032"},
        name = "灵犀任务",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"TR100010"},
        tasktype = 0,
        timeout = 0,
        tips = 0,
        type = 10,
    },

    [62032] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "两名异性好友玩家组队参与任务，共同悉心照料情花成长，成功完成任务后，可以获得丰厚的奖励。",
        goalDesc = "两人一起使用情花，接受诗文熏陶",
        id = 62032,
        initConfig = {},
        lingxi_type = 2,
        missiondone = {},
        name = "灵犀任务",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {},
        tasktype = 7,
        timeout = 0,
        tips = 0,
        type = 10,
    },

}
