-- ./excel/system/artifact/strength.xlsx
return {

    [1] = {
        agility = "",
        cure_power = "",
        endurance = "",
        equip_sid = 22800,
        mag_damage_add = "",
        magic = "",
        phy_damage_add = "",
        physique = "",
        res_seal_ratio = "",
        seal_ratio = "",
        speed_power = "",
        strength = "",
    },

    [2] = {
        agility = "",
        cure_power = "",
        endurance = "",
        equip_sid = 22801,
        mag_damage_add = "",
        magic = "",
        phy_damage_add = "",
        physique = "",
        res_seal_ratio = "",
        seal_ratio = "",
        speed_power = "",
        strength = "",
    },

    [3] = {
        agility = "",
        cure_power = "",
        endurance = "",
        equip_sid = 22802,
        mag_damage_add = "",
        magic = "",
        phy_damage_add = "",
        physique = "",
        res_seal_ratio = "",
        seal_ratio = "",
        speed_power = "",
        strength = "",
    },

    [4] = {
        agility = "",
        cure_power = "",
        endurance = "",
        equip_sid = 22803,
        mag_damage_add = "",
        magic = "",
        phy_damage_add = "",
        physique = "",
        res_seal_ratio = "",
        seal_ratio = "",
        speed_power = "",
        strength = "",
    },

    [5] = {
        agility = "",
        cure_power = "",
        endurance = "",
        equip_sid = 22804,
        mag_damage_add = "",
        magic = "",
        phy_damage_add = "",
        physique = "",
        res_seal_ratio = "",
        seal_ratio = "",
        speed_power = "",
        strength = "",
    },

    [6] = {
        agility = "",
        cure_power = "",
        endurance = "",
        equip_sid = 22805,
        mag_damage_add = "",
        magic = "",
        phy_damage_add = "",
        physique = "",
        res_seal_ratio = "",
        seal_ratio = "",
        speed_power = "",
        strength = "",
    },

}
