-- ./excel/huodong/biwu/scene.xlsx
return {

    [1001] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1001,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "1层",
        team_allowed = 1,
    },

    [1002] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1002,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "2层",
        team_allowed = 1,
    },

    [1003] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1003,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "3层",
        team_allowed = 1,
    },

    [1004] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1004,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "4层",
        team_allowed = 1,
    },

    [1005] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1005,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "5层",
        team_allowed = 1,
    },

    [1006] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1006,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "6层",
        team_allowed = 1,
    },

    [1007] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1007,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "7层",
        team_allowed = 1,
    },

    [1008] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1008,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "8层",
        team_allowed = 1,
    },

    [1009] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1009,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "9层",
        team_allowed = 1,
    },

    [1010] = {
        deny_fly = 1,
        guide_map = 0,
        has_anlei = 0,
        id = 1010,
        is_durable = 0,
        jjc = 0,
        line_count = 1,
        map_id = 502000,
        scene_name = "斗法赛场",
        team_allowed = 1,
    },

}
