-- ./excel/task/schoolpass/task_schoolpass.xlsx
return {

    [62011] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5258",
        description = "战胜{submitnpc}",
        goalDesc = "挑战{submitnpc}",
        id = 62011,
        initConfig = {"E5258:62011"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10001"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62012] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5259",
        description = "战胜{submitnpc}",
        goalDesc = "战胜{submitnpc}",
        id = 62012,
        initConfig = {"E5259:62012"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10001"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62013] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5260",
        description = "战胜{submitnpc}",
        goalDesc = "战胜{submitnpc}",
        id = 62013,
        initConfig = {"E5260:62013"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10001"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62014] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5261",
        description = "战胜{submitnpc}",
        goalDesc = "战胜{submitnpc}",
        id = 62014,
        initConfig = {"E5261:62014"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10001"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62015] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5262",
        description = "战胜{submitnpc}",
        goalDesc = "战胜{submitnpc}",
        id = 62015,
        initConfig = {"E5262:62015"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10001"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62016] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5263",
        description = "战胜{submitnpc}",
        goalDesc = "战胜{submitnpc}",
        id = 62016,
        initConfig = {"E5263:62016"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10001"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62021] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5236",
        description = "接受#G太上长老#n的考验",
        goalDesc = "接受#G太上长老#n的考验",
        id = 62021,
        initConfig = {"E5236:62021"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10002"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62022] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5237",
        description = "接受#G太上长老#n的考验",
        goalDesc = "接受#G太上长老#n的考验",
        id = 62022,
        initConfig = {"E5237:62022"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10002"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62023] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5238",
        description = "接受#G太上长老#n的考验",
        goalDesc = "接受#G太上长老#n的考验",
        id = 62023,
        initConfig = {"E5238:62023"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10002"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62024] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5239",
        description = "接受#G太上长老#n的考验",
        goalDesc = "接受#G太上长老#n的考验",
        id = 62024,
        initConfig = {"E5239:62024"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10002"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62025] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5240",
        description = "接受#G太上长老#n的考验",
        goalDesc = "接受#G太上长老#n的考验",
        id = 62025,
        initConfig = {"E5240:62025"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10002"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

    [62026] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "submitnpc:5241",
        description = "接受#G太上长老#n的考验",
        goalDesc = "接受#G太上长老#n的考验",
        id = 62026,
        initConfig = {"E5241:62026"},
        missiondone = {},
        name = "门派试炼",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R10002"},
        tasktype = 4,
        timeout = 900,
        tips = 0,
        type = 8,
    },

}
