-- ./excel/huodong/xingxiu/npc.xlsx
return {

    [1001] = {
        diglogface = 1001,
        event = 1001,
        figureid = 5107,
        grade = 0,
        id = 1001,
        mapid = 0,
        name = "角木蛟",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1002] = {
        diglogface = 1002,
        event = 1001,
        figureid = 5107,
        grade = 0,
        id = 1002,
        mapid = 0,
        name = "亢金龙",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1003] = {
        diglogface = 1003,
        event = 1001,
        figureid = 5107,
        grade = 0,
        id = 1003,
        mapid = 0,
        name = "箕水豹",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1004] = {
        diglogface = 1004,
        event = 1001,
        figureid = 5107,
        grade = 0,
        id = 1004,
        mapid = 0,
        name = "尾火虎",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1005] = {
        diglogface = 1005,
        event = 1001,
        figureid = 5127,
        grade = 0,
        id = 1005,
        mapid = 0,
        name = "房日兔",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [1006] = {
        diglogface = 1006,
        event = 1001,
        figureid = 5127,
        grade = 0,
        id = 1006,
        mapid = 0,
        name = "心月狐",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [2001] = {
        diglogface = 2001,
        event = 1001,
        figureid = 5107,
        grade = 0,
        id = 2001,
        mapid = 0,
        name = "变异角木蛟",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [2002] = {
        diglogface = 2002,
        event = 1001,
        figureid = 5107,
        grade = 0,
        id = 2002,
        mapid = 0,
        name = "变异亢金龙",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [2003] = {
        diglogface = 2003,
        event = 1001,
        figureid = 5107,
        grade = 0,
        id = 2003,
        mapid = 0,
        name = "变异箕水豹",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [2004] = {
        diglogface = 2004,
        event = 1001,
        figureid = 5107,
        grade = 0,
        id = 2004,
        mapid = 0,
        name = "变异尾火虎",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [2005] = {
        diglogface = 2005,
        event = 1001,
        figureid = 5127,
        grade = 0,
        id = 2005,
        mapid = 0,
        name = "变异房日兔",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

    [2006] = {
        diglogface = 2006,
        event = 1001,
        figureid = 5127,
        grade = 0,
        id = 2006,
        mapid = 0,
        name = "变异心月狐",
        nameType = 1,
        rotateY = 0.0,
        title = "二十八星宿",
        tollgateId = 0,
        type = 3,
        x = 0.0,
        y = 0.0,
        z = 0.0,
    },

}
