-- ./excel/task/xuanshang/task_xuanshang.xlsx
return {

    [90011] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90011,
        initConfig = {"NC90011", "E90011:90011"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

    [90012] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90012,
        initConfig = {"NC90012", "E90012:90012"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

    [90013] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90013,
        initConfig = {"NC90013", "E90013:90013"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

    [90014] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90014,
        initConfig = {"NC90014", "E90014:90014"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

    [90015] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90015,
        initConfig = {"NC90015", "E90015:90015"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

    [90016] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90016,
        initConfig = {"NC90016", "E90016:90016"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

    [90017] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90017,
        initConfig = {"NC90017", "E90017:90017"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

    [90018] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90018,
        initConfig = {"NC90018", "E90018:90018"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

    [90019] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90019,
        initConfig = {"NC90019", "E90019:90019"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

    [90020] = {
        acceptConditionStr = {},
        acceptNpcId = 0,
        acceptPlots = {},
        autoSubmit = 0,
        autotype = 1,
        clientExtStr = "",
        description = "缉拿江洋大盗",
        donePlots = {},
        follownpcs = {},
        goalDesc = "缉拿江洋大盗{submitnpc}",
        id = 90020,
        initConfig = {"NC90020", "E90020:90020"},
        missiondone = {},
        name = "缉拿大盗",
        quickFindWay = 0,
        submitNpcId = 0,
        submitRewardStr = {"R1001"},
        tasktype = 4,
        timeout = 0,
        tips = 0,
        type = 16,
    },

}
